### ISSUE TITLE
ERROR：CombineBCR

### ISSUE THREAD

**Issue by zechuanchen** [ncborcherding/scRepertoire#10]
When I run combineBCR，something run 

combined <- combineBCR(contig_list,samples = "PBMC_1",ID = "Normal")

Error in match.names(clabs, names(xi)) : 
  names do not match previous names

But I seem to have found the reason, and I change the code as follow :  
hammingCompare <- function(Con.df, gene, chain, length)

from
out <- as.data.frame(t(out), stringsAsFactors = F)

to 
out <- as.data.frame(out, stringsAsFactors = F)

But I don’t know whether I am correct

**Comment by ncborcherding** [comment]
Just committed the fix, thanks for pointing out the problem and suggesting a solution. Your solution works from my end, but I do not have extensive BCR data, so I am using simulated data. Please check if the recent commit works for you.

Thanks again.
