### ISSUE TITLE
combineBCR error

### ISSUE THREAD

**Issue by Sa753** [ncborcherding/scRepertoire#100]
Dear Nick,

I installed the most recent version of the package Version 1.3.3 but I am getting this error when I run combineBCR() function.

Error in x[[jj]][iseq] <- vjj : replacement has length zero

When I looked at the combined object that should be formed as a result of running the function, it doesn't add the sample name or the ID to the name but instead puts [[1]] or [[2]] for sample 1 and 2....

Could you please help?. combineTCR() works well

Thank you

**Comment by Sa753** [comment]
<img width="506" alt="Screenshot 2021-08-15 at 17 46 20" src="https://user-images.githubusercontent.com/53982843/129486010-c20abf9e-3cd4-463f-a211-335e036f51f8.png">

**Comment by ncborcherding** [comment]
Hey Sa753,

Nice catch, your are completely correct, you are getting that error because of a mistake in the auto-naming function inside combineBCR(). Just commited the change to the dev branch to fix that - should just need a quick reisntall/restart:

```
devtools::install_github("ncborcherding/scRepertoire@dev")
```

**Comment by Sa753** [comment]
Thank you so much for prompt reply. it is  now working
