### ISSUE TITLE
quantContiq()

### ISSUE THREAD

**Issue by Sa753** [ncborcherding/scRepertoire#102]
Dear Nick,

How does the numbers that we get from running quantcontiq correlate with the numbers from running cell ranger VDJ that appear on the web summary?.

i.e : what is meant by total in the output table?. does that correspond to the total number of T cells wether they have productive VDJ or not? or is that the number of T cells with productive VDJ?.

Thx

**Comment by ncborcherding** [comment]
Hey Sa753, 

```quantContig()``` is showing unique clonetypes, so it is not showing number correlations with outputs from cell rangers directly.

However - 
The numbers in ```quantContig()``` will depend on  two things: 
1) how you called ```combineTCR()/combineBCR()```. The major filtering steps here is designated as "productive" and the indicated cell type, "T-AB" does not consider TCRG/D or IG for example. However, their are additional filtering calls. 
2) How you are calling the ```quantContig()``` function itself - again the default will be number of unique clonotypes.

Nick

**Comment by Sa753** [comment]
So what is the total referring to hear?


contigs | values | total| scaled
-- | -- | -- | --
4256 | S1 | 5340 | 79.7003745. 
5550 | S2 | 5633 | 98.52654
1783 | S3 | 5086 | 35.0570193

This is produced from
combined <- combineTCR(contig_list, samples = c("S1", "S2", "S3"), ID = c("pre", "pre", "pre"), cells = 'T-AB')
quantContig_output <- quantContig(combined, cloneCall="gene+nt", 
                                  scale = TRUE, exportTable = TRUE)

**Comment by ncborcherding** [comment]
Oh I see what you are asking now, the column header **total**. 

Yes in your example:

1. **contigs**: unique clonotypes
2. **values**: grouping variable
3. **total**: total cells with recovered from the filter_contig_output
4. **scaled**: unique clonotypes/total

**Comment by Sa753** [comment]
Yes thank you 

is that total number similar to the parameter on websummary called number of cells with productive vDJ?

**Comment by Sa753** [comment]
Another thing I want to calculate is the number of cells with NA ?. from where can I get that as the number of cells is the filtered contig csv file will be the productive ones only?. is the total number of T cells (including those with NA) will be from the gex library or the VDJ web summary?

**Comment by ncborcherding** [comment]
Yes it should be a similar value as the productive vDJ.

<img width="562" alt="Screen Shot 2021-08-16 at 1 00 00 PM" src="https://user-images.githubusercontent.com/22754118/129608727-d73e6548-dbc2-46fe-b7a9-74e531ddeed7.png">

> Another thing I want to calculate is the number of cells with NA ?.

NA for both chains or for one chain? 

> From where can I get that as the number of cells is the filtered contig csv file will be the productive ones only?

No there are unproductive chains in the filtered contig file

>  is the total number of T cells (including those with NA) will be from the gex library or the VDJ web summary?

You are going to have to compare the resulting data sets together - there is no gurantee that all cell barcodes in GEX will be seen in barcodes in VDJ

**Comment by Sa753** [comment]
thank you.

I always have around 10% difference between the the total number of cells I get from quantcontig and the number -f cells with productive VJ pair. is that accepted, it can be between 100-500 depending on the number of all T cells?

**Comment by Sa753** [comment]
Another thing I want to calculate is the number of cells with NA ?.
NA for both chains or for one chain?
So what is the NA on the Dimplot of seuart object refers to?

**Comment by ncborcherding** [comment]
Yeah I would estimate that 10% is probably a reasonable difference (it will range by the size of the library).

NA on the dimPlot() refers to chains with both TCRA and TCRB as NA.

**Comment by Sa753** [comment]
Great how can I get that number of NA?

**Comment by ncborcherding** [comment]
quickest way is probably doing it across your 3 samples with:

table(complete.cases(combined[[1]]))

**Comment by Sa753** [comment]
Thank you so much. One last question 

should be calculate the number of unique clones as percentage of productive clones only (i.e excluding those NA) instead of the total number of cells recovered from filtered annotation contig csv file especially that you said above that this file can contain productive and non productive?

**Comment by Sa753** [comment]
so for example I run qauntcontiq and I had total = 1434 , unique 1113
then when I run table(complete.cases(combined[[1]])), I got TRUE: 1303 and FALSE:303 . I assume that false should be the NA ones. so the number of unique clones could be 1113/1303 instead of 1113/1434?. or this is wrong

**Comment by ncborcherding** [comment]
No complete.cases() identifies rows with NA values in TCRA or TCRB (rows with NA in TCRA and TCRB are excluded from combined). So the math includes barcodes where 1 chain has an NA, but not the other one. You can filter out any barcodes without both chains during ```combineTCR(.....,filterNA = TRUE)```

**Comment by Sa753** [comment]
Ok I understand now. Thank you so much for explaining.
