### ISSUE TITLE
adding column to combineTCR() output

### ISSUE THREAD

**Issue by Sa753** [ncborcherding/scRepertoire#106]
Dear Nick,

Is there a way that I add a column to the output of CombineTCR() function , please?. I want the added column to match by cell names.

I tried to add it to the filtered_contig.csv file but the added column was not picked up so I thought it needs to be added to the output of the function rather than adding it to the input.

Thanks

**Comment by ncborcherding** [comment]
You just want a duplicate of your cell barcodes? Or the cell barcodes before the prefix added? 

For the former, a quick for loop should work. 
```
for (i in seq_along(combined)){
      combined[[i]]$BarcodesDuplicate <- combined[[i]]$barcodes
```

I can write a for loop for the latter situation, just give me the format of the barcodes after ```combineTCR().```


Thanks,
Nick

**Comment by Sa753** [comment]
Hi Nick,

Sorry , I didn't make myself clear. I want to add a data frame to the output of combineTCR(). The data frame should be matched to the combineTCR at the cell barcode. i.e, I want to add a value for each cell from another data frame.
I don't need to duplicate the barcodes

Thanks

**Comment by ncborcherding** [comment]
No worries, same sort of idea - you should be able to merge the second data frame with the list of data frames after ```combineTCR()```.  Just make sure you indicate what column is the barcode in, if they have different names, you can set **by.x=** and **by.y=**, instead of just **by=**. The merge should not effect the downstream functions, so you should be good to go.

```
for (i in seq_along(combined)){
      combined[[i]] <- merge(combined[[i]], second.data.frame, by = "barcode")
}
```

**Comment by Sa753** [comment]
Thank you so much
