### ISSUE TITLE
Restore old colors

### ISSUE THREAD

**Issue by JFavaloro** [ncborcherding/scRepertoire#107]
Hi Nick,

Thanks as always for your continued development of this fantastic package!

Not so much an issue, but hoping you'd be able to give some quick advice RE: restoring the original colors in your plots e.g.

colorblind_vector <- colorRampPalette(c("#FF4B20", "#FFB433", "#C6FDEC", "#7AC5FF", "#0348A6"))

I'm not too familiar with where this information is stored in the ggplot object, else I would simply change it there.

Thanks as always!

**Comment by ncborcherding** [comment]
Yeah sorry, I should have included that in the newest version of the vignette. 

The functions that return graphs are actually returning the ggplot objects, so the easiest way is something similar to calling ```DimPlot()``` [here](https://ncborcherding.github.io/vignettes/vignette.html#61_Combining_both_TCR_and_BCR) in the vignette. 


- For UMAP/DimPlot -  ```+ scale_color_manual(values = colorblind_vector(), na.value="grey")``` a number has to be added to the ```colorblind_vector()``` to work
- For bar graphs - ```+ scale_fill_manual(values = colorblind_vector())```

Hope that helps and let me know if you have any other questions.

Nick

**Comment by JFavaloro** [comment]
Thanks so much as always :)

On 9 Sep 2021, at 8:46 pm, theHumanBorch ***@***.******@***.***>> wrote:



Closed #107<https://protect-au.mimecast.com/s/4MsCCWLVlZT9mVZOixBcWf?domain=github.com>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://protect-au.mimecast.com/s/vjoHCVARkYHwoYm3fGexha?domain=github.com>, or unsubscribe<https://protect-au.mimecast.com/s/QV6ECXLW01T5oWj2UDj8bs?domain=github.com>.
Triage notifications on the go with GitHub Mobile for iOS<https://protect-au.mimecast.com/s/nu7_CYW8n2I12wmMHVqVFs?domain=apps.apple.com> or Android<https://protect-au.mimecast.com/s/8H3wCZY1o3f490AlHxgNGm?domain=play.google.com>.
