### ISSUE TITLE
question about function 'alluvialClonotypes()'

### ISSUE THREAD

**Issue by xiachenrui** [ncborcherding/scRepertoire#109]
Hi, I meet another question.
When I run
```
[alluvialClonotypes](url)(b_cell, cloneCall = "gene", 
                   y.axes = c("orig.ident", "cell_type", "seurat_clusters"), 
                   color = "seurat_clusters") 
```
I find the plot do not show the all the categories in seurat object, for example there are three categories in 'orig.ident'
```
table(b_cell$orig.ident)
xh_rna.h5   zh_rna.h5 zmy1_rna.h5 
     1067        1804         896 
```
but in the picture it only shows 2 of them
Similarly，there are 13 clusters(0-12) in seurat objects and only shows 0-11
![image-20210910200746118](https://gitee.com/huhansan666666/picture/raw/master/img/image-20210910200746118.png)
Best wishes!

**Comment by xiachenrui** [comment]
Sorry, the command I run is 
```
alluvialClonotypes(b_cell, cloneCall = "gene", 
                   y.axes = c("orig.ident", "cell_type", "seurat_clusters"), 
                   color = "seurat_clusters") 
```

**Comment by ncborcherding** [comment]
Hey Xia, 

My first question is does every sample and every cluster have B cells? If not, ```alluvialClonotypes()``` will drop levels that do not have clones - for example potentially cluster 12 is not B cells or does not have recovered clonotypes.

One way to check this would be to use the ```table()``` function like you used above, but return any NA values:

```
table(b_cell$orig.ident, b_cell$cloneType, , useNA = "ifany")
table(b_cell$seurat_clusters, b_cell$cloneType, , useNA = "ifany")
```

If this doesn't work, feel free to[ email me](mailto:ncborch@gmail.com) your meta data (b_cell[[]] or b_cell@meta.data as a csv) and I'd be happy to see if I can track down the problem.

Thanks, 
Nick

**Comment by xiachenrui** [comment]
Thanks a lot! Exactly the same as you said,  `NA` lead to the error.

Best wishes!
Xia
