### ISSUE TITLE
Issue with parsing B-cell data from TRUST4 via combineTRUST4

### ISSUE THREAD

**Issue by gusarv** [ncborcherding/scRepertoire#111]
Hi Nick,

Thanks for implementing a way to parse data generated via TRUST4 to scRepertoir. I am however having trouble with the function combineTRUST4 which generates an error when I try to pass my list of B-cell samples to it. I suspect it has something to do with the function lvCompare() in combineContigs.R which is called by combineTRUST4 but I wasn't able to figure it out. 

Input example:
```{r}
> head(clono_TRUST4[[1]], n=3)

           barcode cell_type
1 GTCATTTTCTGGGCCA       abT
2 ATTGGTGTCAATCACG         B
3 TTTACTGAGATCTGAA         B
                                                                                                                                      chain1
1 TRBV12-4*01,TRBD2*01,TRBJ2-2*01,*,TGTGCCAGCATTCACCGGGGAGTTGGTTGGGGCGGGGAGCTGTTTTTT,CASIHRGVGWGGELFF,2.00,GTCATTTTCTGGGCCA-1_57026,100.00,0
2          IGHV5-51*01,IGHD3-3*01,IGHJ4*02,*,TGTGCGAGGCAATCCCCCCTCGCTGGATTTTCGGACTACTGG,CARQSPLAGFSDYW,2.00,ATTGGTGTCAATCACG-1_11057,92.86,0
3                                                                                                                                          *
                                                                                                         chain2
1                                                                                                             *
2   IGKV4-1*01,*,IGKJ1*01,*,TGTCACCAATATTATAATACTCCTCGGACGTTC,CHQYYNTPRTF,7.06,ATTGGTGTCAATCACG-1_35740,93.55,0
3 IGKV3-20*01,*,IGKJ4*01,IGKC,TGTCAGCAGTATGTTAGCTCACCGCTCACTTTC,CQQYVSSPLTF,6.73,TTTACTGAGATCTGAA-1_493,96.77,1
  secondary_chain1 secondary_chain2
1                *                *
2                *                *
3                *                *
```

```{r}
> nrow(clono_TRUST4[[1]])
[1] 3760
> length(clono_TRUST4)
[1] 30`
```

```{r}
> combined <- combineTRUST4(clono_TRUST4,
+                     samples = names(clono_TRUST4),
+                     ID = NULL,
+                     cells = c("B"),
+                     removeNA = TRUE)
 Error in which(norm.row >= threshold) : 
  argument "threshold" is missing, with no default 
>
 ```

Not sure what's going on but I'd find it great if there was a way to solve it so I can compare the TRUST4 output with my VDJ libraries.

Thanks for a great package btw!

Cheers,

Gustav

**Comment by ncborcherding** [comment]
Hey Gustav,

Thanks for reaching out, I should have time to look into it today. 

Quick question though - what is x? The error makes me think that x is not defined in your global environment? I could be wrong here. 

Glad someone is using the ```combineTRUST4()```!

Nick

**Comment by gusarv** [comment]
Hi Nick,

Thanks for the quick reply! I ran into some memory issues when trying to pass my list of VDJ samples to combineBCR so I resorted to iterating over the samples and thought I'd do that for combineTRUST4 as well. The x in the example above is a leftover from that, sorry.

Hope you can help me figure this out.

Best,

G

**Comment by gusarv** [comment]
Sorry about the confusion, I changed the original post now.

**Comment by ncborcherding** [comment]
Hey Gustav, 

Thanks for the clarification - this is actually my fault. I have been working on a newer version of ```combineBCR()``` that should be faster and less memory intensive (and also lets you select how close of cdr3 sequences to call **threshold**), but I forgot to get the changes to ```combineTRUST4()```. Just hit comit so if you reinstall the dev version and restart your R instances, should work now!

Nick

**Comment by gusarv** [comment]
Great, thanks! I'll reinstall and try it out.

**Comment by gusarv** [comment]
Seems to be working now. Thanks for fixing it so quickly!
