### ISSUE TITLE
scRepertoire and Seurat

### ISSUE THREAD

**Issue by aurorelei** [ncborcherding/scRepertoire#112]
Hi Nick,

Thanks for the great package. I am relatively new to R so I am still figuring out how some of this stuff works. I have a question about merging scRepertoire with Seurat. Is there an option to not only split the analysis by cluster but also by sample eg WT and KO. It seems like I can do one or the other, but not both. 

Cheers,
Auri

**Comment by ncborcherding** [comment]
Hey Auri, 

Thanks for reaching out - yes there is a way to do both by cluster and condition. You should be able to isolate by cluster or group/condition using ```expression2List()``` [[vignette link here](https://ncborcherding.github.io/vignettes/vignette.html#7_Working_with_clonotypes_after_clustering)]

so something you could do is: 
```
combined.by.cluster <- expression2List(seurat, group = "cluster")
combined.by.condition <- expression2List(seurat, group = condition) #here condition is the header of the meta data that corresponds to WT/KO
```

Feel free to reach out anytime if you have more questions! Good luck with the analysis. 

Nick

**Comment by aurorelei** [comment]
Hi Nick,

Thanks. I'll give that a go.

Auri
