### ISSUE TITLE
Error when CombineExpression

### ISSUE THREAD

**Issue by Yvonne-Yue** [ncborcherding/scRepertoire#113]
Hi, I’m having this problem when trying to combine TCR(combined contig_list) with the Seurat object.

My codes included:
combined <- combineTCR(contig_list, samples = c("xx"), ID = c("xxx"),cells ="T-AB")
TCR1 <-readRDS(file = "xxx/T.rds")
seurat <- combineExpression(combined, TCR1, cloneCall="gene", groupBy = "sample")

Then I got this error:
Error in `$<-.data.frame`(`*tmp*`, "cloneType", value = NA) : replacement has 1 row, data has 0

I've checked other closed issues and tried to re-install all kinds of versions including from BiocManager/Github/@dev branch/@master branch but still unable to run this line.

My version:
R version 4.1.1 (2021-8-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
scRepertoire 1.3.2

Looking forward to your reply.
Thank you!

**Comment by ncborcherding** [comment]
Hey Yvonne, 

Thanks for reaching out - I am happy to help. I don't think I have seen that issue before - but I have a couple of questions first:

- You are getting this error during the **combineExpression()** call? 
- What is the TCR1.rds object? Is that your single-cell expression/Seurat object?

Thanks,
Nick

**Comment by Yvonne-Yue** [comment]
Hi Nick,
Thanks for your reply!

1)Yes, this occurred when combineExpression
2)TCR1 is a Seurat object

**Comment by ncborcherding** [comment]
Ok interesting, I will dive into the code today and see if I can find the issue!

**Comment by ncborcherding** [comment]
Hey Yvonne, 

I am not able to replicate the problem, would you mind sending me your data or subset of your data so I can take a look? You can email me [here](mailto:ncborch@gmail.com).

If not, I understand and will try to work through the error without the repro example. 

Thanks,
Nick

**Comment by Yvonne-Yue** [comment]
Hi Nick,
Thanks so much for your advice! I did remove "groupBy" when I tried which I didn't notice. ^^

**Comment by ncborcherding** [comment]
Great thanks for the follow up!
