### ISSUE TITLE
alpha/beta chains listed as T-GD after combineTCR

### ISSUE THREAD

**Issue by kkearns13** [ncborcherding/scRepertoire#115]
Hi, thank you for the great tool! I have been trying to use scRepertoire with an output file from TRUST4. The TRUST4 file has been filtered using code provided on their GitHub and looks like this:
<img width="1197" alt="Screen Shot 2021-10-01 at 1 01 01 PM" src="https://user-images.githubusercontent.com/91350016/135679623-d6384c83-48e6-4728-b730-1f1b71291a5b.png">

There are TRG and TRD chains listed and (mostly) have the appropriately named genes (e.g., TRGV9*01 or TRDV1*01). However, when I try to use combineTCR on this file without specifying either T-AB or T-GD, the resulting list shows T-GD as having alpha and beta chains (shown below). Additionally, the plots for looking at the length of clonotypes look exactly the same for TRA and TRD, and for TRB and TRG. 

```
 barcode sample                      TCR1       cdr3_aa1
11122 tube5_TTTGGTTGTGAGGCTA  tube5 TRAV1-2*01.TRAJ33*01.TRAC   CAVKGGNYQLIW
11129 tube5_TTTGTCAAGTGGACGT  tube5                      <NA>           <NA>
11130 tube5_TTTGTCAAGTGGTAAT  tube5                      <NA>           <NA>
11133 tube5_TTTGTCATCCGCATCT  tube5                      <NA>           <NA>
                                        cdr3_nt1                                  TCR2
11122       TGTGCTGTGAAGGGTGGCAACTATCAGTTAATCTGG                                  <NA>
11129                                       <NA>  TRBV3-1*01.TRBD2*02.TRBJ2-7*01.TRBC2
11130                                       <NA>      TRBV5-1*01.None.TRBJ1-1*01.TRBC1
11133                                       <NA> TRBV11-2*01.TRBD2*01.TRBJ2-1*01.TRBC2
             cdr3_aa2                                      cdr3_nt2
11122            <NA>                                          <NA>
11129  CASSQPSGTYEQYF    TGTGCCAGCAGCCAACCTAGCGGGACCTACGAGCAGTACTTC
11130 CASSPSVGANTEAFF TGCGCCAGCAGCCCATCTGTGGGCGCGAACACTGAAGCTTTCTTT
11133 CASSPGGAFIDEQFF TGTGCCAGCAGCCCCGGGGGGGCCTTTATCGATGAGCAGTTCTTC
                                        CTgene
11122             TRAV1-2*01.TRAJ33*01.TRAC_NA
11129  NA_TRBV3-1*01.TRBD2*02.TRBJ2-7*01.TRBC2
11130      NA_TRBV5-1*01.None.TRBJ1-1*01.TRBC1
11133 NA_TRBV11-2*01.TRBD2*01.TRBJ2-1*01.TRBC2
                                                  CTnt               CTaa
11122          TGTGCTGTGAAGGGTGGCAACTATCAGTTAATCTGG_NA    CAVKGGNYQLIW_NA
11129    NA_TGTGCCAGCAGCCAACCTAGCGGGACCTACGAGCAGTACTTC  NA_CASSQPSGTYEQYF
11130 NA_TGCGCCAGCAGCCCATCTGTGGGCGCGAACACTGAAGCTTTCTTT NA_CASSPSVGANTEAFF
11133 NA_TGTGCCAGCAGCCCCGGGGGGGCCTTTATCGATGAGCAGTTCTTC NA_CASSPGGAFIDEQFF
                                                                                       CTstrict
11122                      TRAV1-2*01.TRAJ33*01.TRAC_TGTGCTGTGAAGGGTGGCAACTATCAGTTAATCTGG_NA_NA
11129     NA_NA_TRBV3-1*01.TRBD2*02.TRBJ2-7*01.TRBC2_TGTGCCAGCAGCCAACCTAGCGGGACCTACGAGCAGTACTTC
11130      NA_NA_TRBV5-1*01.None.TRBJ1-1*01.TRBC1_TGCGCCAGCAGCCCATCTGTGGGCGCGAACACTGAAGCTTTCTTT
11133 NA_NA_TRBV11-2*01.TRBD2*01.TRBJ2-1*01.TRBC2_TGTGCCAGCAGCCCCGGGGGGGCCTTTATCGATGAGCAGTTCTTC
      cellType
11122     T-GD
11129     T-GD
11130     T-GD
11133     T-GD
```

That said, I am reading only one file in and got a message saying "the condition has length > 1 and only the first element will be usedthe condition has length > 1 and only the first element will be usedthe condition has length > 1 and only the first element will be used" (phrase was repeated in message in R), but I'm not sure if this is the reason why I'm getting these results? I would appreciate any help you can provide!

**Comment by ncborcherding** [comment]
Hey Kkearns, 

Apologies for the delay - 

So my understanding is that you have used TRUST4  to recover contigs from a 5' experiment and a conversion function in TRUST4 to convert their output to the 10x format you have in your screen shot? 

My guess of what is happening here is that scRepertoire requires a **cells** call for ```combineTCR()```. So if you wanted to organize contigs from T-AB and T-GD, you would actually need to call ```combineTCR()``` twice. 

The error  (below) is from the fact the function ```combineTCR()``` has cells stored as = c("T-AB", "T-GD"), so if you do not specify which, the warning will be the following. However I am not sure how this results in assigning TRA/TRB chains as "T-GD".

> condition has length > 1 and only the first element will be used

If you try calling ```combineTCR(cells = "T-AB")``` and still have this problem, please let me know. In the mean time, I will improve the way the function is written and documentation. 

Thanks for reaching out,
Nick
