### ISSUE TITLE
?Issue with Demultiplexing

### ISSUE THREAD

**Issue by pankomah** [ncborcherding/scRepertoire#121]
Hi Nick, 

Thanks for a really great program. I"m having some issues with a multiplexed experiment and was hoping for some help. I have an experiment with 8 combined samples (from 8 separate patients). My filtered_contig_annotations file has 10,574 observations. However, when I use createHTOContigList to demultiplex, the total observations in the resulting contig.list decrease substantially down to 169 (14, 18, 37, 26, 17, 28, 8 and 21 observations each for Patients 1-8). Any ideas of what may be going on?

Thanks, 
Pierre

**Comment by ncborcherding** [comment]
Hey Pierre, 

Thanks for reaching out.

Those numbers make me think there is an issue with barcodes matching between the contig file and the Seurat object. This can be due to having multiple multiplex sequences combined as well. Do you have the outputs for your Seurat meta data ```head(SeuratObj[[]])``` and ```head(contig.list[[1]])```?

Thanks,
Nick

**Comment by pankomah** [comment]
Hi Nick, 

Thanks much for the quick reply. The outputs are as below -- I did make sure the formatting for the barcodes were
similar.                   

head(contig.list[[1]])
[1] "AAACCTGAGGACTGGT" "AAACCTGAGGACTGGT" "AAACCTGAGGGTGTTG" "AAACCTGAGGGTGTTG" "AAACCTGAGTAACCCT" "AAACCTGAGTAACCCT"

head(SeuratObj[[]])                    orig.ident nCount_RNA nFeature_RNA nCount_ADT nFeature_ADT demux_type assignment percent.mt   SampleIdent Patient
AAACCTGAGACTCGGA SeuratProject       1675          892       1661          124    singlet   Sample_5  6.5074627 SeuratProject     P68
AAACCTGAGAGTCGGT SeuratProject       2236          935       1051          124    singlet   Sample_8  1.6547406 SeuratProject     P08
AAACCTGAGGACGAAA SeuratProject       3039         1433        851          123    singlet   Sample_4  1.9414281 SeuratProject     P66
AAACCTGAGGCATGGT SeuratProject       1570          966        368          100    singlet   Sample_4  0.8280255 SeuratProject     P66
AAACCTGAGGGAAACA SeuratProject       2394         1101       1008          125    singlet   Sample_2  2.7151211 SeuratProject     P41
AAACCTGAGTGATCGG SeuratProject       2888         1210        686          113    singlet   Sample_8  2.1468144 SeuratProject     P08

Thanks, 
Pierre

**Comment by ncborcherding** [comment]
Hey Pierre, 

Thanks for the outputs, you are correct, no mods for the barcodes, so that is not the issue. 

How many multiplexed runs do you have? As of right now ```createHTOContigList()``` can't de-multiplex across sequencing runs, but only within the same run. What might be happening (just based on the low numbers you recovered) is that you are getting randomly matched barcodes from different multiplex runs. 

Hope that helps, 

Nick

**Comment by pankomah** [comment]
Hi Nick, 

It's a single sequencing run, though with multiple multiplexed samples (48 total different samples) combined within that run. If createHTOContigList() won't work, can I utilize this approach (https://www.biostars.org/p/384640/) to add the VDJ sequence data to the Seurat metadata, and then use scRepertoire for the analysis?

Thanks, 
Pierre

**Comment by ncborcherding** [comment]
Hey Pierre, 

Can you post the function call for ```createHTOContigList()``` - if you have multiple samples at multiple time points, that could also be confusing the demultiplex. You will need a single variable that has 48 levels. After you run ```createHTOContigList()``` and combine the contigs, you can resort them into different groups. 

Also do you have any duplicate barcodes across the 1 sequencing run? I am not sure how you are getting 48 samples in one run?

In terms of scRepertoire usage with other ways of attaching contigs to the Seurat metadata - it is possible but would involve a number of scripting to adjust things. Right now there is no universal way to attach meta data, so scRepertoire is only using the outputs from ```combineExpression()```, ```combineBCR()``` and ```combineTCR()```. 

Nick

**Comment by pankomah** [comment]
Hi Nick, 

Thanks a lot for working with me on this. I do have multiple samples at multiple time points --- it's an experiment with 16 different patients each with samples for three days. I combine 8 samples (different patients, each with a separate antibody hashing tag) into a single multiplex experiment, and create a 5' GEX and VDJ library. All the RNA data has already been combined into a Seurat object (with Patient and Day metadata), and now I want to add the VDJ data from the 6 contig files.

I'm calling the demultiplexing function thus: 
T1 <- read.csv("~/T1/filtered_contig_annotations.csv")
T1.contig.list <- createHTOContigList(T1, SeuratObj, group.by = "Patient")

I do this for all 6 contig files (T1 to T6), but each results in a substantial reduction in the total observations in the contig.list relative to the contig file. 

Let me know if there was a different way you wanted to see the createHTOContigList function call --- I'm still an R novice so may have misunderstood your ask. 

Thanks, 
Pierre

**Comment by ncborcherding** [comment]
Hey Pierre, 

No that is exactly what I need. 

> I'm calling the demultiplexing function thus:
T1 <- read.csv("~/T1/filtered_contig_annotations.csv")
T1.contig.list <- createHTOContigList(T1, SeuratObj, group.by = "Patient")

When I created ```createHTOContigList()``` - I did not think of users already having integrated seuratObj across multiple sequencing runs. So the confusion is arising because ```createHTOContigList()``` is trying to match barcodes across the 6 sequencing runs. The fact you are getting 10-40 recovered indicates to me that the contigs recovered are likely just the incidental duplicate barcodes of other runs. 

Would you mind [emailing me](mailto:ncborch@gmail.com) your meta data and contig files? I'll write a quick script to get things working and then I can hopefully integrate that into the ```createHTOContigList()``` so there are no future issues.

Thanks,
Nick

**Comment by pankomah** [comment]
Hi Nick, 

Thanks for being so responsive. Files sent!

**Comment by ncborcherding** [comment]
Hey Pierre, 

Thanks for the data! I think we figured it out, but wanted to post an update for other users.

As of right now, ```createHTOContigList()``` is designed for single sequencing runs, so if you are using an integrated seurat object from multiple sequencing runs, best practice would be to run ```createHTOContigList()``` for each sequencing run (possibly before the integration step would be easiest). 

I will work on a more sophisticated function call to prevent this issue.

Nick
