### ISSUE TITLE
clonalNetwork function can't be found

### ISSUE THREAD

**Issue by Eomesodermin** [ncborcherding/scRepertoire#124]
Hi Nick, 

Excited to use your new clonalNetwork() function. I installed latest @dev version of the package from github. I can query ?clonalNetwork and see the documentation for the function. However, I cant find the function. 

scRepertoire::clonalNetwork() returns Error: 'clonalNetwork' is not an exported object from 'namespace:scRepertoire'
clonalNetwork() returns cloud not find function 
getAnywhere("clonalNetwork") returns no object named "clonalNetwork" was found 

I'm at a loss as to how to find the function. Probably something silly on my side but given you just published this, was wondering if something on your side has hidden it. 

thoughts?

**Comment by ncborcherding** [comment]
Hey Dillon, 

I just re-installed directly from github and I am able to see the ```clonalNetwork()``` function and I see it in the repo - very strange. Have you restarted your R session? 

Nick

**Comment by Eomesodermin** [comment]
I tried a lot of things, stupidly, restarting the R session was not one of them. This fixed the issue. 

thanks for taking a look and sorry for the hassle. now to make some beautiful clonalNetwork plots :).

**Comment by ncborcherding** [comment]
No problem - it happens to me a lot actually. Let me know if you have any suggestions!!

**Comment by leeanapeters** [comment]
Hi, I received this error as well, I reinstalled from dev and now am able to find the function, but get this error:
Error in names(x) <- value : 
  'names' attribute [3] must be the same length as the vector [0]
Here is the code
My object has the clusters I am trying to group by and the specified dimensionality reduction, so not sure where the error is coming from 

Thanks!

Leeana
