### ISSUE TITLE
Question about function clonalNetwork()

### ISSUE THREAD

**Issue by xiachenrui** [ncborcherding/scRepertoire#126]
Hi, could you please tell me what the arrow means in the result of function clonalNetwork(), I have no idea about this. And I am also want to know more about what infomation do the picture want to present.
![image-20211206171631229](https://gitee.com/huhansan666666/picture/raw/master/img/image-20211206171631229.png)

Best wishes!

**Comment by ncborcherding** [comment]
The arrows indicate the direction of sharing. The edges of the network will start at the middle of a cluster (node 1) and proceed to a second cluster (node 2 - where the arrow points). The arrow indicates the direction of that interaction, which is colored by the proportion of shared clones of node 1 + node 2 / total clones of node 1.

Hope that helps, let me know if you have other questions.

Nick

**Comment by xiachenrui** [comment]
Thanks a lot. But why not every arrow is symmetrical. For example, there is an edge from A to B, but sometimes not exists an edge from B to A.

**Comment by mieko-cc** [comment]
> The arrows indicate the direction of sharing. The edges of the network will start at the middle of a cluster (node 1) and proceed to a second cluster (node 2 - where the arrow points). The arrow indicates the direction of that interaction, which is colored by the proportion of shared clones of node 1 + node 2 / total clones of node 1.
> 
> Hope that helps, let me know if you have other questions.
> 
> Nick

**Comment by mieko-cc** [comment]
Thanks for the nice function of clonalNetwork(), but in the version of scRepertoire1.4.0, this function can not work, and I can not install the more development version.
Could you please show me how to use clonalNetwork() ?
Thank you！

**Comment by mieko-cc** [comment]
> The arrows indicate the direction of sharing. The edges of the network will start at the middle of a cluster (node 1) and proceed to a second cluster (node 2 - where the arrow points). The arrow indicates the direction of that interaction, which is colored by the proportion of shared clones of node 1 + node 2 / total clones of node 1.
> 
> Hope that helps, let me know if you have other questions.
> 
> Nick
Thanks for the nice function of clonalNetwork(), but in the version of scRepertoire1.4.0, this function can not work, and I can not install the more development version.
Could you please show me how to use clonalNetwork() ?
Thank you！

**Comment by ncborcherding** [comment]
@xiachenrui - this is because if you draw all the lines, it is very difficult to see, so there is a filter function for the first half of the identities. I can add parameters for more filtering contols for this if you think it is necessary.

@mieko-cc function is brand new - it is only in the dev version on github

```
devtools::install_github("ncborcherding/scRepertoire@dev")
```

**Comment by mieko-cc** [comment]
> @xiachenrui - this is because if you draw all the lines, it is very difficult to see, so there is a filter function for the first half of the identities. I can add parameters for more filtering contols for this if you think it is necessary.
> 
> @mieko-cc function is brand new - it is only in the dev version on github
> 
> ```
> devtools::install_github("ncborcherding/scRepertoire@dev")
> ```

Thanks for your kind reply~

**Comment by mieko-cc** [comment]
> 



> @xiachenrui - this is because if you draw all the lines, it is very difficult to see, so there is a filter function for the first half of the identities. I can add parameters for more filtering contols for this if you think it is necessary.
> 
> @mieko-cc function is brand new - it is only in the dev version on github
> 
> ```
> devtools::install_github("ncborcherding/scRepertoire@dev")
> ```

And one more question, how to manually set the color of clusters

Thank you so much

**Comment by ncborcherding** [comment]
Hey mieko-cc, 

The clusters are plotted using ggplot, so you can modify them using the gg structure. So for example:

```
clonalNetwork(...) + 
    scale_color_manual(values = c("red", "orange", ...)
```

**Comment by mieko-cc** [comment]
> Hey mieko-cc,
> 
> The clusters are plotted using ggplot, so you can modify them using the gg structure. So for example:
> 
> ```
> clonalNetwork(...) + 
>     scale_color_manual(values = c("red", "orange", ...)
> ```

Yes, it works!

Thank you ~_~
