### ISSUE TITLE
cannot find the function of clonalNetwork()

### ISSUE THREAD

**Issue by mieko-cc** [ncborcherding/scRepertoire#127]
Thanks for the nice function of clonalNetwork(), but in the version of scRepertoire1.4.0, this function can not work, and I can not install the more development version.
Could you please show me how to use clonalNetwork() ?
Thank you！

**Comment by ncborcherding** [comment]
Duplicate of #126 

Need to install the github dev version, see https://github.com/ncborcherding/scRepertoire/issues/126#issuecomment-986983172
