### ISSUE TITLE
clonesizeDistribution can be used BCR?

### ISSUE THREAD

**Issue by Liripo** [ncborcherding/scRepertoire#128]
`clonesizeDistribution`  Can it be used in BCR?
I use it but get an error: `Error in gammfit[[bestfit]] :  attempt to select less than one element in get1index`
I checked, it is in the `powerTCR::fdiscgammagpd` function error

**Comment by ncborcherding** [comment]
Hey Liripo, 

Technically you should be able to use ```clonesizeDistribution()``` for BCR - it was not designed that way (it is a wrapper function for the *powerTCR* package). ```powerTCR::fdiscgammagpd``` uses a mixed model for the fitting and just based on the error it looks like the gamma portion of the model is not working (this has less to do with scRepertoire than powerTCR, but happy to look into it more)

Would you mind giving me your ```sessionInfo()``` and maybe a reproducible example (code + sample data) - you can post here or [email me](mailto:ncborch@gmail.com). 

Thanks,
Nick

**Comment by ncborcherding** [comment]
Hey Liripo, 

Thanks for sending code along with the data - the issue specifically was not allowing for larger thresholds. What I ended up doing is adding a new parameter (**threshold**) to```clonesizeDistribution()``` 

<img width="270" alt="Screen Shot 2021-12-12 at 5 08 46 AM" src="https://user-images.githubusercontent.com/22754118/145709967-95e4c46d-d46d-4f97-9c03-4369714740e1.png">

Here is the result:

<img width="396" alt="Screen Shot 2021-12-12 at 5 08 43 AM" src="https://user-images.githubusercontent.com/22754118/145709989-d22f9b84-c2ad-4b6d-ad64-50495560d64f.png">

I still need to update the vignette, but I just sent a comit for the function to the dev version.

Thanks for bringing this up!

Nick
