### ISSUE TITLE
scatter compare after combine with seurat

### ISSUE THREAD

**Issue by HocheolJang426** [ncborcherding/scRepertoire#131]
Hi
I'd like to use scatterClonotype() in your package.
TCR data are already combined with seurat object, and seurat object are subclustered.
I want to show scatter of clonetype between two seurat cluster
How can I modify your scatterClonotype function?

I already tried expression2List function like this, but error comes;
> newList <- expression2List(seurat, group = "seurat_clusters")
Error in expression2List(seurat, group = "seurat_clusters") : 
  unused argument (group = "seurat_clusters")

As I told you, seurat object had already subclustered and had each own cluster number

How can I solve this problem?

**Comment by ncborcherding** [comment]
Hey HocheolJang426, 

What version of scRepertoire are you using? Most recent versions of scRepertoire have adopted the Seurat parameter usages (to make it easier for users), so for ```expression2List()``` there is no longer **group**, but **split.by**

If running the msot recnt versions > 1.3.3, you should also be able to call ```scatterClonotype()``` directly on the seurat object by the following:

```
scatterClonotype(SeuratObject,
                   split.by = "seurat_clusters", 
                    x.axis = "Cluster 1", 
                    y.axis = "Cluster 2",
                    ...)
```

Let me know if you have any more questions.

Nick
