### ISSUE TITLE
Using compareClonotypes function with Seurat Object

### ISSUE THREAD

**Issue by HocheolJang426** [ncborcherding/scRepertoire#132]
I really thanks for your help.
I have one question

I want to show the change of top 10 TCR clonetype according to time point
My scTCR data and scRNA data are merged using combineExpression function
of course, my scRNA data have time point meta data

I want to use compareClonotypes function, but How can I use this function in Seurat object?
How can I modify the code?

**Comment by ncborcherding** [comment]
Hey HocheolJang426, 

```compareClonotype()``` can be used with either the list of combined TCR/BCR or with a Seurat object (after ```combineExpression()```). To use a Seurat object, you'll just need to indicate the variable along the x-axis using **split.by=**. If **split.by** is left NULL, the function will automatically use the cluster assignments. 

Let me know if you have any other questions.

Nick

**Comment by HocheolJang426** [comment]
It worked! thanks!
