### ISSUE TITLE
bioconductor tutorial error

### ISSUE THREAD

**Issue by ckfromCN** [ncborcherding/scRepertoire#133]
I am running bioconductor's sample code with the problem
``` R
for (i in seq_along(contig_list)) {
    contig_list[[i]] <- stripBarcode(contig_list[[i]], column = 1, connector = "_", num_connects = 3)
}
```

After my attempts, setting the parameter to `contig_list[[i]] <- stripBarcode(contig_list[[i]], column = 3, connector = "_", num_connects = 1) ` works fine

**Comment by ncborcherding** [comment]
Hey ckfromCN, 

The built-in data and vignette for both bioconductor and the current github repo does not require the ```stripBarcode()``` function, as there are no prefixes for the barcodes in the **contig_list** data set. I built the function by request from some users for pre and post processing after ```combineTCR()```, but is generally not required for the workflow. 

I will clarify this in the documentation and vignette - will be updated with the next bioconductor relsease. 

Thanks,
Nick
