### ISSUE TITLE
Length distribution and Gene usage with combined object

### ISSUE THREAD

**Issue by annecar** [ncborcherding/scRepertoire#137]
HI Nick, 
I just noticed that "lengthContig" and "vizGenes" do not seem to work when working with a combined (Seurat and TCR contig) object. Any reason for this? 
I run: 
vizGenes(COVPat_TCR_freq2022, gene = "V", chain = "TRB", plot = "bar", order = "variance", scale = TRUE)
Error: Cannot find '1' in this Seurat object

but when i run 
vizGenes(combinedTCRs, gene="V", chain = "TRB", order= "variance")

it works. 
Any idea? 
Thanks a lot 
Anne

**Comment by ncborcherding** [comment]
Hey Anne, 

I just noticed this too the other day - all the viz functions should work with a single-cell object. I think something must have gone wrong with my version control. I will fix it ASAP.

Thanks,
Nick

**Comment by annecar** [comment]
Great! Happy to hear that is not mi mistake… 
And thanks for taking care of this. 
Bye! 
Anne 


Anne Eugster, PhD
Scientist AG Bonifacio

Technische Universität Dresden
Center for Molecular and Cellular
Bioengineering (CMCB) 
Center for Regenerative Therapies (CRTD)
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: ***@***.*** 
Webpage: http://www.tu-dresden.de/cmcb/crtd/

**Comment by ncborcherding** [comment]
I think I got it figured out now in the dev version, I tested it on my end, but please let me know if you still experience an issue and I can troubleshoot more.

Thanks again for reaching out!

Nick

**Comment by annecar** [comment]
Dear Nick 
Thanks a lot for troubleshooting. I installed the dev version, but still i se ether same error…. 

Anne

Anne Eugster, PhD
Scientist AG Bonifacio

Technische Universität Dresden
Center for Molecular and Cellular
Bioengineering (CMCB) 
Center for Regenerative Therapies (CRTD)
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: ***@***.*** 
Webpage: http://www.tu-dresden.de/cmcb/crtd/

**Comment by ncborcherding** [comment]
I think there was an issue with the newer ```vizGenes()``` function, but ```lengthContig()``` is working for me. Made a commit to fix vizGenes, might want to try reinstall the dev version and restart your R instance. 

Nick

**Comment by annecar** [comment]
You are right, lengthContig is indeed working! 
Thanks you. Let me know if there are any news about visGene
Bye! 
Anne


Anne Eugster, PhD
Scientist AG Bonifacio

Technische Universität Dresden
Center for Molecular and Cellular
Bioengineering (CMCB) 
Center for Regenerative Therapies (CRTD)
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: ***@***.*** 
Webpage: http://www.tu-dresden.de/cmcb/crtd/

**Comment by annecar** [comment]
Hi Nick, 
Any news about the problem with vizGenes? 
Best 
Anne 


Anne Eugster, PhD
Scientist AG Bonifacio

Technische Universität Dresden
Center for Molecular and Cellular
Bioengineering (CMCB) 
Center for Regenerative Therapies (CRTD)
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: ***@***.*** 
Webpage: http://www.tu-dresden.de/cmcb/crtd/

**Comment by ncborcherding** [comment]
Hey Anne, 

Should be already fixed in the dev branch. 

Nick

**Comment by annecar** [comment]
perfect i will try! 
thanks a lot 
anne 


Anne Eugster, PhD
Scientist AG Bonifacio

Technische Universität Dresden
Center for Molecular and Cellular
Bioengineering (CMCB) 
Center for Regenerative Therapies (CRTD)
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: ***@***.*** 
Webpage: http://www.tu-dresden.de/cmcb/crtd/
