### ISSUE TITLE
Does parseBCR have a mistake?

### ISSUE THREAD

**Issue by JanMichler** [ncborcherding/scRepertoire#138]
Dear Nick, 

thank you for this very useful package. 
Just by chance I came across a weird observation that I made and I wanted to mention it to you:

I am working with a contig file (filtered_contig_annotations.csv from cellranger) like this:
![image](https://user-images.githubusercontent.com/78206705/151408928-cc285430-99be-42ad-9f6c-6e4804ed550c.png)

If you look at lines 1 and 2, you see that these two belong to the same cell barcode (AAACCTGAGATGTGTA). One sequence represents a heavy chain (contig 1), one sequence represents a light chain (contig 2). 

If you look at lines 14 and 15, you see that these two also belong to the same cell barcode (AAACCTGCATTATCTC). This time contig 1 is the light chain, and contig 2 is the heavy chain.

I noticed that only in cases where the first of the two contigs which are associated with a cell barcode is the light chain sequence, the output of combineBCR is correct.
See below the output of combineBCR for my contig file - subsetted to the relevant cell barcodes.

![image](https://user-images.githubusercontent.com/78206705/151396720-8e7e408b-52fe-4426-9292-3b3680ea9a59.png)

You see, that only in one of the two cases, the information of both chains is there.

Is there a reason why this is coded in this way, or is this a mistake?
I hope I haven't overlooked something.

Best wishes and greetings from Switzerland
Jan

**Comment by ncborcherding** [comment]
Hey Jan, 

Thank you for reaching out! I think you have identified an error when the BCR contigs are parsing - I will work on fixing it. If you don't mind, could you [email me](mailto:ncborch@gmail.com) the reproducible example above (it is very well layed out and would help find the issue). 

If not, I can also work using the example data. 

Thanks again,
Nick

**Comment by JanMichler** [comment]
Hi Nick,

thanks for your prompt reply.
I will send you sample data and also a proposal of how to fix it - I did already a fix that seems to work for me.
Best,
Jan

**Comment by ncborcherding** [comment]
Hey Jan,

Got the changes committed to both the master and dev branches. Thanks - of the 138 issues that have been opened, you are the 2nd person to send the code to fix it!!!

Very cool.

Nick
