### ISSUE TITLE
vizGenes() 

### ISSUE THREAD

**Issue by amkhasawneh** [ncborcherding/scRepertoire#141]
Hello.

Thank you very much. scRepertoire is very useful! 

I have run into one issue--namely, that I can't invoke the vizGenes() function. Am I missing something important? 
I have installed the package both from CRAN and remotes/GitHub.

Thank you.

Abdullah

**Comment by ncborcherding** [comment]
Hey Abdullah, 

Thanks for reaching out.

Would you mind sharing your versions of scRepertoire? 

```vizGene()``` is not yet available in the bioconductor version - but both the master and dev branch on github contain the function. 

Thanks,
Nick

**Comment by amkhasawneh** [comment]
Hello, Nick.

Thank you very much for the reply. I apologize for the late reply, but I was not at work, and had no access to the computer there.

Running `sessionInfo()` shows that I have scRepertoire_1.4.0.

Thanks again.
Abdullah

**Comment by ncborcherding** [comment]
Hey Abdullah, 

No problem! Unfortunately, there was an issue with version control between the bioconductor vs github repos. 

Should be able to access ```vizGenes()``` by installing the github repo and restarting your R session:

```
devtools::install_github("ncborcherding/scRepertoire")
```

Let me know if that works or there are any other issues. 

Thanks,
Nick

**Comment by amkhasawneh** [comment]
Hey Nick,

Thanks a lot. 
I have the function now! I'll start working on it Monday.

Best,
Abdullah
