### ISSUE TITLE
error with combineTCR "replacement has 1 row, data has 0"

### ISSUE THREAD

**Issue by kkearns13** [ncborcherding/scRepertoire#143]
Hi there, I've been trying to use combineTCR with TCR repertoires reconstructed using TRUST4 on SMARTseq samples (the output files don't have all the columns that are required by the combineTCR function so I had to add some, see below), but I have been running into an issue that says:

> Error in `$<-.data.frame`(`*tmp*`, "sample", value = "TS0013") : replacement has 1 row, data has 0. 

I saw that someone encountered a similar issue (#97) and I tried the same solutions listed (i.e. making productive and is_cell as TRUE, installing the current version of scRepertoire) but I still get the same error.

This is the code I used to adjust the data before running combineTCR:
```
adjust_contig <- lapply(contig_list, function(x) {
  x$chain <- substr(x$C, 1, 3)
  x$productive <- TRUE
  x$cdr3 <- "None"
  x$barcode <- gsub("(.*)_assemble\\d+", "\\1", x$cid)
  x$is_cell <- TRUE
  return(x)
})
```

Thank you for any help you can provide!

**Comment by ncborcherding** [comment]
Hey kkearns13, 

Good to hear from you again and thanks for checking out other issues before posting. 

For TRUST4 outputs, there are 2 options:

- There is a export function in TRUST4 to make a csv format similar to 10x. 
- The other option is there is a ```combineTRUST4()``` function as well. 

Let me know if those options don't work. 

Nick

**Comment by kkearns13** [comment]
Hi Nick,

Thank you for the quick reply and suggestions! 

For some more background, the samples were sorted in single cell wells and sequenced from there. I ran TRUST4 using the SMARTseq wrapper (since that was the method by which the samples were sequenced) and it doesn't output the typical barcode_report.tsv file that you would normally get without the wrapper, which is the file that you could use that `barcoderep-to-10x` function you're talking about. Maybe I'll try redoing the reconstruction using the "plain" TRUST4 code and see if I can get that to work.

I tried using the SMARTseq output plain as it is and I've also tried converting it to an AIRR format since I saw the TRUST4 GitHub had a script for that, but they both don't work (I was just trying anything... I'm not sure if that should have worked anyway since I saw on the vignette that scRepertoire takes output from the 10x Cell Ranger pipeline).

I tried using `combineTRUST4()` function but would get errors like:
> Error in str_split(df[[i]]$chain1, ",", simplify = TRUE)[, seq_len(6)] : subscript out of bounds

I guess a more naive question I have is whether this type of data without barcodes is amenable to scRepertoire or if I should try a different tool?

Thank you so much! Sorry if these are naive questions/issues, still trying to get a grasp of all this!

**Comment by ncborcherding** [comment]
Hey kkearns, 

I see now, thanks for the explanation. Would you mind [emailing](mailto:ncborch@gmail.com) a sample of your data? As of right now I don't think scRepertoire would support this format, it is highly dependent on the initial format of the contigs. But if I have a example, I might be able to adjust ```combineTCR()``` or ```combineTRUST4()``` to work with your data (and others in the future). 

I think in terms of R tools that might work - [immunarch](https://immunarch.com/articles/v2_data.html) might be your best bet. They are probably the gold standard for immune repertoire toolkit and have a number of formats they support for loading. Downside is it doesn't (yet) have the best interaction with single-cell data.

Nick

**Comment by ncborcherding** [comment]
Hey Kendall, 

Finally got the universal ```loadContig``` function up, but unfortunately, combineTCR() relies on barcoded sequences in order to assemble clonotypes, so I can not get your data to work without significant changes to ```combineTCR()```. Don't know if this is still an issue, but wanted to follow up. 

Apologies,
Nick
