### ISSUE TITLE
Way to use ScRep with own methodology 

### ISSUE THREAD

**Issue by dsrai** [ncborcherding/scRepertoire#145]
Hi, I'm working on a novel method to sequence TCRs with no barcoding. 

I have paired alpha and beta clonotypes and proportions- Is there a way to use ScRep in this circumstance?

**Comment by ncborcherding** [comment]
scRepertoire is set up to work with barcode-based TCR sequences. Probably the best alternative is [immunarch ](https://immunarch.com/)for both barcode and nonbarcode based sequencing.

Nick
