### ISSUE TITLE
Clarification between combine contigs as list and createHTOContigList

### ISSUE THREAD

**Issue by denvercal1234GitHub** [ncborcherding/scRepertoire#146]
Hi Nick, 

Thank you again for a great package. 

I want to clarify whether the "contig_list <- list(S1, S2, S3, S4)" is just one of the two inputs of the createHTOContigList()? For example, if I have contig annotations and gene expression from the same donors and sample types, then I can just use createHTOContigList() to merge them for integrative analysis? 

For me, I had previously analyzed the gene expression and scTCR-seq data obtained from a tissue (3 donors, 2 sorted cell populations R5pos and R5neg if you remembered). Now I have data from the same donors and the same sorted cell populations, but they were from another tissue type. My aim is to see if there is clonal relationship between the cells in these 2 tissue types. Would you mind letting me know how to best proceed? Should I just make them all into 1 list?

I saw the tutorial (https://ncborcherding.github.io/vignettes/vignette.html) has this situation of paired blood and tumor, so quite similar to mine, but wanted to make sure. 

Thank you again very much for your help!

Similar issue = #51

**Comment by ncborcherding** [comment]
Hey Quang, 

Good to hear from you again!!

```createHTOContigList()``` is intended to be used with the multiplexed filter_contig_annotations.csv file and a seurat object to generate a contig_list to be used. So after using ```createHTOContigList()```, the workflow for ```combineTCR()``` and ```combineExpression()``` is the same. 

In the scenario of > 1 tissue type, I think for the simple clonal measure, you should separate them. For instance ```clonalHomeostasis()``` should be much different between tissues. However, if ultimately, you just want to combine the contigs and seurat object, it doesn't really matter. The only issue might be how ```combineExpression()``` classifies the frequency of the clonotypes. 

Hope that helps,
Nick

**Comment by denvercal1234GitHub** [comment]
Thanks Nick. 

I have 2 Seurat objects. One for blood and one for another tissue. Is there any caution when I merge these two Seurat objects before putting them in the combineExpression()? My goal is to examine if there is clonal sharing between the tissues among the clusters.

**Comment by ncborcherding** [comment]
The only concern I would have is making sure you somehow differentiate the barcodes of the two seurat objects in order to eventually use ```combineExpression()```, but other than that, you should be good to go.
