### ISSUE TITLE
issues with compareClonotypes

### ISSUE THREAD

**Issue by nbahlis** [ncborcherding/scRepertoire#150]
Hi Nick,

thank you for a wonderful tool.
I downloaded the sceRepertoire latest dev version.
When I run compareClonotypes as per below it is returning an empty plot without stating an error. 
compareClonotypes(combined, numbers = 10, samples = c("PB", "BM"), 
                  cloneCall="aa", graph = "alluvial")
Any advice what may be going wrong here?

many thanks
nizar

**Comment by ncborcherding** [comment]
Hey Nizar, 

What is your code for ```combineTCR()``` or ```combineBCR()```? The *samples* parameter is filtering for the sample parameter in the combined object, so potentially they are mismatched and returning nothing?

Nick
