### ISSUE TITLE
Trouble with clonalDiversity

### ISSUE THREAD

**Issue by xiaotong-666** [ncborcherding/scRepertoire#151]
Hi Nick,
Thanks for this great package! Very useful. 

When I try to calculate  the clonal diversity of T cells using the funcition "clonalDiversity" in the package  of dev version ,  the results  were confusing.  Diffferent results would be got, when I used the different "df" which included the product of expression2List() and combineExpression().

What is  the difference between the product of "expression2List() " and "combineExpression()", when I use the function "clonalDiversity()"?

Thanks a lot
annecar

**Comment by ncborcherding** [comment]
Hey, 

Thanks for reaching out. What kind of differences are you seeing? Also what specific version are you using?

[Another user](https://github.com/ncborcherding/scRepertoire/issues/148#issue-1173289671) noted there was an issue with the naming variables when using the group.by parameter in ```clonalDiversity()``` which might be the underlying issue. Updating the dev version might help if you are seeing similar results.

But there should be no real fundamental difference from using the single-cell object (from ```combineExpression()```) or the list from ```expression2List()``` - in fact, when using a seurat object for ```clonalDiversity()```, the underlying processing before the diversity estimates use the function ```expression2List()```.

<img width="537" alt="Screen Shot 2022-03-25 at 5 56 43 AM" src="https://user-images.githubusercontent.com/22754118/160108661-f6f9dc97-6cf8-4e95-8207-9afe097a512c.png">

There is also a major caveat that ```clonalDiversity()``` is also using bootstraps for estimates, so there is a degree of randomness in the diversity estimates (but not major changes).

Thanks,
Nick

**Comment by ncborcherding** [comment]
I am going to close this issue due to lack of activity, please feel free to follow up.
