### ISSUE TITLE
Question about 'CTstrict' in combineBCR()

### ISSUE THREAD

**Issue by xiachenrui** [ncborcherding/scRepertoire#152]
Dear Nick,
      I got confused by combineBCR() output. In help document: ` Clonotype clusters will then be labeled with "LD" with the CTstrict header.` So in my opinion, 'CTstrict' column will be used to define the clonoType after combineBCR(). But I notice I can only choose one of ['gene','nt','aa','gene+nt'] when using quantContig() or other funcitons. I want to know if and how  I can use the 'CTstrict'  in BCR data.
I will so happy if you can give any comments on the difference of using 'CTstrict'  ,'aa' or 'nt'.

----------------------------------------------------------------------
```{R}
> quantContig(combined_bcr, cloneCall="CTstrict", scale = T,chain = 'IGH',group.by='group')
Error in x[[jj]][iseq] <- vjj: replacement has length zero
Traceback:

1. quantContig(combined_bcr, cloneCall = "CTstrict", scale = T, 
 .     chain = "IGH", group.by = "group")
2. `[<-`(`*tmp*`, i, 4, value = structure(list(), .Names = character(0), row.names = 1L, class = "data.frame"))
3. `[<-.data.frame`(`*tmp*`, i, 4, value = structure(list(), .Names = character(0), row.names = 1L, class = "data.frame"))

```

**Comment by ncborcherding** [comment]
Hey xiachenrui, 

Thanks for reaching out and pointing out the inconsistency. 

For the ```combineBCR()``` workflow "gene+nt" will pull the CTstrict column to use for the functions like ```quantContig()```

So if you want to examine the groups computed by edit distance, you could use:

```
quantContig(combined_bcr, cloneCall="gene+nt", scale = T,chain = 'IGH',group.by='group')
```

However, I will change the documentation to be more specific and likely the calls to avoid confusion. You have also given me the idea to allow users to pass the column headers directly into **cloneCall**, which I think is a great idea. 

Thanks,
Nick

**Comment by xiachenrui** [comment]
Thank you a lot !
I am really enjoy using scRepertoire !

chenrui

**Comment by ncborcherding** [comment]
This has been updated in the dev version on GitHub - all the documentation now refers to "strict" to grab the gene+nt (for TCR) and cluster+gene (BCR). In addition, using "CTstrict", "CTaa", "CTnt", "CTgene" will also pass for any **cloneCall** parameter in scRepertoire.
