### ISSUE TITLE
Problem with gene names

### ISSUE THREAD

**Issue by mihem** [ncborcherding/scRepertoire#153]
Hi @ncborcherding,

thanks again for the great package and constant improvements and additions.

I struggle with the gene names:

In an older version after `combineBCR` with the settings `removeNA = TRUE` (so only keep if heavy and light chain available) I got genes names (`CTgene`) like: `NA_IGLV3-25.IGLJ2.IGLC2`. In the recent version from github `scRepertoire_1.3.5`, this clone is now split into two entries `IGHV4-34.IGHJ4.IGHM_IGLV3-25.IGLJ2.IGLC2` and `IGHV4-34.IGHJ4.IGLC2_IGLV3-25.IGLJ2.IGHM`.
Shouldn't those two entries be the same and the second entry is incorrect because it has a `IGLC2` in the heavy chain and a `IGHM` in the light chain?

This has due to with the `makeGene` function. If I only change the `makeGenes` function, e.g. from here https://github.com/ncborcherding/scRepertoire/blob/9ebeff3e1c87576975c1fbc1a057b76b56432fdd/R/utils.R but keep all the remaining functions from the most recent scRepertoire version, I end up with the previous version `NA_IGLV3-25.IGLJ2.IGLC2`.

It this a bug or a misunderstanding on my side?

What I would like to get is a gene name without NA, but also a distinct one.

Thanks,
Mischko

**Comment by ncborcherding** [comment]
Hey Mischko, 

Thanks for reaching out - 

Can I ask what code you changed for the ```makeGenes()``` function? Would like to evaluate and maybe incorporate into the package. 

There was an issue with the NA values in the heavy chain assignments due to the internal ```parseBCR()``` function that was updated in the most recent dev version (1.5.2) and might have solved this issue. This is most likely the cause of the **NA_IGLV3-25.IGLJ2.IGLC2**. If you install the dev version, I would expect the NA issue to be resolved:

```
devtools::install_github("ncborcherding/scRepertoire@dev")
```

Thanks,
Nick

**Comment by mihem** [comment]
Hey Nick,

thanks for the super fast reply.

Sorry for not being clear. I just stole your code from an earlier version, so

```
makeGenes <- function(cellType, data2, chain1, chain2) {
    if(cellType %in% c("T-AB", "T-GD")) {
        data2 <- data2 %>% 
            mutate(TCR1 = ifelse(chain == chain1, paste(with(data2, 
            interaction(v_gene,  j_gene, c_gene))), NA)) %>%
            mutate(TCR2 = ifelse(chain == chain2, paste(with(data2, 
            interaction(v_gene,  j_gene, d_gene, c_gene))), NA))
    }
    else {
        data2 <- data2 %>% 
            mutate(IGKct = ifelse(chain == "IGK", paste(with(data2, 
            interaction(v_gene,  j_gene, c_gene))), NA)) %>%
            mutate(IGLct = ifelse(chain == "IGL", paste(with(data2, 
            interaction(v_gene,  j_gene, c_gene))), NA)) %>%
            mutate(IGHct = ifelse(chain == "IGH", paste(with(data2, 
            interaction(v_gene, j_gene, d_gene, c_gene))), NA))
    }
    return(data2)
    
}
```

This then lead to **NA_IGLV3-25.IGLJ2.IGLC2**. Now (in the process of revision ;) ) I reanalyzed the dataset and now suddenly, there are no NA (which is great), but instead there are multiple CTgene, which should be the same in my understanding and are just caused by an inconsistency of order? This is also true for the development version. I end up with **IGHV4-34.IGHJ4.IGLC2_IGLV3-25.IGLJ2.IGHM** but also the same gene (both CTaa and CTnt) called **IGHV4-34.IGHJ4.IGHM_IGLV3-25.IGLJ2.IGLC2**. Happy to share data if that helps?

Thanks,
Mischko

**Comment by ncborcherding** [comment]
Hey Mischko, 

Thanks for sending along the data - What version of scRepertoire are you currently using?

When I used the new 1.5.2 from the dev branch, I get some clonotypes using A vs M heavy chains, but no mismatches in the the chains between heavy or light.

![Screen Shot 2022-04-14 at 9 47 33 AM](https://user-images.githubusercontent.com/22754118/163415582-021e9a1a-1916-4a6c-bf02-624870a3cd4d.png)

Thanks,
Nick

**Comment by mihem** [comment]
Thanks Nick. Oh that's interesting, I think it actually boilds down to `read_csv` from `readr` vs `read.csv` from `base` .

```
dat1 <- read_csv(file.path("raw_merge_v6", "p1_biopsy1_bcr", "outs", "filtered_contig_annotations.csv"))
combined_bcr_dat1 <- scRepertoire::combineBCR(dat1,
                        samples = "p1",
                        ID = "biopsy1",
                        removeNA = TRUE,
                        removeMulti = TRUE) 

combined_bcr_dat1[[1]] |>
    dplyr::filter(str_detect(CTgene, "IGHV4-34.IGHJ4")) |>
    tibble()|>
    dplyr::count(CTgene)
```

```
  CTgene                                        n
  <chr>                                     <int>
1 IGHV4-34.IGHJ4.IGHA1_IGLV3-25.IGLJ2.IGLC2     1
2 IGHV4-34.IGHJ4.IGHM_IGLV3-25.IGLJ2.IGHM      40
3 IGHV4-34.IGHJ4.IGHM_IGLV3-25.IGLJ2.IGLC2     32
4 IGHV4-34.IGHJ4.IGLC2_IGLV3-25.IGLJ2.IGHA1     4
5 IGHV4-34.IGHJ4.IGLC2_IGLV3-25.IGLJ2.IGHA2     2
6 IGHV4-34.IGHJ4.IGLC2_IGLV3-25.IGLJ2.IGHM    309
7 IGHV4-34.IGHJ4.IGLC2_IGLV3-25.IGLJ2.IGLC2   247
```

```
dat2 <- read.csv(file.path("raw_merge_v6", "p1_biopsy1_bcr", "outs", "filtered_contig_annotations.csv"))

combined_bcr_dat2 <- scRepertoire::combineBCR(dat2,
                        samples = "p1",
                        ID = "biopsy1",
                        removeNA = TRUE,
                        removeMulti = TRUE) 

combined_bcr_dat2[[1]] |>
    dplyr::filter(str_detect(CTgene, "IGHV4-34.IGHJ4")) |>
    tibble()|>
    dplyr::count(CTgene)
```


```
  CTgene                                        n
  <chr>                                     <int>
1 IGHV4-34.IGHJ4.IGHA1_IGLV3-25.IGLJ2.IGLC2     6
2 IGHV4-34.IGHJ4.IGHA2_IGLV3-25.IGLJ2.IGLC2     4
3 IGHV4-34.IGHJ4.IGHM_IGLV3-25.IGLJ2.IGLC2    625
```

So i can easily switch to base, but I would still be interested in knowing what the cause of the trouble is (and I also prefer read_csv). 

And sorry for being off topic: But how would you explain the inconsistencies between IgA and IgM?

Thanks,
Mischko

**Comment by ncborcherding** [comment]
Very interesting and way to solve the issue! I just tested out your code and got the exact same thing. My guess in terms of the difference is that I have not built any of the functions with tibble format in mind. However, I can easily add that to the ```combineTCR/BCR()``` functions - I will add that to my to do list. 

> And sorry for being off topic: But how would you explain the inconsistencies between IgA and IgM?

Isotype switching may be a sign of tertiary lymphoid structures or atleast possible germinal center?  I think you would have to show that more convincingly than just 10 cells. 

Nick

**Comment by mihem** [comment]
Sorry to continue this closes thread, just a minor thing also related to this issue.
Works well with read.csv, but I also ended up with
IGHV3-7..IGHJ4.IGHA1_IGKV1-39.IGKJ5.IGKC
IGHV3-7.IGHJ4.IGHA1_IGKV1-39.IGKJ5.IGKC

which again leads to the problem that the barcodes are not recognized as one clone if defined by gene. I think the problem is again within the `makeGenes` function.

Thanks,
Mischko

**Comment by ncborcherding** [comment]
Hey Mischko, 

No worries, always feel free to reach out if you're having issues . 

This is a weird problem as generally the ".." would mean a missing or NA gene segment in the contigs file, but you are recovering essentially the same gene breakdown. What is the breakdown of one vs the other? 

One quick fix for now (so you can move forward with the analysis), might be to use ```gsub("..", ".", variable)``` - I would do this specifically in this clone as it would also modify other clones as well. 

Nick

**Comment by mihem** [comment]
Hey Nick,

thank you. Regarding the quick fix: You are right, however, the dot needs an escape character, so I used the following in my Seurat object:

`sc_rep$CTgene <- str_replace(sc_rep@meta.data$CTgene, "\\.\\.", "\\.")`

I realized that the problem is the d gene column. In one 10x output files, it's all empty and after reading it in with `read.csv` you get a column with only NAs:
```
# A tibble: 3,727 × 1
   d_gene
   <lgl> 
 1 NA    
 2 NA    
 3 NA    
 4 NA    
 5 NA    
 6 NA    
 7 NA    
 8 NA    
 9 NA    
10 NA    
```
and in the other case, there were a few d_genes, however the missing values were not recognized as NA by read.csv, e.g.

```
# A tibble: 991 × 1
   d_gene    
   <chr>     
 1 ""        
 2 ""        
 3 "IGHD6-13"
 4 ""        
 5 ""        
 6 ""        
 7 ""        
 8 ""        
 9 ""        
10 ""        
```

So again the problem laied in reading the data. Changing the na.strings argument in read.csv solved the problem for me:

```
read.csv("filtered_contig_annotations.csv", na.strings = "")
```

Maybe it's worthwhile mentioning that in the vignette.


Best,
Mischko

**Comment by ncborcherding** [comment]
Hey Mischko, 

Thank you for running this down - I will indeed update the vignette to reflect the **na.strings** and I will update scRepertoire to process "" to NAs in the ```combineTCR()/BCR()``` functions. 

Thanks for all the help,
Nick

**Comment by mihem** [comment]
Thank you, great package.

**Comment by mihem** [comment]
@ncborcherding I saw that you already worked on fixing this "bug", great.
Unfortunately, in the example given above I still get the strange order of gene names, when using `readr::read_csv`.

```
  CTgene                                        n
  <chr>                                     <int>
1 IGHV4-34.IGHJ4.IGHA1_IGLV3-25.IGLJ2.IGLC2     1
2 IGHV4-34.IGHJ4.IGHM_IGLV3-25.IGLJ2.IGHM      40
3 IGHV4-34.IGHJ4.IGHM_IGLV3-25.IGLJ2.IGLC2     32
4 IGHV4-34.IGHJ4.IGLC2_IGLV3-25.IGLJ2.IGHA1     4
5 IGHV4-34.IGHJ4.IGLC2_IGLV3-25.IGLJ2.IGHA2     2
6 IGHV4-34.IGHJ4.IGLC2_IGLV3-25.IGLJ2.IGHM    309
7 IGHV4-34.IGHJ4.IGLC2_IGLV3-25.IGLJ2.IGLC2   247


```

I even now get this output when using `read.csv` with the dev branch. When switching back to the main branch, `read.csv`works fine while `readr::read_csv` doesn't

Best,
Mischko

**Comment by ncborcherding** [comment]
Hey Mischko,

Think I got a fix up in the dev version - I had to modify makeGenes to use str_replace_na instead of na.omit. Would you mind checking if it works from your end? If so, I will pull request to the master branch so no user has the same issue. 

Thanks,
Nick

**Comment by mihem** [comment]
Hey Nick,

does it work for you?
I end up with:

```
Error in match.names(clabs, names(xi)) : 
  names do not match previous names
```
traceback:

```
5: stop("names do not match previous names")
4: match.names(clabs, names(xi))
3: rbind.data.frame(heavy, kappa, lambda)
2: makeGenes(cellType = "B", data2)
1: scRepertoire::combineBCR(dat2, samples = "p1", ID = "biopsy1", 
       removeNA = TRUE, removeMulti = TRUE)
```
So the problem is that colnames of heavy, kappa, lambda are not the same. It works if using `bind_rows` instead of `rbind`, not sure if this is what you intended.

Best,
Mischko

**Comment by ncborcherding** [comment]
Hey Mischko,

Thanks for bearing with me - i did indeed mean ```bind_rows()``` instead of rbind - I have updated the dev version once again to reflect this and it has passed the devtools::check(). Teaches me to try to code before my daughter wakes up.

Nick

**Comment by mihem** [comment]
Hey Nick,

haha, impressive how you do this next to your family and other work .. but yes `devtools::check` at minimum, and maybe some unit testing is a good habit I guess.

Now it finally works, nice work. Same results using `read.csv` (with or without na.strings) and `read_csv` for me and no wrong ordering anymore.

Best,
Mischko
