### ISSUE TITLE
Phylogenetic tree

### ISSUE THREAD

**Issue by mihem** [ncborcherding/scRepertoire#158]
Hi Nick,

have you thought about implementing phylogenetic trees? I think this could be quite useful in many situations.
Ideally, I envision tracing clonal evolution using information from TCR/BCR plus the single cell object.

I just read about enclone, which creates phylogenetic trees with 10x data, but lacks the integration with single cell object and has a rather poor visualization I think (https://10xgenomics.github.io/enclone/pages/auto/tree.html). But maybe the output could be used for scRepertoire?

I also read that a similar extension was proposed in immunarch, but hasn't been implemented yet i think https://github.com/immunomind/immunarch/issues/150.

Thanks,
Mischko

**Comment by ncborcherding** [comment]
Hey Mischko, 

I think that is a good suggestion - I will add it to my to-do list. At least in the context of BCR, the approach would be able to map clonal lineages - I am not sure the utility of it in TCR - but it would be similar approach to TCRdist? 

Also I think immunarch just released a dev version with this exact feature (I played around with it before the release and it was pretty fun!): https://github.com/immunomind/immunarch/blob/dev/R/phylip.R

**Comment by mihem** [comment]
That would be great.
Also sas the following package just published which might be also helpful
https://dowser.readthedocs.io/en/latest/

**Comment by mihem** [comment]
Hey Nick any news on that feature? Before it was just a fun idea of mine; now a reviewer specifically asked  for that :D .

I know not the right place .. but I tried dowser and had problems with the format and in immunarch, I always got the error:
`No data in mandatory V.end column in sample airr_rearrangement!` You said you ran that successfully with 10x VDJ data?

Thank you!

**Comment by ncborcherding** [comment]
Hey Mischko,

I have tried the implementation of something similar to immcantation/immunarch, but it requires a number of additional dependencies that would make the package flag on Bioconductor. Like the Kleinstein group's approach I think this is probably better as a stand-alone package, separate from scRepertoire. However, this might change if I can solve the issues related to dependencies. 

I have gotten the immunarch pipeline to work on their example data, not 10x VDJ TCR data. 

As of right now, I am still working on it. Sorry.

Nick

**Comment by mihem** [comment]
Hello Nick,

thanks for your swift response. Ah, too bad.
But I understand that this implies quite some changes and additional dependencies.

Good luck with that, I am happy to do some early testing.

Best,
Mischko
