### ISSUE TITLE
Running scRepertoire

### ISSUE THREAD

**Issue by s849** [ncborcherding/scRepertoire#16]
Hi, 

Thank you for sharing scRepertoire. I think this will be great for my analysis. I have a couple of questions. I finished mapping and started analysis but got stuck pretty early with the following error:

> for (i in seq_along(contig_list)) 
+   {
+   contig_list[[i]] <- stripBarcode(contig_list[[i]], column = 1, connector = "_", num_connects = 3)
+ }
**Error in `[.data.frame`(as.data.frame(t(data.frame(strsplit(contigs[,  : 
  undefined columns selected**
> combined <- combineTCR(contig_list, 
+                        samples = c("Sample1", "Sample2", "Sample3"), 
+                        ID = c("Pos", "Neg", "Healthy"), cells ="T-AB")
**Error: Make sure the sample and ID labels match the length of the 
            list of data frames (df).**
> example <- addVariable(combined, name = "Patient_batch", 
+                        variables = c("b1", "b2", "b3"))
**Error in addVariable(combined, name = "Patient_batch", variables = c("b1",  : 
  object 'combined' not found**
> example[[1]][1:5,ncol(example[[1]])] # This is showing the first 5 values of the new column added
**Error in example[[1]] : object of type 'closure' is not subsettable**

Any advice will be greatly appreciated. Thanks!

**Comment by s849** [comment]
I have fixed the problem. I am now wondering whether it is possible to represent the shared clonotype data as chord plots instead of alluvial plots in the current version of scRepertoire?

**Comment by ncborcherding** [comment]
I'll mark the above issue as closed.

Unfortunately, cord plots are not built into the current version of scRepertoire. Outputs of scRepertoire can be combined with the [circilize package](https://jokergoo.github.io/circlize_book/book/). The cord plots below rely on assumptions like direction of contribution, that would make it difficult to include in scRepertoire.

![Asset 1](https://user-images.githubusercontent.com/22754118/84759685-aebb1580-af8c-11ea-930e-4a1686a95da9.png)

Feel free to [email me](mailto:ncborch@gmail.com) if you'd like help with the cord diagram.
