### ISSUE TITLE
Separate Gene Usage

### ISSUE THREAD

**Issue by amkhasawneh** [ncborcherding/scRepertoire#161]
Hello, Nick!

Thank you very much.

Not so much an issue as a general inquiry... 

When using CombineBCR() (and CombineExpression()), is there a way to maintain gene data in separate columns (i.e., v_gene, j_gene, etc., without the "full clonotype" as seen in "CTgene")? If not, do you suggest a way to "separate" them if one feels so inclined? (I'm wrestling with regular expression, with varying results.)

I'm trying to examine V-J gene usage frequency, of the heavy chains in B cells, and I would like to try that on the Seurat object, for consistency.

Thanks again.

Best,
Abdullah

**Comment by ncborcherding** [comment]
Hey Abdullah, 

Yes there is - you will need to seperate the CTgene by chain and then genes. Below would be the code I would use to isolate the genes from the CTgene column - you can then decide how to add it to the SeuratObj. 

```
BCR <- stringr::str_split(SeuratObj$CTgene, "_", simplify = TRUE)
Heavy <- stringr::str_split(BCR[,1], "[.]", simplify = TRUE)
Light <- stringr::str_split(BCR[,2], "[.]", simplify = TRUE)
```

Let me know if you have any questions!!

Nick

**Comment by amkhasawneh** [comment]
Thanks a lot!

That's very similar to what I've settled on, eventually. Here's one example, where BCR is the Seurat Object with the B cells:

`BCR$v_gene <- vapply(strsplit(BCR$CTgene, "[.]"), "[", "", 1)`

where I add a heavy-chain v_gene column to the metadata (and later deal with NAs).
