### ISSUE TITLE
Error in the combineTCR() function using v.1.6.0

### ISSUE THREAD

**Issue by aditisk** [ncborcherding/scRepertoire#163]
Hi @ncborcherding,

I recently updated to v1.6.0 and my previous script doesn't work anymore. I am getting an error at the combineTCR() step.

Error: Seems to be an error in the naming of the contigs, ensure 
            the barcodes are labeled like, AAACGGGAGATGGCGT-1 or 
            AAACGGGAGATGGCGT, use stripBarcode to get the basic 
            format
            
My barcodes do have a prefix (Pt_27_Post_Tumor_AAAGCAATCATTTGGG-6) but this has not been a problem in the previous versions. Has something changed recently ? 

Thanks

**Comment by ncborcherding** [comment]
Hey Aditisk, 

Thanks for reaching out - not sure what version you started with, but the only change in the barcode modification is now IDs are optional. 

I would make sure the **-number** at the end of the barcode matches, for example - Pt_27_Post_Tumor_AAAGCAATCATTTGGG-6 vs Pt_27_Post_Tumor_AAAGCAATCATTTGGG-**1**. If the filtered_contig files have this already, no problem, but the default output for 10x is to use **-1** (unless you are highly multiplexed.

Let me know if you keep having issues. 

Nick

**Comment by aditisk** [comment]
Thanks for the quick response. These contig files are actually modified to subset a certain cell type. I used the Seurat metadata sheet to get the barcodes of the cells I’m interested in and subsetted the original filtered_contigs.csv file by modifying the barcodes to match my Seurat object.

If I change the number to -1, I will have to modify my Seurat object again to be able to add this information back. Could you suggest an easier to way to do this ? I’ve used the cellranger aggr command which is why all the samples (except the 1st one) end with suffix like -6 etc.

Most recently I was using v1.5.3, will reverting to that solve my problem since I was able to make it work with barcodes ending in numbers other than -1 ?  Thanks a lot.

**Comment by ncborcherding** [comment]
> Most recently I was using v1.5.3, will reverting to that solve my problem since I was able to make it work with barcodes ending in numbers other than -1 ?

All version will work with numbers other than -1, but the contig_list and seurat object need to match the ending number for it to work. There is no change in 1.6 that would be causing this issue specifically. 

Just based on your experimental set up - I think it would be easier to modify the list that is the output of ```combineTCR()```. There is actually no direct support for the outputs of the cellranger aggr, as it does not have a standardized output (but it is something to keep in mind for the future).

What are the outputs of: 
```
head(SeuratObj@meta.data) 
head(combinedTCR[[1]])
```

**Comment by aditisk** [comment]
I am sending you an email with the requested outputs instead of posting data here. I will close this ticket and comment once we find a solution in case anyone else has the same issue. Thanks.

**Comment by aditisk** [comment]
Quick update - I was able to solve this issue by downloading the package on Github using this command:

devtools::install_github("ncborcherding/scRepertoire")
