### ISSUE TITLE
combineTCR with gd T cells

### ISSUE THREAD

**Issue by immune-sc** [ncborcherding/scRepertoire#164]
Hey Nicholas thank you so much for developing this great package.

Previously I have been able to combineTCR with ab and gd TCRs fine, but I think recently I updated to version 1.5.2 and now have problems with the gd TCRs

contigsAB <-read.csv(".../abTCR/filtered_contig_annotations.csv")
contigsGD <-read.csv(".../gdTCR/filtered_contig_annotations.csv")

combinedAB <-combineTCR(contigsAB,
                        samples = ("B35"),
                        cells = "T-AB",
                        removeMulti = FALSE)

combinedGD <-combineTCR(contigsGD,
                        samples = ("B35"),
                        cells = "T-GD",
                        removeMulti = FALSE)

> str(contigsGD)
'data.frame':	809 obs. of  31 variables:
 $ barcode              : chr  "AAACGGGAGACTTGAA-1" "AAACGGGAGACTTGAA-1" "AAACGGGCAGTATGCT-1" "AAACGGGGTACTCTCC-1" ...
 $ is_cell              : logi  TRUE TRUE TRUE TRUE TRUE TRUE ...
 $ contig_id            : chr  "AAACGGGAGACTTGAA-1_contig_1" "AAACGGGAGACTTGAA-1_contig_2" "AAACGGGCAGTATGCT-1_contig_1" "AAACGGGGTACTCTCC-1_contig_1" ...
 $ high_confidence      : logi  TRUE TRUE TRUE TRUE TRUE TRUE ...
 $ length               : int  691 572 552 553 659 578 599 615 559 545 ...
 $ chain                : chr  "TRG" "TRD" "TRD" "TRD" ...
 $ v_gene               : chr  "TRGV9" "TRDV2" "TRDV1" "TRDV1" ...
 $ d_gene               : chr  "" "" "TRDD2" "" ...
 $ j_gene               : chr  "TRGJP" "TRDJ1" "TRDJ1" "TRDJ1" ...
 $ c_gene               : chr  "TRGC1" "TRDC" "TRDC" "TRDC" ...
 $ full_length          : logi  TRUE TRUE TRUE TRUE TRUE TRUE ...
 $ productive           : logi  TRUE TRUE TRUE TRUE TRUE TRUE ...
 $ fwr1                 : chr  "AGHLEQPQISSTKTLSKTARLECVVS" "IELVPEHQTVPVSIGVPATLRCSMK" "AQKVTQAQSSVSMPVRKAVTLNCLYE" "AQKVTQAQSSVSMPVRKAVTLNCLYE" ...
 $ fwr1_nt              : chr  "GCAGGTCACCTAGAGCAACCTCAAATTTCCAGTACTAAAACGCTGTCAAAAACAGCCCGCCTGGAATGTGTGGTGTCT" "ATTGAGTTGGTGCCTGAACACCAAACAGTGCCTGTGTCAATAGGGGTCCCTGCCACCCTCAGGTGCTCCATGAAA" "GCCCAGAAGGTTACTCAAGCCCAGTCATCAGTATCCATGCCAGTGAGGAAAGCAGTCACCCTGAACTGCCTGTATGAA" "GCCCAGAAGGTTACTCAAGCCCAGTCATCAGTATCCATGCCAGTGAGGAAAGCAGTCACCCTGAACTGCCTGTATGAA" ...
 $ cdr1                 : chr  "GITISATS" "GEAIGNYY" "TSWWSYY" "TSWWSYY" ...
 $ cdr1_nt              : chr  "GGAATAACAATTTCTGCAACATCT" "GGAGAAGCGATCGGTAACTACTAT" "ACAAGTTGGTGGTCATATTAT" "ACAAGTTGGTGGTCATATTAT" ...
 $ fwr2                 : chr  "VYWYRERPGEVIQFLVS" "INWYRKTQGNTMTFIYR" "IFWYKQLPSKEMIFLIR" "IFWYKQLPSKEMIFLIR" ...
 $ fwr2_nt              : chr  "GTATATTGGTATCGAGAGAGACCTGGTGAAGTCATACAGTTCCTGGTGTCC" "ATCAACTGGTACAGGAAGACCCAAGGTAACACAATGACTTTCATATACCGA" "ATTTTTTGGTACAAGCAACTTCCCAGCAAAGAGATGATTTTCCTTATTCGC" "ATTTTTTGGTACAAGCAACTTCCCAGCAAAGAGATGATTTTCCTTATTCGC" ...
 $ cdr2                 : chr  "ISYDGTVRKESG" "EKDIYG" "QGSDEQ" "QGSDEQ" ...
 $ cdr2_nt              : chr  "ATTTCATATGACGGCACTGTCAGAAAGGAATCCGGC" "GAAAAGGACATCTATGGC" "CAGGGTTCTGATGAACAG" "CAGGGTTCTGATGAACAG" ...
 $ fwr3                 : chr  "IPSGKFEVDRIPETSTSTLTIHNVEKQDIATYY" "PGFKDNFQGDIDIAKNLAVLKILAPSERDEGSYY" "NAKSGRYSVNFKKAAKSVALTISALQLEDSAKYF" "NAKSGRYSVNFKKAAKSVALTISALQLEDSAKYF" ...
 $ fwr3_nt              : chr  "ATTCCGTCAGGCAAATTTGAGGTGGATAGGATACCTGAAACGTCTACATCCACTCTCACCATTCACAATGTAGAGAAACAGGACATAGCTACCTACTAC" "CCTGGTTTCAAAGACAATTTCCAAGGTGACATTGATATTGCAAAGAACCTGGCTGTACTTAAGATACTTGCACCATCAGAGAGAGATGAAGGGTCTTACTAC" "AATGCAAAAAGTGGTCGCTATTCTGTCAACTTCAAGAAAGCAGCGAAATCCGTCGCCTTAACCATTTCAGCCTTACAGCTAGAAGATTCAGCAAAGTACTTT" "AATGCAAAAAGTGGTCGCTATTCTGTCAACTTCAAGAAAGCAGCGAAATCCGTCGCCTTAACCATTTCAGCCTTACAGCTAGAAGATTCAGCAAAGTACTTT" ...
 $ cdr3                 : chr  "CALWEVHTPLGKKIKVF" "CACDGLAGRDTRQGVTDKLIF" "CALGETFLPKLGPLKLIF" "CALGELQFPWGWGPLKLIF" ...
 $ cdr3_nt              : chr  "TGTGCCTTGTGGGAGGTGCACACCCCTCTGGGCAAAAAAATCAAGGTATTT" "TGTGCCTGTGACGGCCTAGCTGGGAGGGATACGCGCCAGGGGGTTACCGATAAACTCATCTTT" "TGTGCTCTTGGGGAAACCTTCCTACCAAAACTGGGGCCTCTTAAACTCATCTTT" "TGTGCTCTTGGGGAATTACAGTTTCCCTGGGGCTGGGGACCGCTTAAACTCATCTTT" ...
 $ fwr4                 : chr  "GPGTKLIIT" "GKGTRVTVEP" "GKGTRVTVEP" "GKGTRVTVEP" ...
 $ fwr4_nt              : chr  "GGTCCCGGAACAAAGCTTATCATTACAG" "GGAAAAGGAACCCGTGTGACTGTGGAACCAA" "GGAAAAGGAACCCGTGTGACTGTGGAACCAA" "GGAAAAGGAACCCGTGTGACTGTGGAACCAA" ...
 $ reads                : int  206 727 1308 5269 35 4027 13 5872 1051 1523 ...
 $ umis                 : int  5 5 13 11 5 24 3 23 21 23 ...
 $ raw_clonotype_id     : chr  "clonotype88" "clonotype88" "clonotype18" "clonotype206" ...
 $ raw_consensus_id     : chr  "clonotype88_consensus_2" "clonotype88_consensus_1" "clonotype18_consensus_1" "clonotype206_consensus_1" ...
 $ exact_subclonotype_id: int  1 1 1 1 1 1 1 1 1 1 ...

> str(combinedGD)
List of 1
 $ B35:'data.frame':	0 obs. of  13 variables:
  ..$ barcode : chr(0) 
  ..$ sample  : chr(0) 
  ..$ TCR1    : logi(0) 
  ..$ cdr3_aa1: logi(0) 
  ..$ cdr3_nt1: logi(0) 
  ..$ TCR2    : logi(0) 
  ..$ cdr3_aa2: logi(0) 
  ..$ cdr3_nt2: logi(0) 
  ..$ CTgene  : chr(0) 
  ..$ CTnt    : chr(0) 
  ..$ CTaa    : chr(0) 
  ..$ CTstrict: chr(0) 
  ..$ cellType: chr(0) 
>

**Comment by ncborcherding** [comment]
Hey immune-sc, 

Thanks for reaching out! Sorry about the issue - there should be an error message returned if no clonotypes are returned. Would you mind sending me your data or a randomly sampled subset of the gamma delta contigs (you can email me [here](mailto:ncborch@gmail.com))? Gamma-delta sequencing runs are more rarer and I have alignments from earlier versions of 10x Cell Ranger, but it looks like you are using >= v5. I understand if the data can't be shared - but could you let me know what version of cell ranger you are using, just so I can try to make a reproducible example.

Thanks,
Nick

**Comment by ncborcherding** [comment]
Just wanted to update here if any user is having a similar issue - 

the internal ```parseTCR()``` was updated in v1.5.2 to allow for > 3 contigs per cell. As part of the update the code was streamlined for speed and aesthetics, but accidentally dropped support for Gamma/Delta contigs. This has been updated in the dev version (v1.5.3) and can be installed using:

```
devtools::install_github("ncborcherding/scRepertoire@dev")
```

The fix will also be pushed to the master branch after some additional testing. 

Thanks @immune-sc for pointing out the issue and providing a reproducible example, very much appreciated!!
