### ISSUE TITLE
discrepancy between quantContig and clonalHomeostasis output

### ISSUE THREAD

**Issue by annecar** [ncborcherding/scRepertoire#167]
HI Nick
I have a dataset where 1 cluster has manly NAs in terms of TCR. When running quantContig this is nicely reflected by the fact that the cluster contains mainly unique clonotypes; when running clonalHomeostasis, the cluster is "filled"out by large clonotypes, and  i assume this is due to the NAs. 
I assumed that NAs would be disregarded in all the functions of scRepertoire. 
DO you have an idea what could be the problem there? 

Thank a lot! 
annecar

**Comment by ncborcherding** [comment]
Hey Annecar,

Sorry just getting back from vacation. 

What version of scRepertoire are you currently using? What does the output of ```clonalProportion()``` look like compared to the other outputs? (This function has the exact same set up as ```clonalHomeostasis()```).

The two functions are doing somewhat different things - ```quantContig()``` is really identifying the unique clonotypes, so the function simplifies everything into individual clonotypes. In contrast, the internal workings of ```clonalHomeostasis()``` is identifying the non-NA clonotypes in a group, then summarizinging them by proportion of total reads. So it could be maintaining NA calls - that being said there is a step for the removal of NA values in the function itself and running the vignette data, I do not see any NAs kept for graphing. 

Let me know and we can troubleshoot from there. Thanks.

Nick

**Comment by annecar** [comment]
Hi Nick, 
Thanks for answering! 

- We are using the 1.5.2 Version at the moment. 
-I attach you the three plots: clonalProportion, clonalHomeostasis and quantContig. 
The problem is, as you can see, that cluster 9 seems to be made of unique TCRs according to quantContig but looking at the other two, it seems to contain expansions. 
The same accounts for cluster 4 and 5 which seems to be containing mostly unique TCRs in quantContig  but the two other functions show that there are expansions. 

Does this suffice you t o get an idea? 
Let me know what else i can send. 
Thanks you very much already 
Best 
Anne 





Anne Eugster, PhD
Scientist AG Bonifacio

Technische Universität Dresden
Center for Molecular and Cellular
Bioengineering (CMCB) 
Center for Regenerative Therapies (CRTD)
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: ***@***.*** 
Webpage: http://www.tu-dresden.de/cmcb/crtd/`

**Comment by annecar** [comment]
Anne Eugster, PhD
Scientist AG Bonifacio

Technische Universität Dresden
Center for Molecular and Cellular
Bioengineering (CMCB) 
Center for Regenerative Therapies (CRTD)
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: ***@***.*** 
Webpage: http://www.tu-dresden.de/cmcb/crtd/

**Comment by annecar** [comment]
Hi Nick, 
did you receive them now? 
About Cell ranger, i need to enquire at the sequencing facility. But knowing them, i would guess it is the latest version. I will get back to you… 
Best 
Anne 


Anne Eugster, PhD
Scientist AG Bonifacio

Technische Universität Dresden
Center for Molecular and Cellular
Bioengineering (CMCB) 
Center for Regenerative Therapies (CRTD)
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: ***@***.*** 
Webpage: http://www.tu-dresden.de/cmcb/crtd/

**Comment by ncborcherding** [comment]
Hey Anne, 

The images are not showing up in github - mind [emailing](mailto:ncborch@gmail.com) me them? 

Thanks,
Nick

**Comment by ncborcherding** [comment]
Hey Anne, 

Thanks for sending the images along - I actually think this is not necessarily a problem with NAs, but more a result of NA removal. I tried to make the following to describe what might be going on (the numbers vary just for convenience). 

```quantContig()``` 
![Picture1](https://user-images.githubusercontent.com/22754118/173623547-7b650d66-8bfe-454f-ae05-abcf1aae01d5.png)


```clonalHomeostasis()```
![Picture2](https://user-images.githubusercontent.com/22754118/173623504-2d9b7868-751e-4f5f-bee3-fc0c268b61fa.png)

**Comment by annecar** [comment]
Hi Nick 
Thanks, great, that makes things clear. 
But: should nit the % of uniques in qauntContig be =Relative abundance of  the smallest fraction in clonalHomeostasis()? Here it seems, for cluster 0, the we have 80% uniques and rather 90% taken u by the small fraction… 
How can this be explained? 

Thanks again! 
Anne 


Anne Eugster, PhD
Scientist AG Bonifacio

Technische Universität Dresden
Center for Molecular and Cellular
Bioengineering (CMCB) 
Center for Regenerative Therapies (CRTD)
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: ***@***.*** 
Webpage: http://www.tu-dresden.de/cmcb/crtd/

**Comment by annecar** [comment]
Hi Nick, 
the cellranger multi version cellranger-6.1.2. version was used. 

Best 
Anne 


Anne Eugster, PhD
Scientist AG Bonifacio

Technische Universität Dresden
Center for Molecular and Cellular
Bioengineering (CMCB) 
Center for Regenerative Therapies (CRTD)
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: ***@***.*** 
Webpage: http://www.tu-dresden.de/cmcb/crtd/

**Comment by ncborcherding** [comment]
Hey Anne,

**qauntContig be =Relative abundance of  the smallest fraction in clonalHomeostasis()?** 

Not necessarily - ```quantContig()``` is showing the number of unique clonotypes (or relative proportion) - which incorporates each clonotype regardless of the grouping (Rare, Small, Medium, etc). So the numerator is different in ```quantContig()```. 

Nick
