### ISSUE TITLE
Cannot add clonotype to metadata

### ISSUE THREAD

**Issue by s849** [ncborcherding/scRepertoire#17]
Hi Nick,

Thanks again for developing scRepertoire. I have a couple more questions.

Question 1. I am working through the pipeline and it works wonderfully. I am now in the step where I need to add the clonotype information in the Seurat object metadata but it doesn't seem to be working with my data. I can generate the graph showing the composition of each cluster prior adding clonoType as factor and projecting on UMAP/TSNE. I have 4 samples - each sample has a modified columns name to include a prefix to be recognizable and make different from all other barcodes (i.e. barcodes from other samples). At first I thought this would be the problem, so I added the same prefix for the CSV file and re-run the pipeline again but with no luck. Do you have any suggestions as to what could be happening here?

Question 2. What is the best way to readjust the cutpoints for clonoTypes on my data (i.e. Single, Small, Medium, Large, and Hyperexpanded)?

Question 3. I can generate the alluvial plots, but I do not see "connections" between clonotypes in my data set. Does this also have to do with the same problem I encountered in question 1 above?

Thanks for your help!

**Comment by ncborcherding** [comment]
Thanks for the questions.

1. This is a very common issue and stems from the likely mismatch of the barcodes in the output of combineExpression() and the cell names in the single-cell object. Could you send me the output of head(combined[[1]]) and head(seuratobject[[]])? Or at least a sample of your cell names using rownames(seuratobject[[]]) and combined[[1]]$barcode.

2. When using the combineExpression() function, adjust the cloneType parameter:
`combineExpression(
  df,
  sc,
  cloneCall = "gene+nt",
  groupBy = "none",
  **cloneTypes = c(None = 0, Single = 1, Small = 5, Medium = 20, Large = 100,
    Hyperexpanded = 500)**,
  filterNA = FALSE)`


3. Alluvial plots will depend on having the clonotype information properly attached to your single-cell object, this should work once we can troubleshoot issue #1.

**Comment by s849** [comment]
Thanks for your prompt response and help. This may be the problem. This is what I get:
<img width="374" alt="Screen Shot 2020-06-23 at 4 06 28 PM" src="https://user-images.githubusercontent.com/47041278/85475808-8e322300-b56b-11ea-8f92-eab5858714df.png">
<img width="329" alt="Screen Shot 2020-06-23 at 4 06 37 PM" src="https://user-images.githubusercontent.com/47041278/85475809-8ecab980-b56b-11ea-8396-8e0f1e900f51.png">
<img width="163" alt="Screen Shot 2020-06-23 at 4 05 49 PM" src="https://user-images.githubusercontent.com/47041278/85475807-8e322300-b56b-11ea-84a5-672a9ce358ae.png">
<img width="657" alt="Screen Shot 2020-06-23 at 4 05 34 PM" src="https://user-images.githubusercontent.com/47041278/85475806-8d00f600-b56b-11ea-9e0f-1039377da9e3.png">

**Comment by ncborcherding** [comment]
**Found the issue**
Your combined[[1]][,"barcode"] has the format of **Sample1_Pos_**ADWST10:XXXXXX
While your pancreas.integrated3[[]] rownames do no have the "Sample1_Pos_" prefix

These two will need to match in order to merge the data. A simple solution might be using the stringr::str_split(barcode, "_", simplify=T)[,3] on the combined list in order to remove the prefixes and then try to combineExpression(). Or use the RenameCells() function built into Seurat.

I am going to close the issue as this is not a problem with scRepertoire itself, but feel free to [email me ](mailto:ncborch@gmail.com) and I can help you troubleshoot more on how to get everything combined.

**Comment by s849** [comment]
Hi Nick,

Thanks for your message and explanation. I adjusted the names and it works great now! Should I have any questions I will email you. Thanks again for developing such a great tool!
