### ISSUE TITLE
can we split the compareClonotypes(combined2, numbers = 40,  cloneCall="aa", graph = "alluvial") by identity?

### ISSUE THREAD

**Issue by EAC-T** [ncborcherding/scRepertoire#172]
Hi Nick,

I have 2 groups (KO and WT), I merged them and did seurat and got 4 clusters. 
I used the compareClonotypes(combined2, numbers = 40,  cloneCall="aa", graph = "alluvial") to plot the clones that are shared between my clusters. 
I have two questions, first, can we plot without the legend? (sequence of clones?)
and second, can we split the plot between KO and WT, these two are under "orig.ident" whereas my clusters are "new.ident"
For now that plot is using new.ident and I have 4 columns which is great, can I seperate them into orig.ident as well? 

Thank you a lot

**Comment by ncborcherding** [comment]
Duplicate issue posted #170
