### ISSUE TITLE
Using dataset with multiple PBMC types

### ISSUE THREAD

**Issue by scas224** [ncborcherding/scRepertoire#173]
Hi! I'm just starting to learn how to use this package in anticipation of data I am going to get from a 10x cellranger multi run, and I am working with some sample data to practice. I was wondering if it is okay to use a seurat object with scRNA data from multiple types of immune cells (macrophages, B cells, platelets, NK cells, and T cells), because obviously not all of these cells are going to match to the VDJ contig data since that is specifically for T cells. 

So far it seems to be working and let me use combineExpression, but there are many <NA> values in the clonotype columns for the non-T cells, and I am starting to get some errors (such as Error in names(x) <- value : 'names' attribute [3] must be the same length as the vector [0] when trying to use clonalNetwork), and I was wondering if that may be related and could be causing more errors with my analysis.

Is it okay to use a seurat object with all of the cells, or should I subset it to only include the T cells?
Thank you for your help!

**Comment by ncborcherding** [comment]
Hey Scas224, 

Thanks for reaching out. Should have no problems using scRepertoire for data sets with multiple lineages. The error you mention is not related to that and I have not had a reproducible example yet for that to troubleshoot. 

I am not sure if multi run provides the individual sample contig annotation files (the newer version might), but scRepertoire does [have a function](https://ncborcherding.github.io/vignettes/vignette.html#122_Multiplexed_Experiment) to demultiplex the runs. ```createHTOContigList()``` works best if you are using the individual sequencing run before integrating across multiple sequencing runs. 

Hope that helps,
Nick

**Comment by ncborcherding** [comment]
The referenced issue above is from #168
