### ISSUE TITLE
clonalDiversity function 

### ISSUE THREAD

**Issue by patti-s1** [ncborcherding/scRepertoire#175]
Hello,

I am using scRepertoire 1.6.0 but when I use the clonalDiversity function I am still only getting 4 graphs and I am missing the graph with inverse Pielou data as shown in the vignette.
Many thanks for your help!

**Comment by ncborcherding** [comment]
Hey pattie-s1, 

The Bioconductor version number is unfortunately different than GitHub (for now).  The newer clonal metric is available in the master branch. Which you can install with

```
devtools::install_github("ncborcherding/scRepertoire")
```

Thanks,
Nick

**Comment by patti-s1** [comment]
Thanks Nick,

I was able to make it work using the dev version from github

Best,
Patti
