### ISSUE TITLE
clonotypeBias Z-scores and Matrix Output

### ISSUE THREAD

**Issue by CurlsForScience** [ncborcherding/scRepertoire#176]
Hi Nick,

I am using clonotypeBias and have a couple questions. 

1) I think there is a small error in the code for returning the matrix. [Line 68](https://github.com/ncborcherding/scRepertoire/blob/master/R/clonalBias.R) has `return(mat)`, but the matrix appears to be called `bias`. So running clonotypeBias with `exportTable = TRUE` just gives an error.

2) The original [paper](https://www.biorxiv.org/content/10.1101/2021.09.20.458613v1.full) seemed to use  z-score cutoffs to determine clonotypes with actual bias. See lines 783 to 785 of the [methods](https://elifesciences.org/articles/76339.pdf). Would you consider adding these z-scores to the output matrix? I think this would be very helpful in being able to identify the biased clonotypes.

Thank you!

**Comment by ncborcherding** [comment]
Hey CurlsForScience - 

First off thanks for the excellent rundown of issues and line references!! Very helpful. 

Fixed the ```exportTable = TRUE``` issue and is up in the dev version of the package. The new dev version also includes z-score calculation of bias in the **bias** matrix, which you can get access with ```exportTable = TRUE```. I will think about the best way to add a filtering option using z-score as well. 

Thanks again,
Nick

**Comment by CurlsForScience** [comment]
Hi Nick,

Thank you so much for the update.

I noticed that the z-score you added is just the scaled bias score. According to the paper, the z-score is calculated based on the difference to the background distribution.

"On the distribution of permuted clonotype bias scores, binned by clone size, we determined expected mean and standard deviation for each clone size bin. Z scores for observed clonotype bias scores were then calculated as the number of standard deviations from the background mean (Z score = 5 corresponds to a p-value ~6*10-7)." Lines [782-785](https://elifesciences.org/articles/76339.pdf)

Would you consider adding in this z-score calculation? I think it would be helpful to identify clones that do not match the null distribution.

Thank you!

**Comment by ncborcherding** [comment]
You're absolutely correct - teaches me to read/respond before 6 am. 

I will work on adding it

**Comment by ncborcherding** [comment]
Apologies for the delay - z-score calculation based on the mean/std bias of the boot straps has now been implemented. It will appear in the data frame if exportTable = T
