### ISSUE TITLE
Question about vizGenes heatmap

### ISSUE THREAD

**Issue by fredust** [ncborcherding/scRepertoire#179]
Hello, thank you for creating this great package.
I just started to analyze the TCR data. I notice in the `vizGenes` function, I can make the heatmap to show the frequency of V-J pairs. I have multiple samples so I tried with the code in vignettes:
`vizGenes(combined[c(1,3,6,9)], 
         gene = "V", 
         chain = "TRB", 
         y.axis = "J", 
         plot = "heatmap", 
         scale =T, 
         order = "gene")`
I also export the table by setting `exportTable = T`. The heatmap seemed not consistent with the results in the exported table.  The table contained` (Var1, Var2, element.names, n, sum, varcount, sd, mean)` columns.
so I checked the code:
`plot <- ggplot(e, aes(x=Var1, y = Var2, fill =n)) + 
              geom_tile() + 
              theme_classic() + 
              theme(axis.title.x = element_blank(), #remove titles
              axis.ticks.x = element_blank(), #removes ticks
              axis.text.x = element_text(angle = 90, 
                                       vjust = 0.5, hjust=1, size=rel(0.5)), 
              axis.title.y = element_blank(), 
              axis.text.y = element_text(size=rel(0.5)))`

Here you set the `fill=n`. If there are multiple samples, should we set the `fill=mean` to use the "mean" column in the exported table?

Thank you very much.

**Comment by ncborcherding** [comment]
Hey fredust - 

Thanks for the excellent run down - both the master and dev branch have the fix committed. 

Let me know if you have any other questions or issues

**Comment by fredust** [comment]
Hello, sorry to ask again.
I saw that you change the `fill=mean` back to `fill=n`
Is that mean we still should use the `n` value in the heatmap of gene usage?
Thank you very much

**Comment by ncborcherding** [comment]
Hey fredust,

No you are completely correct - this must be a versioning issue and let me track it down in order to figure out what happen. I will also get it changed today. 

Nick
