### ISSUE TITLE
Error in cellT(cells) : object 'chain1' not found

### ISSUE THREAD

**Issue by chrismahony** [ncborcherding/scRepertoire#181]
Hi

I have run the following but I get an error message, could you help?

Thanks
Chris

library(scRepertoire)

tcr_PBMC1 <- read.csv("/mypath/per_sample_outs/PBMC1/vdj_t/filtered_contig_annotations.csv")

tcr_PBMC4 <- read.csv("/mypath/PBMC4/outs/per_sample_outs/PBMC4/vdj_t/filtered_contig_annotations.csv")

tcr_PBMC5 <- read.csv("/mypath/PBMC5/outs/per_sample_outs/PBMC5/vdj_t/filtered_contig_annotations.csv")

PBMC_list_t <- list(tcr_PBMC1, tcr_PBMC4, tcr_PBMC5)

combined_PBMCt <- combineTCR(PBMC_list_t, 
                samples = c("1", "4", "5"), 
                ID=c("a", "b", "c"),
                cells ="PBMC")

Error in cellT(cells) : object 'chain1' not found

**Comment by ncborcherding** [comment]
Hey Chris, 

I think the issue involves the **cells** parameter. 

**cells** is telling the function what type of TCR to extract - either T-AB or T-GD, thus **PBMC** is confusing the function. Here is the change I would recommend. 

```
combined_PBMCt <- combineTCR(PBMC_list_t,
samples = c("1", "4", "5"),
ID=c("a", "b", "c"),
cells ="T-AB")
```
Thanks,
Nick

**Comment by chrismahony** [comment]
Thanks for the quick reply. This does solve the problem thanks.

I have continued in the vingette and I can plot most of the graphs, but I am having some issues:

quantContig(combined_PBMCt, cloneCall="gene+nt", chain = "TRA")

Error in quantContig(combined_PBMCt, cloneCall = "gene+nt", chain = "TRA") : 
  unused argument (chain = "TRA")


vizGenes(combined_PBMCt, gene = "V", 
+          chain = "TRB", 
+          plot = "bar", 
+          order = "variance", 
+          scale = TRUE)
Error in vizGenes(combined_PBMCt, gene = "V", chain = "TRB", plot = "bar",  : 
  could not find function "vizGenes"


I downloaded using devtools::install_github("ncborcherding/scRepertoire@dev"). If you could help this would be great, thanks

**Comment by ncborcherding** [comment]
Hey Chris - 

Sounds like you might be using an older version of scRepertoire - ```VizGenes()``` is in the newest versions of scRepertoire (current dev version included). If you just made the install of the dev version, make sure you restart your R session. 

Nick

**Comment by chrismahony** [comment]
OK, thanks for this. This is also now working.

Next thing is this, if you could help I would really appreciate it:

PBMC_integrated <- combineExpression(combined_ALLt_PBMC, PBMC_integrated, 
                   cloneCall="gene", 
                   group.by = "sample", 
                   proportion = FALSE, 
                   cloneTypes=c(Single=1, Small=5, Medium=20, Large=100, Hyperexpanded=500))
Error in `$<-.data.frame`(`*tmp*`, "cloneType", value = NA) : 
  replacement has 1 row, data has 0

**Comment by ncborcherding** [comment]
Hey Chris, 

Some sort of internal filtering is removing the contig data. My first guess is that the barcodes in the contig data (from ```combineTCR()```) does not match the Seurat Object. 

You can check this with the following code and looking at the barcodes. 
```
head(PBMC_integrated[[]])
head(combined_ALLt_PBMC[[1]])
```

**Comment by chrismahony** [comment]
Thanks, the barcodes were not he same.

head(PBMC_integrated[[]])
                        orig.ident nCount_RNA nFeature_RNA nCount_Protein nFeature_Protein sample percent.mito T_clonotype_id
AAACCTGAGAAACCAT-1_1 SeuratProject       1362          632            329              102  PBMC1   0.09471366  clonotype3145

head(combined_ALLt_PBMC[[1]])
               barcode sample    ID                TCR1       cdr3_aa1                                   cdr3_nt1
1 1_PBMC_AAACCTGAGAAACCAT-1      1 PBMC1   TRAV21.TRAJ8.TRAC CAAWGYTGFQKLVF TGTGCCGCCTGGGGGTACACAGGCTTTCAGAAACTTGTATTT


And here is what I ran to sort it:

barcodes_combined_ALLt_PBMC1<-combined_ALLt_PBMC[["1_PBMC1"]][["barcode"]]
barcodes_combined_ALLt_PBMC1<-as.data.frame(barcodes_combined_ALLt_PBMC1)
barcodes_combined_ALLt_PBMC1<-cSplit(barcodes_combined_ALLt_PBMC1, 'barcodes_combined_ALLt_PBMC1', sep="_", type.convert=FALSE)
barcodes_combined_ALLt_PBMC1$PBMC<-str_c(barcodes_combined_ALLt_PBMC1$barcodes_combined_ALLt_PBMC1_3, '_', barcodes_combined_ALLt_PBMC1$barcodes_combined_ALLt_PBMC1_1)
combined_ALLt_PBMC[["1_PBMC1"]][["barcode"]]<-barcodes_combined_ALLt_PBMC1$PBMC

Then I repeated this for PBMC2, PBMC3 etc

Thanks for the help.
Chris
