### ISSUE TITLE
Install version 1.5.4

### ISSUE THREAD

**Issue by NK-HD** [ncborcherding/scRepertoire#182]
Hey Nick,

thanks for your amazing package!
Sorry if this might be basic question but is there a way to still download and install the 1.5.4 version (as related to https://ncborcherding.github.io/vignettes/vignette.html#5_More_Advanced_Clonal_Analysis) ?

That would be amazing as I would like to keep my package versions consistent throughout analysis. :)
Thanks for your help!
Best, Niklas

**Comment by ncborcherding** [comment]
Hey Niklas, 

Thanks for reaching out!

You should be able to install the specific version using: 

```
install_github("ncborcherding/scRepertoire@v1.5.4")
```

Nick

**Comment by NK-HD** [comment]
Hi Nick,

thanks for your quick response!

Unfortunately this gives me the following error:

```
devtools::install_github("ncborcherding/scRepertoire@1.5.4")

Downloading GitHub repo ncborcherding/scRepertoire@1.5.4
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/ncborcherding/scRepertoire/tarball/1.5.4'
```

Thanks for your help!
Best, Niklas

**Comment by ncborcherding** [comment]
My bad, should have checked the code - you should be able to install the specific commit (the one below is the last commit in v1.5.4)

```
install_github("ncborcherding/scRepertoire@4604ff3cd4a749099539d0bad0844bb0e7cd69d6")
```

**Comment by NK-HD** [comment]
Awesome, thanks - works!
