### ISSUE TITLE
how to reorder x-axis when plotting

### ISSUE THREAD

**Issue by xinmiaoyan** [ncborcherding/scRepertoire#183]
I want to change samples order when plotting, and I tried names(combined) <- c("B", "A", etc) , but failed, the result shows a different plot but the same x-axis when compared to default parameters.

appreciate it if you could help

**Comment by ncborcherding** [comment]
Hey Xinmiaoyan, 

WOuld you mind giving me your ```sessionInfo()``` and an example of what you are trying to do?

Thanks,
Nick

**Comment by ncborcherding** [comment]
I am closing this due to lack of response, but feel free to follow up.
