### ISSUE TITLE
How to fully transfer all TCR clonotype info into Seurat object by combineExpression()?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [ncborcherding/scRepertoire#186]
Hi Nick, 

Thanks for a great package. 

When I performed `combineExpression()`, I noticed only the info below got transferred onto the Seurat object, regardless of how many other meta.data I add in the TCR object:

"barcode"                                                             "CTgene"                                                             
"CTnt"                                                                "CTaa"                                                               
"CTstrict"                                                            "Frequency"                                                          
"cloneType"              

I see that the info above would already include the rest of the info that not transferred, but is there a way to transfer all other TCR info, e.g. cdr3_aa1, cdr3_nt1, etc. as separate meta.data columns? Because if I added additional variable to the list, these would not get transferred as well.

Thank you.

**Comment by ncborcherding** [comment]
Hey Quang, 

As of right now, ```combineExpression()``` does not include an option for the add the variables you mention. However, they are stored in the CTnt, CTaa, and CTgene columns and can be split into chain information using ```stringr::str_aplit()```

Let me think more on if/how to implement adaptive adding of variables. 

Nick

**Comment by sloanlewis** [comment]
Hi Nick, 

I am also interested in this. I would like to split the CTaa column in the Seurat object into TRA and TRB columns. Can you help with how I would use str_split to do this? 

Thanks!
Sloan

**Comment by ncborcherding** [comment]
Hey Sloan,

You can separate the chains with something like: 

```
SeuratObj$TCRA <- stringr::str_split(SeuratObj, "_", simplify = T)[,1]

SeuratObj$TCRB <- stringr::str_split(SeuratObj, "_", simplify = T)[,2]
```

I'm on a phone at the moment so might need adjustments. Hope that helps.

Nick

**Comment by sloanlewis** [comment]
Awesome that worked! Just one edit:
SeuratObj$TCRA <- stringr::str_split(SeuratObj$CTaa, "_", simplify = T)[,1]
Thanks for the quick response!!!
