### ISSUE TITLE
Problem with combineExpression(): Not all contigs are attached to seurat object

### ISSUE THREAD

**Issue by ic23oluk** [ncborcherding/scRepertoire#187]
Hi, thanks for the great package.

I have an issue with combineExpression. I have for conditions, therefore my contigs is a list of 4. Now, when trying to attach these to my seurat object (group.by = "sample"), only two of them get attached. 

In order for the barcodes to match, I used the following code to rename the barcodes in my seurat object:

```
new_barcodes <- rna_singlet@meta.data %>% rownames_to_column("barcode") %>% unite("barcode", c(HTO_classification, barcode), sep = "_", remove = FALSE) %>% select(barcode) %>% as.vector()
new_barcodes <- as.vector(new_barcodes$barcode)

rna_singlet <- RenameCells(rna_singlet, new.names = new_barcodes)
```

Thanks in advance.

**Comment by ic23oluk** [comment]
Hi Nick, 

thanks for your quick reply.

When I subset the combined Seurat object to a condition that has not been successfully attached with clonotype information, `head(sub_sample@meta.data)` looks like this:

```
orig.ident nCount_RNA nFeature_RNA nCount_HTO nFeature_HTO HTO_maxID    HTO_marginHTO_classification tissue genotype HTO_classification.global   hash.ID RNA_snn_res.0.5 seurat_clusters
thymus-wt_AAACCTGAGATACACA-1         LG       1986         1228       1392            4 thymus-wt 4.175809  thymus-wt thymus       wt                   Singlet thymus-wt               2               2
thymus-wt_AAACCTGAGCTCCTCT-1         LG       1878         1133        686            4 thymus-wt 3.136210  thymus-wt thymus       wt                   Singlet thymus-wt               0               0
thymus-wt_AAACCTGAGTATTGGA-1         LG       1885         1051        758            4 thymus-wt 3.672209  thymus-wt thymus       wt                   Singlet thymus-wt               5               5
thymus-wt_AAACCTGCAATGGAAT-1         LG       3011         1443        597            4 thymus-wt 3.346623  thymus-wt thymus       wt                   Singlet thymus-wt               0               0
thymus-wt_AAACCTGCAGTCACTA-1         LG       3658         1491        883            4 thymus-wt 3.603592  thymus-wt thymus       wt                   Singlet thymus-wt               5               5
thymus-wt_AAACCTGGTGTATGGG-1         LG       2852         1258        966            4 thymus-wt 3.725432  thymus-wt thymus       wt                   Singlet thymus-wt               4               4
```

the respective barcodes in the combined_ab object after `combineTCR()` looks like this:

`head(combined_ab[["thymus-wt"]][1:4])`
```
                        barcode    sample                     TCR1        cdr3_aa1
1  thymus-wt_AAACCTGAGATCGGGT-1 thymus-wt     TRAV14-2.TRAJ49.TRAC  CAASANTGYQNFYF
3  thymus-wt_AAACCTGAGGTTCCTA-1 thymus-wt TRAV4-4-DV10.TRAJ43.TRAC    CAAPNNNNAPRF
5  thymus-wt_AAACGGGAGAAACGAG-1 thymus-wt     TRAV8N-2.TRAJ37.TRAC   CATVAGNTGKLIF
7  thymus-wt_AAACGGGAGGTGCTAG-1 thymus-wt     TRAV12-2.TRAJ30.TRAC  CALSQDTNAYKVIF
9  thymus-wt_AAACGGGAGTAATCCC-1 thymus-wt      TRAV6-3.TRAJ12.TRAC  CAMRAGTGGYKVVF
11 thymus-wt_AAACGGGGTACCATCA-1 thymus-wt    TRAV14N-1.TRAJ52.TRAC CAASDTGANTGKLTF
```

Also, I notice that after `combineExpression()` in my `combined` seurat object in the column `barcode` only the two (of four) conditions are listed, rest is `NA`:

```
combined_df <- combined@meta.data %>% separate(barcode, into = c("id", "barcode"), sep = "_")
combined_df$id <- as_factor(combined_df$id)
length(levels(combined_df$id))
> 2
```

I am using scRepertoire version 1.7.2

Hope that made sense.

Thank you!

Michael

**Comment by ncborcherding** [comment]
Hey Michael, 

Thanks for the thorough run down! Really appreciated. You are correct, there should be no duplicate barcodes if this is a multiplexed sequencing run. 

If you are getting partial attachment of your contig information across 2 of the 4 contigs using ```combineExpression()```, that likely indicated there is a prefix/suffix barcode mistmatch between the ```combinedTCR()``` output and the Seurat object. 

What are the barcodes of the seurat object and ```combinedTCR()``` output for the conditions you are not getting the contig information attached for?

Thanks for bearing with me, hope to figure this out!

Nick

**Comment by ic23oluk** [comment]
Hi Nick,

we are getting closer. You are right, the Barcodes of two conditions are swapped, which together with the prefix of the actual conditions doesn't match. To be honest, though, I don't see at which step this mistake is happening.. ideas?

**Comment by ncborcherding** [comment]
Hey Michael, 

My guess is that during the ```combineTCR()``` step, the sample parameter is not in the correct order? The order should correspond to the filter_contig files in the list. 

Nick

**Comment by ic23oluk** [comment]
Hey Nick,

thank you so much, the issue is solved. Apologies for the silly mistake.

Best, Michael
