### ISSUE TITLE
5' scRNA-seq GEX for clonotype reconstruction

### ISSUE THREAD

**Issue by beginner984** [ncborcherding/scRepertoire#188]
Hi

Please I need your personal view of point

Actually in our lab we are trying to reconstruct clonotype information from a `10X Genomics 5' scRNA-seq` run `(without dedicated V(D)J amplification)`. I admit that with 3' libraries there will be very few extracted TCRs or even nothing, because CDR3 is quite distant from the 3' end. But, by 10x 5' mRNA libraries as I have read, using a software like `MiXCR` that is possible to recontract clonotypes.

Please could you correct me on what I have perceived from my Googling? clonotype reconstruction by **_10x 5' mRNA libraries without TCR/BCR libraries_**

Thanks a lot for any thought

**Comment by ncborcherding** [comment]
Hey beginner984, 

You are thinking correctly - 5' libraries should contain the VDJ sequences and be recovered. 

I do not have experience using MiXCR for single-cell runs - I would imagine that there is some requirements for the UMI/barcode portion of the reads. I have used [TRUST4](https://github.com/liulab-dfci/TRUST4), which works very smoothly with 10x 5' RNA data. 

Hope that helps - I am closing this issue as it is not an issue with scRepertoire per say. However, feel free to keep asking questions below. 

Nick

**Comment by beginner984** [comment]
Thanks a lot

As I got from your comment, I run TRUST4 and I have these in my folder

`./run-trust4 -f hg38_bcrtcr.fa --ref human_IMGT+C.fa -u /data/GEX_S3_L001_R2_001.fastq.gz --barcode /data/GEX_S3_L001_R1_001.fastq.gz --barcodeRange 0 15 + -t 8`

```
AlignAlgo.hpp            example                     main.cpp             TRUST_PN0340_0001_GEX_S3_L001_R2_001_airr_align.tsv
alignments.hpp           fastq-extractor             main.o               TRUST_PN0340_0001_GEX_S3_L001_R2_001_airr.tsv
annotator                FastqExtractor.cpp          Makefile             TRUST_PN0340_0001_GEX_S3_L001_R2_001_annot.fa
Annotator.cpp            FastqExtractor.o            mouse                TRUST_PN0340_0001_GEX_S3_L001_R2_001_assembled_reads.fa
Annotator.o              FilterAnnotatedAssembly.pl  ReadFiles.hpp        TRUST_PN0340_0001_GEX_S3_L001_R2_001_barcode_airr.tsv
bam-extractor            hg19_bcrtcr.fa              README.md            TRUST_PN0340_0001_GEX_S3_L001_R2_001_barcode_report.tsv
BamExtractor.cpp         hg38_bcrtcr.fa              run-trust4           TRUST_PN0340_0001_GEX_S3_L001_R2_001_cdr3.out
BamExtractor.o           human_IMGT+C.fa             samtools-0.1.19      TRUST_PN0340_0001_GEX_S3_L001_R2_001_final.out
BarcodeCorrector.hpp     human_vdjc.list             scripts              TRUST_PN0340_0001_GEX_S3_L001_R2_001_raw.out
BuildDatabaseFa.pl       KmerCode.hpp                SeqSet.hpp           TRUST_PN0340_0001_GEX_S3_L001_R2_001_report.tsv
BuildImgtAnnot.pl        KmerCount.hpp               SimpleVector.hpp     TRUST_PN0340_0001_GEX_S3_L001_R2_001_toassemble_bc.fa
BuildImgtVquestAnnot.pl  KmerIndex.hpp               trust4               TRUST_PN0340_0001_GEX_S3_L001_R2_001_toassemble.fq
Cgene.list               kseq.h                      trust-airr.pl        trust-simplerep.pl
defs.h                   LICENSE.txt                 trust-barcoderep.pl  trust-smartseq.pl
```
