### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by rolaniyi** [ncborcherding/scRepertoire#19]
2 functions - StartracDiversity() and changeNames() - mentioned in the vignette of this package are missing.

**Comment by ncborcherding** [comment]
These functions are both in the development branch - sorry for the confusion. I am in the process of getting things submitted to BioConductor and they were on the chopping block for various reasons.

**Comment by rolaniyi** [comment]
Ah ok.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
