### ISSUE TITLE
Inconsistency between the table output from clonalNetwork() and manual checking of shared clones?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [ncborcherding/scRepertoire#192]
Hi Nick, 

Again, I love the package and especially the graphics of `clonalNetwork`. 

However, I am puzzled by the result of my recent analysis. I found the clone sharing that was reported in the `clonalNetwork()` result table did not match when I checked the same combined object that was used as input to `clonalNetwork()` manually. 

I checked it by doing as below. Would you mind helping me diagnose what I did wrong here?
Thank you so much!

```
#Subset the Seurat obj with TCR info `(obj)` transferred to obtain the cluster of interest for checking clonal sharing 
subset(obj, cells= WhichCells(obj, expression = `Tissue_Type` == "PBMC" & `clusterID` == "25", invert = F)) -> subset25

#Check how many cells in this cluster has TCR transferred 
subset25@meta.data %>% dplyr::filter(!is.na(CTstrict)) %>% dim()

#Check whether any of the clones transferred for this cluster is duplicated or all single/unique clone 
any(duplicated(subset25$CTstrict))
unique(subset25$CTstrict)

#Subset the original Seurat obj `(obj)` excluding cluster 25 of interest 
subset(obj, cells= WhichCells(obj, expression = clusterID == "25", invert = T)) -> allsubsets_minus25

#Check whether any clones in object without subset25 cells (ie allsubsets_minus25 is the same compared to all clones of subset25)

table(allsubsets_minus25$CTstrict %in% subset25$CTstrict)

# Which are these clones?
allsubsets_minus25$CTstrict[(allsubsets_minus25$CTstrict %in% subset25$CTstrict)] -> subset25clones_sharedwElse_clones

#Check which clusters do these clones identified come from
subset(allsubsets_minus25, cells = WhichCells(allsubsets_minus25, expression = `cell_barcodes` %in% names(subset25clones_sharedwElse_clones))) -> subset25clones_sharedwElse_clones_obj

#THIS CLUSTER IDENTIFIED AS HAVING SHARED CLONES WITH SUBSET25 HERE DO NOT MATCH WITH WHAT REPORTED IN CLONALNETWORK FOR THIS CLUSTER
table(subset25clones_sharedwElse_clones_obj$clusterID)

```

**Comment by ncborcherding** [comment]
Hey Quang, 

Thanks for the question and code used to check - would you mind giving me the outputs that you are seeing from the code? It is difficult to isolate the problem with just the code. 

Thanks,
Nick

**Comment by denvercal1234GitHub** [comment]
Hi @ncborcherding - My great apologies. Is it possible to send you the outputs of the codes via email instead?

**Comment by denvercal1234GitHub** [comment]
and @ncborcherding - plz do let me know if having the Seurat obj with TCR info transferred or the expression2List obj would be better to diagnose this discrepancy. Thank you for your help. I hope all is well.

**Comment by ncborcherding** [comment]
Hey Quang, 

Sorry did not see the edits to the comment above - what are the 7 clones identified by clonal netowrk?

Nick

**Comment by denvercal1234GitHub** [comment]
Hi Nick - How do I get that info, because the output table of clonalNetwork() only have "to", "from" and "weight"?

**Comment by ncborcherding** [comment]
Hey Quang - would you mind sending me the seurat object with the TCR attached - I think I will have to diagnose the issue by going under the hood of both of the functions. 

thanks, Nick.

**Comment by ncborcherding** [comment]
Hey Quang, 

Figured out the point of the inconsistency - ```clonalNetwork()``` default cloneCall = "aa" and not "strict". Once it is changed it identifies the correct overlap. The reason there is only 3 identified in the code below instead of 4 is that ```clonalNetwork()``` is quantifying unique clonotypes by cluster and only looking at the proportion of unique clonotypes shared between cluster. 

```
clonalNetwork(obj, identity = "Tissue_Cell_Leiden_clusterID", cloneCall = "strict", exportTable = T) -> obj_clonalNetwork_table
obj_clonalNetwork_table %>% dplyr::filter(to == "TMNC_CD8T_25") -> sharedClones_wSubset25_fromClonalNetwork 

# Which are the clone-sharing clusters(s) of the 4 clones with subset25?
#CHECKING result of clonalNetwork showed 7 clones (and not 4 clones as shown by compareClonotypes and manual checking) were shared with subset25
table(sharedClones_wSubset25_fromClonalNetwork$from)

PBMC_CD8T_11  TMNC_CD8T_2  TMNC_CD8T_8 
           1            1            1
```

Sorry for the delay in this and let me know if you have any other questions.

Nick

**Comment by denvercal1234GitHub** [comment]
Thank you, Nick. I see now cluster ID number 8 have 2 clones shared, so clonalNetwork counted that once, right?

**Comment by ncborcherding** [comment]
Yes. correct.
