### ISSUE TITLE
clusterTCR visualization

### ISSUE THREAD

**Issue by aranham** [ncborcherding/scRepertoire#193]
Hi Nick,

Is there a way to visualize the output from clusterTCR as a dendogram?

Thanks,
Michelle

**Comment by ncborcherding** [comment]
Hey Michelle, 

In the current iteration, the way the edit distance is stored will not let a dendrogram be created. I think this is an interesting suggestion, let me see if I can investigate a way to incorporate it. 

I'll mark this for now as enhancement and do some investifateion.

Thanks,
Nick

**Comment by aranham** [comment]
Thank you!

Best,
Michelle
