### ISSUE TITLE
combineTCR() not saving 4 recovered TCRs per barcode

### ISSUE THREAD

**Issue by TeodoraTockovska** [ncborcherding/scRepertoire#194]
Hi! I have 52 barcodes that contain 4 TCRs. However, the combineTCR() function is not saving them. I am using scRepertoire dev version 1.7.2. I also tried using scRepertoire v1.6.0 (installed via Bioconductor). Below is how I call the function, using default parameters. 

Thank you.

`combineTCR(contig_lst, samples = sample_names,  ID = c("Memory", "Memory", "Naive", "Naive"), cells ="T-AB")`

**Comment by ncborcherding** [comment]
They Teodora, 

Both the versions you mention have an internal filter to remove unporductive clones from 10x data? Could that possibly be the cause? 

What is the output of head(contig_list[[1]])?

Do you receive any errors or is ```combineTCR()``` returning an empty list? 

Thanks,
Nick

**Comment by TeodoraTockovska** [comment]
Hi Nick,

Thanks for your reply. I analyzed the code again using v1.7.2 and compared my barcodes with the results. The great news is that the TCRs were retained. I am not certain what the issue was yesterday. 

Sorry for the inconvenience! I am closing the issue.

Sincerely, 
Teodora
