### ISSUE TITLE
interpretation of CTstrict

### ISSUE THREAD

**Issue by trnguyenuka** [ncborcherding/scRepertoire#198]
Hello, 

thank you for developing this great tool. I'm using it for my recent data analysis of BCR data. 

I have a question regarding the interpretation of CTstrict column in the output of `combineBCR`. I know that this is a combination of the two genes from heavy and light chain, but it would be great to understand more on the numbers and the indices in these values (I assume that they must be related to some Lehvenstein distance between the CDR3 strings?), e. g. `IGH:LD.2547_IGHV1-39_IGLC:LD.16_IGKV6-23` 

Thank you again and I'm looking forward to your response.

All the best,
H.N

**Comment by ncborcherding** [comment]
Hey trnguyenuka, 

Thanks for reaching out and pointing out that I probably need to add additional documentation for the ```combineBCR()``` function. 

You are correct on the combination of Lehvenstein distance and CDR3 string. The distance is actually a normalized edit distance using the mean of the cdr3 length as a denominator. The default setting for the threshold is to call anything > 0.85 normalized edit difference as a group (with a "LD: + unique number) with the added V gene usage. If no group is found, just a unique number is used (no LD). 

In your example:
```IGH:LD.2547_IGHV1-39_IGLC:LD.16_IGKV6-23```

Both the heavy and light chain had matches using (LD + unique number) with the IGH LD group of 2547 and light chain group of LD16. 

Let me know if that makes sense or if you have any suggestions. I added improve documentation to the "to-do" list. I'm going to close this as an issue, as it doesn't relate to a bug in the package per say. But feel free to follow up below. 

Thanks,
Nick

**Comment by jjs847** [comment]
thanks so much, this makes sense. Is it this normal in single-cell data that the light chain is captured way more than heavy chain transcripts? Also, is there documentation on the meaning of the output of CTstrict besides whats described here? https://www.borch.dev/uploads/screpertoire/articles/combining_contigs?
