### ISSUE TITLE
compareClonotypes output 

### ISSUE THREAD

**Issue by gt7901b** [ncborcherding/scRepertoire#20]
Hi, Nick:

Thanks for developing this nice package.
I was trying my own data with scRepertoire. I can get it working with all the plots before integrating seurat, except the compareClonotypes output. It displays an empty plot with only Y axis label. What might be the issue here?

**Comment by ncborcherding** [comment]
Sorry about that! I think I will need more information, I am not sure based on the description.

Mind sending a copy of the compareClonotype() call and if any errors are present? 

Can you give me any more details on your samples? How many samples do you have?

Thanks,
Nick

**Comment by gt7901b** [comment]
![image](https://user-images.githubusercontent.com/22965838/89450403-7c29cf80-d728-11ea-8eec-93379dc2d5a4.png)

No error message.  It has 6 samples. Any other way I can check?

**Comment by ncborcherding** [comment]
What is the output of names(combined)?

My guess is that you have incomplete sample names - by default scRepertoire will add the sample + ID together during the combinedTCR() step to form a single name. So from the vignette- sample = "PZ", ID = "T" --> sample = "PZ_T"

**Comment by gt7901b** [comment]
You're right, Nick. I should've read vignette more carefully.
many thanks!

**Comment by ncborcherding** [comment]
Great glad we got it figured out, let me know if you have any other issues!
