### ISSUE TITLE
Group parameter for plotting

### ISSUE THREAD

**Issue by meaksu** [ncborcherding/scRepertoire#200]
Hi,
I noticed while going through the available plotting functions that some functions such as lengthContig() have a group parameter where you can change the groupings from individual sample to condition. However, other plots such as clonalProportion and clonalOverlap don't accept a group parameter. Is there a way to change the default grouping on functions without a group parameter?

Thanks!

**Comment by ncborcherding** [comment]
Hey Meaksu, 

Sorry this might be confusing and I will work on the documentation. If you have the TCR/BCR data attached to a single-cell object, you should be able to use the ```split.by``` parameter to use any of the meta data variables. 

Is that what you are asking for? Also what version of scRepertoire are you using?

Thanks,
Nick

**Comment by meaksu** [comment]
Hi,
Thanks for your quick response. What I was asking was: some functions like abundanceContig I can use a "group" parameter where clonotypes are pooled into groups rather than individual samples, like this -  
`abundanceContig(combinedTCR, cloneCall = "gene", group = "sample", scale = F)`
The "sample" in this case is in the metadata and the way I labeled it represents the condition rather than the default which is the individual sample names. 

However it seems like most other functions don't have this capability. I tried "split.by" in clonalHomeostasis, and clonalProportion, but it looks like these functions don't accept the parameter and can only output based on the default which is individual samples. Is this correct?

I'm using version 1.6.0

Thanks!

**Comment by ncborcherding** [comment]
Hey Meaksu, 

Thanks for pointing this out - I've just committed the addition of the ```group.by``` parameter in a number of additional visualizations (including the clonalProportion() and Homeostasis()). I will test it and get it incorporated into the master version as soon as I can. 

You can install (then restart your R session) with: 
```
devtools::install_github("ncborcherding/scRepertoire@dev")
```

Nick
