### ISSUE TITLE
Cells with more than one pair of VJ and VDJ chains

### ISSUE THREAD

**Issue by singlecellfan** [ncborcherding/scRepertoire#204]
Hi,

first of all, thanks for this amazing package. It is very helpful!

Not sure you can answer this but how would you suggest handling cells that have more than one pair of VJ sequences for the alpha chain (see image attached)?
Are these doublets?

<img width="1130" alt="Screenshot 2022-11-13 at 22 29 13" src="https://user-images.githubusercontent.com/79158757/201545478-8617d42c-5731-4884-8703-9bad4bd4b240.png">

Apparently there is also some evidence for a dual IR model. The python based tool "scirpy" can account for this. Is this also possible with scRepertoire or how would you handle these cells/barcodes?

Thank you much in advance!

**Comment by singlecellfan** [comment]
I realized the "combineTCR" function can exactly account for this. Therefore I closed it.

**Comment by ncborcherding** [comment]
Hey singlecellfan, 

Thanks for the question and follow up! Thought I would provide a comment just in case other users are searching. 

```combinTCR()``` will automatically combine all productive TCR chains in the 10x data - depending on the version of cell ranger being run, this can result in cells with 4 or 5 productive chains (that is the most I've seen personally). If retaining the multiple chains is not your goal, you can set ```combinTCR(..., filter.multi = TRUE)```. This will automatically assign the top TCRA and TCRB chain by read count. There is also '``combinTCR(..., remove.multi = TRUE)```, to eliminate cells with multiple chains. 


Thanks again, 
Nick
