### ISSUE TITLE
How to get top ranked clone?

### ISSUE THREAD

**Issue by wajm** [ncborcherding/scRepertoire#205]
Thank you for great package.

I'm wondering how to get top ranked clones in the package function.
vizGenes etc.

one more thing,
vizGenes(df, gene = "V", chain = "TRB", plot = "heatmap", scale = TRUE, order = "variance", group.by = "time")
group.by option is not working, something wrong? They just showed each sample without any grouping.

**Comment by ncborcherding** [comment]
Hey wajm, 

Thanks for reaching out. 

What version of scRepertoire are you running?

All visualizations should have an **exportTable** parameter that will let you return the data frame that is plotted. Alternatively, if you are looking for the top clones in a group - you might want to try ```compareClonotypes()``` which will do the sorting of top clones.

for your issue:
```
vizGenes(df, gene = "V", chain = "TRB", plot = "heatmap", scale = TRUE, order = "variance", group.by = "time")
```

What do you mean by returning without any grouping? 

Thanks,
Nick

**Comment by wajm** [comment]
Hi Nick,
Thank you for your kindness.
1.8.0 version is running on my site.

regarding my issue, my dataset has total 481 scTCRRNAseq with 5 groups(time group: 1,2,3,4,5). 
I'd like to show the group difference with vizGenes().
vizGenes() results show every single sample with/without group.by option.

compareClonotypes() function only compare between specific samples, right? is there any option to compare between group?

**Comment by ncborcherding** [comment]
Hey wajm, 

Thanks for the reply.

For both ```vizGenes()``` and ```compareClonotypes()``` the **group.by** paramter should be able to be used to display variables after ```combineTCR()```. However, potentially the issue here is that the you have not stored the sample groups - you might want to look at ```addVariable()``` to add the respective grouping number to each of the 481 sequencing runs. 

Alternatively, if you have attached the TCR data to a single-cell RNA object with ```combineExpression()```, there is a **split.by** parameter that can be used similarly on the single-cell object. 

Hope that helps - if it doesn't, would you mind providing an example of the code you are using to load the contigs through combineTCR() so I can start troubleshooting?

Thanks,
Nick

**Comment by wajm** [comment]
Hi Nick,

I did addVariable() but group.by parameter was not working.
4 different variables(cellType, time, group, patients)
They show each sample's clone list of the group.

> head(combined[[1]])
                     barcode sample ID                                  TCR1                        cdr3_aa1
1  H001_0_AAACCTGCAGCCTGTG-1   H001  0                TRAV23/DV6.TRAJ18.TRAC                    CAASTFLGRLYF
3  H001_0_AAACCTGGTTCCATGA-1   H001  0                   TRAV8-3.TRAJ21.TRAC                   CAVGEDNFNKFYF
6  H001_0_AAACGGGAGTACCGGA-1   H001  0                    TRAV41.TRAJ42.TRAC                   CAHHGGSQGNLIF
8  H001_0_AAACGGGGTCTTCGTC-1   H001  0                     TRAV5.TRAJ39.TRAC                  CAELRANAGNMLTF
10 H001_0_AAACGGGGTGATGTGG-1   H001  0 TRAV41.TRAJ43.TRAC;TRAV20.TRAJ28.TRAC CAAVRGRNDMRF;CAVQEGAYSGAGSYQLTF
14 H001_0_AAAGATGAGTGGACGT-1   H001  0              TRAV38-2/DV8.TRAJ42.TRAC               CAYRSAGYGGSQGNLIF
                                                                                      cdr3_nt1                        TCR2
1                                                         TGTGCAGCAAGCACGTTCCTGGGGAGGCTATACTTT   TRBV9.TRBD1.TRBJ1-1.TRBC1
3                                                      TGTGCTGTGGGTGAGGACAACTTCAACAAATTTTACTTT     TRBV27.NA.TRBJ2-7.TRBC2
6                                                      TGTGCTCACCACGGAGGAAGCCAAGGAAATCTCATCTTT     TRBV27.NA.TRBJ2-3.TRBC2
8                                                   TGTGCAGAGTTGAGGGCTAATGCAGGCAACATGCTCACCTTT     TRBV30.NA.TRBJ2-5.TRBC2
10 TGTGCTGCCGTCAGAGGTAGAAATGACATGCGCTTT;TGTGCTGTGCAGGAAGGCGCATACTCTGGGGCTGGGAGTTACCAACTCACTTTC TRBV7-2.TRBD2.TRBJ2-3.TRBC2
14                                         TGTGCTTATAGGAGCGCGGGGTATGGAGGAAGCCAAGGAAATCTCATCTTT      TRBV2.NA.TRBJ2-3.TRBC2
           cdr3_aa2                                         cdr3_nt2
1   CASNAGGGWGTEAFF    TGTGCCAGCAACGCAGGGGGGGGATGGGGCACTGAAGCTTTCTTT
3    CASSNTGGKNEQYF       TGTGCCAGCAGTAATACAGGGGGTAAGAACGAGCAGTACTTC
6    CASSLVGSTDTQYF       TGTGCCAGCAGTTTAGTAGGGAGCACAGATACGCAGTATTTT
8    CAWQETGGSETQYF       TGTGCCTGGCAAGAGACGGGCGGGAGTGAGACCCAGTACTTC
10 CASSDGTSGSGDTQYF TGTGCCAGCAGCGACGGGACTAGCGGGAGTGGAGATACGCAGTATTTT
14    CASIPSWTDTQYF          TGTGCCAGCATCCCCAGCTGGACAGATACGCAGTATTTT
                                                              CTgene
1                   TRAV23/DV6.TRAJ18.TRAC_TRBV9.TRBD1.TRBJ1-1.TRBC1
3                        TRAV8-3.TRAJ21.TRAC_TRBV27.NA.TRBJ2-7.TRBC2
6                         TRAV41.TRAJ42.TRAC_TRBV27.NA.TRBJ2-3.TRBC2
8                          TRAV5.TRAJ39.TRAC_TRBV30.NA.TRBJ2-5.TRBC2
10 TRAV41.TRAJ43.TRAC;TRAV20.TRAJ28.TRAC_TRBV7-2.TRBD2.TRBJ2-3.TRBC2
14                   TRAV38-2/DV8.TRAJ42.TRAC_TRBV2.NA.TRBJ2-3.TRBC2
                                                                                                                                           CTnt
1                                                            TGTGCAGCAAGCACGTTCCTGGGGAGGCTATACTTT_TGTGCCAGCAACGCAGGGGGGGGATGGGGCACTGAAGCTTTCTTT
3                                                            TGTGCTGTGGGTGAGGACAACTTCAACAAATTTTACTTT_TGTGCCAGCAGTAATACAGGGGGTAAGAACGAGCAGTACTTC
6                                                            TGTGCTCACCACGGAGGAAGCCAAGGAAATCTCATCTTT_TGTGCCAGCAGTTTAGTAGGGAGCACAGATACGCAGTATTTT
8                                                         TGTGCAGAGTTGAGGGCTAATGCAGGCAACATGCTCACCTTT_TGTGCCTGGCAAGAGACGGGCGGGAGTGAGACCCAGTACTTC
10 TGTGCTGCCGTCAGAGGTAGAAATGACATGCGCTTT;TGTGCTGTGCAGGAAGGCGCATACTCTGGGGCTGGGAGTTACCAACTCACTTTC_TGTGCCAGCAGCGACGGGACTAGCGGGAGTGGAGATACGCAGTATTTT
14                                                  TGTGCTTATAGGAGCGCGGGGTATGGAGGAAGCCAAGGAAATCTCATCTTT_TGTGCCAGCATCCCCAGCTGGACAGATACGCAGTATTTT
                                               CTaa
1                      CAASTFLGRLYF_CASNAGGGWGTEAFF
3                      CAVGEDNFNKFYF_CASSNTGGKNEQYF
6                      CAHHGGSQGNLIF_CASSLVGSTDTQYF
8                     CAELRANAGNMLTF_CAWQETGGSETQYF
10 CAAVRGRNDMRF;CAVQEGAYSGAGSYQLTF_CASSDGTSGSGDTQYF
14                  CAYRSAGYGGSQGNLIF_CASIPSWTDTQYF
                                                                                                                                                                                                         CTstrict
1                                                                             TRAV23/DV6.TRAJ18.TRAC_TGTGCAGCAAGCACGTTCCTGGGGAGGCTATACTTT_TRBV9.TRBD1.TRBJ1-1.TRBC1_TGTGCCAGCAACGCAGGGGGGGGATGGGGCACTGAAGCTTTCTTT
3                                                                                  TRAV8-3.TRAJ21.TRAC_TGTGCTGTGGGTGAGGACAACTTCAACAAATTTTACTTT_TRBV27.NA.TRBJ2-7.TRBC2_TGTGCCAGCAGTAATACAGGGGGTAAGAACGAGCAGTACTTC
6                                                                                   TRAV41.TRAJ42.TRAC_TGTGCTCACCACGGAGGAAGCCAAGGAAATCTCATCTTT_TRBV27.NA.TRBJ2-3.TRBC2_TGTGCCAGCAGTTTAGTAGGGAGCACAGATACGCAGTATTTT
8                                                                                 TRAV5.TRAJ39.TRAC_TGTGCAGAGTTGAGGGCTAATGCAGGCAACATGCTCACCTTT_TRBV30.NA.TRBJ2-5.TRBC2_TGTGCCTGGCAAGAGACGGGCGGGAGTGAGACCCAGTACTTC
10 TRAV41.TRAJ43.TRAC;TRAV20.TRAJ28.TRAC_TGTGCTGCCGTCAGAGGTAGAAATGACATGCGCTTT;TGTGCTGTGCAGGAAGGCGCATACTCTGGGGCTGGGAGTTACCAACTCACTTTC_TRBV7-2.TRBD2.TRBJ2-3.TRBC2_TGTGCCAGCAGCGACGGGACTAGCGGGAGTGGAGATACGCAGTATTTT
14                                                                    TRAV38-2/DV8.TRAJ42.TRAC_TGTGCTTATAGGAGCGCGGGGTATGGAGGAAGCCAAGGAAATCTCATCTTT_TRBV2.NA.TRBJ2-3.TRBC2_TGTGCCAGCATCCCCAGCTGGACAGATACGCAGTATTTT
   cellType time group patients
1      T-AB st_0    HD     H001
3      T-AB st_0    HD     H001
6      T-AB st_0    HD     H001
8      T-AB st_0    HD     H001
10     T-AB st_0    HD     H001
14     T-AB st_0    HD     H001

**Comment by ncborcherding** [comment]
Hey wajm, 

What is the code you are using to call ```vizGenes()``` ?

Nick

**Comment by wajm** [comment]
Hi Nick,
here is
vizGenes(combined , gene = "V", chain = "TRB", plot = "bar", scale = TRUE, order = "variance", group.by = "time")

**Comment by ncborcherding** [comment]
Hey wajm, 

And what is the plot you are getting from the vizGenes call?

Nick

**Comment by wajm** [comment]
Hi Nick,
this is a vizGenes plot from a subset combined data.
![image](https://user-images.githubusercontent.com/30439753/205516000-7a556740-2158-4831-8860-6fb10d20532b.png)

**Comment by ncborcherding** [comment]
Hey Wajm, 

If you are displaying bar graphs, the **group.by** variable will group the specific variable and report mean with error bars (which is what your graph is showing). What exactly were you trying to achieve? What specifically do you mean by *group summarized plot using "group.by" option.*?

Thanks,
Nick

**Comment by wajm** [comment]
Hi Nick,
in my case, group.by = "time", the group has 7 components.
So I'd like to show top list of each component.
I thought the vizGenes plot show one summerized bar plot not the each sample of group.
But, I have misunderstant about the vizGenes function.

**Comment by ncborcherding** [comment]
Hey wajm, 

No worries about the misunderstanding - vizGenes() is really looking at the V (and other gene usages) of the TCR/BCR. I think your best bet for top clones is still ```compareClonotype()```. 

Good luck and let me know if you have any additional questions, 
Nick
