### ISSUE TITLE
Reopen issue 206

### ISSUE THREAD

**Issue by Sa753** [ncborcherding/scRepertoire#208]
Hi Nick,

I am sorry to reopen this issue but there is something that doesn't make sense.

If Shannon diversity index is high, this means that there is clonal diversity as you kindly highlighted above. If Pieolu is an evenness index so high  Pielou means more clonal expansion as you also highlighted and in your package, it is inv  Pielou so the lower the value, the more evenness and more clonal expansion. so the same dataset can't show high Shannon index and low inv  Pielou as those two are opposite to each other. 

By the way, I am probably the user who requested an evenness index or clonal expansion index so you added Inv  Pielou, unless you meant  Pielou and not Inverse  Pielou. in this case, it makes sense that a dataset can have high Shannon and low  Pielou not low INVERSE  Pielou. 

This is contradiction is even present with the dataset in your vignette so it is not a dataset ambiguous results. 

Please clarify as this makes the data interpretation completely different

Thanks

_Originally posted by @Sa753 in https://github.com/ncborcherding/scRepertoire/issues/206#issuecomment-1345758413_

**Comment by ncborcherding** [comment]
Will continue this thread at #206 to prevent confusion
