### ISSUE TITLE
TRA / TRB heatmap

### ISSUE THREAD

**Issue by p-gueguen** [ncborcherding/scRepertoire#209]
Hello Nick,

Thanks again for scRepertoire! I was wondering if it's currently possible to display both TRA and TRB chains co-occurences in the same heatmap, for instance with vizGenes.

Thanks a lot,
Paul

**Comment by p-gueguen** [comment]
Thanks a bunch Nick; well appreciated!

Paul

**Comment by ncborcherding** [comment]
V2 officially has this as of Tuesday this week and will be getting the beta out by December 1st. Sorry for the delay!

**Comment by p-gueguen** [comment]
Thanks! And congrats on V2 Nick! It looks very nice.
