### ISSUE TITLE
suggestion of new 'occupied repertoire space' plot

### ISSUE THREAD

**Issue by sjcarmona** [ncborcherding/scRepertoire#21]
Hi Nick

We had a great experience with your package

A minor suggestion: we believe that a function to make a barplot like this (i.e. clonotypes classified by absolute number of cells):

![image](https://user-images.githubusercontent.com/7525176/89538531-f62a8900-d7fa-11ea-9546-0f4cf718fc6e.png)

would be a useful additional feature.

Default clone type classification by frequency can be problematic for small datasets, where singletons might account for a significant proportion of the total cells; as in:

```clonalHomeostasis(..., cloneCall = "gene", cloneTypes = c(Rare=rareFreq, Small = 0.5, Medium = 0.1, Large = 1))```
 
Please see https://carmonalab.github.io/ProjecTILs_CaseStudies/Xiong19_TCR.html#clonality-analysis for a reproducible example

**Comment by ncborcherding** [comment]
Hey Santiago, 

I saw that with your link this morning and great idea and I will add it to the next commit!

Thanks for the suggestion,
Nick

**Comment by ncborcherding** [comment]
Added to the most recent commit, thanks again.
