### ISSUE TITLE
Issues with WAT3R outputs

### ISSUE THREAD

**Issue by kromine1130** [ncborcherding/scRepertoire#212]
Hello,
I am using WAT3R outputs and am running into several issues. 

1.) This one is resolved but should be noted: The parseWAT3R function is missing the colname "chain" which causes downstream issues. e.g 
   ```
chain3 <-  df[[i]][,c(1,23,24,19,18,22,20)]
    chain3 <- data.frame(chain3[,1], chain = "TRA",chain3[,2],  d_gene = NA, chain3[,3], c_gene = NA, chain3[,4:7])
    colnames(chain3) <- c("barcode", "chain", "v_gene", "d_gene", "j_gene", "c_gene", "cdr3_nt", "cdr3", "reads", "umis")
    data2 <- rbind(chain1, chain2, chain3)
    data2[data2 == ""] <- NA
    df[[i]] <- data2
    df[[i]] <- df[[i]][with(df[[i]], order(reads, chain)),]
```
Additionally, this line: 
```
chain2 <- data.frame(chain2[,1:4], chain = "TRA", chain2[,2:4], c_gene = NA, chain2[,5:8])`  
```
causes several duplicated columns.

2.) The unresolved issue I am having is in the combineTCR() step. It gives me this error: 
```
Error in productive %in% c(TRUE, "TRUE", "True", "true") : 
  object 'productive' not found
```
Which I believe is due to the fact that this column is added with the parse10X but not parseWAT3R function. Any help would be appreciated. We cannot proceed without this initial step it appears.

**Comment by ncborcherding** [comment]
Hery kromine1130, 

Thanks for reaching out and having a good rundown of the problem. What version of scRepertoire are you using?

## Problem 1

Can you give me an example of the issues you are encountering for this?

Chain should be in the data frame created with this call with **chain = "TRA" : 

```
chain3 <- data.frame(chain3[,1], chain = "TRA",chain3[,2],  d_gene = NA, chain3[,3], c_gene = NA, chain3[,4:7])
```

## Problem 2
```
chain2 <- data.frame(chain2[,1:4], chain = "TRA", chain2[,2:4], c_gene = NA, chain2[,5:8])`  
```
 You are correct - I just commited the change in the dev branch to remove the duplicate columns - thanks!

## Problem 3

This is a strange error as the master and dev branches should only evaluate "productive" if there is a colname "productive" See this line of ```combineTCR()```

![Screen Shot 2023-01-19 at 7 55 58 AM](https://user-images.githubusercontent.com/22754118/213460827-5a25a603-a1a3-4bfb-9fba-892b9f7b29fd.png)

This makes me think you might be using in out of date version? 

Hope that helps and let me know the follow up - would be happy to troubleshoot with you.

Nick

**Comment by kromine1130** [comment]
Yes  I noticed when looking through the source code that it should not be running that line but was doing so anyways. I am using version 1.6.0, which I believe is correct. I also tried re-installing it and still get the same problem.

**Comment by ncborcherding** [comment]
What version are you currently running after the re-install?

**Comment by kromine1130** [comment]
Still 1.6.0. Is this the incorrect version?

**Comment by kromine1130** [comment]
Also meant to copy this. This the loadContigs and parseWAT3R with the changes we had to make. Think there were several changes that I forgot about:
```
loadContigs <- function(dir, 
                        format = "10X") {
  format.list <- list("WAT3R" = "barcode_results.csv", 
                      "10X" =  "filtered_contig_annotation.csv", 
                      "AIRR" = "airr_rearrangement.tsv", 
                      "TRUST4" = "barcode_report.tsv")
  file.pattern <- format.list[[format]]
  contig.files <- list.files(dir, pattern = file.pattern, recursive = T, full.names = T)
  #contig.files <- paste0(dir, "/", file.pattern)
  
  if (format %in% c("10X", "WAT3R")) {
    df <- lapply(contig.files, read.csv)
    if (format =="WAT3R") {
      df <- parseWAT3R(df)
    } else {
      df <- parse10x(df)
    }
  } else {
    df <- lapply(dir, read.delim)
    if (format =="TRUST4") {
      df <- parseTRUST4(df) 
    } else {
      df <- parseAIRR(df)
    }
  }
  return(df)
}
#Formats wat3r data
parseWAT3R <- function(df) {
  for (i in seq_along(df)) {
    #i <- 1
    colnames(df[[i]])[1] <- "barcode"
    df[[i]][df[[i]] == ""] <- NA
    chain2 <- df[[i]][,c(1,8,9,10,4,3,7,5)]
    #chain2 <- data.frame(chain2[,1:4], chain = "TRA", chain2[,2:4], c_gene = NA, chain2[,5:8])
    chain2 <- data.frame(chain2[,1], chain = "TRA", chain2[,2:4], c_gene = NA, chain2[,5:8])
    colnames(chain2) <- c("barcode", "chain", "v_gene", "d_gene", "j_gene", "c_gene", "cdr3_nt", "cdr3", "reads", "umis")
    
    #TRA Chain 1
    chain1 <-  df[[i]][,c(1,16,17,12,11,15,13)]
    chain1 <- data.frame(chain1[,1], chain = "TRA",chain1[,2], d_gene = NA, chain1[,3], c_gene = NA, chain1[,4:7])
    colnames(chain1) <- c("barcode", "chain", "v_gene", "d_gene", "j_gene", "c_gene", "cdr3_nt", "cdr3", "reads", "umis")
    data2 <- rbind(chain1, chain2)
    data2[data2 == ""] <- NA
    
    #TRA Chain 2
    chain3 <-  df[[i]][,c(1,23,24,19,18,22,20)]
    chain3 <- data.frame(chain3[,1], chain = "TRA",chain3[,2],  d_gene = NA, chain3[,3], c_gene = NA, chain3[,4:7])
    colnames(chain3) <- c("barcode", "chain", "v_gene", "d_gene", "j_gene", "c_gene", "cdr3_nt", "cdr3", "reads", "umis")
    data2 <- rbind(chain1, chain2, chain3)
    data2[data2 == ""] <- NA
    df[[i]] <- data2
    df[[i]] <- df[[i]][with(df[[i]], order(reads, chain)),]
  }
  return(df)
}
```

**Comment by ncborcherding** [comment]
could you try installing the dev version and see if the problem persists?

```
devtools::install_github("ncborcherding/scRepertoire@dev")
```

**Comment by kromine1130** [comment]
So that gives me Version 1.7.1, so that is an improvement. Addtionally, I am also able to run combineTCR() on the sample data, but not my own. I think this is a simple separate issue. I am trying to run the following: 
```
combineTCR(
  contig.list,
  samples =  c("S2_8638",
  "S3_9018",
  "S4_9019",
  "S5_8831",
  "S6_8823",
  "S7_8701",
  "S8_8829"),
  cells = "T-AB",
)
```
And I get: 
```
Error: Make sure the sample and ID labels match the length of the 
            list of data frames (df).
```
The samples "S2_8638" contained our barcode_results.csv files so I assumed those would be the maintained sample IDs in the output contig.list but maybe that is incorrect?

**Comment by ncborcherding** [comment]
What is the code you are using for making **contig.list**?

The error itself is saying that ```length(contig.list) != length(samples)```

When you say:

> The samples "S2_8638" contained our barcode_results.csv files

Does that mean the contig.list is made from a list of the **barcode_results.csv** or a product of the ```loadContig()``` function?

Nick

**Comment by kromine1130** [comment]
The code I used to generate the contig list using the modified loadContigs above and: 
```
contig.output <- c(
                   "./S2_8638/",
                   "./S3_9018/",
                   "./S4_9019/",
                   "./S5_8831/",
                   "./S6_8823/",
                   "./S7_8701/",
                   "./S8_8829/"
                   )

contig.list <- loadContigs(dir = contig.output, 
                           format = "WAT3R")

```
The contig.kist is therefore the result of the loadContigs function. I can confirm that the contig.list is a list of 7 (for 7 samples) with the correct modifications from loadContigs function.

**Comment by kromine1130** [comment]
sent, thanks!

**Comment by ncborcherding** [comment]
Hey Kyle, 

Thanks for sending on the data (and code you have been using). Weirdly the code below runs smoothly and without error

```
load("~/Downloads/contig.list.RData")
combined <- combineTCR(
                  contig.list,
                  samples =  c("S2_8638",
                  "S3_9018",
                  "S4_9019",
                  "S5_8831",
                  "S6_8823",
                  "S7_8701",
                  "S8_8829"),
                  cells = "T-AB",
)
```

I will email you the output of the ```combineTCR()``` function as well. 

I was thinking more on the error you are getting - I would make sure your loaded scRepertoire version is > 1.7.0 - that error is actually only in older versions of scRepertoire, which required a "samples" and "ID" parameter in `combineTCR()```, but is actually not in the code anymore.

Nick

**Comment by kromine1130** [comment]
All issues resolved, thanks so much!
