### ISSUE TITLE
How to pull sequences for CDR3/V/J alpha and beta chains separately?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [ncborcherding/scRepertoire#214]
Hi Nick, 

Thanks so much again for the package!

I was attempting to write a script to pull these info for all my cells/clones. When you get a chance, would you mind helping me confirm that the following info I pulled from the scRepertoire metadata correctly correspond to the amino acid sequences for these segments per chain of interest? Or if scRepertoire already has some functions to do it?

Thanks again for your help!

**“gene” or CTgene = the VDJC genes comprising the TCR/Ig.** 
EX: TRAV13-2.TRAJ26.TRAC_TRBV7-2.TRBD2.TRBJ1-1.TRBC1
Thus:
V alpha chain = TRAV13-2
J alpha chain = TRAJ26
C alpha chain = TRAC

V beta chain = TRBV7-2
D beta chain = TRBD2
J beta chain = TRBJ1-1
C beta chain = TRBC1

**“nt” or CTnt = the nucleotide sequence of the CDR3 region.** 
EX: TGTGCAGAGATCCTGGTCA..._TGTGCCAGCAGCCGTCGTG....
Thus:
CDR3 alpha chain sequence = TGTGCAGAGATCCTGGTCA...
CDR3 beta chain sequence = TGTGCCAGCAGCCGTCGTG....

 **“aa” or CTaa = the amino acid sequence of the CDR3 region.** 
EX: CAEILLG...._CASSRRG....
Thus:
CDR3 alpha chain sequence = CAEILLG....
CDR3 beta chain sequence = CASSRRG....

**Comment by ncborcherding** [comment]
Hey Quang, 

All of that is correct, each variable the TCR chains are seperated TCRA_TCRB.

Nick

**Comment by denvercal1234GitHub** [comment]
Thanks @ncborcherding. May I ask if all the constant chain would just be TRAC, what was the utility of including the constant chain gene there?

**Comment by ncborcherding** [comment]
Not all the contigs actually call the constant region confidently - that is why TRAC or NA is included.

Nick
