### ISSUE TITLE
combineBCR from TRUST4 data: Error in `slice_max()

### ISSUE THREAD

**Issue by ncborcherding** [ncborcherding/scRepertoire#215]
This is an issue posted as part of #213 but moving to separate issue for the ```combineBCR()``` error

```
directory <- c("/home/pedrosousa/newrepertoires/SRR14466432/SRR14466432_barcode_report.tsv")
contig_list <- loadContigs(directory, format = "TRUST4")
combined_B <-combineBCR(
  contig_list,
  samples = NULL,
  ID = NULL,
  threshold = 0.85,
  removeNA = T,
  removeMulti = FALSE
)

Error in `slice_max()`:
! Problem while computing indices.
ℹ The error occurred in group 1: barcode = "AGGGGAGTTACCCGATTGGAG", chain = "IGK".
Caused by error:
! object 'reads' not found
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/rlang_error>
Error in `slice_max()`:
! Problem while computing indices.
ℹ The error occurred in group 1: barcode = "AGGGGAGTTACCCGATTGGAG", chain = "IGK".
Caused by error:
! object 'reads' not found
---
Backtrace:
  1. scRepertoire::combineBCR(...)
 15. base::local(...)
 16. base::eval.parent(substitute(eval(quote(expr), envir)))
 17. base::eval(expr, p)
 18. base::eval(expr, p)
 19. base::eval(...)
 20. base::eval(...)
 21. reads
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/rlang_error>
Error in `slice_max()`:
! Problem while computing indices.
ℹ The error occurred in group 1: barcode = "AGGGGAGTTACCCGATTGGAG", chain = "IGK".
Caused by error:
! object 'reads' not found
```

## Whats going on here:

```combineBCR()``` relies on calling clonotype groups between heavy and light chains by normalized edit distance. To be able to compare each chain across the repertoire - only a single chain can be called per locus (meaning a single cell can only have 1 heavy and 1 light chain). 10x data gets around this by automatically sorting the top chains by read count - this is not necessarily true for other formats seen in ```loadContigs()```. Will need to think through method of filtering for these formats.

**Comment by ncborcherding** [comment]
@pdrofelipe if you get a chance - would you mind [emailing](mailto:ncborch@gmail.com) 1-2 BCR contig files (totally confidential) you have? I just want to ensure I am making the fix on up-to-date formats.

**Comment by pdrofelipe** [comment]
Ok, Nick
 
I sent the email
:)

**Comment by ncborcherding** [comment]
```loadContigs()``` will now retain the reads to allow for ```combineBCR()``` as of version 1.7.3 on the development branch. I have also deprecated the previous ```combineTRUST4()``` function so all formats go through ```loadContigs()``` to prevent any confusion.
