### ISSUE TITLE
combineBCR samples misassigned

### ISSUE THREAD

**Issue by purisuto** [ncborcherding/scRepertoire#218]
I'm slightly puzzled about the behaviour of `combineBCR()`.  I found that the order of the sample list given to the function needs to match their order in `contig.list`, or the barcodes in `combined` will be mislabelled with the sample id.   I generated `contig.list` with `createHTOContigList(contig = B_cells_BCR, sc = seurat_object, group_by = "sample_id")`, and the results were correct. Therefore, would it be better to just call the function as `combineBCR(contig.list, samples = names(contig.list), ...)`?

Can you please test if this is the case?  I'm sorry that I cannot provide examples without significant effort to anonymise.

**Comment by ncborcherding** [comment]
Hey David, 

That is correct - the order of the ```contig.list``` needs to match the order od the **sample** variable. Yes the call: ```combineBCR(contig.list, samples = names(contig.list), ...)``` should work just fine. Please let me know if this is not the case or there is an issue. 

Thanks,
Nick

**Comment by purisuto** [comment]
Ok thanks very much for clarifying that.
