### ISSUE TITLE
Metrics for combineBCR()

### ISSUE THREAD

**Issue by purisuto** [ncborcherding/scRepertoire#219]
Thanks again for the great package.

Is there a way to make some diagnostic plots like these?
1) Percent of GEX barcodes that have at least one BCR chain.
2) Of the BCR-positive cells, show a breakdown of proportions of different combinations of chains (IGH, IGK, IGL, IGH-IGK, IGH-IGL, ...).

(Actually, I ended up making these plots, but I was just wondering if package can already do?)

**Comment by purisuto** [comment]
Something along these lines can be used to compare contig.list and combined.

```library(tidyverse)

# Strip prefix from barcode added by combineBCR
for (i in 1:length(combined)) {
  combined[[i]]$barcode <- gsub("^.*GEM", "GEM", combined[[i]]$barcode)
}

bcr_clonotype_df <- do.call(rbind, combined)

seurat_metadata <- seurat_object@meta.data
seurat_metadata$barcode <- rownames(seurat_metadata)

# Join the two data frames on the "barcode" column
merged_df <- left_join(seurat_metadata, bcr_clonotype_df, by = "barcode")

# Check for absence of IGH or any BCR info
merged_df$hasIGH <- ifelse(is.na(merged_df$IGH),
                           ifelse(is.na(merged_df$CTstrict), "no BCR reads", "no IGH"),
                           "has IGH")

# Aggregate the data by clonotype and cell type
agg_df <- merged_df %>% 
  group_by(hasIGH, HTO_classification.global, sample_id) %>% 
  summarize(count = n())

# Plot
p <- ggplot(agg_df, aes(x = HTO_classification.global, y = count, fill = hasIGH)) +
  geom_col() +
  labs(x = "HTO classification", y = "Number of Cells", fill = "Cell Type") +
  theme_classic() +
  facet_wrap(~sample_id, nrow = 3, scales = "free")

p```

**Comment by ncborcherding** [comment]
Hey David, 

Dev version has a new function ```checkContigs()``` that will quantify the na values per grouping of either the chain/gene usage. So as of right now you can quantify the percent of cells with NAs per chain (not at least one chain). Please feel free to [email ](mailto:ncborch@gmail.com) me any suggestions for further improvements.

The second suggestion I think will be incorporated into the new #209 ```vizGenes()``` function that will be able to compare different chains. Which is next on my list. 

Nick
