### ISSUE TITLE
Does the y axis of `clonalHomeostasis` represent clonotypes or cells?

### ISSUE THREAD

**Issue by lucygarner** [ncborcherding/scRepertoire#223]
Hi,

As clarification, does `clonalHomeostasis` plot the proportion of clonotypes that are in each category or the proportion of cells that belong to a clonotype in each category i.e. does the y axis refer to clonotypes or cells? It seems to be the latter based on the output.

Best wishes,
Lucy

**Comment by ncborcherding** [comment]
Hey Lucy, 

```clonalHomeostasis()``` plots the relative proportion of overall cells with clonotypes in the assigned groupings - this can be thought of as the proportion of the recovered repertoire. Hope that helps, let me know if you have any other questions.

Nick
