### ISSUE TITLE
question about combineTRUST4 function

### ISSUE THREAD

**Issue by louxiaoying** [ncborcherding/scRepertoire#224]
1.Was TRUST4 output file named "airr.tsv" the input object for config_list? Or the entire directory?

2.TRUST4 output file named "airr.tsv" didn't have chain column,but I found the code of combineTRUST4 function has "TCRA <- str_split(df[[i]]$chain2, ",", simplify = TRUE)[,seq_len(6)]", and I always got error here with "Error in str_split(df[[i]]$chain1, ",", simplify = TRUE)[, seq_len(6)] : subscript out of bounds"

Can you please explain your combineTRUST4 function in detail?

**Comment by ncborcherding** [comment]
Hey @louxiaoying, 

Thanks for reaching out. ```combineTRUST4()``` functions with the barcode_report.tsv file. The function itself assumes a list data frames - each barcode_report.tsv should be read in and formed into a list. 

In the newer version of scRepertoire (see dev version) ```combineTRUST4()``` has been deprecated and replaced by ```loadContigs()```, which will format a number of pipelines to be compatible with scRepertoire before using ```combineTCR()```. 

Hope that helps and feel free to reach out if you have any other questions. 

Nick

**Comment by louxiaoying** [comment]
Thank you for your timely reply,Nick. I have successfully run all your code after solving input file question~

Xiaoying Lou
