### ISSUE TITLE
ClonalNetwork

### ISSUE THREAD

**Issue by codeneeded** [ncborcherding/scRepertoire#225]
When using the clonal network function I see arrows going to nearly all clusters. Some of these clusters include B cells and monocytes which would not have TCR.  In the example vignette, analysis is performed on T-Cells alone, rather than a PBMC data set containing T-Cells. 

Do you need to first filter cells to only T-Cells before doing this analysis? Is my understanding of this correct, in that ClonalNetwork graph is telling me there between the two clusters connected by an arrow there are shared clonotypes in both clusters that originated from the origin of the arrow? (In which case you shouldn't see shared TCR clonotypes in B cells or monocytes?

**Comment by ncborcherding** [comment]
Hey codeneeded, 

The addition of the TCR data with ```combineExpression()``` will add the clonotype information across the entire single-cell object. It is really common to see TCRs or BCRs in non-lymphoid clusters - this might be a result of doublets, ambient RNA, etc. If you truly want to see the relationship between TCRs of T cells, I generally suggest you remove the TCRs (in the meta data) in non-T cell clusters (if you are fairly confident the clusters are not T cells). 

When there is an arrow between clusters in ```clusterNetwork()``` there means there are shared clonotypes. The direction of the arrow indicates the relative proportion of "overlap" from the origin to the destination (where the arrow points). This does not necessarily say that the clonotypes "started" or "originated" in the cluster, but a way to visualize relative overlaps of clonotypes across the UMAP. 

Nick

**Comment by codeneeded** [comment]
Thank you. Another potential issue is the chain argument here. Regardless of what chain I call (both, IGH, IGL) I get equivalent graphs to TRA and TRB in my combined TCR. 

When using BCR, calling any chain gives the same output.

**Comment by codeneeded** [comment]
Also to visualize TCR I would use the cloneCall = aa or nt (CDRC3), while for BCR I should use 'gene' (VDJC gene). Strict would then show both TCR and BCR? Is this correct?

**Comment by ncborcherding** [comment]
Hey codeneeded, 

As the function is written - there are no filtering across any visualization to separate BCRs from TCRs (or vice versa). The chain argument will select the heavy/light or TRA/TRB chains relative to the combined clonotypes (CTaa, CTnet, etc). There is a large degree of overlap between the clone calls in "gene", "aa", "nt", so the clonalNetwork may be the best way to evaluate that. 

Nick

**Comment by codeneeded** [comment]
Is there any way to look at clonotype distribution separated by cluster? I'm trying to look at the amount of clonotype per cluster to see if its just ambient RNA or something else.

I tried the occupiedscRepitoire function but I'm unable to get an interpretable graph out of it. It seems all the clusters are overlapping and put next to each other from the output. Is there any way to fix this output? Thanks so much for your help!
![Rplot2](https://user-images.githubusercontent.com/123397843/221613406-91ee608a-db20-4788-9c32-3090a67d31ca.png)

**Comment by ncborcherding** [comment]
What do you mean by clonotype distribution across clusters?

**Comment by purisuto** [comment]
Sorry to jump in here, but with clonalNetwork() is it possible to list out the information of the shared clones?  It would be useful to have a list of the top shared clones across Seurat clusters with associated information like chain type and number of cells in each cluster with that clone.

**Comment by ncborcherding** [comment]
Hey David, 

Great suggested - as of right now clonalNetwork only exports weights - you could likely identify the clones using compareClonotypes() iteratively. But that is not a ideal scenario. I will maker this as a suggestion for future versions (actively working on a bigger release).

**Comment by purisuto** [comment]
As a workaround for the meantime, I did this:

`trace(clonalNetwork, edit = T)`

Put in line 
`netout <<- clones.to.filter`

Then you can highlight the actual cells
`seurat <- highlightClonotypes(seurat, cloneCall= "aa", sequence = netout)`

And plot them on a UMAP of your choosing
`p <- DimPlot(seurat, group.by = "highlight", cols = c("red","blue","green"), na.value = "#80808030", pt.size = 2) + theme(plot.title = element_blank())`
