### ISSUE TITLE
List output of most expanded clonotypes

### ISSUE THREAD

**Issue by codeneeded** [ncborcherding/scRepertoire#226]
Is there a way to extract a cluster-wise list of clonotypes,  arranged in order of frequency of expression?

So the output would be:
Column 1 - Clonotype (The input used for the highlight clonotype function) | Column 2 - Frequency of Occurrence | Column 3 - Seurat Cluster | Column 4 - Sample

**Comment by ncborcherding** [comment]
Hey codeneeded, 

You can extract this type of information with dplyr with a call like: 

```
seuratObj@meta.data %>%
        group_by(CTaa, seurat_cluster, Sample) %>% #This is assuming you want CTaa as your clonotype. 
        count()
```

The output of this will be a 4 column tibble with:

- column 1- clonotype
- column 2 - cluster
- column 3 - sample
- column 4 - frequency of the clonotype across the above info

You can adjust the group_by variable to get other clonotype frequency information. 

Hope that helps,
Nick

**Comment by codeneeded** [comment]
> Hey codeneeded,
> 
> You can extract this type of information with dplyr with a call like:
> 
> ```
> seuratObj@meta.data %>%
>         group_by(CTaa, seurat_cluster, Sample) %>% #This is assuming you want CTaa as your clonotype. 
>         count()
> ```
> 
> The output of this will be a 4 column tibble with:
> 
> * column 1- clonotype
> * column 2 - cluster
> * column 3 - sample
> * column 4 - frequency of the clonotype across the above info
> 
> You can adjust the group_by variable to get other clonotype frequency information.
> 
> Hope that helps, Nick

Thank you so much. This helps  a ton!
