### ISSUE TITLE
Question about diversity metrics and sample cell numbers

### ISSUE THREAD

**Issue by sloanlewis** [ncborcherding/scRepertoire#227]
Hi Nick!
This is not an issue, but I have a question about a data set I am working on and using scRepertoire to analyze. I am trying to calculate diversity metrics across some samples that have very different numbers of cells (ie. 50 cells vs. 2,000 cells). It seems that a lot of the diversity metrics are affected by this large difference. I am trying to avoid downsampling, so I was wondering if you knew of a diversity metric that was not dependent on cell number? And then jumping from there, it would be great if there were a few more diversity metric options within scRepertoire so that I can test more (Gini-simpson was one I was looking for). Any advice would be very helpful and thanks for a really great single cell analysis tool!
Sloan

**Comment by ncborcherding** [comment]
Hey Sloan, 

You are very right - the downsampling would be pretty unreliable in comparing something like 50 and 2000 cells. Unfortunately I am not aware of really any diversity metric that does not have some inherent bias in the comparison between large population differences. You might try the [iNEXT](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.12613) R package for rarefication and extrapolation of the different populations. 

The Inv Simpson index is the inverse of the Gini-Simpson Index, so you can just use 1/index to get the desired value. 

Hope that helps, let me know if you have any other questions.

Nick

**Comment by sloanlewis** [comment]
Thanks! I will check that out.
