### ISSUE TITLE
error with dataframe undefined columns

### ISSUE THREAD

**Issue by dxl3742** [ncborcherding/scRepertoire#228]
Hello,
I am running scRepertoire 1.7.1, previously I subsetted all my seurat object to keep only cells with tcr sequences, then ran clustering, and the codes were fine. However, I just combined TCR into the original seurat object (after clustering), and none of the functions work. All of my clusters have cells both with and without tcr. I have tried subsetting on cells with tcr, but it still returns the same error. I'm not sure what the problem is, all the functions ran fine before. :(
Error in `[.data.frame`(meta, , split.by) : undefined columns selected

**Comment by dxl3742** [comment]
Hey Nick,
Thank you so much for the prompt reply!
I haven't inputted anything into the code. None of the codes work, and they all return the same error.
quantContig(cd8, cloneCall="gene+nt", scale = T)
abundanceContig(cd8, cloneCall = "gene", scale = F)
Error in `[.data.frame`(meta, , split.by) : undefined columns selected

> cd8
An object of class Seurat
20057 features across 88986 samples within 1 assay
Active assay: RNA (20057 features, 2000 variable features)
3 dimensional reductions calculated: pca, harmony, umap

cd8@meta.data$tcr <- 'no'
cd8@meta.data$tcr[which(cd8@meta.data$Frequency>0)] <- 'tcr'
> table(cd8@meta.data$tcr, cd8@meta.data$RNA_snn_res.0.5)

          0     1    10    11    12    13    14    15    16    17    18    19
  no   3145  3209  1394   240   171   644   432   365   458   407   123   270
  tcr 18523 16313   106   645   706   206   264   293   123    89   273   108

          2    20     3     4     5     6     7     8     9
  no   1651   113  4335   803   958  2675   509   322   456
  tcr 10875    28  3836  5237  4073   744  1327  1473  1064

**Comment by ncborcherding** [comment]
And you have used ```combineExpression()``` on the cd8 seurat object to attach your TCRs?

Nick

**Comment by dxl3742** [comment]
Hey again Nick,
Yes, I have, I did read.csv, combineTCR, and combineExpression. 
I'm sorry about the previous error, I realized I was calling the quantContig functions from the seurat object instead of the combined TCR list. Now I am able to DimPlot clonotype and clonaloverlay, but not clonalDiversity. I am still getting the same split.by error.

**Comment by ncborcherding** [comment]
Hey dxl3742, 

A couple of thoughts:

1.  if left NULL, **split.by** will pull the default identity of seurat object. I would make sure you have ```Ident(seuratObj)``` returning a variable or implicitly call **split.by = "X"** for whatever variable. 
2. Newer version of scRepertoire have expanded support for seurat objects to allow for direct visualizations of clone information and not everything has been passed to the master branch. You might try updating to the dev version with ```devtools::install_github("ncborcherding/scRepertoire@dev")``` and restart your R session.

Please let me know if the problem persists and we can troubleshoot from there. 

Nick

**Comment by dxl3742** [comment]
Hey Nick,
Thanks for the reply, it turns out that I had a few empty cluster identities without cells left after subsetting the seurat object, then all the package functions started working again after I cleaned those up. Thanks for the great package!
Happy weekends. :)
