### ISSUE TITLE
possible inconsistency in compareClonotypes frequency calculation

### ISSUE THREAD

**Issue by gianfilippo** [ncborcherding/scRepertoire#231]
Hi,

I tried to run compareClonotypes using first the combineTCR output and then the expression2List from the Seurat object after combineExpression.
I may be wrong, but I see an inconsistency in the frequency calculation.
The inconsistency may be due to the different length of the combineTCR output and the expression2List from the Seurat object after combineExpression. 
This is because in combineTCR not all barcode are associated to an actual cell, which are removed by the combineExpression function.

Best

**Comment by ncborcherding** [comment]
Hey Gianfilippo, 

Thanks for reaching out - your instincts are correct. The output of ```compareClonotype()``` is likely to change between the direct ```combineTCR()``` object and ```expression2List()``` output as a result of matching the barcodes to the single-cell object. ```combineExpression()``` will remove the contigs/barcodes that do not have the corresponding expression values. In my experience, there is usually about an 80-85% overlap between the recovered contigs and RNA values. So ultimately, this is not necessarily an issue, but a result of the analysis workflow.

Hope that helps clarify and please let me know if you have any additional questions or suggestions.

Nick

**Comment by gianfilippo** [comment]
Hi Nick,

thanks for your reply. I just wanted to make sure. Thanks for developing the package!!

On a different note, I thought it could be useful to be able to track clonotypes across conditions and clusters, for instance having a compareClonotype kind of plot, with a couple (or more) of extra vertical axis, like
clonotypes (condA/time1), clusters (condA/time1), (condB/time2), clonotypes (condB/time2)

I am looking at the ggalluvial package, which I believe you also used. Is there a simpler/better way to do this ?

Best

**Comment by gianfilippo** [comment]
Thanks
