### ISSUE TITLE
Clarification vizgenes

### ISSUE THREAD

**Issue by NK-HD** [ncborcherding/scRepertoire#234]
Hey Nick,

amazing work & package! One clarifying question regarding the vizgenes() VDJ usage analysis function:
- Are the gene counts normalised to Clonotype frequency or total count per sample? (so potentially biased by clonotype freq)?

Excuse me, if I missd this info somewhere!

Thanks a lot and have a nice day!
Best,
Niklas

**Comment by ncborcherding** [comment]
Hey Niklas, 

Thanks for reaching out and actually good question! The scaling is based on the size of the repertoire per sample. The actual call is: 

```
df[,"n"] <- df[,"n"]/df[,"sum"]
```

So it is taking the number for an individual clone over the total number of clones in the sample (sum is the sum(n))

I hope that makes sense and please let me know if you have suggestions! I need to clarify this in the documentation and vignette too. 

Nick
