### ISSUE TITLE
Annotation BCR

### ISSUE THREAD

**Issue by beginner984** [ncborcherding/scRepertoire#238]
Hi

By your software I have `1269 BCRs` having matched barcode with `GEX 5'` and I can recognize hyper expanded clones too

But, I am desperate to know these BCR clones related to what (`cancer`, `virus`, etc)

I have found `TBAdb` databse but none of my BCRs are there;

Based on your experiences, please how do you annotate these BCR clones (to public or novel)?

Thank you very much for any help

**Comment by ncborcherding** [comment]
Hey @beginner984, 

Unfortunately, I have yet to find a good resource for annotating BCRs. I would love to add something like ```annotateDB()``` in [Trex](https://ncborcherding.github.io/vignettes/Trex.html#5_Annotating_possible_epitopes) for BCRs. If you find a resource, please let me know!

Nick

**Comment by beginner984** [comment]
Thank you @ncborcherding 

Today I noticed this for BCR http://tools.iedb.org/main/bcell/

By the way, today I just knew about Trex for TCR annotation, thanks for developing that
I am going to try that on my data
