### ISSUE TITLE
display more than two samples/tissues in compareClonotypes ?

### ISSUE THREAD

**Issue by gt7901b** [ncborcherding/scRepertoire#24]
Hi,Nick:

Currently, it seems that compareClonotypes can only take two samples. Is it possible to take 3 or 4? like in 
alluvialClonotypes function? 

thanks

**Comment by ncborcherding** [comment]
Hey gt7901b,

You should be able to compare any or all of your samples in compareClonotype - you can use the **samples** parameter to select the ones you are interested in or leave it blank and it will display all the samples. 

Feel free to post your compareClonotype() call here or [email me](mailto:ncborch@gmail.com) and we can see what is up. Or send me the error you are getting.

Thanks,
Nick

**Comment by gt7901b** [comment]
yes. It worked when I leave samples blank. Thank you!

**Comment by gt7901b** [comment]
Hi: Nick

I wonder if you could add power law plot for abundanceContig function?  thanks
