### ISSUE TITLE
filter out non expanded clonotypes

### ISSUE THREAD

**Issue by christoforos-dimitropoulos** [ncborcherding/scRepertoire#240]
Hello,

This might have been asked or mentioned somewhere already, but I probably missed it:

how can unexpanded clones be filtered out of the dataset? like for example, if I want to exclude clonotypes that are found in less than 4 cells 
and a bit more generally: is there an easy way to calculate the counts of each clonotype apart from the frequency?

Thanks a lot 

Update

**Comment by ncborcherding** [comment]
Hey Christoforos, 

Thanks for reaching out - I actually don't believe I have gotten this question before. Are you envisioning filtering after ```combineTCR()/combineBCR()``` or ```combineExpression()```? For the latter, you could use dplyr to identify the clones, then remove the cells with those clones:

```
library(dplyr)
meta <- seurat[[]]
clone.summary <- meta %>%
                   group_by(CTaa) %>%
                   count() %>% 
                   filter(n > 4)
cells <- rownames(meta)[meta$CTaa %in% clone.summary[,1]]
subset.seurat <- subset(seurat, cells = cells)
```
I am on a phone so please check that code. If that is not what you are thinking, let me know and I can help troubleshoot!

Thanks,
Nick

**Comment by ncborcherding** [comment]
I am closing this for now - please let me know if you have any additional questions or suggestions.
