### ISSUE TITLE
Subscript out of bounds error with clusterTCR

### ISSUE THREAD

**Issue by khain2650** [ncborcherding/scRepertoire#242]
Hi Nick,

Thank you very much for the useful package! I am analyzing single cell BCR/TCR seq data. The TCR and seurat object have been combined using the combineExpression function, and I'm currently trying to cluster the clonotypes. For some reason, when I use clusterTCR() on my seurat object, I run into the error:
```
Error in str_split(dat[[y]]$CTaa, "_", simplify = TRUE)[, 1] : 
  subscript out of bounds
```
This error is not seen when running the function with the combined contig file. 

I understand clusterTCR functionality with single cell objects is restricted to the dev version only; I'm using the dev version of scRepertoire (1.7.4). I'd appreciate any advice you may have!

**Comment by ncborcherding** [comment]
Hey Khain2650, 

Thanks for reaching out - the error indicates there is likely an issue in splitting the column - this may in fact be my fault, as I have just upgraded the function to work faster. Could you do me a favor and give me:

- the exact call you are using for ``clusterTCR()```
- the output of ```head(seuratObj)```
- the output of ```sessionInfo()```

I should be able to track the issue done from there and get you a fix (I hope!).

Nick

**Comment by khain2650** [comment]
Hi Nick,

I used the following call for clusterTCR:

`seurat <- clusterTCR(seurat,
                     chain = "TRB",
                     group.by = "group", 
                     sequence = "aa", 
                     threshold = 0.85)`

The output of head(seuratObj) is as follows:
`                                  orig.ident nCount_RNA nFeature_RNA   batch      group percent.mt nCount_SCT nFeature_SCT integrated_snn_res.0.4 seurat_clusters
pouch_ctrl_1_AAACCTGAGCAGACTG-1 pouch_ctrl_1       5988         2122 MGI3943 pouch_ctrl   1.937208       4110         2079                      1               1
pouch_ctrl_1_AAACCTGAGGTCGGAT-1 pouch_ctrl_1       4018         1433 MGI3943 pouch_ctrl   3.409657       3697         1433                      1               0
pouch_ctrl_1_AAACCTGAGTATCTCG-1 pouch_ctrl_1       3956         1676 MGI3943 pouch_ctrl   7.178969       3725         1676                      1               1
pouch_ctrl_1_AAACCTGCATCTCGCT-1 pouch_ctrl_1       8816         2933 MGI3943 pouch_ctrl   5.977768       4228         2214                      1               8
pouch_ctrl_1_AAACCTGGTAGTAGTA-1 pouch_ctrl_1       3218         1514 MGI3943 pouch_ctrl   7.706650       3322         1514                      1               3
pouch_ctrl_1_AAACCTGTCTCACATT-1 pouch_ctrl_1      10824         3401 MGI3943 pouch_ctrl   3.058019       3760         1771                      1               8
pouch_ctrl_1_AAACGGGAGAATGTGT-1 pouch_ctrl_1       5356         2239 MGI3943 pouch_ctrl   6.814787       4154         2235                      6              10
pouch_ctrl_1_AAACGGGAGGCATTGG-1 pouch_ctrl_1       2976         1540 MGI3943 pouch_ctrl   3.763441       3176         1539                      6               2
pouch_ctrl_1_AAACGGGGTACAGCAG-1 pouch_ctrl_1       1967         1106 MGI3943 pouch_ctrl   4.524657       2922         1118                      7               6
pouch_ctrl_1_AAACGGGGTCGATTGT-1 pouch_ctrl_1       5570         2123 MGI3943 pouch_ctrl   9.784560       4119         2114                      6              10
                                pANN_0.25_0.005_1010.775 doublet_finder pANN_0.25_0.001_1170.825 pANN_0.25_0.005_1131.525 pANN_0.25_0.01_1184.925
pouch_ctrl_1_AAACCTGAGCAGACTG-1               0.14444444        Singlet                       NA                       NA                      NA
pouch_ctrl_1_AAACCTGAGGTCGGAT-1               0.12222222        Singlet                       NA                       NA                      NA
pouch_ctrl_1_AAACCTGAGTATCTCG-1               0.10000000        Singlet                       NA                       NA                      NA
pouch_ctrl_1_AAACCTGCATCTCGCT-1               0.14444444        Singlet                       NA                       NA                      NA
pouch_ctrl_1_AAACCTGGTAGTAGTA-1               0.23333333        Singlet                       NA                       NA                      NA
pouch_ctrl_1_AAACCTGTCTCACATT-1               0.05555556        Singlet                       NA                       NA                      NA
pouch_ctrl_1_AAACGGGAGAATGTGT-1               0.08888889        Singlet                       NA                       NA                      NA
pouch_ctrl_1_AAACGGGAGGCATTGG-1               0.14444444        Singlet                       NA                       NA                      NA
pouch_ctrl_1_AAACGGGGTACAGCAG-1               0.08888889        Singlet                       NA                       NA                      NA
pouch_ctrl_1_AAACGGGGTCGATTGT-1               0.16666667        Singlet                       NA                       NA                      NA
                                pANN_0.25_0.001_2298.975 pANN_0.25_0.04_958.65 pANN_0.25_0.005_1038.75 pANN_0.25_0.02_676.2 pANN_0.25_0.005_376.5
pouch_ctrl_1_AAACCTGAGCAGACTG-1                       NA                    NA                      NA                   NA                    NA
pouch_ctrl_1_AAACCTGAGGTCGGAT-1                       NA                    NA                      NA                   NA                    NA
pouch_ctrl_1_AAACCTGAGTATCTCG-1                       NA                    NA                      NA                   NA                    NA
pouch_ctrl_1_AAACCTGCATCTCGCT-1                       NA                    NA                      NA                   NA                    NA
pouch_ctrl_1_AAACCTGGTAGTAGTA-1                       NA                    NA                      NA                   NA                    NA
pouch_ctrl_1_AAACCTGTCTCACATT-1                       NA                    NA                      NA                   NA                    NA
pouch_ctrl_1_AAACGGGAGAATGTGT-1                       NA                    NA                      NA                   NA                    NA
pouch_ctrl_1_AAACGGGAGGCATTGG-1                       NA                    NA                      NA                   NA                    NA
pouch_ctrl_1_AAACGGGGTACAGCAG-1                       NA                    NA                      NA                   NA                    NA
pouch_ctrl_1_AAACGGGGTCGATTGT-1                       NA                    NA                      NA                   NA                    NA
                                pANN_0.25_0.005_599.55 pANN_0.25_0.01_86.25 pANN_0.25_0.03_288.525 pANN_0.25_0.01_463.725 pANN_0.25_0.07_570.75
pouch_ctrl_1_AAACCTGAGCAGACTG-1                     NA                   NA                     NA                     NA                    NA
pouch_ctrl_1_AAACCTGAGGTCGGAT-1                     NA                   NA                     NA                     NA                    NA
pouch_ctrl_1_AAACCTGAGTATCTCG-1                     NA                   NA                     NA                     NA                    NA
pouch_ctrl_1_AAACCTGCATCTCGCT-1                     NA                   NA                     NA                     NA                    NA
pouch_ctrl_1_AAACCTGGTAGTAGTA-1                     NA                   NA                     NA                     NA                    NA
pouch_ctrl_1_AAACCTGTCTCACATT-1                     NA                   NA                     NA                     NA                    NA
pouch_ctrl_1_AAACGGGAGAATGTGT-1                     NA                   NA                     NA                     NA                    NA
pouch_ctrl_1_AAACGGGAGGCATTGG-1                     NA                   NA                     NA                     NA                    NA
pouch_ctrl_1_AAACGGGGTACAGCAG-1                     NA                   NA                     NA                     NA                    NA
pouch_ctrl_1_AAACGGGGTCGATTGT-1                     NA                   NA                     NA                     NA                    NA
                                pANN_0.25_0.01_141.225 pANN_0.25_0.01_84.525 pANN_0.25_0.005_274.5 pANN_0.25_0.01_109.425 pANN_0.25_0.005_161.25
pouch_ctrl_1_AAACCTGAGCAGACTG-1                     NA                    NA                    NA                     NA                     NA
pouch_ctrl_1_AAACCTGAGGTCGGAT-1                     NA                    NA                    NA                     NA                     NA
pouch_ctrl_1_AAACCTGAGTATCTCG-1                     NA                    NA                    NA                     NA                     NA
pouch_ctrl_1_AAACCTGCATCTCGCT-1                     NA                    NA                    NA                     NA                     NA
pouch_ctrl_1_AAACCTGGTAGTAGTA-1                     NA                    NA                    NA                     NA                     NA
pouch_ctrl_1_AAACCTGTCTCACATT-1                     NA                    NA                    NA                     NA                     NA
pouch_ctrl_1_AAACGGGAGAATGTGT-1                     NA                    NA                    NA                     NA                     NA
pouch_ctrl_1_AAACGGGAGGCATTGG-1                     NA                    NA                    NA                     NA                     NA
pouch_ctrl_1_AAACGGGGTACAGCAG-1                     NA                    NA                    NA                     NA                     NA
pouch_ctrl_1_AAACGGGGTCGATTGT-1                     NA                    NA                    NA                     NA                     NA
                                pANN_0.25_0.01_932.55 pANN_0.25_0.005_1435.5 nCount_integrated nFeature_integrated SCT_snn_res.0.4 SCT_snn_res.0.6
pouch_ctrl_1_AAACCTGAGCAGACTG-1                    NA                     NA                 0                   0               0               1
pouch_ctrl_1_AAACCTGAGGTCGGAT-1                    NA                     NA                 0                   0               1               0
pouch_ctrl_1_AAACCTGAGTATCTCG-1                    NA                     NA                 0                   0               0               1
pouch_ctrl_1_AAACCTGCATCTCGCT-1                    NA                     NA                 0                   0               0               8
pouch_ctrl_1_AAACCTGGTAGTAGTA-1                    NA                     NA                 0                   0               6               3
pouch_ctrl_1_AAACCTGTCTCACATT-1                    NA                     NA                 0                   0               0               8
pouch_ctrl_1_AAACGGGAGAATGTGT-1                    NA                     NA                 0                   0               3              10
pouch_ctrl_1_AAACGGGAGGCATTGG-1                    NA                     NA                 0                   0               3               2
pouch_ctrl_1_AAACGGGGTACAGCAG-1                    NA                     NA                 0                   0               5               6
pouch_ctrl_1_AAACGGGGTCGATTGT-1                    NA                     NA                 0                   0               3              10
                                                        barcode                                                                                       CTgene
pouch_ctrl_1_AAACCTGAGCAGACTG-1                            <NA>                                                                                         <NA>
pouch_ctrl_1_AAACCTGAGGTCGGAT-1 pouch_ctrl_1_AAACCTGAGGTCGGAT-1                                           TRAV29/DV5.TRAJ40.TRAC_TRBV7-2.TRBD1.TRBJ1-2.TRBC1
pouch_ctrl_1_AAACCTGAGTATCTCG-1 pouch_ctrl_1_AAACCTGAGTATCTCG-1                                             TRAV9-2.TRAJ29.TRAC_TRBV20-1.TRBD2.TRBJ2-3.TRBC2
pouch_ctrl_1_AAACCTGCATCTCGCT-1                            <NA>                                                                                         <NA>
pouch_ctrl_1_AAACCTGGTAGTAGTA-1 pouch_ctrl_1_AAACCTGGTAGTAGTA-1                                             TRAV23/DV6.TRAJ29.TRAC_TRBV20-1.NA.TRBJ2-2.TRBC2
pouch_ctrl_1_AAACCTGTCTCACATT-1 pouch_ctrl_1_AAACCTGTCTCACATT-1 TRAV14/DV4.TRAJ23.TRAC;TRAV8-6.TRAJ27.TRAC_TRBV7-6.NA.TRBJ2-5.TRBC2;TRBV7-2.NA.TRBJ2-7.TRBC2
pouch_ctrl_1_AAACGGGAGAATGTGT-1 pouch_ctrl_1_AAACGGGAGAATGTGT-1                                                 TRAV19.TRAJ34.TRAC_TRBV11-3.NA.TRBJ2-5.TRBC2
pouch_ctrl_1_AAACGGGAGGCATTGG-1 pouch_ctrl_1_AAACGGGAGGCATTGG-1                                             TRAV9-2.TRAJ43.TRAC_TRBV29-1.TRBD1.TRBJ2-3.TRBC2
pouch_ctrl_1_AAACGGGGTACAGCAG-1 pouch_ctrl_1_AAACGGGGTACAGCAG-1                                                TRAV38-1.TRAJ41.TRAC_TRBV7-8.NA.TRBJ2-7.TRBC2
pouch_ctrl_1_AAACGGGGTCGATTGT-1 pouch_ctrl_1_AAACGGGGTCGATTGT-1                                              TRAV14/DV4.TRAJ8.TRAC_TRBV11-2.NA.TRBJ2-7.TRBC2
                                                                                                                                                                                                    CTnt
pouch_ctrl_1_AAACCTGAGCAGACTG-1                                                                                                                                                                     <NA>
pouch_ctrl_1_AAACCTGAGGTCGGAT-1                                                                                       TGTGCAGCAAGCGTAGAATCAGGAACCTACAAATACATCTTT_TGTGCCAGCAGCCCCGGACAGGGGTTTGGCTACACCTTC
pouch_ctrl_1_AAACCTGAGTATCTCG-1                                                                                 TGTGCTCTGCGGGGCTCAGGAAACACACCTCTTGTCTTT_TGCAGTGCTCCCGGACTAGCGGGAGGGCAACCAGATACGCAGTATTTT
pouch_ctrl_1_AAACCTGCATCTCGCT-1                                                                                                                                                                     <NA>
pouch_ctrl_1_AAACCTGGTAGTAGTA-1                                                                                    TGTGCAGCAAGCACCGCAGGAAACACACCTCTTGTCTTT_TGCAGTGCTCCGCCTAGCGGTACGAACACCGGGGAGCTGTTTTTT
pouch_ctrl_1_AAACCTGTCTCACATT-1 TGTGCAATGAGAGAGGGCCACAGCCAGGGAGGAAAGCTTATCTTC;TGTGCTGTGAGTGATCGGGCCAATGCAGGCAAATCAACCTTT_TGTGCCAGCAGCCAACCAGGGGGCCAAGAGACCCAGTACTTC;TGTGCCAGCAGCCAGAGCTCCTACGAGCAGTACTTC
pouch_ctrl_1_AAACGGGAGAATGTGT-1                                                                                    TGTGCTCTGAGTGAGACTACGAACGACAAGCTCATCTTT_TGTGCCAGCAGCTTAGGGGGGAGGGTTTCGGAGACCCAGTACTTC
pouch_ctrl_1_AAACGGGAGGCATTGG-1                                                                                                TGTGCTCTGAGTGTCAATGACATGCGCTTT_TGCAGCGTTGAAGGAGGAGGGGGCATAGATACGCAGTATTTT
pouch_ctrl_1_AAACGGGGTACAGCAG-1                                                                                    TGTGCTGAACGGGCTGATTCCGGGTATGCACTCAACTTC_TGTGCCAGCAGCTTATTACAGGGGCCATCCTACGAGCAGTACTTC
pouch_ctrl_1_AAACGGGGTCGATTGT-1                                                                                          TGTGCAATGCCCGGCTTTCAGAAACTTGTATTT_TGTGCCAGCAGCTTAGAATTTCACAGGACTCACGAGCAGTACTTC
                                                                                      CTaa
pouch_ctrl_1_AAACCTGAGCAGACTG-1                                                       <NA>
pouch_ctrl_1_AAACCTGAGGTCGGAT-1                               CAASVESGTYKYIF_CASSPGQGFGYTF
pouch_ctrl_1_AAACCTGAGTATCTCG-1                             CALRGSGNTPLVF_CSAPGLAGGQPDTQYF
pouch_ctrl_1_AAACCTGCATCTCGCT-1                                                       <NA>
pouch_ctrl_1_AAACCTGGTAGTAGTA-1                              CAASTAGNTPLVF_CSAPPSGTNTGELFF
pouch_ctrl_1_AAACCTGTCTCACATT-1 CAMREGHSQGGKLIF;CAVSDRANAGKSTF_CASSQPGGQETQYF;CASSQSSYEQYF
pouch_ctrl_1_AAACGGGAGAATGTGT-1                              CALSETTNDKLIF_CASSLGGRVSETQYF
pouch_ctrl_1_AAACGGGAGGCATTGG-1                                  CALSVNDMRF_CSVEGGGGIDTQYF
pouch_ctrl_1_AAACGGGGTACAGCAG-1                              CAERADSGYALNF_CASSLLQGPSYEQYF
pouch_ctrl_1_AAACGGGGTCGATTGT-1                                CAMPGFQKLVF_CASSLEFHRTHEQYF
                                                                                                                                                                                                                                                                                             CTstrict
pouch_ctrl_1_AAACCTGAGCAGACTG-1                                                                                                                                                                                                                                                                  <NA>
pouch_ctrl_1_AAACCTGAGGTCGGAT-1                                                                                                                                 TRAV29/DV5.TRAJ40.TRAC_TGTGCAGCAAGCGTAGAATCAGGAACCTACAAATACATCTTT_TRBV7-2.TRBD1.TRBJ1-2.TRBC1_TGTGCCAGCAGCCCCGGACAGGGGTTTGGCTACACCTTC
pouch_ctrl_1_AAACCTGAGTATCTCG-1                                                                                                                             TRAV9-2.TRAJ29.TRAC_TGTGCTCTGCGGGGCTCAGGAAACACACCTCTTGTCTTT_TRBV20-1.TRBD2.TRBJ2-3.TRBC2_TGCAGTGCTCCCGGACTAGCGGGAGGGCAACCAGATACGCAGTATTTT
pouch_ctrl_1_AAACCTGCATCTCGCT-1                                                                                                                                                                                                                                                                  <NA>
pouch_ctrl_1_AAACCTGGTAGTAGTA-1                                                                                                                                TRAV23/DV6.TRAJ29.TRAC_TGTGCAGCAAGCACCGCAGGAAACACACCTCTTGTCTTT_TRBV20-1.NA.TRBJ2-2.TRBC2_TGCAGTGCTCCGCCTAGCGGTACGAACACCGGGGAGCTGTTTTTT
pouch_ctrl_1_AAACCTGTCTCACATT-1 TRAV14/DV4.TRAJ23.TRAC;TRAV8-6.TRAJ27.TRAC_TGTGCAATGAGAGAGGGCCACAGCCAGGGAGGAAAGCTTATCTTC;TGTGCTGTGAGTGATCGGGCCAATGCAGGCAAATCAACCTTT_TRBV7-6.NA.TRBJ2-5.TRBC2;TRBV7-2.NA.TRBJ2-7.TRBC2_TGTGCCAGCAGCCAACCAGGGGGCCAAGAGACCCAGTACTTC;TGTGCCAGCAGCCAGAGCTCCTACGAGCAGTACTTC
pouch_ctrl_1_AAACGGGAGAATGTGT-1                                                                                                                                    TRAV19.TRAJ34.TRAC_TGTGCTCTGAGTGAGACTACGAACGACAAGCTCATCTTT_TRBV11-3.NA.TRBJ2-5.TRBC2_TGTGCCAGCAGCTTAGGGGGGAGGGTTTCGGAGACCCAGTACTTC
pouch_ctrl_1_AAACGGGAGGCATTGG-1                                                                                                                                            TRAV9-2.TRAJ43.TRAC_TGTGCTCTGAGTGTCAATGACATGCGCTTT_TRBV29-1.TRBD1.TRBJ2-3.TRBC2_TGCAGCGTTGAAGGAGGAGGGGGCATAGATACGCAGTATTTT
pouch_ctrl_1_AAACGGGGTACAGCAG-1                                                                                                                                   TRAV38-1.TRAJ41.TRAC_TGTGCTGAACGGGCTGATTCCGGGTATGCACTCAACTTC_TRBV7-8.NA.TRBJ2-7.TRBC2_TGTGCCAGCAGCTTATTACAGGGGCCATCCTACGAGCAGTACTTC
pouch_ctrl_1_AAACGGGGTCGATTGT-1                                                                                                                                       TRAV14/DV4.TRAJ8.TRAC_TGTGCAATGCCCGGCTTTCAGAAACTTGTATTT_TRBV11-2.NA.TRBJ2-7.TRBC2_TGTGCCAGCAGCTTAGAATTTCACAGGACTCACGAGCAGTACTTC
                                Frequency            cloneType
pouch_ctrl_1_AAACCTGAGCAGACTG-1        NA                 <NA>
pouch_ctrl_1_AAACCTGAGGTCGGAT-1         1  Single (0 < X <= 1)
pouch_ctrl_1_AAACCTGAGTATCTCG-1         5   Small (1 < X <= 5)
pouch_ctrl_1_AAACCTGCATCTCGCT-1        NA                 <NA>
pouch_ctrl_1_AAACCTGGTAGTAGTA-1         1  Single (0 < X <= 1)
pouch_ctrl_1_AAACCTGTCTCACATT-1         1  Single (0 < X <= 1)
pouch_ctrl_1_AAACGGGAGAATGTGT-1         1  Single (0 < X <= 1)
pouch_ctrl_1_AAACGGGAGGCATTGG-1         1  Single (0 < X <= 1)
pouch_ctrl_1_AAACGGGGTACAGCAG-1         6 Medium (5 < X <= 20)
pouch_ctrl_1_AAACGGGGTCGATTGT-1         1  Single (0 < X <= 1)`

SessionInfo():
`R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.8.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=C              LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] SeuratObject_4.0.2 Seurat_4.0.4      

loaded via a namespace (and not attached):
  [1] nlme_3.1-152          matrixStats_0.61.0    spatstat.sparse_2.0-0 RcppAnnoy_0.0.19      RColorBrewer_1.1-2    httr_1.4.2            sctransform_0.3.2    
  [8] tools_4.1.0           utf8_1.2.2            R6_2.5.0              irlba_2.3.3           rpart_4.1-15          KernSmooth_2.23-20    uwot_0.1.14.9000     
 [15] mgcv_1.8-35           DBI_1.1.1             lazyeval_0.2.2        colorspace_2.0-2      tidyselect_1.1.1      gridExtra_2.3         compiler_4.1.0       
 [22] cli_3.0.1             plotly_4.9.4.1        labeling_0.4.2        scales_1.1.1          lmtest_0.9-38         spatstat.data_2.1-0   ggridges_0.5.3       
 [29] pbapply_1.5-0         goftest_1.2-2         stringr_1.4.0         digest_0.6.27         spatstat.utils_2.2-0  pkgconfig_2.0.3       htmltools_0.5.1.1    
 [36] parallelly_1.28.1     fastmap_1.1.0         htmlwidgets_1.5.3     rlang_0.4.11          rstudioapi_0.13       shiny_1.6.0           farver_2.1.0         
 [43] generics_0.1.0        zoo_1.8-9             jsonlite_1.7.2        ica_1.0-2             dplyr_1.0.7           magrittr_2.0.1        patchwork_1.1.1      
 [50] Matrix_1.3-3          Rcpp_1.0.7            munsell_0.5.0         fansi_0.5.0           abind_1.4-5           reticulate_1.22       lifecycle_1.0.0      
 [57] stringi_1.7.3         MASS_7.3-54           Rtsne_0.15            plyr_1.8.6            grid_4.1.0            parallel_4.1.0        listenv_0.8.0        
 [64] promises_1.2.0.1      ggrepel_0.9.1         crayon_1.4.1          miniUI_0.1.1.1        deldir_0.2-10         lattice_0.20-44       cowplot_1.1.1        
 [71] splines_4.1.0         tensor_1.5            pillar_1.6.2          igraph_1.2.6          spatstat.geom_2.2-2   future.apply_1.8.1    reshape2_1.4.4       
 [78] codetools_0.2-18      leiden_0.3.9          glue_1.4.2            data.table_1.14.0     png_0.1-7             vctrs_0.3.8           httpuv_1.6.1         
 [85] gtable_0.3.0          RANN_2.6.1            purrr_0.3.4           spatstat.core_2.3-0   polyclip_1.10-0       tidyr_1.1.3           scattermore_0.7      
 [92] future_1.22.1         assertthat_0.2.1      ggplot2_3.3.5         mime_0.11             xtable_1.8-4          later_1.2.0           survival_3.2-11      
 [99] viridisLite_0.4.0     tibble_3.1.3          cluster_2.1.2         globals_0.14.0        fitdistrplus_1.1-5    ellipsis_0.3.2        ROCR_1.0-11  `

Let me know what other info you may need!

**Comment by ncborcherding** [comment]
Hey Khain2650,

Thanks for the info -I think there might be an issue with NAs in the data. It looks like you have several barcodes without the corresponding contigs after ```combineExpression()```, which is normal. However, instead of the NAs in these places I just see blanks. Can you confirm that?

For those cells/barcodes to be ignored for ```clusterTCR()```, they need to be NAs. So something like this might work:

```
seurat$CTaa[seurat$CTaa == ""] <- NA #replacing all blanks with NA
seurat <- clusterTCR(seurat, chain = "TRB", group.by = "group",  sequence = "aa",  threshold = 0.85)
```

If this is not the case, we can keep troubleshooting. 

Thanks,
Nick
