### ISSUE TITLE
quantContig  contig number differs depending on split.by variable in expression2List()

### ISSUE THREAD

**Issue by YamilMaluje** [ncborcherding/scRepertoire#244]
Thanks for the amazing package. I am using scRepertoire_1.7.0. Everything works as expected following the vignette. `combineTCR()`  then `combineExpression()` to the seurat object using "aa" as cloneCall, so far so good. No I want to know the unique clonotypes that are in each condition (symtomatic and asymtomatic ), for then to check which ones are shared within both condition (with `clonalOverlap()` or `getCirclize()` and `intersect()`)

Hence, for this I used `expression2List()` split by "Sample" and then perfom `quantContig` with the exportTable set to True to check the "contigs" values .
   contigs   values total    scaled
1       70  Sample1    92  76.08696
2       31  Sample2    31 100.00000
3       75  Sample3    94  79.78723
4      149  Sample4   149 100.00000
5       20  Sample5    20 100.00000
6      194  Sample6   206  94.17476
7       78  Sample7    88  88.63636
8       90  Sample8    97  92.78351
9       53  Sample9    53 100.00000
10      78 Sample10    86  90.69767
11      31 Sample11    37  83.78378
12      13 Sample12    13 100.00000

were If I sum the contigs values (to see the total number of unique clonotypes) we get **882**. So far so good ....

But the issue is that if I repeat the  `expression2List()` split by  another metadata variable (symtomatic and asymtomatic patients)  and then perfom `quantContig`with the exportTable set to True to check the "contigs" values I obtain a different total number of unique contigs (total number of unnique clonotypes/contigs **877**. )

   contigs         values           total       scaled
1     466 Asymptomatisch   534     87.26592
2     411  Symptomatisch    432     95.13889

Is there something that I am doing wrong or not something that I am missing out? as the Total number in both cases are the same **966**. 

Thank you in advance

**Comment by ncborcherding** [comment]
Hey YamilMaluje, 

Thanks for reaching out - the confusion here is coming from how we are defining unique clones - using ```expression2List()``` on **sample** you are asking what are the unique clones across each individual sample, while ```expression2List()``` on **condition** you are asking what are the unique clones across each condition. You are actually getting consistent data (the third column is total clones, and each split you are getting 966), just the definition of unique clones is changing. 

Hope that helps and let me know if you have any other questions.

Nick
