### ISSUE TITLE
Error every time when running clonalNetwork()

### ISSUE THREAD

**Issue by mwu2001** [ncborcherding/scRepertoire#245]
Hello, 

I keep running into the following error when running clonalNetwork on my Seurat object. I have no issues when doing clonalOverlay, but when running clonalNetwork, the following error pops up — I've tried to change the identity and cloneCall according to my own naming of the metadata but still run into this same error: 
`Error in check.length(gparname) : 
  'gpar' element 'lwd' must not be length 0`

My input is the following, as commented: 

> scRepertoire::clonalNetwork(
>   pediatric_csf_T,
>   reduction = "integrated_sct_umap", # the umap reduction I have 
>   identity = "ident", # I tried changing this to seurat_clusters / other reductions of the umap clustering I have 
>   filter.clones = NULL,
>   filter.identity = NULL,
>   cloneCall = "CTaa", #the column in the metadata for naming of each clone by aa CDR3 sequence 
>   exportTable = FALSE
> )

I'm not sure what is the issue? 

Thanks!

**Comment by ncborcherding** [comment]
Hey Melody, 

Thanks for reaching out - I am highly suspecting this is an issue with the ggraph version you have as this error has been [previously reported](https://stackoverflow.com/questions/76061439/ggraph-igraph-not-recognizing-numeric-edge-attributes). Could you try updated you ggraph version? 

If that does not work, happy to troubleshoot, could you give me the output of ```sessionInfo()```?

Thanks,
Nick

**Comment by mwu2001** [comment]
Hi Nick, 

I tried updating ggraph but this doesn't seem to work still. 
Here's my sessionInfo() output: 

> sessionInfo()
R version 4.2.0 (2022-04-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS

> Matrix products: default
> BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
> LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
>  [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
> [10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats4    stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] ggraph_2.0.5                scRepertoire_1.7.4          RColorBrewer_1.1-3         
>  [4] stringr_1.5.0               tidyr_1.3.0                 dplyr_1.1.2                
>  [7] SeuratObject_4.1.3          Seurat_4.1.1                SingleCellExperiment_1.18.1
> [10] SummarizedExperiment_1.26.1 Biobase_2.56.0              GenomicRanges_1.48.0       
> [13] GenomeInfoDb_1.32.4         IRanges_2.30.1              S4Vectors_0.34.0           
> [16] BiocGenerics_0.42.0         MatrixGenerics_1.8.1        matrixStats_0.62.0         
> [19] ggplot2_3.4.2              
> 
> loaded via a namespace (and not attached):
>   [1] VGAM_1.1-6             plyr_1.8.7             igraph_1.3.1           lazyeval_0.2.2        
>   [5] sp_1.6-0               splines_4.2.0          powerTCR_1.16.0        listenv_0.8.0         
>   [9] scattermore_0.8        digest_0.6.29          foreach_1.5.2          htmltools_0.5.2       
>  [13] viridis_0.6.2          ggalluvial_0.12.5      fansi_1.0.3            magrittr_2.0.3        
>  [17] truncdist_1.0-2        tensor_1.5             cluster_2.1.3          doParallel_1.0.17     
>  [21] ROCR_1.0-11            globals_0.15.0         graphlayouts_0.8.0     spatstat.sparse_3.0-1 
>  [25] colorspace_2.0-3       ggrepel_0.9.3          RCurl_1.98-1.6         jsonlite_1.8.0        
>  [29] spatstat.data_3.0-1    progressr_0.10.0       survival_3.3-1         zoo_1.8-10            
>  [33] iterators_1.0.14       glue_1.6.2             polyclip_1.10-0        gtable_0.3.0          
>  [37] zlibbioc_1.42.0        XVector_0.36.0         leiden_0.4.2           DelayedArray_0.22.0   
>  [41] evd_2.3-6.1            future.apply_1.9.0     abind_1.4-5            SparseM_1.81          
>  [45] scales_1.2.0           DBI_1.1.2              spatstat.random_3.1-5  miniUI_0.1.1.1        
>  [49] Rcpp_1.0.8.3           isoband_0.2.5          viridisLite_0.4.0      xtable_1.8-4          
>  [53] reticulate_1.25        spatstat.core_2.4-4    htmlwidgets_1.5.4      httr_1.4.3            
>  [57] ellipsis_0.3.2         ica_1.0-2              pkgconfig_2.0.3        farver_2.1.0          
>  [61] uwot_0.1.14            deldir_1.0-6           utf8_1.2.2             labeling_0.4.2        
>  [65] tidyselect_1.2.0       rlang_1.1.1            reshape2_1.4.4         later_1.3.0           
>  [69] munsell_0.5.0          tools_4.2.0            cli_3.6.1              generics_0.1.2        
>  [73] ggridges_0.5.3         fastmap_1.1.0          goftest_1.2-3          evmix_2.12            
>  [77] fitdistrplus_1.1-8     tidygraph_1.2.1        purrr_1.0.1            RANN_2.6.1            
>  [81] pbapply_1.5-0          future_1.25.0          nlme_3.1-157           mime_0.12             
>  [85] compiler_4.2.0         rstudioapi_0.13        plotly_4.10.0          png_0.1-7             
>  [89] spatstat.utils_3.0-3   tibble_3.2.1           tweenr_1.0.2           stringi_1.7.6         
>  [93] gsl_2.1-7.1            rgeos_0.5-9            cubature_2.0.4.4       lattice_0.20-45       
>  [97] Matrix_1.5-4           vegan_2.6-2            permute_0.9-7          vctrs_0.6.2           
> [101] stringdist_0.9.10      pillar_1.9.0           lifecycle_1.0.3        spatstat.geom_3.2-1   
> [105] lmtest_0.9-40          RcppAnnoy_0.0.19       data.table_1.14.2      cowplot_1.1.1         
> [109] bitops_1.0-7           irlba_2.3.5            httpuv_1.6.5           patchwork_1.1.1       
> [113] R6_2.5.1               promises_1.2.0.1       KernSmooth_2.23-20     gridExtra_2.3         
> [117] parallelly_1.31.1      codetools_0.2-18       MASS_7.3-57            withr_2.5.0           
> [121] sctransform_0.3.5      GenomeInfoDbData_1.2.8 mgcv_1.8-40            parallel_4.2.0        
> [125] rpart_4.1.16           grid_4.2.0             Rtsne_0.16             ggforce_0.3.3         
> [129] shiny_1.7.1 

Thank you!

**Comment by mwu2001** [comment]
Thanks! It finally worked! I had some issues I think due to running this on an R studio server. I had initially had the package updated but the older versions were still loaded!
