### ISSUE TITLE
combineBCR with trust 4 output

### ISSUE THREAD

**Issue by laurie-tonon** [ncborcherding/scRepertoire#246]
Hello,

I installed the latest version of scRepertoire (v1.10.0) but I can't load the output of TRUST4 for my data with the following code:

`
library(scRepertoire)

directory <- c("~/gnomic/home/tonon/projects/paraneo/BCRseq/trust4/outs_trust4/PC4_barcode_report.tsv")
contig_list <- loadContigs(directory, format = "TRUST4")

combined_B <-combineBCR(
  contig_list,
  samples = "PC2",
  ID = "PC2",
  threshold = 0.85,
  removeNA = T,
  removeMulti = FALSE
)
`

The function combineBCR always crashes with the message:

Error in `slice_max()`:
! Can't compute indices.
ℹ In group 1: `barcode = "AAACCTGAGAAACCAT"`, `chain = "IGH"`.
Caused by error:
! object 'reads' not found

I read the closed issues and thought this bug solved, but I can't make it work on my data.

Thanks a lot for your help.

**Comment by ncborcherding** [comment]
Hey Laurie, 

There is a persistent issue with versions between bioconductor and github - problem should be solved if you use the dev version via: 

```
devtools::install_github("ncborcherding/scRepertoire@dev")
```

Please let me know if you have any questions.

Nick

**Comment by laurie-tonon** [comment]
Thank you, it works.
I installed the dev version (v1.7.4), and found out that I needed to read the trust4 output before calling the loadContigs function:

d2 <- read_tsv("~/gnomic/home/tonon/projects/paraneo/BCRseq/trust4/outs_trust4/PC4_barcode_report.tsv")
contig_list <- loadContigs(list(d1,d2), format = "TRUST4")

now I can call the combineBCR function and it works.

Again thank you.

Laurie
