### ISSUE TITLE
Possibility to facet or separate clonalHomeostasis/clonalProportion plot by ID?

### ISSUE THREAD

**Issue by ddressman91** [ncborcherding/scRepertoire#247]
I'd like to have the output of clonalHomeostasis and clonalProportion be a plot that still has one column per sample, but is either faceted by the "ID" variable I provided to combineTCR, or has breaks in the graph to separate the categories in the ID variable.  The group.by argument in clonalHomeostasis allows me to group by ID, but then it aggregates the sample repertoires by ID as well, instead of maintaining one repertoire display column per sample.

I'm guessing there's a way to add a facet_wrap layer that will accomplish this, but I haven't figured out what argument to pass to facet_wrap that will match with the parameters of clonalHomeostasis/clonalProportion.  Would it be possible to either see an example of a facet_wrap call on top of clonalHomeostasis or clonalProportion that would accomplish this, or perhaps have the clonalHomeostasis and clonalProportion functions enhanced to allow for this feature?

Thanks in advance!

**Comment by ncborcherding** [comment]
Apologies for the delay - because of the way the function is set up the grouping is part of the calculation, so there is likely not a simple way to do a **facet_wrap** per say. I actually think this a good feature request to have multilayer groupings for the **group.by** variable (so I'll add it to the list)

An alternative for now would be to create a new variable that combines a sample name and group (something like "S1_Healthy) and ```exportTable = TRUE```, then split the variable into 2 columns and plot yourself with ```facet_wrap(~condition)```. If that makes sense? More than happy to provide a reprex if you give me some language around your groupings. 

Thanks,
Nick

**Comment by ddressman91** [comment]
I coded somewhat of a workaround, that basically extracted the data from the clonalHomeostasis object and calls ggplot2 to create a similar plot.  My sample IDs have composite naming with [Sample number]_[ID] as you suggested, so I used those to create an extra "Condition" column for faceting.  It's not perfect, because the use of `scale = "free"` in `facet_wrap` means that each facet is the same width, rather than each sample being the same column width, making it so that some columns have dividing lines between them and some don't, regardless of how wide I make the plot (this might be fixable with the right `theme` call).

```
clonehomeo <- clonalHomeostasis(combined, cloneCall = "strict",
                  cloneTypes = c(Rare = 1e-04, Small = 0.001, Medium = 0.01,
                                 Large = 0.1, Hyperexpanded = 1))
clonehomeodata <- clonehomeo$data
colnames(clonehomeodata) <- c("Patient","Clonotype.group", "Percentage")
clonehomeodata$Condition <- clonehomeodata$Patient
clonehomeodata$Condition <- str_replace(clonehomeodata$Condition,".*_","")
colorblind_vector <- colorRampPalette(rev(c("#0D0887FF", "#47039FFF", 
                                            "#7301A8FF", "#9C179EFF", "#BD3786FF", "#D8576BFF",
                                            "#ED7953FF","#FA9E3BFF", "#FDC926FF", "#F0F921FF")))

ggplot(clonehomeodata,aes(x = Patient, y = Percentage, fill = Clonotype.group)) +
  geom_bar(position = "fill",stat = "identity") +
  facet_wrap(facets = vars(Condition), scales = "free_x") +
  scale_fill_manual(values = rev(colorblind_vector(5)), name = "Clonotype Group") +
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank(),axis.title.x = element_blank()) +
  ggtitle("Breakdown of T cell clones by clonotype group")
```
