### ISSUE TITLE
Feature request: Allow for cloneTypes with absolute counts in clonalHomeostasis?

### ISSUE THREAD

**Issue by ddressman91** [ncborcherding/scRepertoire#249]
Hello, thanks so much for this package and your responsiveness!  I was wondering if we could add the option to clonalHomeostasis to have cloneTypes either by proportion or by absolute count, just as in combineExpression?  I have a few samples with very low T cell counts, so the single clones from these samples are currently showing as hyperexpanded or large, because they are taking up 1-10% of a small T cell repertoire in these samples.  I tried to get this to work by using absolute counts in my combineExpression call, using expression2List to create a new combined object, then running clonalHomeostasis on that, but it didn't work.

**Comment by ncborcherding** [comment]
Good request - will add it to the list. 

As of right now ```clonalHomeostasis()``` calculates the proportions on the fly (allowing for grouping variables) - so there is not anyway around it. But will look into adding the functionality of absolute counts. 

Nick
