### ISSUE TITLE
Cluster labels in clonalNetwork plot

### ISSUE THREAD

**Issue by ElviMagda** [ncborcherding/scRepertoire#250]
Hi Nick,

thanks again for this great package :)

I was wondering if there is a way to show the labels of the clusters in the clonalNetwork plot. 
I find this plot very useful but I always need to come back to my labeled UMAP to identify which cluster was which. It would be great if the cluster labels are shown in the plot (or alternatively in the legend as the UMAP is colored by cluster).

I was playing around with geom_text(), but I couldn´t make it work. If you have any suggestion, I would greatly appreciate it.

Thanks again!
Best,
Elvira

![download](https://github.com/ncborcherding/scRepertoire/assets/58399552/8c9f02e8-4405-4a30-91bf-71d464765b6c)

**Comment by ncborcherding** [comment]
Hey Elvira, 

Thanks for reaching out and the kind words. 

There is no way to do that in the current function - however you might be able to hack something together using ggplots by adding an additional layer of geom_text(). 

So I am thinking something like this: 
```
df <- data.frame(SeuratObj@reductions$umap@cell.embeddings,
                  SeuratObj[[]])

#Here we are calcuating the mean position of each cluster
centers = df %>% 
          group_by(seurat_clusters) %>% 
          summarize(across(c("UMAP_1", "UMAP_2"),mean)) %>%
          as.data.frame()

clonalNetwork(seuratObj, 
              reduction = "umap", 
              identity = "ident",
              filter.clones = NULL,
              filter.identity = NULL,
              cloneCall = "aa") + 
    geom_text(data = centers, mapping =  aes(x=centers[,2], y = centers[,3], label = seurat_clusters), 
              color = "black", size = 5) 
```

There might need to be adjustments/edits to the code above - one problem I can foresee is the central dot is located at the mean of the cluster as well. Happy to help more too, let me know. 

Nick

**Comment by ncborcherding** [comment]
Wow what a cool plot!
