### ISSUE TITLE
combineTRUST4

### ISSUE THREAD

**Issue by saramoein372** [ncborcherding/scRepertoire#253]
Hello,

IS combineTRUST4 works in new version of scRepertoire? 
It is giving me error:
could not find function "combineTRUST4"

Thanks for your help!

**Comment by ncborcherding** [comment]
Hey Sara, 

```combineTRUST4()``` has been superseded by ```loadContigs()```. Looks like I need to update the vignettes. Let me know if you have any issues or questions.

Nick

**Comment by saramoein372** [comment]
Thanks Nick, for fast replying! Appreciate it.
Are you telling me to use loadContigs() instead of combineTRUST4()?
And do you know specifically, which of the trust4's output I should use? Bcuz trust4 generates multiple output files.

**Comment by ncborcherding** [comment]
Sorry, should have linked the [manual](https://rdrr.io/github/ncborcherding/scRepertoire/man/loadContigs.html)

For ```loadContigs()``` all you need to do is point the fucntion to the directory or directories that the output is in (**dir**) and the format (**format**), it should automatically load and format the data frame to work with ```combineTCR()``` downstream. 

Because the function is recursive - it will automatically detect multiple files with the label **barcode_report.tsv** label in the directory you indicate.

**Comment by saramoein372** [comment]
Thank you so very much!
To continue, I just need to use combineTCR(TCR_cellRanger, TCR_trust4). 
Is it correct?

**Comment by ncborcherding** [comment]
Sorry on a phone - but you'll need to make a list to pass to combineTCR().

combineTCR(list(TCR_cellRanger, TCR_trust4))

**Comment by saramoein372** [comment]
Thanks Nick!
I did that and my list= combinedTCR(list(TCR_cellRanger, TCR_trust4)) has two elements. list[[1]] has 41 columns and list[[2]] has 19 columns.

And after quantContig(x, cloneCall="gene+nt", scale = F) I am getting error.
Error in x[[jj]][iseq] <- vjj : replacement has length zero

Any comments?

**Comment by saramoein372** [comment]
Nick,
I could solve this error. But my question is:

my expectation is that repertoire combines the cellRanger and trust4 results AS ONE SAMPLE. But here I see the combining is like I have two samples: one cellRanger and one trust4. Do I understand and run correctly?

**Comment by ncborcherding** [comment]
```combineTCR()``` is not necessarily set up to combine different technologies into a single data frame - you could try ```rbind()``` your Cell Ranger and TRUST4 outputs after ```loadContigs()```?
