### ISSUE TITLE
"clonalHomeostasis" and "clonalProportion"

### ISSUE THREAD

**Issue by saramoein372** [ncborcherding/scRepertoire#254]
Good morning,

Would you please provide some details about how two functions "clonalHomeostasis" and "clonalProportion" per sample and per seurat clusters, are working?

Thanks!

**Comment by ncborcherding** [comment]
Hey saramoein372, 

Both are visualizations of the space occupied by specifc categories within the repertoire. Per sample or per cluster is really just organizing the definition of repertoire (changing the denominator) - for sample, you are looking across the TCR sequences recovered by sample and for cluster you are looking across the TCR sequences that are recovered within the indicated cluster. 

In terms of the functions themselves - ```clonalHomeostasis()``` shows the relative repertoire space per cluster occupied clones at specific levels of expansion. ```clonalProportion()``` shows the relative repertoire space per cluster occupied by clones ordered from largest (1) to smallest (n).

Hope that helps and let me know if you have any other questions. 

Nick

**Comment by saramoein372** [comment]
Thanks Nick.

**Comment by saramoein372** [comment]
Nick,
Would you please provide some details about the clonal_diversity plot and the index scores? How we should interpret this plot per each of the measures (shannon,...)?

**Comment by ncborcherding** [comment]
Hey saramoein372, 

I think the first major consideration for the diversity plots is the default setting is for bootstrapping - meaning the function will take the lowest number of TCRs across all sample/group, then sample that number across all samples iteratively, and then calculate the diversity. 

The diversity metrics themselves are an evolution of information theory and ecology - you can read more on [this wiki](https://en.wikipedia.org/wiki/Diversity_index). scRepertoire calculates diversity through the [vegan](https://github.com/vegandevs/vegan) R package. Each of the metrics have some underlying assumptions. 

Nick

**Comment by saramoein372** [comment]
Thanks Nick!
One more question if you don't mind:

That Clone Network plot looks very interesting! Can I ask how the
directions of arrows are determined?

Best,
Sara

**Comment by ncborcherding** [comment]
As a default the clonal network will show both arrow directions - where the arrow originated is the numerator and denominator is the original cluster plus the end cluster (in terms of TCR space). 

Nick
