### ISSUE TITLE
Shannon index

### ISSUE THREAD

**Issue by saramoein372** [ncborcherding/scRepertoire#257]
Hi,

Can I ask if the Shannon index is based on (1-E(H))? I am asking, since if your answer is yes, then my interpretation will change.
Would you please say how you interpret the Shannon index? The lower the index the lower is the diversity?

**Comment by ncborcherding** [comment]
Hey Saramoein372,

Here is the basis of the Shannon Index:
H = -sum p_i log(b) p_i, where p_i is the proportional abundance of species i and b is the base of the logarithm.

The higher the index, the higher the relative diversity.

Hope that helps,
Nick

**Comment by saramoein372** [comment]
Thanks, thanks helped perfectly!
