### ISSUE TITLE
chain tcr is not found in the combineTCR and not able to combine vdj with seurat object

### ISSUE THREAD

**Issue by Rimanpreet1** [ncborcherding/scRepertoire#258]
i tried to add my vdj_t data in seurat object but when I combine my all vdj data from different samples, and run quantContig(combined, cloneCall = "gene+nt", chain= "TCR") after running combineTCR, it showed chain argument is not found. 
2nd, I was not able to combine my vdj data with seurat object, could you please help me this this

**Comment by ncborcherding** [comment]
Hey Rimanpreet1, 

Thanks for reaching out and happy to help. To trouble shoot, I will need some more information. 

Could you provide: 

1. Output of ```sessionInfo()```
2. Code on that you used to get to ```quantContig()```
3. Any error messages associated with the vdj/seurat combination.

Thanks,
Nick

**Comment by ncborcherding** [comment]
I am going to close this issue due to inactivity.
