### ISSUE TITLE
All TRB and IGH chains are NA after loadContigs from TRUST4

### ISSUE THREAD

**Issue by Jammm11** [ncborcherding/scRepertoire#259]
Hi, thank you for the great tool! 
I have installed the dev version (v1.11.0). I tried to use scRepertoire with the test output file from TRUST4 in manual:
TRUST4 <- read.csv("https://www.borch.dev/uploads/contigs/TRUST4_contigs.csv")
contig.list4 <- loadContigs(TRUST4, format = "TRUST4")

But all the TRB and IGH chains are NA:
> head(contig.list4[[1]],30)
              barcode       v_gene d_gene    j_gene c_gene
1  TCGAGGCCAAGTAGTA-1         <NA>   <NA>      <NA>   <NA>
2  CATCAAGCAAGTACCT-1 IGKV2D-29*01   None  IGKJ4*01   None
3  CAGATCAGTAGGGACT-1 IGKV2D-29*01   None  IGKJ4*01   None
4  TCTTTCCCAATCGGTT-1 IGKV2D-29*01   None  IGKJ4*01   None
5  CTTACCGTCTTGAGGT-1     TRAV6*02   None TRAJ23*01   None
6  TAGCCGGCATACTCTT-1 IGKV1D-43*01   None  IGKJ5*01   None
7  CGCGTTTAGTGGGTTG-1         <NA>   <NA>      <NA>   <NA>
8  AGAATAGGTAGCCTAT-1         <NA>   <NA>      <NA>   <NA>
9  CACATTTAGGGCACTA-1   TRAV9-2*02   None TRAJ29*01   TRAC
10 CTAATGGTCCTCGCAT-1         <NA>   <NA>      <NA>   <NA>
11 TGAGGGAGTAATCACC-1  IGLV1-40*01   None  IGLJ3*02  IGLC2
12 TCAGGATTCACTTACT-1         <NA>   <NA>      <NA>   <NA>
13 TGCCCATAGCTAGTCT-1         <NA>   <NA>      <NA>   <NA>
14 TCATTTGTCCACTGGG-1         <NA>   <NA>      <NA>   <NA>
15 CACATAGAGGCCGAAT-1    TRAV17*01   None  TRAJ6*01   None
16 CAGCCGACAGACGCTC-1  IGKV1-17*01   None  IGKJ4*01   IGKC
17 TATCTCAGTGACGGTA-1    TRAV10*01   None TRAJ17*01   None
18 GTAACTGTCATAGCAC-1  IGLV2-14*01   None  IGLJ2*01  IGLC2
19 TGTGGTAAGGTAAACT-1         <NA>   <NA>      <NA>   <NA>
20 ACGTCAAAGCTGTTCA-1         <NA>   <NA>      <NA>   <NA>
21 CGTAGCGTCATCATTC-1         <NA>   <NA>      <NA>   <NA>
22 CCGGGATAGTGGTAGC-1         <NA>   <NA>      <NA>   <NA>
23 TAGTTGGAGCGATCCC-1         <NA>   <NA>      <NA>   <NA>
24 GAACGGAAGTTCGCAT-1         <NA>   <NA>      <NA>   <NA>
25 ACATACGTCCAAACAC-1 IGKV2D-29*01   None  IGKJ4*01   IGKC
26 CCGTTCAGTGGGTATG-1    TRAV21*01   None TRAJ31*01   TRAC
27 GTGTGCGCAAGAAGAG-1         <NA>   <NA>      <NA>   <NA>
28 TAAGAGACATTCTCAT-1    TRAV27*01   None TRAJ40*01   None
29 TCGCGAGTCCAGGGCT-1 IGKV2D-29*01   None  IGKJ4*01   None
30 CTCATTATCGAACGGA-1         <NA>   <NA>      <NA>   <NA>
                                            cdr3_nt             cdr3 reads chain
1                                              <NA>             <NA>  <NA>  <NA>
2                 TGCAAGCAAAGTATACAGTTTCCGCTCACTTTC      CKQSIQFPLTF  1.00   IGK
3                 TGCAAGCAAAGTATACAGTTTCCGCTCACTTTC      CKQSIQFPLTF  1.00   IGK
4                 TGCAAGCAAAGTATACAGTTTCCGCTCACTTTC      CKQSIQFPLTF  2.88   IGK
5        TGTGCTCTCGAGCCTTATAACCAGGGAGGAAAGCTTATCTTC   CALEPYNQGGKLIF  1.00   TRA
6                 TGTCTGAAACTTAATGAGTACCCGATCACGTTT      CLKLNEYPITF  1.00   IGK
7                                              <NA>             <NA>  <NA>  <NA>
8                                              <NA>             <NA>  <NA>  <NA>
9     TGTGCTCTGAGTGATCGGAATTCAGGAAACACACCTCTTGTCTTT  CALSDRNSGNTPLVF  6.44   TRA
10                                             <NA>             <NA>  <NA>  <NA>
11             TGCCAGTCCTATGACAGCAGCCTGAGAGGGGTGTTC     CQSYDSSLRGVF 24.56   IGL
12                                             <NA>             <NA>  <NA>  <NA>
13                                             <NA>             <NA>  <NA>  <NA>
14                                             <NA>             <NA>  <NA>  <NA>
15 TGTGCTACGATCGGCCCTCCATCAGGAGGAAGCTACATACCTACATTT CATIGPPSGGSYIPTF  1.00   TRA
16                TGTCTCCAGCATAATAGTTACCCGGTCACTTTC      CLQHNSYPVTF 61.30   IGK
17          TGTGTGGTGACCAAAGCTGCAGGCAACAAGCTAACTTTT    CVVTKAAGNKLTF  1.67   TRA
18       TGCAGCTCATATACAAGCAGGAGTCCTATCGATGTGGTATTC   CSSYTSRSPIDVVF 43.17   IGL
19                                             <NA>             <NA>  <NA>  <NA>
20                                             <NA>             <NA>  <NA>  <NA>
21                                             <NA>             <NA>  <NA>  <NA>
22                                             <NA>             <NA>  <NA>  <NA>
23                                             <NA>             <NA>  <NA>  <NA>
24                                             <NA>             <NA>  <NA>  <NA>
25                TGCAAGCAAAGTATACAGTTTCCGCTCACTTTC      CKQSIQFPLTF  1.79   IGK
26       TGTGCTGTGAGCAAAAGTAGTAACAATGCCAGACTCATGTTT   CAVSKSSNNARLMF  3.33   TRA
27                                             <NA>             <NA>  <NA>  <NA>
28       TGTGCAGGAGCAGAGAGTGGAGGAACCTACAAATACATCTTT   CAGAESGGTYKYIF  1.00   TRA
29                TGCAAGCAAAGTATACAGTTTCCGCTCACTTTC      CKQSIQFPLTF  1.00   IGK
30                                             <NA>             <NA>  <NA>  <NA>

The TRUST4 object contains TRB and IGH:
head(TRUST4,10)
            X.barcode cell_type
1  TCGAGGCCAAGTAGTA-1       abT
2  CATCAAGCAAGTACCT-1         B
3  CAGATCAGTAGGGACT-1         B
4  TCTTTCCCAATCGGTT-1         B
5  CTTACCGTCTTGAGGT-1       abT
6  TAGCCGGCATACTCTT-1         B
7  CGCGTTTAGTGGGTTG-1       abT
8  AGAATAGGTAGCCTAT-1       abT
9  CACATTTAGGGCACTA-1       abT
10 CTAATGGTCCTCGCAT-1       abT
                                                                                                                                          chain1
1               TRBV27*01,TRBD1*01,TRBJ1-5*01,*,TGTGCCAGCAGTTTACTTCAGGGGTATCAGCCCCAGCATTTT,CASSLLQGYQPQHF,7.90,TCGAGGCCAAGTAGTA-1_46430,100.00,0
2                                                                                                                                              *
3                                                                                                                                              *
4                                                                                                                                              *
5       TRBV18*01,TRBD2*01,TRBJ2-5*01,TRBC1,TGTGCCAGCTCACCACCAGTACTAGCGCAAGAGACCCAGTACTTC,CASSPPVLAQETQYF,5.62,CTTACCGTCTTGAGGT-1_98176,100.00,0
6                                                                                                                                              *
7  TRBV14*01,TRBD2*02,TRBJ2-7*01,*,TGTGCCAGCAGCCAAGATGTCTCCCCGGGATACTCCTACGAGCAGTACTTC,CASSQDVSPGYSYEQYF,1.00,CGCGTTTAGTGGGTTG-1_114407,100.00,0
8        TRBV20-1*02,TRBD2*01,TRBJ2-5*01,TRBC2,TGCAGTGCTCCGGCCGGGGGGGTTCGGGAGACCCAGTACTTC,CSAPAGGVRETQYF,16.55,AGAATAGGTAGCCTAT-1_13490,100.00,1
9                                                                                                                                              *
10          TRBV5-1*01,TRBD1*01,TRBJ2-2*01,*,TGCGCCAGCAGCTATCGGACAGGGAGCGGCGGGGAGCTGTTTTTT,CASSYRTGSGGELFF,4.13,CTAATGGTCCTCGCAT-1_25894,97.37,0
                                                                                                                             chain2
1                                                                                                                                 *
2                     IGKV2D-29*01,*,IGKJ4*01,*,TGCAAGCAAAGTATACAGTTTCCGCTCACTTTC,CKQSIQFPLTF,1.00,CATCAAGCAAGTACCT-1_14538,93.55,0
3                     IGKV2D-29*01,*,IGKJ4*01,*,TGCAAGCAAAGTATACAGTTTCCGCTCACTTTC,CKQSIQFPLTF,1.00,CAGATCAGTAGGGACT-1_17223,93.55,0
4                     IGKV2D-29*01,*,IGKJ4*01,*,TGCAAGCAAAGTATACAGTTTCCGCTCACTTTC,CKQSIQFPLTF,2.88,TCTTTCCCAATCGGTT-1_16237,93.55,0
5           TRAV6*02,*,TRAJ23*01,*,TGTGCTCTCGAGCCTTATAACCAGGGAGGAAAGCTTATCTTC,CALEPYNQGGKLIF,1.00,CTTACCGTCTTGAGGT-1_74271,100.00,0
6                    IGKV1D-43*01,*,IGKJ5*01,*,TGTCTGAAACTTAATGAGTACCCGATCACGTTT,CLKLNEYPITF,1.00,TAGCCGGCATACTCTT-1_145390,76.67,0
7                                                                                                                                 *
8                                                                                                                                 *
9  TRAV9-2*02,*,TRAJ29*01,TRAC,TGTGCTCTGAGTGATCGGAATTCAGGAAACACACCTCTTGTCTTT,CALSDRNSGNTPLVF,6.44,CACATTTAGGGCACTA-1_22679,100.00,1
10                                                                                                                                *
                                                                                                                        secondary_chain1
1                                                                                                                                      *
2                                                                                                                                      *
3                                                                                                                                      *
4                                                                                                                                      *
5  TRBV7-9*01,TRBD1*01,TRBJ2-1*01,*,TGTGCCAGCAGCTTAGGACAGGGACTATACAATGAGCAGTTCTTC,CASSLGQGLYNEQFF,5.29,CTTACCGTCTTGAGGT-1_19734,100.00,0
6                                                                                                                                      *
7                                                                                                                                      *
8                                                                                                                                      *
9                                                                                                                                      *
10                                                                                                                                     *
   secondary_chain2
1                 *
2                 *
3                 *
4                 *
5                 *
6                 *
7                 *
8                 *
9                 *
10                *

I didn't know what went wrong. I would appreciate any help you can provide!

**Comment by ncborcherding** [comment]
Hey Jammm11, 


I think the confusion here is that the TRUST4 alignment can lead to NAs and this is not an error on your part. ```loadContigs()``` is just prepping the data before organizing everything by individual barcode. Following the manual: 

```
TRUST4 <- read.csv("https://www.borch.dev/uploads/contigs/TRUST4_contigs.csv")
contig.list <- loadContigs(TRUST4, format = "TRUST4")
View(contig.list[[1]])
```
<img width="882" alt="Screenshot 2023-08-24 at 8 04 05 AM" src="https://github.com/ncborcherding/scRepertoire/assets/22754118/846cbc13-9b89-4b91-89c5-dbb7d1152446">

During the ```combineTCR()``` step, these NA reads will be removed, allowing you to look at the TCRs of interest (or you can use ```combineBCR()``` if you are interested in the IG)

Let me know if you have any other questions, 
Nick

**Comment by Jammm11** [comment]
Thanks for fast replying! Appreciate it.
But it contains the TRB and IGH chains in the input file before loadContigs():
TRUST4 <- read.csv("https://www.borch.dev/uploads/contigs/TRUST4_contigs.csv")
 View(TRUST4)
<img width="660" alt="p1" src="https://github.com/ncborcherding/scRepertoire/assets/143055588/afcd2b53-b47a-437f-9771-2be8bf0934f7">
The combineTCR()/combineBCR() step can filter NAs but that means all TRB and IGH information will lose after loadContigs step and may have influence in the following analysis. Could it be that the format is incompatible in TRUST4 output?
I have used my own TRUST4 output barcode_report.tsv file before that, and I also encountered the same problem. 
Could you help me with this problem? Thanks!

**Comment by ncborcherding** [comment]
Hey Jammm11,

The example data in the manual is subsetted from a larger cohort and has both B and T receptors so that it can be used for testing functions. The * will be processed as NA and may be excluded in the combineTCR/BCR() process (depending on the paramters, like **filterNA**). As a default, these chains are actually retained as NAs and not nessecarily lost.

If you are asking to combine TCR and BCR analyses, you can just invoke both functions:
```
BCR.combined <- combineBCR(TRUST4, ...)
TCR.combined <- combineTCR(TRUST4, ...)
```

I am not sure what exactly you are asking, so please follow up if I am not answering correctly. 

Nick

**Comment by Jammm11** [comment]
Thank you for your patience.
In the csv file, you can see it contains TRB and IGH chains:
> TRUST4 <- read.csv("https://www.borch.dev/uploads/contigs/TRUST4_contigs.csv")
> View(TRUST4)
![image](https://github.com/ncborcherding/scRepertoire/assets/143055588/3c050960-b011-4b0e-bcd0-4191deb7d726)

After loadContigs, I notice there are not any TRB and IGH chains in contig.list. For example, you can compare the first barcode(TCGAGGCCAAGTAGTA-1) in contig.list with the same barcode in previous csv file:
> contig.list <- loadContigs(TRUST4, format = "TRUST4")
> View(contig.list[[1]]) 
![image](https://github.com/ncborcherding/scRepertoire/assets/143055588/c976c64e-2bcc-4ec7-b926-17d9d65a82e5)
You can find following chain information for this barcode become NA. And this kind of situation exists in the total table in TRB and IGH.

**Comment by ncborcherding** [comment]
Apologies for the confusion - ```loadContigs()``` is matching the format of 10x, in order to allow all the functions to work. For TRUST4 data - it is stacking the data.frame of 2 chains on top of one another. What you are seeing is the NA values for chain2, if you search through **contig.list** you will find the Beta chain for TCGAGGCCAAGTAGTA.
