### ISSUE TITLE
compareClonotypes for specific clones

### ISSUE THREAD

**Issue by mass-a** [ncborcherding/scRepertoire#26]
Thanks for the nice package!

I have been trying to plot the frequencies of some specific clones across a few samples using the `compareClonotypes` function. I found the 'clonotypes' option, which should allow me to select my clones of interest, however the functions fails to do the filtering.  A quick look at the code suggest a possible reason:
```
 if (!is.null(clonotypes)) {
        Con.df <- Con.df[Con.df$Sample %in% clonotypes, ]
 }
```
The Con.df$Clonotypes column should be used for the selection instead of Con.df$Sample, or am I missing something?

Thanks,
-m

**Comment by ncborcherding** [comment]
Hey mass-a,

You are absolutely right, nice catch, just committed the fix, thanks.

Let me know if you find any other issues or have suggestions.
