### ISSUE TITLE
vizGenes group by Seurat clusters

### ISSUE THREAD

**Issue by purisuto** [ncborcherding/scRepertoire#263]
vizGenes appears to have a `group.by` option.  My `combined` is divided up by sample ID, but I have included a column with seurat cluster definitions.  But when I put e.g. `group.by = "seurat_clusters"`, the heatmap is unchanged, and is still divided up by sample ID.

I tried using `combineExpression(... group.by = "seurat_clusters") `followed by `expression2List(..., split.by = "seurat_clusters")`, which gave the data as a list split by the seurat clusters, but this still gave a heatmap split by sample ID.

Many thanks,
David

**Comment by ncborcherding** [comment]
Hey David, 

What version of scRepertoire are you using? There is an older issue that the seurat_clusters supersceded any other variable for the **group.by** parameter. So it might be worth updating your version. 

If the problem persists, would you mind sharing a reproducible example (maybe using the built-in data) to show the problem?

Thanks,
Nick

**Comment by purisuto** [comment]
I updated to 1.11.0, but I still can't get it to plot the rows of the heatmap by anything other than sample_id.  If I look in `combined` I can see the various metadata columns in there (like for condition and seurat clusters).

Is the following the correct way to go about it?

```
contig.list <- createHTOContigList(contig = *my_BCR_data*, sc = seurat, group.by = "sample_id")

combined <- combineBCR(contig.list, samples = names(contig.list), removeNA = TRUE, threshold = 0.85)

seurat <- combineExpression(combined, seurat, 
                            cloneCall="strict", 
                            group.by = "seurat_clusters", 
                            proportion = TRUE, 
                            cloneTypes = c(Rare = 1e-04, Small = 0.001, Medium = 0.01, Large = 0.1, Hyperexpanded =1))

combined2 <- expression2List(seurat, split.by = "seurat_clusters")

p <-vizGenes(combined2, gene = "V", 
         chain = "IGH", 
         plot = "heatmap", 
         order = "variance", 
         scale = TRUE,
         group.by = "seurat_clusters")
```

**Comment by ncborcherding** [comment]
I think I see the problem - ```expression2List()``` does not necessarily retain the meta data information - have you tried calling ```vizGenes()``` directly with the seurat object - something like: 

```
seurat <- combineExpression(combined, seurat, 
                            cloneCall="strict", 
                            group.by = "seurat_clusters", 
                            proportion = TRUE, 
                            cloneTypes = c(Rare = 1e-04, Small = 0.001, Medium = 0.01, Large = 0.1, Hyperexpanded =1))
p <-vizGenes(seurat, 
         gene = "V", 
         chain = "IGH", 
         plot = "heatmap", 
         order = "variance", 
         scale = TRUE,
         group.by = "seurat_clusters")
```

**Comment by purisuto** [comment]
Oh silly me.  I was not updating the y.axis = "seurat_clusters".  It now labels the rows according to the metadata I choose, but I have to set each of group.by, split.by and y.axis to that value.  It works straight from the seurat object after running combineExpression.
