### ISSUE TITLE
Feedback on a Potential Issue with the clonalDiversity Function in the scRepertoire Package

### ISSUE THREAD

**Issue by thekingofall** [ncborcherding/scRepertoire#264]
Dear scRepertoire Development Team,

I am a researcher conducting single-cell immunome analyses using your scRepertoire package. I have encountered some issues in the process and would like to bring them to your attention.

While using the clonalDiversity function to calculate clonal diversity, I noticed that the function calculates the minimum number of cells per sample with the line `min <- short.check(df, cloneCall)` before sampling. However, I encountered a problem when some samples inherently have a low number of BCRs or TCRs. For example, one of the samples in my dataset only has 60 TCRs, while the others have over a thousand. This results in the function only sampling the minimum quantity, such as 50 TCRs.

This approach leads to a significant distortion of the calculated diversity metrics, like the Chao1 index, which in this case, resulted in an output of around 200. I understand this might be to ensure a fair comparison of clones across all samples, but in cases where there is a significant difference in cell numbers amongst samples, this may lead to biased results.

I suggest that within the clonalDiversity function, an additional argument could be considered to allow users to choose whether to apply this minimum sample size limitation, or perhaps provide a more flexible way to handle situations where sample sizes vary greatly.

I hope my feedback can be of assistance to your work, and I look forward to your reply.

Thank you

**Comment by ncborcherding** [comment]
Thank you for the issue and suggestion - the current version of scRepertoire (v1.11.0) has a parameter in ```clonalDiversity()``` called **skip.boots**. Set to TRUE, **skip.boots** will take the whole repertoire and perform the calculations (no boot strapping either). 

Please let me know if you have any other issues!
Nick

**Comment by thekingofall** [comment]
你好,老茅已收到你的来信，稍后我会仔细查看，谢谢(这是自动回复，不用回复过来）
