### ISSUE TITLE
combineExpression 

### ISSUE THREAD

**Issue by Roedani** [ncborcherding/scRepertoire#265]
Hi @ncborcherding 
I started to work with VDJ scRNAseq data and I found your package which is wonderful for what I need, however, I am facing some troubles with the combineExpression. I looked at the scRepertorie Issues and I tried all the things that might be related to my issue, but I could not fix it.

this one shows that I do not have a problem with combineTCR.
clonalHomeostasis(combined, cloneCall = "gene", 
                  cloneTypes = c(Rare = 1e-04, 
                                 Small = 0.001, 
                                 Medium = 0.01, 
                                 Large = 0.1, 
                                 Hyperexpanded = 1))
![image](https://github.com/ncborcherding/scRepertoire/assets/74432483/df1279f5-c20f-442d-a980-d4122edaf6d5)

So, I had to change the barcode's name so each one recognized the other
tail(combined$pre_mix2$barcode)
[1] "pre_mix2_TTTGCGCGTCGAAAGC" "pre_mix2_TTTGGTTGTCTCTCTG"
[3] "pre_mix2_TTTGGTTGTGTTCTTT" "pre_mix2_TTTGGTTTCCTCATTA"
[5] "pre_mix2_TTTGGTTTCTTTAGGG" "pre_mix2_TTTGTCATCATGCTCC"
> tail(immune.combined_p_m1.2.1[[1]])
                             orig.ident
pre_mix2_TTTGTCAGTCCGAACC SeuratProject
pre_mix2_TTTGTCAGTGCGAAAC SeuratProject
pre_mix2_TTTGTCAGTTCAACCA SeuratProject
pre_mix2_TTTGTCATCATAACCG SeuratProject
pre_mix2_TTTGTCATCCCTTGTG SeuratProject
pre_mix2_TTTGTCATCTGCAAGT SeuratProject

Then, I run the combinedExpression
test <- combineExpression(combined, test, 
+                            cloneCall="gene", 
+                            group.by = "NULL", 
+                            proportion = FALSE, 
+                            cloneTypes=c(Single=1, Small=5, Medium=20, Large=100, Hyperexpanded=500))
Warning message:
In combineExpression(combined, test, cloneCall = "gene", group.by = "NULL",  :
  < 1% of barcodes match: Ensure the barcodes in 
            the Seurat object match the 
            barcodes in the combined immune receptor list from 
            scRepertoire - most common issue is the addition of the 
            prefixes corresponding to `samples` and 'ID' in the combineTCR/BCR() 
            functions

And I got a warning message that less than 1 % of barcodes were matched.

I keept runnig the code to see if that warning message would not affect but it does.

DimPlot(test, group.by = "id")  +
  scale_color_manual(values=colorblind_vector(5)) + 
  theme(plot.title = element_blank())
![image](https://github.com/ncborcherding/scRepertoire/assets/74432483/b84d4fb6-c8e7-40f8-b773-2f1142054e0e)

Manly in this image.
![image](https://github.com/ncborcherding/scRepertoire/assets/74432483/9544e10c-4ad8-4a97-b023-ef689d5ef780)

Do you have any clue why this is happening?
Thanks in advance,
Rodrigo

**Comment by ncborcherding** [comment]
Hey Rodrigo, 

I have had this happen to me before and I think I know what is going on.

Unlike the common problem of barcode mismatch (which would give you all NAs in the meta data), you are getting some clones. 

- Between different sequencing runs there will be ~1% of overlapping barcodes. This actually fits your results pretty well.
- The order of your runs in the ```combineTCR()``` step is likely different than the samples/ID parameters

Let me know either way if that changes anything and happy to troubleshoot further if needed. 

Nick

**Comment by Roedani** [comment]
Hi @ncborcherding 
Thanks so much for getting back to me, I really appreciate your quick reply.
I did some analysis to overlap the barcodes to see why they did not match.
This is the characteristic of the data for each one I used.
Seurat object barcodes:
cellnames
AAACCTGCAAGCCGTC-1
AAACCTGCAAGTTCTG-1
AAACCTGCAATAGCGG-1
filtered_contig_annotations.csv:
barcode                 
AAACCTGCAATAGCGG-1    
AAACCTGGTAAATGAC-1  
AAACCTGGTAAATGAC-1
Combined:
barcode
AAACCTGAGAGCTGGT-1
AAACCTGAGCATCATC-1
AAACCTGAGTGGTCCC-1
and doing the Veen plot I got this.
![#18_venn_diagramm](https://github.com/ncborcherding/scRepertoire/assets/74432483/bb80f264-1b67-49c6-b661-9f943f34388e)
This confirms that they do not match, like less than 1 %.

Do you why doing the combineTCR() change the barcodes?
Best wishes,
Rodrigo

**Comment by ncborcherding** [comment]
Hey @Roedani, 

During ```combineTCR()``` check the order of your contig.list is the same as the order of **samples = **.  I think what is going you are switching your sequencing runs and then only getting the overlapping barcodes attached to your seurat object. 

Nick

**Comment by Roedani** [comment]
Hi @ncborcherding 
I am sorry for the late reply. 
Thanks so much, I will work on it. I deeply appreciate your quick and kindly response.

All the best,
Rodrigo
