### ISSUE TITLE
Visualizing multiple samples and moving each pair of sample next to each other

### ISSUE THREAD

**Issue by synatkeamsk** [ncborcherding/scRepertoire#268]
Dear professor Nick,

Hope you are doing great. first, i would like to thank you for developing scRepertoire package. I am wondering how could I visualize multiple samples in **compareClonotypes** to make more sense my data. Some samples are paired together, but I could not move them next to each other. Kindly review my attached graph. I hide the sample name because these are real patients. Hope you do not mind. Is there a way to group sample into different groups and visualize them in **compareClonotypes**. I hope you could help me. Thank you so much. 

Kind Regards,

Synat
![Capture](https://github.com/ncborcherding/scRepertoire/assets/121846660/af419c26-a0a9-4def-8294-5654838f9f4c)

**Comment by ncborcherding** [comment]
Hey Synat, 

I would recommend only visualizing the paired samples together - it allows for the alluvial ribbons to go across the full graph and prevents too many clones from being plotted. You can to it 1 of 2 ways: 

1. Use the **samples** argument in ```compareClonotypes()``` to subset the comparison.
2. Subset the list of the combined clones - something like ```combined[c(1,3,5)]```

Hope that helps and let me know if you have any other questions.

Nick

**Comment by synatkeamsk** [comment]
Dear Professor,

Thank you so much for your kind help. I would like to ask you one more question if you do not mind.  I got stuck a bit as I'm trying to understand how to interact TCRseq with Single cell RNAseq. My dataset contains both single cell RNAseq and ScTCRSeq of 9 patients. I have so far completed subclustering of T cell cluster for ScRNAseq and have annotated all the clusters using seurat pipeline. However, this T cell subcluster does not have barcode to match with TCRSeq yet. Do you think it is possible to add barcode to T cell subclusters. I do not know how to do it yet. really appreciated if you could guide with it code as i do not know how to do it yet. I understand you are very busy and I really appreciate your help. I attached T cell subcluster seurat object and scTCRseq object for you to review.  

Kind regards,


Synat 
![TCRSeq Barcode](https://github.com/ncborcherding/scRepertoire/assets/121846660/e059ddd1-1b68-4b76-a1ff-5f62cff61bf6)
![T cell subcluster Object](https://github.com/ncborcherding/scRepertoire/assets/121846660/1e722070-c88e-4fee-91c9-497709b45a57)

**Comment by ncborcherding** [comment]
Hey Synat, 

First off please call me Nick. 

The problem you are encountering is the most common issue for scRepertoire. The major difference between default barcodes used in the seurat pipeline and in scRepertoire is how they are modified for different sequencing runs. 

In particular, by default, Seurat will amend the suffix of the barcodes with **_X**, so the barcodes change like: 

- original: XXXXXXXXXXXXXXXX-1
- seurat modified: XXXXXXXXXXXXXXXX-1_1

scReprtoire uses the **samples** in ```combineTCR()``` to add a prefix to the barcodes: 

- original: XXXXXXXXXXXXXXXX-1
- scRepertoire modified: Sample1_XXXXXXXXXXXXXXXX-1

The easiest way to make these compatible is to rename the cell barcodes in the seurat object by using the ```RenameCells()```

```
cell.barcodes <- rownames(seuratObj[[]])
cell.barcodes <- stringr::str_split(cell.barcodes, "_", simplify = TRUE)[,1] #This is removing the _1 at the end of the barcodes)
cell.barcodes <- paste0(seuratObj$orig.ident, "_", cell.barcodes) #This is adding the prefix of the orig.ident to the barcodes, assuming that is the sample ids
seuratObj <- RenameCells(seuratObj, new.names = cell.barcodes)
```

**Comment by synatkeamsk** [comment]
Thanks you Nick. It worked now. Really appreciated your immense help and special thank you for building this package for non-computational bioligist like myeself to use. Keep up the good work. 

Kind Regards
