### ISSUE TITLE
Support for new MiXCR v4.5 outputs?

### ISSUE THREAD

**Issue by jeremymsimon** [ncborcherding/scRepertoire#269]
Hi @ncborcherding! I'm in the process of finding and testing open-source alternatives to `cellranger vdj` for 10x 5' TCR/BCR pre-processing. I noticed that the [newest version of MiXCR](https://github.com/milaboratory/mixcr/releases/tag/v4.5.0) seems to get us a bit closer to recapitulating a lot of the same outputs and groupings as `cellranger`, namely the `clones.tsv` and `clone.groups.tsv` files. They may not be filtered in the same way the `filtered_contig_annotations.csv` file is, and the columns are similar (but not identical), but I wonder if it would be possible to extend `scRepertoire` to support these output files directly? Alternatively I can request their developers make these outputs conform to the same format standard as `cellranger`'s outputs if you think that makes more sense. I've attached a screenshot where I've selected the key columns in the `clones.tsv` file to give you a sense.

Of course if there's something I'm missing- ie a key distinction between the contents or assumptions of these files- please let me know what the limitations may be here. I ultimately want to attach the clonotype information to an existing scRNA object I've analyzed in Seurat.

Thanks! Appreciate any help or insight you may have here-

<img width="1036" alt="Screenshot 2023-10-16 at 12 20 27 PM" src="https://github.com/ncborcherding/scRepertoire/assets/37712091/b9d462c2-362a-4747-81af-a238783fec37">

**Comment by ncborcherding** [comment]
@jeremymsimon Thanks for reaching out, support for MiXCR will be out with the v2 release of scRepertoire. Which will be out as a beta by the end of November. In addition there will be support for: 10X, AIRR, TRUST4, BD, WAT3R, and Omniscope.

Thanks for the suggestion - if you can think of any other formats or features, feel free to let me know. 

Nick

**Comment by jeremymsimon** [comment]
Ah great to hear, thanks! Looking forward to v2

**Comment by PoslavskySV** [comment]
Hi guys, this is Stan from MiXCR. @ncborcherding  please, let me know if you need any help with the integration from our side.

**Comment by ncborcherding** [comment]
Hey @PoslavskySV thanks for reaching out - if you have an example updated clones.txt output from ```exportClones``` - that would be great to use for internal testing functions and the vignette I will make for loading data. Feel free to [email](mailto:ncborch@gmail.com)

**Comment by jeremymsimon** [comment]
Tagging @mourisl as well in case any additional coordination on the `TRUST4` side of things is needed. At the very least, it's probably best they're aware this is coming soon too!

**Comment by mourisl** [comment]
Thank you for the tagging @jeremymsimon . @ncborcherding - If you need more columns in the AIRR format from TRUST4, please let me know.

**Comment by linderss** [comment]
Hi, i was wondering if there is already a workaround until the  v2 release of scRepertoire will be out?

**Comment by ncborcherding** [comment]
@linderss 

v2 is out and stable in the [master branch](https://github.com/ncborcherding/scRepertoire) of the github repo

I am working on getting it up in bioconductor develop version for a 3.19 release. 

Nick
