### ISSUE TITLE
change the default sample order in compareClonotypes 

### ISSUE THREAD

**Issue by gt7901b** [ncborcherding/scRepertoire#27]
Hi, Nick:

I did compareClonotypes like the below, without specifying sample names.
compareClonotypes(combined, numbers = 10, cloneCall="aa", graph = "alluvial")

I have 5 samples. Is there a way to specify the order of samples in the Alluvial plot output? 

thanks for your time

**Comment by ncborcherding** [comment]
You should be able to order the samples on the x-axis by defining the sample as a factor and ordering the levels to the specific order you would like.

`
seurat[[]]$sample <- factor(seurat[[]]$sample, levels = c("sample1", "sample2", sample3"....)

`

This is very similar idea to ordering the frequency groups in the vignette with the following code:

`
slot(seurat, "meta.data")$cloneType <- factor(slot(seurat, "meta.data")$cloneType, 
                levels = c("Hyperexpanded (100 < X <= 500)", "Large (20 < X <= 100)", 
                            "Medium (5 < X <= 20)", "Small (1 < X <= 5)", 
                            "Single (0 < X <= 1)", NA))
`

Let me know if you have any more questions and feel free to share an example of the code, so I can give more specifics.

**Comment by gt7901b** [comment]
Hi, Nick:
It's not seurat object. contigs <- list(csv1,csv2,csv3,csv4)
combined <- combineTCR(contigs, 
                        samples = c("Tumor","Normal", "LymphNode", "Blood"), 
                        ID = c("A1001","A1001", "A1001","A1001"), cells ="T-AB")
compareClonotypes(combined, numbers = 10,samples = c("Normal_A1001", "Tumor_A1001","LymphNode_A1001","Blood_A1001"),
                    cloneCall="aa", graph = "alluvial")
but out is default to order tumor lymph normal blood. Is there a way to change that order?  Also, is there a way to export the shared/unique clonotype size to do some comparison later?  thanks

**Comment by ncborcherding** [comment]
You are totally correct, my fault. There are 2 solutions you can go about it with - 

1. Change names for a quick second - the x-axis should be plotted in alphabetical order (not sure why yours is not - looks like it is in reverse order), but just assign new names to your combined object.

```
#order the new names by the corresponding order you'd like to graph
names(combined) <- c("B", "A", etc) 
```

2. Get the intermediate data frame (little more investment)

You will need to define the parameters in the function call you are making like normal, the output will be a data frame called Con.df.

```
#modified function
compareClonotypes.mod <- function(df, cloneCall = "gene+nt", samples = NULL, 
                        clonotypes = NULL, numbers = NULL, graph = "alluvial"){
    cloneCall <- theCall(cloneCall)
    if (!is.null(numbers) & !is.null(clonotypes)) {
        stop("Make sure your inputs are either numbers or clonotype sequences.")
    }
    Con.df <- NULL
    for (i in seq_along(df)) {
        tbl <- as.data.frame(table(df[[i]][,cloneCall]))
        tbl[,2] <- tbl[,2]/sum(tbl[,2])
        colnames(tbl) <- c("Clonotypes", "Proportion")
        tbl$Sample <- names(df[i])
        Con.df <- rbind.data.frame(Con.df, tbl)
    }
    if (!is.null(samples)) {
        Con.df <- Con.df[Con.df$Sample %in% samples,] }
    if (!is.null(clonotypes)) {
        Con.df <- Con.df[Con.df$Clonotypes %in% clonotypes,] }
    if (!is.null(numbers)) {
        top <- Con.df %>% top_n(n = numbers, wt = Proportion)
        Con.df <- Con.df[Con.df$Clonotypes %in% top$Clonotypes,] }
    if (nrow(Con.df) < length(unique(Con.df$Sample))) {
        stop("Reasses the filtering strategies here, there is not 
            enough clonotypes to examine.") }
return(Con.df) }
```
After this, you should be able to set the order of the x-axis by the assigning the Con.df$Sample as a factor with your ordered levels. Then just need to graph using the code below.

```
#graph
ggplot(Con.df, aes(x = Sample, fill = Clonotypes, 
                    stratum = Clonotypes, alluvium = Clonotypes, 
                    y = Proportion, label = Clonotypes)) +
                theme_classic() +
                theme(axis.title.x = element_blank())+ 
                geom_flow() + 
                geom_stratum()
```

Let me know if that makes sense - I will add an exportTable parameter to the compareClonotype function during the next commit so this will not be a future problem for people. 

Thanks.

**Comment by gt7901b** [comment]
great, thank you Nick! It works!
