### ISSUE TITLE
How Seurat.Obj was obtained

### ISSUE THREAD

**Issue by malonzm1** [ncborcherding/scRepertoire#270]
Hi,

In https://github.com/ncborcherding/scRepertoire/blob/master/vignettes/vignette.Rmd a Seurat.Obj was used. May I know how this object was obtained?

Thanks and good day.

**Comment by malonzm1** [comment]
Thanks. Is the Seurat.Obj obtained from the same fastq files used to obtain filtered_contig_annotations.csv or are they corresponding 10x fastq files? That is, from the link above:

GSM3440844	GU0700_T
GSM3440845	GU0715_T
GSM3440846	GU0744_T
GSM3440847	GU0700_P
GSM3440848	GU0715_P
GSM3440849	GU0744_P
GSM3440850	GU0700_T [VDJ sequencing]
GSM3440851	GU0715_T [VDJ sequencing]
GSM3440852	GU0744_T [VDJ sequencing]
GSM3440853	GU0700_P [VDJ sequencing]
GSM3440854	GU0715_P [VDJ sequencing]
GSM3440855	GU0744_P [VDJ sequencing]

Are the filtered_contig_annotations.csv files from GSM3440850 to GSM3440855 and the Seurat objects from GSM3440844 to GSM3440849?

Thanks.

**Comment by ncborcherding** [comment]
Yes that is correct - the sample names might be shuffled around though so don't expect PX --> GU0700.
