### ISSUE TITLE
Importing from TRUST4 output

### ISSUE THREAD

**Issue by RaghadShu** [ncborcherding/scRepertoire#273]
Hello,
I hope this post finds you well. I am excited to analyze BCRs using this package. 

A little overview of what I am doing: I am trying to look into the clonotypes in one multiple myeloma sample named MM1. The sample only has plasma cells. The sequencing was done using 3' kit, but I would like to estimate scBCR information. TRUST4 does have a disclaimer that there might not be enough coverage to extract anything, but that it is worth a try.
 
At the moment, I am having issues importing TRUST4 output into scRepertoire.
This is what my TRUST4 output directory looks like for sample MM1:
![image](https://github.com/ncborcherding/scRepertoire/assets/143171933/54094e5b-5731-452f-961a-32a15aac9053)
which seems like the expected output from TRUST4 (https://github.com/liulab-dfci/TRUST4#inputoutput)

But when I try loadContigs from scRepertoire, I get an empty list: (I even tried format AIRR and the same issue)
![image](https://github.com/ncborcherding/scRepertoire/assets/143171933/0ff29f03-aad1-4021-819e-ea6a31dacbb4)

I feel like I am missing a trivial step but I can't figure out where the issue lies exactly.. 

Looking forward to your input,
Raghad

**Comment by ncborcherding** [comment]
Hey Raghad, 

```loadContigs()``` for TRUST4 is expecting a file with the pattern **"barcode_report.tsv"** if giving the directory of the outputs. Alternatively, you can:

 ```
BCR <- read.delim("./TRUST4/MM1_TRUST4/MM1_report.tsv") #I am assuming this is the file
contig.list <- loadContigs(BCR, "TRUST4")
```

Nick

**Comment by mourisl** [comment]
Hi @RaghadShu , it seems you ran TRUST4 in the bulk RNA-seq mode. You shall specify the cell barcode range on the read or in the bam file through the "--barcode XXX" option, plus --readFormat if input is fastq format. The details can be found at: https://github.com/liulab-dfci/TRUST4#10x-genomics-data-and-barcode-based-single-cell-data . Hope this helps.

**Comment by ncborcherding** [comment]
Thanks Li!!

**Comment by RaghadShu** [comment]
Thank you both for the help! I re-ran TRUST4 and was able to import the list of contigs into R
Now, I am trying to combine the contigs using combineBCR() but I am getting this error:
![image](https://github.com/ncborcherding/scRepertoire/assets/143171933/65e108b1-cb3a-4758-bc84-0456862fe4eb)

I did a deep dive into the previously asked questions and I did install the package using scRepertoire@dev so it should be the latest version.. Any inputs on this?

Thank you again,
Raghad

**Comment by ncborcherding** [comment]
Hey Raghad, 

The **samples** argument in ```combineBCR()``` is required - I'll add an error into the function to give more context. 

Nick
