### ISSUE TITLE
Understanding quantContigs output + cloneType definitions

### ISSUE THREAD

**Issue by RaghadShu** [ncborcherding/scRepertoire#277]
Hello,

Thank you for this smooth and excellent package! I have few questions about my specific output..

Context of the data: All 5 of my samples are 3' sequencing, and are all **plasma cells** from Multiple Myeloma patients at different disease stages. Since MM is a monoclonal gammopathy, we would expect one BCR sequence per sample, and maybe a couple of BCRs in the pre-cursour stages (SMM and MGUS). I attempted to estimate BCR sequences from the data, and I used TRUST4 to extract reads and re-align them to a better immunoglobulin reference. 

I used this command to combine BCR sequences:
`combined2 <- combineBCR(contig.list, samples = c("MM1", "MM2", "MM3", "SMM1", "MGUS1"), removeNA = TRUE, removeMulti = TRUE, filterMulti = TRUE)` 

Then, I used quantContig to quantify "unique" clonotypes:
`quantContig(combined2, cloneCall="strict", chain = "both",scale = TRUE, exportTable = TRUE) `

And I get this table as an output: 
![Screenshot 2023-11-13 at 14 56 07](https://github.com/ncborcherding/scRepertoire/assets/143171933/e7f180db-fe0e-400b-b5a9-d4ab0e4dbc20)
and as mentioned in #102,  
- Contigs is the number of unique clonotypes 
- Values is the grouping variables 
- Total is total cells recovered
- Scaled is unique clonotypes/total

Questions: 
- Since they are multiple myeloma sampels, we expect around 1 unique BCR sequence.. Is it correct to interpert the contigs columns as the number of unique BCR sequences retrieved per sample? And if yes, is there a reason behind the descrepincy of what's expected vs. what we see?
- Is the "total" referring to how many cells TRUST4 was able to read and extract BCRs from? If that's the case, something is off because for MGUS1, the total number of cells is 13,263 cells, but the "total" is 18,420 
- Is there a way I can **extract the unique BCR sequences** per sample and plot them? I would like to see where these lay on the UMAP and if a specific cluster is dominated by a single BCR sequence 
- I'm not sure what does the cloneType cutoff values (these ones: c("Hyperexpanded (100 < X <= 500)", "Large (20 < X <= 100)",  "Medium (5 < X <= 20)",  "Small (1 < X <= 5)", "Single (0 < X <= 1)") stand for (and I looked for them in the manuscript but couldn't find them). Any information on that would be greatly appreciated. 

I apologies if any of the questions have been asked before.
Many thanks in advance,
Raghad

**Comment by ncborcherding** [comment]
Hey Raghad, 

Thanks for the questions: 


- Since they are multiple myeloma sampels, we expect around 1 unique BCR sequence.. Is it correct to interpert the contigs columns as the number of unique BCR sequences retrieved per sample? And if yes, is there a reason behind the descrepincy of what's expected vs. what we see?

> If you are sequencing sort-purified malignant plasma cells, you would expect a single unique contig (or 2 in the case of biclonal disease) (labeled **contig** in the exported table above). With the values you are getting, it makes me wonder if you are sequencing plasma cells in general - which might explain the couple dozen unique contigs. 

- Is the "total" referring to how many cells TRUST4 was able to read and extract BCRs from? If that's the case, something is off because for MGUS1, the total number of cells is 13,263 cells, but the "total" is 18,420.

> You will need to look at the specific sample itself and what numbers you are comparing, the **total** is referring to the total number of cells recovered with clonal sequences from the TRUST4 output - this might be different than the RNA barcodes you recover. When using 10x 5' data - I've commonly seen about 85% of cells will have shared RNA and contig data. I do not know if that is the case for 3' data recovered using TRUST4.


- Is there a way I can extract the unique BCR sequences per sample and plot them? I would like to see where these lay on the UMAP and if a specific cluster is dominated by a single BCR sequence.

> After using ```combineExpression()```, you will have a column in your meta data that is **Frequency** which in the context from the below question - will be the counts of each clone. You can use this + ```highlightClonotypes()``` to plot specific clones on a UMAP. I also commonly create a proportional bar chart in ggplot to look at specific domination of clusters by clones - something like: 

```
meta <- SeuratObj[[]]
ggplot(meta, aes(x=seurat_clusters)) + 
  geom_bar(aes(fill = CTaa), position = "fill") + 
  guides(fill = "none") + 
  theme_classic()
```


- I'm not sure what does the cloneType cutoff values (these ones: c("Hyperexpanded (100 < X <= 500)", "Large (20 < X <= 100)", "Medium (5 < X <= 20)", "Small (1 < X <= 5)", "Single (0 < X <= 1)") stand for (and I looked for them in the manuscript but couldn't find them). Any information on that would be greatly appreciated.

> This is just grouping the clones into bins by frequency. Alternatively, when using ```combineExpression()```, you can leave the default of proportion = TRUE, and the grouping will bin by proportion of repertoire.

**Comment by RaghadShu** [comment]
Hi,
Thank you for the answers! 

For the second question, let me try and explain better: The input cell numbers for MGUS1 is around 13k cells. This is the number of cells from the 10X 3' sequencing, which I used as input for TRUST4. But the "total" here is around 18k.. So I am still confused about the "total" in the quantContigs output. Could it be that that some cells were counted twice, one for each IG chain?

Also, in the quantContigs output, is each "contig" an IGheavy or IGlight chain? or a single complete BCR? 

Thank you again,
Raghad

**Comment by ncborcherding** [comment]
Hey Raghad, 

I think you should quantify the number of barcodes from your TRUST4 output directly or attach the clones to the single-cell object you have to filter out any potential dubious cells. The output of ```quantContig()``` is the number of clones after combining them in ```combineBCR()```, so it is not counting twice.

Nick
