### ISSUE TITLE
clonalLength fails for WAT3R output

### ISSUE THREAD

**Issue by noranekonobokkusu** [ncborcherding/scRepertoire#284]
Hi,

Thanks again for fixing combineTCR!
I noticed that clonalLength crashes because the format of TRC1 and TRC2 columns is different for WAT3R-produced combined.TCR:

<pre>
> clonalLength(combined, 
+              cloneCall="aa", 
+              chain = "TRA", 
+              scale = TRUE) 
Error in switch(c1, TRA = "TRB", IGH = "IGL", TRG = "TRD") : 
  EXPR must be a length 1 vector

# following clonalLength code:
> input.data = combined
> input.data <- .data.wrangle(combined, cloneCall = .theCall(input.data, "aa", check.df = FALSE), chain = "both")
> cloneCall <- .theCall(input.data, "aa")
> chain.pos <- which(colnames(input.data[[1]]) == "cdr3_aa1")-1
> c1 <- na.omit(unique(substr(input.data[[1]][seq_len(10),chain.pos], 1,3)))
> c1
[1] "NA." "TRA"
> substr(input.data[[1]][seq_len(10),chain.pos], 1,3)
 [1] "NA." "TRA" "TRA" "NA." "TRA" "TRA" "NA." "TRA" "TRA" "NA."
> input.data[[1]][seq_len(10),chain.pos]
 [1] "NA.NA.NA;NA.NA.NA"                                          
 [2] "TRAV8-4*01,TRAV8-4*04.TRAJ23*01.NA;NA.NA.NA"                
 [3] "TRAV8-3*01.TRAJ24*02.NA;NA.NA.NA"                           
 [4] "NA.NA.NA;NA.NA.NA"                                          
 [5] "TRAV14/DV4*02.TRAJ53*01.NA;TRAV14/DV4*02.TRAJ53*01.NA"      
 [6] "TRAV26-1*01,TRAV26-1*02.TRAJ22*01.NA;TRAV17*01.TRAJ54*01.NA"
 [7] "NA.NA.NA;NA.NA.NA"                                          
 [8] "TRAV8-1*01.TRAJ5*01.NA;NA.NA.NA"                            
 [9] "TRAV1-2*01,TRAV1-2*03.TRAJ33*01.NA;NA.NA.NA"                
[10] "NA.NA.NA;NA.NA.NA" 
</pre>

So NA is not dropped from c1, because instead of being just NA in the TCR column, it is "NA.NA.NA;NA.NA.NA". It behaves differently for the default contig list (that has plain NAs) so I wonder if this is an expected behavior (though I can easily fix it manually for my dataset).

Best,
K

**Comment by ncborcherding** [comment]
Thanks for letting me know - it actually looks like the WAT3R format may have changed slightly and ```loadContigs()``` is actually broken for the WAT3R format. I will update this issue when the fix is pushed.

Nick

**Comment by Qile0317** [comment]
> Thanks for letting me know - it actually looks like the WAT3R format may have changed slightly and ```loadContigs()``` is actually broken for the WAT3R format. I will update this issue when the fix is pushed.
> 
> 
> 
> Nick

Actually, I wouldn't be so sure it's loadContigs that's the problem, it's more likely related to what I just commented on above in #283 

Looks like my new combineTCR code was even more buggy than expected, we could temporarily revert back to the old version until I thoroughly fix and test the Rcpp accelerated version

**Comment by noranekonobokkusu** [comment]
Ehh which file are you looking at? The final WAT3R output (_barcode_results.csv) has one cell - one line correspondence, the one you are looking at right now is called _barcode_UMI_results.csv which is not the final output of the pipeline!

K

**Comment by ncborcherding** [comment]
Ahh nice catch - 

Good news - I found the several issues (this is why we are beta right now). 

Issue 1 - wat3r has a NA tendency and when use ID-ing chain by using the first 3 characters of a gene (TRAV --> TRA) will have times where the chain is NA., which breaks things.
Issue 2 - combineTCR() without samples will break some functions and will need to be fixed.

I have a repro example (and at least for your single call, it is fixed) I need more testing though for other permutations - again it will be up tomorrow. 

```
wat3r <- read.csv("https://www.dropbox.com/s/5bnn6ttavgyr38f/PB01_barcode_results.csv?dl=1")
contig.list <- loadContigs(wat3r, format = "WAT3R")
combined <- combineTCR(contig.list)
clonalLength(combined, chain = "TRA")
```
<img width="490" alt="Screenshot 2023-12-05 at 3 17 43 PM" src="https://github.com/ncborcherding/scRepertoire/assets/22754118/17bc04b8-67c8-46de-93d6-e04884821a3f">

**Comment by ncborcherding** [comment]
Got it fixed and tested, please check the newest commit and see if you problem persists - this is my output for the code:

```
wat3r <- read.csv("https://www.dropbox.com/s/5bnn6ttavgyr38f/PB01_barcode_results.csv?dl=1")
contig.list <- loadContigs(wat3r, format = "WAT3R")
combined <- combineTCR(contig.list)
```
![Rplot](https://github.com/ncborcherding/scRepertoire/assets/22754118/ca642972-e27e-44eb-803f-6b9cce4e7e61)

**Comment by noranekonobokkusu** [comment]
It works on my data, thank you! The plot looks weird but I assume it's the input data, not the package.
<img width="653" alt="image" src="https://github.com/ncborcherding/scRepertoire/assets/18593728/397f34b4-5210-4c77-88b4-76f9fc8e9004">

**Comment by ncborcherding** [comment]
Thanks for the follow up!
