### ISSUE TITLE
Change sample orders

### ISSUE THREAD

**Issue by mainyanghr** [ncborcherding/scRepertoire#288]
Dear Sir or Madam,

Please help with sample order when plotting, such as ClonalOverlap, vizGenes. It seems the Y-axis list the samples from the biggest number to smallest one. 

If we want to change colors or other things, what should we do? Could we combine the ggplot?

Please look at this examples; 

sample_order <- c("p6106", "p6103", "p6104", "p6102", "p6100", "p44", "p05")

clonalOverlap(TCRallBa, cloneCall = "strict", method = "overlap", ??????, How should plot the Y-axis with that sample order? )

Thank you all.

Best.

**Comment by ncborcherding** [comment]
Thanks for reaching out.

Could you give me more information on what **TCRallBa** is? Is it a Seurat object? Output of ```combineTCR()```?

Also what version of scRepertoire are you using? 

Nick

**Comment by mainyanghr** [comment]
> Thanks for reaching out.
> 
> Could you give me more information on what **TCRallBa** is? Is it a Seurat object? Output of `combineTCR()`?
> 
> Also what version of scRepertoire are you using?
> 
> Nick

Thank you for your fast reply. TCRallBa is the list of data frame. Actually I have the same problems for the combined seurat data as well. It will be great if you could explain for both data format. Have a nice day!
Harry

**Comment by ncborcherding** [comment]
Hey Harry, 

For a list/output of ```combineTCR()```, just reorder your list:

```
TCRallBa <- TCRallBa[c(2,1,4,3,....)]
```

For a seurat object - making the **group.by** argument a factor:

```
seuratObj$group.var <- factor(seuratObj$group.var, levels = c("p6106", "p6103", "p6104", "p6102", "p6100", "p44", "p05"))
```

This is assuming you have the most-up-to-date version of scRepertoire and Seurat. 

Nick
