### ISSUE TITLE
accomodate custom GEO input 

### ISSUE THREAD

**Issue by wvictor14** [ncborcherding/scRepertoire#289]
Hello, I am working with a public scTCRseq dataset that has provided a unique / processed TCR dataframes on GEO. It is 10x data, but each sample has a TCR  csv file that I cannot figure out how to load using scRepertoire framework. Here is TCR data for one sample:

https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3576nnn/GSM3576465/suppl/GSM3576465%5FC9%5FR%5Ffull%2Dlength%5Fproductive%5FTCR%5Ftable.tsv.gz

Here is what it looks like:

![image](https://github.com/ncborcherding/scRepertoire/assets/22013187/e3c4bb2d-8ad1-4219-9621-7002041c9174)

I have tried:

1. pointing loadContigs to the data directory containing these TCR tsv files
2. loading each tsv file using readr::read_tsv and holding as a list of dataframes, and trying to feed into combineTCR, but I get error saying it needs a "chain" column, which am not sure how to derive from the existing data

Is it possible to load this type of data into scRepertoire  workflow?

**Comment by ncborcherding** [comment]
Hey Victor, 

Looks like it is a custom exported data frame from that the researchers made from the contig file themselves - as such, will not be compatible with the scRepertoire workflow without some custom formatting. You can probably modify this to work with scRepertoire - the minimal headers you'll need for compatibility with scRepertoire are: 

- barcode
- chain (missing)
- reads (missing)
- v_gene
- d_gene
- j_gene
- c_gene
- cdr3_nt
- cdr3

As this is not a code issue, I am going to close this. But if you want to discuss more - happy to [email](mailto:ncborch@gmail.com) and give advice. 

Nick
