### ISSUE TITLE
Multiple comparison using compareClonotypes

### ISSUE THREAD

**Issue by eddyhcwang** [ncborcherding/scRepertoire#29]
Hi Nick,

I am wondering if there is an easier way to plot an alluvial-type of graph that can compare the proportion/number of overlapping clonotypes between multiple samples? For example, if I want to compare the number of clonotypes that are shared between PX_P, PX_T AND PY_P. The current example performs a linear comparison of the samples (ie. PX_P to PX_T).

A circular chord diagram like that the Circlize package seems to be what I wanted (to visualize the amount of shared clonotypes between multiple clusters). I exported data frame from compareClonotypes and clonoaloverlap (melt the data frame and removed the NAs), but it didn't look quite right. Do you have any suggestions?

Thanks!

**Comment by ncborcherding** [comment]
Hey eddyhcwang,

Working on getting a function ready to a Chord Diagram from the Circlize package and am planning to introduce it after the acceptance of scRepertoire to bioconductor. It involves a couple assumptions - like directionality and how to account reciprocal relationships, which I still need to figure out before finalizing the function. Here is an example from a [recent publication](https://insight.jci.org/articles/view/137424) where A and B are showing the difference in shared clonotypes between clusters in unaffected and alopecia areata mice. If this is what you were thinking?

![jci insight 137424 f4](https://user-images.githubusercontent.com/22754118/93005199-6fad4980-f514-11ea-956a-5d2b32ce332b.jpg)

In the mean time - if you're interested in working through the troubleshooting process with me - feel free to drop me [a line](mailto:ncborch@gmail.com) and I am happy to share the unfinished code and try to get it up and working for you.

**Comment by gt7901b** [comment]
Hi, Nick:

How do you generate the plot in Fig.C?  Sankey ? do you have an example? will that be incorporated into package?

**Comment by ncborcherding** [comment]
Fig C are alluvial graphs, just subsetted the seurat object by the clusters of interest and then used `alluvialClonotypes()`.
