### ISSUE TITLE
Predict the antigens?

### ISSUE THREAD

**Issue by mainyanghr** [ncborcherding/scRepertoire#291]
This is a great package, I am wondering whether we could predict the antigens or any other packages are recommended for antigen prediction? 

Thank you very much!

**Comment by ncborcherding** [comment]
There is no ideal epitope prediction pipeline for TCRs. scRepertoire does not have prediction capabilities, but there is [Trex ](https://github.com/ncborcherding/Trex)(compatible with scRepertoire), which could be used for unsupervised epitope discovery/prediction.

Other pipelines you might want to check out:

- [GLIPH2](http://50.255.35.37:8080/)
- [NetTCR](https://services.healthtech.dtu.dk/services/NetTCR-2.0/)
- [TCR-BERT](https://github.com/wukevin/tcr-bert)

Just a not - this area is exploding right now with tools and publications. There are a ton of alternative to the above. Best practice is probably combining several and looking at the intersection. 

Hope that helps,
Nick

**Comment by mainyanghr** [comment]
Thank you very much for great response. You are the best!

Have a nice day! Looking forward to collaborate with you.
