### ISSUE TITLE
Order of input contigs influences the results of combineTCR

### ISSUE THREAD

**Issue by michael-kotliar** [ncborcherding/scRepertoire#293]
`removeNA` parameter (I use v1.11.0 installed from GitHub) doesn't work as expected. `combineTCR` function returns different results depending on the order of the contigs in the input file. We don't see big difference unless we set `removeNA=TRUE` and/or `filterMulti=TRUE`.

For example, for input where TRB is before TRA
```
barcode			is_cell	contig_id			high_confidence	length	chain	v_gene	d_gene	j_gene	c_gene	full_length	productive
AACTGGTCATTAGCCA-1	true	AACTGGTCATTAGCCA-1_contig_1	true		499 	TRB	TRBV9	TRBD1	TRBJ2-1	TRBC2	true		true
AACTGGTCATTAGCCA-1	true	AACTGGTCATTAGCCA-1_contig_2	true		563	TRA	TRAV22		TRAJ17	TRAC	true		true
AACTGGTCATTAGCCA-1	true	AACTGGTCATTAGCCA-1_contig_3	true		507	TRB	TRBV6-4		TRBJ2-7	TRBC2	true		true
```
the output of `combineTCR` function will be 
```
barcode			is_cell		contig_id			high_confidence		length	chain	v_gene	d_gene	j_gene	c_gene	full_length	productive
AACTGGTCATTAGCCA-1	true		AACTGGTCATTAGCCA-1_contig_1	true			499	TRB	TRBV9	TRBD1	TRBJ2-1	TRBC2	true		true 
```
But for input where TRA is before TRB (this also happens when we set `filterMulti=TRUE`, because in addition to deletion of one TRB we group by barcode and chain)
```
barcode			is_cell	contig_id			high_confidence	length	chain	v_gene	d_gene	j_gene	c_gene	full_length	productive
AACTGGTCATTAGCCA-1	true	AACTGGTCATTAGCCA-1_contig_2	true		563	TRA	TRAV22		TRAJ17	TRAC	true		true
AACTGGTCATTAGCCA-1	true	AACTGGTCATTAGCCA-1_contig_1	true		499 	TRB	TRBV9	TRBD1	TRBJ2-1	TRBC2	true		true
AACTGGTCATTAGCCA-1	true	AACTGGTCATTAGCCA-1_contig_3	true		507	TRB	TRBV6-4		TRBJ2-7	TRBC2	true		true
```
The output of `combineTCR` function will include `<NA>` for `d_gene`. Thus, this line will be removed when we set `removeNA=TRUE`, because instead of checking only `TCR1` and `TCR2` columns we use `na.omit` for all columns [here](https://github.com/ncborcherding/scRepertoire/blob/5c9b480ca280ef2a852e6015d90ba7c66daf39df/R/utils.R#L132).
```
barcode			is_cell		contig_id			high_confidence	length	chain	v_gene	d_gene	j_gene	c_gene	full_length	productive
AACTGGTCATTAGCCA-1	true		AACTGGTCATTAGCCA-1_contig_2	true		563	TRA	TRAV22	<NA>	TRAJ17	TRAC	true		true
```

**Comment by ncborcherding** [comment]
Hey Michael, 

Thanks for outlining the problem above - is there a difference in the clone designations i.e. headers CTaa, CTnt, CTstrict, CTgene?

The headers/columns you include above are actually ignored after combineTCR().

Nick

**Comment by michael-kotliar** [comment]
Hi Nick,

I think all the other columns look ok, but because `d_gene` has NA, certain cells will be mistakenly removed when setting `removeNA=TRUE`, and almost all cells will be removed when combining `removeNA=TRUE` and `filterMulti=TRUE`. This happens because to for filterMulti we group by barcode and chain, making the order of chains to be first TRA then TRB, and as a result `d_gene` will be NA for all cells except those which have only TRB chain.

**Comment by ncborcherding** [comment]
Hey Michael, 

Apologies for the confusion - I am knee deep working on v2 of scRepertoire (the current main branch).

You may be right that there is unintended removal of contigs using ```removeNA=TRUE```. In  scRepertoire v2, ```combineTCR()``` output is: 

<img width="609" alt="Screenshot 2023-12-21 at 9 17 05 AM" src="https://github.com/ncborcherding/scRepertoire/assets/22754118/42e49ebf-fb67-4136-b827-531e061c22cc">

Everything is concatenated and the individual gene calls are not retained, so this should no longer be an issue. 

Nick

**Comment by michael-kotliar** [comment]
Great! Then I'll start using the latest version from the main branch.
