### ISSUE TITLE
group.by set to NULL in combineExpression fails

### ISSUE THREAD

**Issue by michael-kotliar** [ncborcherding/scRepertoire#294]
When setting `group.by` to `NULL` this line fails because comparing NULL and string doesn't produce any value. `is.null(group.by)` should go before `group.by == "none"`

https://github.com/ncborcherding/scRepertoire/blob/d188e6ffe71db03c7f79f86652c9b2378aeceffe/R/combineExpression.R#L79

```
> NULL == "none"
logical(0)
```

**Comment by ncborcherding** [comment]
Hey Michael, 

Thanks for pointing this out - you are correct. If you find anymore of these, feel free to make a pull request and get your username on the repo. I think it's important to keep track of that. 

Also if you have larger suggestions or functions you might have, feel free to reach out via [email](mailto:ncborch@gmail.com). We are in the process of testing out v2 beta and will be writing a manuscript next year, would be happy to have any contribution. 

Nick
