### ISSUE TITLE
ClonalDiversity function input data 

### ISSUE THREAD

**Issue by nsariipek** [ncborcherding/scRepertoire#296]
Hi Nick, 
Thank you so much for creating the package, it helped us tremendously! My question(not an issue) is there a way to use the ClonalDiversity function using a tibble or dataframe instead of a Seurat Object as data input? I already tried it, and it gave this error:
 `Error in df[[i]][, cloneCall] : incorrect number of dimensions`
I'd greatly help if there is an easy fix!
Thanks
Nurefsan

**Comment by ncborcherding** [comment]
Hey Nurefsan,

Thanks for reaching out. You could likely use the internal functions for ```clonalDiversity()```, such as ```.invsimpson()``` (find them [here ](https://github.com/ncborcherding/scRepertoire/blob/ce55335cdfe703325521d08cd1ab2dcb3efd8161/R/clonalDiversity.R#L188C12-L188C12)), most of these calculations use a count vector of the clone numbers. 

Here would be where I would start - cdr3.data is your clone vector 

```
clone.summary <- as.data.frame(table(cdr3.data))
inv.simpson <- scRepertoire:::.invsimpson(clone.summary[,2])
```

Hope that helps - happy to troubleshoot more via [email](mailto:ncborch@gmail.com). I am going to close this as it is not a software issue per say. 

Nick
