### ISSUE TITLE
Query Regarding CombiningTCR or Merging Different Runs/Samples

### ISSUE THREAD

**Issue by ImtKhu** [ncborcherding/scRepertoire#298]
I've been following your vignette for scRepertoire v1.7.2 and have a question about combineTCR. In the provided example, there are six samples ("PY", "PY", "PX", "PX", "PZ", "PZ"). When quantifying clonotypes, the results are obtained separately for each of the six samples.

My goal is to adapt this code to combine the results into three samples ("PY", "PX", "PZ") for the purpose of increasing cell numbers and merging experiments. Here's the code snippet from the vignette:

combined <- combineTCR(contig_list,  samples = c("PY", "PY", "PX", "PX", "PZ", "PZ"), ID = c("P", "T", "P", "T", "P", "T"), cells = "T-AB")

Could you provide any guidance or suggestions on how to achieve this?

I appreciate your help.

**Comment by ncborcherding** [comment]
Hey ImtKhu,

Thanks for reaching out. 

I would not recommend combining multiple sequencing runs - there will be an issue in duplicate barcodes between runs. The better method would be to group sequencing runs together by variables, so for example: 

```
combined <- combineTCR(contig_list, 
                       samples = c("PY", "PY", "PX", "PX", "PZ","PZ"), 
                       ID = c("P", "T", "P", "T", "P", "T"), 
                       cells ="T-AB")

quantContig(combined, 
            cloneCall="gene+nt", 
            scale = T,
            group.by = "sample")
```

In the above xample - the output will now be showing the unique clones for "PY", "PX", "PZ". 

I hope that helps.

Nick
