### ISSUE TITLE
Custom variable in the clone definition

### ISSUE THREAD

**Issue by noranekonobokkusu** [ncborcherding/scRepertoire#299]
Hi,

I've implemented a custom function to define clones in my data and added it as a new column in the `combineTCR` output. Is it possible to extend the clonal definition function to allow it to use custom columns? The documentation for `clonalQuant` says `cloneCall	
How to call the clonotype - VDJC gene (gene), CDR3 nucleotide (nt), CDR3 amino acid (aa), VDJC gene + CDR3 nucleotide (strict) or a custom variable in the data.`, but it is not allowed in `.convertClonecall`.

Thanks!

**Comment by ncborcherding** [comment]
You are correct - looks like a stop call got added to the ```.convertClonecall``` helper function. 

I am not near a computer at the moment, if you feel comfortable, feel free to make a pull request so we can add your name to the repo. I should get time at the end of this week to fix the issue. 

Nick
