### ISSUE TITLE
Loading 'all_contig_annotations.csv' from  5' gene expression, V(D)J Data and Performing Basic Clonal Analysis. 

### ISSUE THREAD

**Issue by ImtKhu** [ncborcherding/scRepertoire#300]
Thank you for your user-friendly TCR analysis toolkit and for your prompt attention to user questions. I have processed 5' gene expression, V(D)J, and feature barcode data using cellranger multi, resulting in gene expression data and an 'all_contig_annotations.csv' file. I am trying to analyze basic clonal analysis.

In my dataset, there are a total of eight donors/hashtags ("CMO301" to "CMO308") run within a single sample. Four of them are in the control group ("CMO301" to "CMO304"), and the rest are in the treatment group. I've been able to perform clonal quantification for a single sample using the following code:  
read_csv("~/all_contig_annotations.csv") -> CM_con
CM_list <- list(CM_con)
CM.TCR <- combineTCR(CM_list, removeNA = FALSE, removeMulti = FALSE, filterMulti = FALSE)
clonalQuant(CM.TCR, cloneCall = "strict", chain = "both", scale = TRUE)

#However, when I attempted to extend this analysis to include multiple samples, providing sample names as follows:  
CM.TCR <- combineTCR(con_list, samples = c("CMO301", "CMO302", "CMO303", "CMO304", "CMO305", "CMO306", "CMO307", "CMO308"), removeNA = FALSE, removeMulti = FALSE, filterMulti = FALSE)
I encountered an error: 
Error in combineTCR(con_list, samples = c("CMO301", "CMO302", "CMO303", "CMO304", "CMO305", "CMO306", "CMO307", "CMO308"), removeNA = FALSE, removeMulti = FALSE, filterMulti = FALSE) : object 'CMO301' not found

I'm reaching out to seek guidance on whether it's possible to perform this analysis across multiple samples in this way. Any insights or suggestions you can provide would be greatly appreciated. Thank you for your time and assistance.

**Comment by ncborcherding** [comment]
Hey ImtKhu, 

Thanks for reaching out. I do not an obvious issue with your code/function calling (below). 

```
CM.TCR <- combineTCR(con_list, samples = c("CMO301", "CMO302", "CMO303", "CMO304", "CMO305", "CMO306", "CMO307", "CMO308"), removeNA = FALSE, removeMulti = FALSE, filterMulti = FALSE)
```

This leads to to think that your ```con_list``` is likely the issue. What was the code you used to make the list? 

Additionally, ```combineTCR()``` is expecting the length of ```con_list``` to be equal to the length of the **samples** parameter/argument. What is the output of length(con_list)?

Thanks,
Nick

**Comment by ImtKhu** [comment]
Hi Nick,
I appreciate your swift response and sincere assistance. Thank you for your guidance.
The "all_contig_annotations.csv" file contains a total of 31 columns, but unfortunately, there is no "HTO_maxID" column, which is crucial for capturing unique hashtag antibody information. Here are the existing columns:

[1] "barcode"               "is_cell"               "contig_id"             "high_confidence"       "length"                [6] "chain"                 "v_gene"                "d_gene"                "j_gene"                "c_gene"                [11] "full_length"           "productive"            "fwr1"                  "fwr1_nt"               "cdr1"                 [16] "cdr1_nt"               "fwr2"                  "fwr2_nt"               "cdr2"                  "cdr2_nt"              [21] "fwr3"                  "fwr3_nt"               "cdr3"                  "cdr3_nt"               "fwr4"                 [26] "fwr4_nt"               "reads"                 "umis"                  "raw_clonotype_id"      "raw_consensus_id"     [31] "exact_subclonotype_id"

Relevant information: In the gene expression data downloaded and analyzed using Seurat, there is a column named "HTO_maxID" in the Seurat metadata. Seurat's vignette recommends running the following to connect unique barcodes and hashtags:
gene_expression_data <- data_list[["Gene Expression"]]
antibody_capture_data <- data_list[["Antibody Capture"]]
joint1 <- intersect(colnames(gene_expression_data), colnames(antibody_capture_data))

AS you recommended  to run to connect with seurat object and ultimately "HTO_maxID" that  is stored in seurat object:
contig.list <- createHTOContigList(contigs,  Seurat.Obj,group.by = "HTO_maxID")
                                   
However, my objective is to perform basic clonal analysis independently of the Seurat object. I want to use the "all_contig_annotations.csv" file, where, unfortunately, there is no "HTO_maxID" information. Is there any alternative approach for basic clonal analysis in this context?   

As I do not have a background in bioinformatics, there is a possibility of errors in my understanding. Please feel free to correct me if there are any mistakes.

**Comment by ncborcherding** [comment]
Hey ImtKhu,

The key issue here is you need to separate the clonal information by sample - unfortunately you will need the data from your antibody hashing to get separated samples. Like you mention, there is no HTO info in the all_contig_annotation files. 

In addition, to do a lot of the basic analysis, you will need to make a list of the contigs by sample instead of the single data frame - hence the function ```createHTOContigList()```. You could also do that manually by getting the barcodes and sample ids from the seurat object and use that to make separate data frames.

Nick

**Comment by LynnYinU** [comment]
hello After i upload two filtered_contig_annotations.files and want to make a comparison, i find that although i install the package  when use functions like quantCountig, lengthCountig, the R studio tell me that it could not find the function. I have tried to install a new version and an old version, but neither of them take effect. 
<img width="503" alt="截屏2024-01-07 下午7 00 11" src="https://github.com/ncborcherding/scRepertoire/assets/28039787/caf3213b-9799-45e5-a74c-19c45da206ea">

**Comment by ncborcherding** [comment]
@LynnYinU Please open a new issue (and include the output of sessionInfo) - my guess is it is a version issue (see the new function names - [https://www.borch.dev/uploads/screpertoire/](https://www.borch.dev/uploads/screpertoire/))

**Comment by ncborcherding** [comment]
I am going to close this issue due to lack of activity, feel free to continue.
