### ISSUE TITLE
Interacting ScTCRseq with ScRNAseq

### ISSUE THREAD

**Issue by synatkeamsk** [ncborcherding/scRepertoire#310]
Dear Nick, 

I have single cell RNAseq and ScTCRseq data.  I have done the first round of clustering using Seurat, which contain both T cells, NK/NKT and myeloid cells. I then proceeded to T cell subcluster. From there, when I interact single cell RNAseq with single cell TCRseq, should I use overall seurat clustering (T cells, NK/NKT and myeloid) or just T cell subcluster? I was told by an Bioinformatician that I should interact the overall Seurat clustering (T cells, NK/NKT and myeloid) with ScTCRseq, but not T cell subcluster because some T and myeloid cells can stay together (doublet) and doing so can allow us to remove doublet. I am bit confused and I thought I would like to ask for your suggestion because I used your packages. Hope you could help advise me how to proceed and suggest some materials/code I could use. Thanks for your wonderful work building the package. 

Kind Regards,

Synat

**Comment by ncborcherding** [comment]
Hey Synat,

I think the answer will depend on the situation, but mostly use the clusters that are most relevant to the figure you are making.  For example, if you have subsetted all the T cells, reclustered/define subtypes, and then did the clonal analysis - I think you should use the T-cell-specific clusters. 

Nick
