### ISSUE TITLE
Seurat example object link not working

### ISSUE THREAD

**Issue by ycl6** [ncborcherding/scRepertoire#313]
Hi,

The [Google Drive link](https://drive.google.com/file/d/1_YuRraDyg8UgF3oasjF0-jgPnwox-B24/view) to download the seurat object (`scRep_example_full.rds`) is not working anymore. Is there another way to download the file?

**Comment by ncborcherding** [comment]
A folder got moved - back up now. Thanks for letting me know. 

Nick
