### ISSUE TITLE
How to specify the order of plotting for a list `combined` object of dataframes (samples)?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [ncborcherding/scRepertoire#317]
Hi there, 

Thanks again for a great tool. 

I was wondering how would be best to specify the order of the dataframes contained in the list `combined` object in `scRepertoire`? (Note: each dataframe is a sample)

Even when I had the dataframes within the `combined` list object in the order I want, when plotting the order is not reserved but seem to be a bit random.

Thanks for your help!

**Comment by ncborcherding** [comment]
Hey Quang, 

Could you make a reproducible example with the built-in data set to show me exactly what you are asking? That would help a ton, thanks.

Nick

**Comment by ncborcherding** [comment]
I am going to close this issue due to lack of activity, but happy to discuss more
