### ISSUE TITLE
combineExpression chain argument drops chain

### ISSUE THREAD

**Issue by ncborcherding** [ncborcherding/scRepertoire#319]
Per investigation into #318 -

using **chain** = X for ```combineExpression()``` will drop the secondary chain when adding the clones to the single-cell object. Will need to change that, as it is a loss in overall information to be used downstream.

Nick

**Comment by Qile0317** [comment]
I am looking into it!

**Comment by user-pagh** [comment]
Dear authors. Thank you for scRepetoire!

I'm seeing a pattern whereby certain CTaa values are overwritten as "NA_XXX" in the Seurat object after calling `combineExpression` with chain = "both". However, the alpha-chain information is readily available in both the raw CellRanger contig files and in the output files from calling `combineTCR`. 

Is there a common cause for this? Is it related to the above error? 

Kind regards,
Nikolaj

**Comment by ncborcherding** [comment]
Hey Nikolaj, 

Thanks for reaching out!

Can you provide an example? 

```combineExpression()``` is 1) doing some calculations on frequency of a clone and 2) attaching the data. There shouldn't be any modification in the CTaa, CTnt, CTgene, or CTstrict columns during the process (outside of the above issue with dropping a chain).

**Comment by user-pagh** [comment]
Thank you for your quick reply Nick! 

I likely found the culprit after sleeping on it. The specific barcode from the cellranger contig files with the full-chain information was not available in my preprocessed Seurat object.

The missing information is likely unrelated to combineExpression() and just a consequence of pre-filtering mitochondrial genes and RNA content ect. 

Thank you again,
- NIkolaj

**Comment by ncborcherding** [comment]
Will do more extensive testing of this - but will push to master with tagged update
