### ISSUE TITLE
Cleaning doublet before integrating with T cell subcluster

### ISSUE THREAD

**Issue by synatkeamsk** [ncborcherding/scRepertoire#326]
Hi Nick, 

Sorry for many question recently. I appreciated all the support you have provided to me to make me progress through my analysis. I integrated my ScTCRseq with all Seurat Cluster (T cells, B cell and myeloid cells) and found that some TCR clones are in myeloid cluster (kindly review the image below), I was asked by people in my workplace to remove this contaminated clones (doublet) before integrating with Seurat T cell subcluster. Could you guide me with some R script how to do remove these contaminated clones from myeloid cluster then save combined list of TCR object that I can use to integrate with Seurat T cell subcluster. Hope you understand my question and could guide! 
Do you normally clean these doublet for before Integrating with T cell subcluster or I can just ignore it? 

![Cleaning doublet before integrating with T cell subcluster](https://github.com/ncborcherding/scRepertoire/assets/121846660/9bd94026-857c-4a23-8fec-e35f000ed0b8)

``` 
# Combine contig- list
combined <- combineTCR(contig_list, 
                       samples = c("patient1", "patient2", "patient3", "patient4","patient5",
                                   "patient6", "patient7", "patient8", "patient3"))

# read Seurat obj

seurat.obj<- readRDS("seurat.obj.final.rds")
DimPlot(seurat.obj, label = TRUE) + 
  theme_minimal() +
  NoLegend()
```

![seurat obj](https://github.com/ncborcherding/scRepertoire/assets/121846660/d1df85bd-93ab-4bd0-a353-6f7f89546d6d)

Here are some script I used! 
``` 
# Match barcode !
cell.barcodes <- rownames(seurat.obj[[]])
cell.barcodes <- stringr::str_split(cell.barcodes, "_", simplify = TRUE)[,1] #This is removing the _1 at the end of the barcodes)
cell.barcodes <- paste0(seurat.obj$orig.ident, "_", cell.barcodes) #This is adding the prefix of the orig.ident to the barcodes, assuming that is the sample ids
seurat.obj <- RenameCells(seurat.obj, new.names = cell.barcodes)

# Integration 
integrated.obj <- combineExpression(combined, seurat.obj, 
                            cloneCall = "gene", 
                            group.by = "type", 
                            proportion = FALSE, 
                            cloneTypes = c(Single=1, Small=5, Medium=20, Large=100, Hyperexpanded=500))

#Dimplot         
DimPlot(integrated.obj, group.by = "cloneType") +
  theme_minimal() + 
  theme(plot.title = element_blank()) +
  NoAxes()
```

![Cleaning doublet before integrating with T cell subcluster](https://github.com/ncborcherding/scRepertoire/assets/121846660/928fcede-d801-4cdc-b407-f038fe7d6929)

After removing doublet, I would like to integrate the cleaned combined contig with the following T cell subcluster. 

![T subcluster](https://github.com/ncborcherding/scRepertoire/assets/121846660/24717723-6add-451f-953c-259643c91eef)

Best Regards,

Synat

**Comment by ncborcherding** [comment]
Hey Synat,

It is pretty common to see clonal information in non-lymphocyte clusters and is likely a result of ambient RNA (doublets are also a potential factor). 

There are several methods I have seen in the literature: 
1. Remove clonal information for the cells in non-lymphocyte clusters
2. Maintain the clonal information, but disregard them if you are reclustering/subclusteriing T cell-specific clusters or doing further clonal analysis
3. Incorporate all the clonal information

I think there are pluses and minuses to each, I personally use number 2 as I think that is the most transparent & focused. 

> Could you guide me with some R script how to do remove these contaminated clones from myeloid cluster then save combined list of TCR object that I can use to integrate with Seurat T cell subcluster.

I am not exactly sure what you are asking - you want to remove the myeloid barcodes from the **combined**? Why not just do all the analysis from the Seurat object after filtering for the Seurat T cell subcluster? Alternatively, I think you are not using v2.0, so you can use ```expression2List()``` to re-isolate the clonal information from the sSeurat T cell subcluster?

Hope that helps,
Nick

**Comment by synatkeamsk** [comment]
Hi Nick, 

Thanks for your suggestion. I agreed with you. It is just my interest trying to remove clonal information from non-lymphoid cluster. So I attempted the following code using integrated object of Seurat object (containing myeloid, T and B cell cluster) and ScTCRseq. 

![Cleaning doublet before integrating with T cell subcluster](https://github.com/ncborcherding/scRepertoire/assets/121846660/0d00d87f-cb0e-49e9-b429-6e9a564031eb)

``` 
# Identify the non-lymphoid clusters where you want to remove T cell clones
non_lymphoid_clusters <- c("1", "6", "10", "15", "18", "5", "20")  

# Find the T cell clones within those clusters
t_cell_clones <- integrated.obj@meta.data$cloneType == c("Hyperexpanded", "Large", "Medium", "Single", "Small")

#  Filter out the cells corresponding to T cell clones in the specified clusters
keep_cells <- !(integrated.obj@meta.data$seurat_clusters %in% non_lymphoid_clusters[ t_cell_clones])

# Subset the integrated Seurat object based on the logical vector for cells
filtered_obj <- subset(integrated.obj, cells = keep_cells)

``` 
I could not proceed further of err. I am wondering whether you could some R script to remove

**Comment by ncborcherding** [comment]
Hey Synat, 

That should work - but make sure you put in the methods section the additional removal of clonal information using the cluster cell type. 

The following code should be what you are after: 

```
cell.pos <- which(integrated.obj$seurat_clusters %in% c(1, 6, 10, 15, 18, 5, 20)  
integrated.obj$cloneType[cell.pos] <- NA
```

Thanks,
Nick

**Comment by synatkeamsk** [comment]
Hi Nick, 
in version 1, do we have argument to specify the diversity metrics because the default give me 5. I do not need 5. I have been working with version 1 and I do not wanted to upgrade it for now. 

``` 
clonalDiversity(integrated.obj.T, 
                split.by = "ident", 
                cloneCall = "nt", 
                metrics = c("shannon", "inv.simpson", "norm.entropy")) +
  theme_minimal()

Error in clonalDiversity(integrated.obj.T, split.by = "ident", cloneCall = "nt",  : 
  unused argument (metrics = c("shannon", "inv.simpson", "norm.entropy"))

``` 

Sorry for too many questions. Hope you do not mind me! 

Kind Regards,

synat

**Comment by ncborcherding** [comment]
Hey Synat, 

No there is not a method for selecting just an individual metric for < v2 (hence the addition). You could ```exportTable = TRUE``` in the call and then plot the selected metric using ggplot? 

Nick
