### ISSUE TITLE
loadContigs from AIRR data

### ISSUE THREAD

**Issue by JHYSiu** [ncborcherding/scRepertoire#328]
Hi 

I used to be able to load my AIRR data using the following method from the vignette:

```
#List of data frames example
S1 <- [read.csv](https://rdrr.io/r/utils/read.table.html)("~/Documents/MyExperiment/Sample1/outs/barcode_results.csv")
S2 <- [read.csv](https://rdrr.io/r/utils/read.table.html)("~/Documents/MyExperiment/Sample2/outs/barcode_results.csv")
S3 <- [read.csv](https://rdrr.io/r/utils/read.table.html)("~/Documents/MyExperiment/Sample3/outs/barcode_results.csv")
S4 <- [read.csv](https://rdrr.io/r/utils/read.table.html)("~/Documents/MyExperiment/Sample4/outs/barcode_results.csv")

contig_list <- [list](https://rdrr.io/r/base/list.html)(S1, S2, S3, S4)
contig.list <- [loadContigs](https://www.borch.dev/uploads/screpertoire/reference/loadcontigs)(input = contig.output, 
                           format = "WAT3R")
```

But with this new update (1.12), I can't seem to be able to do that anymore. I get the error "Error in list.files(dir, file.pattern) : invalid 'path' argument".

What's the best way to import AIRR data (coming off of Immcantation)? I've attached an example (but saved it as csv instead for Github purposes). I can't seem to import from the folder directory either where I get "Permission deniedError in file(file, "rt") : cannot open the connection".

[SOMEDONOR_airr_rearrangement - Copy.csv](https://github.com/ncborcherding/scRepertoire/files/14495001/SOMEDONOR_airr_rearrangement.-.Copy.csv)

**Comment by ncborcherding** [comment]
Hey Jacqueline, 

Thanks for reaching out - the broader support for formats can be found in scRepertoire v2.  Which can be installed with: 

```
devtools::install_github("ncborcherding/scRepertoire")
```

It is also up on bioconductor under the devel version (3.19) as v 1.99.x. 

Hope that helps and let me know if you have any other questions.

Nick

**Comment by JHYSiu** [comment]
Thanks!
