### ISSUE TITLE
loadContigs function typos

### ISSUE THREAD

**Issue by JHYSiu** [ncborcherding/scRepertoire#329]
Hi

It looks like there's some typos in the loadContigs function (https://github.com/ncborcherding/scRepertoire/blob/master/R/loadContigs.R) when loading Immcantation data. 

Line 58 `else if("json")`  should probably be `else if (format %in% c("json"))`

Line 232 `df[[i]] <- df[[i]][,c("sequence_id", "locus", "consensus_count",  "v_call", "d_call", "j_call", "c_gene", "cdr3", "cdr3_aa")]` should be `df[[i]] <- df[[i]][,c("sequence_id", "locus", "consensus_count",  "v_call", "d_call", "j_call", "c_call", "cdr3", "cdr3_aa")]`

Line 234 `df[[i]] <- str_split(df[[i]][,"barcode"], "_", simplify = TRUE)[,1]` can be `df[[i]]$barcode <- str_split(df[[i]][,"barcode"], "_", simplify = TRUE)[,1]`

Hopefully those fixes work. I'm using scRepertoire for the first time.

**Comment by ncborcherding** [comment]
Thanks for pointing these out - do you want to make a pull request with the fixes to get your name on the repo? Or else I am happy to make these changes.

Nick

**Comment by JHYSiu** [comment]
I'll do a pull request. Thanks! (sorry trying to multi-task too much)
