### ISSUE TITLE
Combining TCR and BCR

### ISSUE THREAD

**Issue by msaezpalma** [ncborcherding/scRepertoire#331]
Hi!
I'm currently working on TCR and BCR data and when I combine the Expression with the combineExpression function, both datsets are integrated in the Seurat Object metadata with the same name. That makes me not able to differentiate BCR and TCR in columns. I don't know if maybe I just need to add some line to the sunction or if I should continue doing all the analysis separately anthough I'll like to have all the data on one same Seurat Object. 
Thanks a lot in advanced.
Maria

PD: The script I'm using now is this one:
bcr <- combineBCR(bcr_P7, samples = "L",
                  ID = "AV11081", threshold = 0.85)

tcr <- combineTCR(
  tcr_P7,
  samples = "L",
  ID = "AV11081",
  cells = "T-AB",
  removeNA = FALSE,
  removeMulti = FALSE,
  filterMulti = FALSE
)

list.receptors <- c(tcr, bcr)

prova <-  combineExpression(list.receptors, 
                            P7_FNA, 
                            cloneCall="gene",
                            chain = "both",
                            filterNA = FALSE,
                            cloneTypes = c(Rare = 1e-04, Small = 0.001, Medium = 0.01, Large = 0.1, Hyperexpanded = 1),
                            proportion = TRUE)

**Comment by ncborcherding** [comment]
Hey @msaezpalma, 

Thanks for reaching out. 

Could you use clusters to differentiate between TCR and BCR? 

Alternatively, you could add a column to your meta.data using something like: 

```
prova$receptor <- substring(prova$CTaa, 1,2)
````

This would extract the first 2 characters in the CTaa column to use to differentiate. Although that might not work for clones that have NA_XXXX. You might need to play around with it more to get all the info you need. 

Thanks,
Nick

**Comment by ncborcherding** [comment]
Hey Maria, 

Unfortuantely, changing the column names will likely break the functions you want to use. 

In scRepertoire v2 - most visualizations have an parameter called **chain**, which you could use to isolate on TCR or BCRs using "TRB" or "IGH" respectively. 

You can install it with: 

```
devtools::install_github("ncborcherding/scRepertoire")
```
There is a change in a lot of function names - so heads up if you are upgrading. The other issue here is that the 2 graphs you show (now ```clonalOverlay()``` and ```clonalOccupy()```) are utilizing the precalculated variables from ```combineExpression()``` and do not have **chain** argument - so if you wanted those in particular the best way would be to subset your Seurat object into B and T cells. 

Nick
