### ISSUE TITLE
clonalDiversity input error for SCE object

### ISSUE THREAD

**Issue by JHYSiu** [ncborcherding/scRepertoire#332]
Hi 

There appears to be an input error when I try to use `clonalDiversity(sce, cloneCall = "gene")` with a SCE object. 

Error message: Error in `[.data.frame`(meta, , split.by) : undefined columns selected. Any suggestions would be appreciated!

I'm using scRepertoire_2.0.0

**Comment by JHYSiu** [comment]
Similar error for clonalOccupy as well when using SCE object

**Comment by ncborcherding** [comment]
Traveling at the moment so sorry this is on a phone - you'll need to call distinct variables using group.by as there is no standardized identity for SCE. So calls will have to include group.by = "meta.variable". 

Nick

**Comment by JHYSiu** [comment]
Thanks
