### ISSUE TITLE
Visualization Clonotype as number in alluvial plot

### ISSUE THREAD

**Issue by synatkeamsk** [ncborcherding/scRepertoire#333]
Hi Nick, 

Hope you are doing well. In scRepertoire package, I am wondering whether we can visualize the Clonotypes in Alluvial plot as number (Kindly Review the image attached from published paper). Hope you could help! 

Best Regards,

Synat
![TCRseq](https://github.com/ncborcherding/scRepertoire/assets/121846660/1426ffec-792b-472f-b0af-32c233c66e11)

**Comment by ncborcherding** [comment]
Hey Synat - 

Not knowing the publication - my guess is that the authors are subsetting individual clusters and then generating the alluvial plots using clonalCompare() (or compareClonotypes() if you are using an older version). 

Nick
