### ISSUE TITLE
Larger clonotypes showing up as NA

### ISSUE THREAD

**Issue by joglekar-lab** [ncborcherding/scRepertoire#335]
Hi Nick,

Thanks so much for this amazing resource! A big fan!

I have seen this issue a couple of times now, where while using combineExpression() with proportion=FALSE, I get TCR clones with frequencies beyond a certain threshold showing up as cloneType = NA. I used custom boundaries for combineExpression ():

AJ109_vdj_gex_v4 <- combineExpression(AJ109_vdj, AJ109_hash_renamed_v2, cloneCall="aa", proportion=FALSE, cloneType = c(Single = 1, Small = 9, Medium = 100, Large = 1000, Hyperexpanded=10000 ))

I see that the frequency of some of the clonotypes is >100, but the cloneType = NA (see below in the screenshot)

![image](https://github.com/ncborcherding/scRepertoire/assets/62300803/4aa939b9-9b2f-4014-bb9f-4267a0e120d6)

It's happened a couple of times before, at this threshold. Am I doing something wrong? If i use this with proportion=TRUE, it does classify the clonotypes correctly, but i would like to have the absolute numbers. 

This is integrating 4 mouse scRNAseq datasets with cell hashing. 

Thanks!
Alok

**Comment by ncborcherding** [comment]
Hey Alok, 

Thanks for reaching out - this was a previous bug that required users to know the size of the clones before ```combineExpression()```, which was not ideal. The system was updated for scRepertoire v2, which you can download with: 

```
devtools::install_github("ncborcherding/scRepertoire")
```

If you get a chance to install and let me know if the problem persist (or doesn't persist), I'd really appreciate it. 

Thanks,
Nick

**Comment by ncborcherding** [comment]
Closing due to lack of follow-up, feel free to post below.

**Comment by joglekar-lab** [comment]
Hi Nick,
sorry it took a while, but i did reinstall the package (updated to the newer version), and the issue is still there.

I integrated 4 different seurat objects in this project. If i look at one of the objects, there are clonotypes marked as large:
![image](https://github.com/ncborcherding/scRepertoire/assets/62300803/afa7d457-7e5d-46ac-932b-f0f5f3cff042)

It's definitely happening at this line:
slot (all_immune.combined, "meta.data")$cloneType <- factor(slot(all_immune.combined, "meta.data")$cloneType, 
                                                             levels = c("Hyperexpanded (1000 < X <= 10000)", "Large (100 < X <= 999)", 
                                                                        "Medium (9 < X <= 100)", "Small (1 < X <= 9)", 
                                                                        "Single (0 < X <= 1)", NA))

The object before this line has the large clonotypes defined:
![image](https://github.com/ncborcherding/scRepertoire/assets/62300803/af160af3-a168-445a-8bc1-d9fab3c6bd48)

It's going to be something stupid (like a typo), but so far i haven't been able to figure it out. 

THanks!

**Comment by joglekar-lab** [comment]
Ok, so I seemed to have resolved it - I just copied the names from the console into the command, and it seems to have worked. But i didn't notice any changes to the command.

**Comment by ncborcherding** [comment]
Hey Alok,

I have done this so many time before: 

```
slot (all_immune.combined, "meta.data")$cloneType <- factor(slot(all_immune.combined, "meta.data")$cloneType,
levels = c("Hyperexpanded (1000 < X <= 10000)", "Large (100 < X <= 999)",
"Medium (9 < X <= 100)", "Small (1 < X <= 9)",
"Single (0 < X <= 1)", NA))
```

If you are going to order the factors - they need to match exactly. I would make sure that your groupings for ```cloneType``` are matching the levels you enter.

Nick
