### ISSUE TITLE
na.include = FALSE, is not working in clonalOccupy

### ISSUE THREAD

**Issue by mainharryHR** [ncborcherding/scRepertoire#337]
Dear Sir,
Thanks for great package. After downsample, I wanna plot the clonal information for annotated T cell,  I realised that the T cells without TCR information is not plotted no matter how I change the `clonalOccupy( na.include = FALSE or TRUE)`. It seems the NA value is always excluded when plotting or in exported table.

Any strategies to include the number of T cells without TCR information. 

I appreciate for your kind help!

Best,
Harry

`clonalOccupy(
  Object,
  x.axis = "ident",
  label = TRUE,
  facet.by = "Cancer",
  proportion = FALSE,
  na.include = FALSE,
  exportTable = TRUE,
  palette = "inferno"
)`

**Comment by ncborcherding** [comment]
Hey Harry, 

thanks for letting me know - indeed you found a bug. I have just pushed a fix to the dev branch and will get it tested this week before I commit it to the master branch. 

You can install the dev fix using: 

```
devtools::install_github("ncborcherding/scRepertoire@dev")
```

Nick

**Comment by mainharryHR** [comment]
Great! I really appreciate your kind help great "service".  
Have a great day!
Best!

Harry

**Comment by mainharryHR** [comment]
Thank you for working on that. Finally I had chanced to test again. There are several new problems for the updated version. Please see attached pics for difference:  Here comes the summary:
1:  NA value is not assigned to each cell types.
2; Many cell types and clonal frequency are lost and not showing properly. 

I appreciate your kind help!

Best,
Harry

<img width="658" alt="Screenshot 2024-03-31 at 12 50 23" src="https://github.com/ncborcherding/scRepertoire/assets/164251298/53a3504b-b365-45f9-b6a7-e2c59a412f75">

**Comment by ncborcherding** [comment]
This should be fixed now in the new version available in the master branch. Thanks again for letting me know and your follow up.

**Comment by EeSsSs** [comment]
I just re-installed the latest version of the package (2.0.5 with R version 4.4.1) and for me the NA values are also not showing up in the clonaloccupy plot, while they are there when I just make a dimplot with clonesize

**Comment by ncborcherding** [comment]
Thanks for reaching out.

Please make a [reproducible example](http://adv-r.had.co.nz/Reproducibility.html) for this issue so I know what you are experiencing. 

Nick

**Comment by EeSsSs** [comment]
FSP_TCR_combined_all <- combineTCR(FSP_TCR, samples='FSP', removeNA=F, removeMulti = F, filterMulti = T)
FSP_TCR_combined_all$FSP$barcode <- str_remove(FSP_TCR_combined_all$FSP$barcode, 'FSP_')
FSP_TCR_combined_all$FSP <- cbind(FSP_TCR_combined_all$FSP, 
                                FSP_filtered@meta.data[match(FSP_TCR_combined_all$FSP$barcode,
                                                             rownames(FSP_filtered@meta.data)),
                                                       'Donor'])
colnames(FSP_TCR_combined_all$FSP)[13] <- 'Donor'
FSP_filtered_TCR <- combineExpression(FSP_TCR_combined_all,FSP_filtered,group.by =  'Donor', 
                                      cloneCall = 'aa', chain = 'both',
                                      proportion = F,
                                      cloneSize=c(Single=1, Rare=2, Small=5, Medium=10, Expanded=50))
DimPlot(FSP_filtered_TCR, group.by = "cloneSize", pt.size = .4) 
clonalOccupy(FSP_filtered_TCR, x.axis='RNA_snn_res.0.4', proportion = T, na.include=T, label=T)

FSP_filtered@meta.data <- dput(FSP_filtered@meta.data[1:20,])
structure(list(orig.ident = structure(c(1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L), levels = "FSP", class = "factor"), 
    nCount_RNA = c(7765, 2009, 6849, 2095, 7366, 7067, 6345, 
    1861, 5330, 4832, 5518, 3334, 4840, 3250, 5663, 11043, 8738, 
    5711, 10586, 6900), nFeature_RNA = c(2640L, 1024L, 2487L, 
    1167L, 2249L, 2846L, 2200L, 987L, 2161L, 1736L, 2196L, 1329L, 
    1809L, 1402L, 2042L, 3585L, 2820L, 2207L, 3199L, 2374L), 
    nCount_ADT = c(1700, 883, 1957, 1046, 1866, 2212, 1922, 235, 
    1647, 2586, 1355, 736, 1178, 373, 2590, 1593, 1307, 959, 
    2104, 1417), nFeature_ADT = c(10L, 10L, 10L, 10L, 10L, 10L, 
    10L, 10L, 10L, 10L, 10L, 10L, 10L, 10L, 10L, 10L, 10L, 10L, 
    10L, 10L), percent.mt = c(2.17643271088216, 3.18566450970632, 
    1.53307052124398, 4.43914081145585, 1.09964702688026, 2.51874911560775, 
    3.16784869976359, 1.45083288554541, 1.03189493433396, 0.227649006622517, 
    1.30482058716926, 1.9496100779844, 1.17768595041322, 1.53846153846154, 
    3.23150273706516, 1.59376980892873, 0.858319981689174, 1.34827525827351, 
    1.2469299074249, 1.59420289855072), percent.ribo = c(33.650998068255, 
    30.9109009457442, 32.5886990801577, 22.1957040572792, 40.9448818897638, 
    22.824395075704, 32.2773837667455, 29.8226759806556, 26.1350844277674, 
    38.5140728476821, 29.0685030808264, 37.4025194961008, 38.1818181818182, 
    31.0153846153846, 35.2993113190888, 28.226025536539, 37.1023117418174, 
    29.0316932236036, 35.4713772907614, 33.7826086956522), S.Score = c(-0.0740353956283032, 
    -0.0723471837596801, -0.0708561234725496, -0.0103838028239838, 
    -0.0974760753166953, 0.0387584337777187, -0.0703057701616523, 
    -0.0293300153363912, -0.0947863191282281, -0.00916448458189195, 
    -0.0145284897259919, -0.043216755714151, 0.0118163174494839, 
    -0.0928201090587158, 0.0522764914747454, 0.092645791529207, 
    -0.0659372809781483, 0.00663062497793063, -0.0335308420124335, 
    -0.0279848478020128), G2M.Score = c(-0.132691539293379, -0.101102980340982, 
    -0.116213017576823, -0.0680104276129055, -0.0651503755810307, 
    1.04523903163742, -0.124250324768246, -0.0819383687416872, 
    -0.0663687707109106, -0.0652238825720866, -0.0822126544282594, 
    -0.0881114567087572, -0.0179395862439813, -0.00219514374548674, 
    0.0284525473829916, -0.0312508504587002, -0.0702732590397545, 
    0.0130257391482406, -0.0299327493742494, -0.0781575065481768
    ), Phase = c("G1", "G1", "G1", "G1", "G1", "G2M", "G1", "G1", 
    "G1", "G1", "G1", "G1", "S", "G1", "S", "S", "G1", "G2M", 
    "G1", "G1"), donor_id = c("donor5", "unassigned", "donor5", 
    "donor3", "donor2", "donor4", "donor5", "doublet", "doublet", 
    "donor4", "donor2", "donor2", "donor1", "doublet", "donor0", 
    NA, "donor4", "donor1", "doublet", "donor0"), hash.ID = structure(c(2L, 
    3L, 2L, 4L, 5L, 1L, 2L, 3L, 2L, 6L, 5L, 5L, 7L, 3L, 1L, NA, 
    6L, 7L, 1L, 8L), levels = c("Doublet", "L3", "Negative", 
    "L4", "L5", "L2", "L1", "L6"), class = "factor"), organ = c("Spleen", 
    "Spleen", "Spleen", "Spleen", "Spleen", "Spleen", "Spleen", 
    "Spleen", "Spleen", "Spleen", "Spleen", "Spleen", "Spleen", 
    "Spleen", "Spleen", NA, "Spleen", "Spleen", "Spleen", "Spleen"
    ), subject = structure(c(6L, 7L, 6L, 4L, 3L, 5L, 6L, 8L, 
    8L, 5L, 3L, 3L, 2L, 8L, 1L, NA, 5L, 2L, 8L, 1L), levels = c("d009_18", 
    "d007_21", "d010_21", "d008_23", "d004_18", "d006_21", "unassigned", 
    "doublet"), class = "factor"), gestation = structure(c(2L, 
    4L, 2L, 3L, 2L, 1L, 2L, 5L, 5L, 1L, 2L, 2L, 2L, 5L, 1L, NA, 
    1L, 2L, 5L, 1L), levels = c("18", "21", "23", "unassigned", 
    "doublet"), class = "factor"), RNA_snn_res.0.2 = structure(c(2L, 
    2L, 1L, 3L, 2L, 6L, 1L, 2L, 3L, 2L, 1L, 1L, 1L, 2L, 2L, 2L, 
    2L, 2L, 4L, 2L), levels = c("0", "1", "2", "3", "4", "5", 
    "6"), class = "factor"), RNA_snn_res.0.3 = structure(c(2L, 
    2L, 1L, 3L, 2L, 5L, 1L, 2L, 3L, 2L, 6L, 1L, 1L, 2L, 2L, 2L, 
    2L, 2L, 4L, 2L), levels = c("0", "1", "2", "3", "4", "5", 
    "6", "7", "8"), class = "factor"), RNA_snn_res.0.4 = structure(c(1L, 
    1L, 2L, 5L, 1L, 8L, 2L, 1L, 5L, 1L, 3L, 3L, 2L, 1L, 1L, 1L, 
    1L, 1L, 4L, 1L), levels = c("0", "1", "2", "3", "4", "5", 
    "6", "7", "8", "9"), class = "factor"), RNA_snn_res.0.5 = structure(c(1L, 
    1L, 2L, 3L, 1L, 9L, 2L, 1L, 3L, 1L, 7L, 5L, 2L, 1L, 1L, 1L, 
    1L, 1L, 4L, 1L), levels = c("0", "1", "2", "3", "4", "5", 
    "6", "7", "8", "9", "10"), class = "factor"), RNA_snn_res.0.6 = structure(c(2L, 
    2L, 1L, 3L, 2L, 11L, 1L, 2L, 3L, 2L, 7L, 6L, 1L, 2L, 2L, 
    2L, 2L, 2L, 4L, 2L), levels = c("0", "1", "2", "3", "4", 
    "5", "6", "7", "8", "9", "10", "11", "12", "13", "14"), class = "factor"), 
    RNA_snn_res.0.7 = structure(c(2L, 2L, 1L, 3L, 2L, 12L, 1L, 
    2L, 3L, 2L, 7L, 6L, 1L, 2L, 2L, 2L, 2L, 2L, 4L, 2L), levels = c("0", 
    "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", 
    "12", "13", "14"), class = "factor"), RNA_snn_res.0.8 = structure(c(2L, 
    2L, 1L, 3L, 2L, 12L, 1L, 2L, 3L, 2L, 7L, 5L, 1L, 2L, 2L, 
    2L, 2L, 2L, 4L, 2L), levels = c("0", "1", "2", "3", "4", 
    "5", "6", "7", "8", "9", "10", "11", "12", "13", "14"), class = "factor"), 
    RNA_snn_res.0.9 = structure(c(2L, 2L, 1L, 3L, 13L, 12L, 1L, 
    2L, 3L, 5L, 7L, 6L, 1L, 2L, 2L, 2L, 2L, 2L, 4L, 2L), levels = c("0", 
    "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", 
    "12", "13", "14", "15"), class = "factor"), RNA_snn_res.1 = structure(c(1L, 
    1L, 3L, 4L, 14L, 12L, 3L, 1L, 4L, 1L, 8L, 6L, 6L, 1L, 1L, 
    1L, 1L, 1L, 5L, 1L), levels = c("0", "1", "2", "3", "4", 
    "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", 
    "16"), class = "factor"), seurat_clusters = structure(c(1L, 
    1L, 3L, 4L, 14L, 12L, 3L, 1L, 4L, 1L, 8L, 6L, 6L, 1L, 1L, 
    1L, 1L, 1L, 5L, 1L), levels = c("0", "1", "2", "3", "4", 
    "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", 
    "16"), class = "factor"), pANN_0.25_0.2_875 = c(0.326229939489608, 
    0.233096553538543, 0.344646145751118, 0.203630623520126, 
    0.275190739279137, 0.366482504604052, 0.322283609576427, 
    0.123914759273875, 0.398316232570376, 0.226256248355696, 
    0.259142330965535, 0.152065245987898, 0.183635885293344, 
    0.242304656669298, 0.24388318863457, 0.449092344119968, 0.317811102341489, 
    0.283346487766377, 0.425151275980005, 0.318863456985004), 
    DF.classifications_0.25_0.2_875 = c("Singlet", "Singlet", 
    "Singlet", "Singlet", "Singlet", "Singlet", "Singlet", "Singlet", 
    "Singlet", "Singlet", "Singlet", "Singlet", "Singlet", "Singlet", 
    "Singlet", "Doublet", "Singlet", "Singlet", "Singlet", "Singlet"
    ), CD4_ADT = c(1.11683981685083, 0.791873072764484, 2.47826007463373, 
    1.01754452050554, 0.268687942247982, 2.51245908144789, 2.23655134822189, 
    0.883254029269942, 2.04206478402807, 0.238104257647166, 2.23233049047037, 
    2.18424533301505, 2.27893712196837, 0.5680916527347, 0.262672852328498, 
    0.214626440674391, 0.196395257941802, 1.15873680676986, 2.69636978044339, 
    0.341164395850222), CD8_ADT = c(1.57170516811142, 1.36808977008972, 
    0.327721232690515, 1.81022722043909, 2.51062788894182, 0.959155588755894, 
    0.661968538804572, 1.14946748947059, 1.85134669493369, 2.24492440505505, 
    0.838559978510677, 0.904387237717268, 0.285197893276344, 
    1.57370275136779, 2.22728900356946, 1.98980999642868, 2.64051844293718, 
    1.78173409578312, 0.419466875996471, 2.05425822773632), CD4CD8_ADT_double = c(FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE), Donor = structure(c(2L, 6L, 2L, 5L, 7L, 3L, 2L, 8L, 
    8L, 3L, 7L, 7L, 4L, 8L, 1L, NA, 3L, 4L, 8L, 1L), levels = c("d004", 
    "d008", "d007", "d006", "d009", "unassigned", "d010", "doublet", 
    "donor4", "d008_23", "donor5", "donor0", "donor3", "donor2"
    ), class = "factor")), row.names = c("AAACCTGAGAGACTTA-1", 
"AAACCTGAGAGTAATC-1", "AAACCTGAGATCACGG-1", "AAACCTGAGATCGATA-1", 
"AAACCTGAGCACCGCT-1", "AAACCTGAGGACGAAA-1", "AAACCTGAGTGTACGG-1", 
"AAACCTGCACAGTCGC-1", "AAACCTGCACGAAATA-1", "AAACCTGCACTTCTGC-1", 
"AAACCTGCAGCCACCA-1", "AAACCTGCAGGGAGAG-1", "AAACCTGCAGGTGGAT-1", 
"AAACCTGCATGGTCTA-1", "AAACCTGGTACACCGC-1", "AAACCTGGTACAGTTC-1", 
"AAACCTGGTAGCACGA-1", "AAACCTGGTATAGGTA-1", "AAACCTGGTCTAAAGA-1", 
"AAACCTGGTTCCGTCT-1"), class = "data.frame")
