### ISSUE TITLE
using TCR data vs. Seurat + TCR

### ISSUE THREAD

**Issue by Sogand65** [ncborcherding/scRepertoire#339]
Hi Mr. Borcherding!

Thanks for the very nice and useful package you and your team provided!
I have a question regarding adding the TCR data to the Seurat object, I kind of compared the two approach where I do some analysis with the TCR data (without Seurat object) and compared it with integrated object (Seurat + TCR). I do not know why the two approaches are different slightly! Below you can find my code. Because my Seurat object is already integrated from 12 samples, there are sample names on the cell already. The only different is the cells has "_GEX" while the TCR data cell names contained "_TCR" so I decided to change the "_TCR" to "_GEX" (though the latter might be a bit meaningless here!)
library(Seurat)
library(scRepertoire)
library(ggplot2)
cbmc <- LoadSeuratRds("~/../annot_indv/cbmc_integAnno.RDS")
% Making contig_list

inPath <- "~/.../Result/BCR-TCR/" 
patTCR <- list.files(path = inPath, pattern = "_TCR$")
contig_list_TCR <- list()
read_contig_file <- function(file_name, path_prefix) {
  full_path <- paste0(path_prefix, file_name, "/outs/filtered_contig_annotations.csv")
  read.csv(full_path)
  }

contig_list_TCR <- lapply(patTCR, read_contig_file, path_prefix = inPath)
names(contig_list_TCR) <- patTCR
TCR <- combineTCR(contig_list_TCR, samples = patTCR, removeNA = FALSE, 
                  removeMulti = FALSE, filterMulti = FALSE)
% Here I made names compatible:
TCR <- lapply(TCR, function(x) {
  x$barcode <- gsub("_TCR", "_GEX", x$barcode)
  return(x)
})
scRep_tcr <- combineExpression(TCR, cbmc, cloneCall="gene", proportion = TRUE)

% Now when I for instance doing an example analysis once using scRep_tcr object and once using TCR they have slightly different outputs!
# clonalQuant
p1 <- clonalQuant(scRep_tcr, cloneCall="strict", chain = "both", scale = T, 
            group.by = "orig.ident",exportTable = T)
p2 <- clonalQuant(TCR, cloneCall="strict", chain = "both", scale = T, 
                  exportTable = T)
p1
   contigs    values total orig.ident   scaled
1      127 MG147_GEX   142  MG147_GEX 89.43662
2      596 MG148_GEX   676  MG148_GEX 88.16568
3      256 MG149_GEX   261  MG149_GEX 98.08429
4      504 MG150_GEX   511  MG150_GEX 98.63014
5       93 MG152_GEX   102  MG152_GEX 91.17647
6      432 MG153_GEX   571  MG153_GEX 75.65674
7       70 MG154_GEX    79  MG154_GEX 88.60759
8      481 MG155_GEX   623  MG155_GEX 77.20706
9      160 MG156_GEX   190  MG156_GEX 84.21053
10     815 MG157_GEX  1155  MG157_GEX 70.56277
11      48 MG158_GEX    50  MG158_GEX 96.00000
12     113 MG159_GEX   116  MG159_GEX 97.41379
p2
   contigs    values total   scaled
1      188 MG147_TCR   208 90.38462
2      793 MG148_TCR   903 87.81838
3      320 MG149_TCR   335 95.52239
4      598 MG150_TCR   608 98.35526
5      112 MG152_TCR   129 86.82171
6      512 MG153_TCR   674 75.96439
7       96 MG154_TCR   113 84.95575
8      738 MG155_TCR  1036 71.23552
9      202 MG156_TCR   240 84.16667
10     871 MG157_TCR  1256 69.34713
11      69 MG158_TCR    72 95.83333
12     140 MG159_TCR   143 97.90210                  
                  
I really appreciate any suggestions or thoughts on why this can happen and which version might be preciser? or might be something wrong in the way I incorporated the Seurat and BCR objects? 

Thanks a lot for your help,

**Comment by ncborcherding** [comment]
Hey @Sogand65, 

Excellent run down of the issue - thanks so much. This is an important point so I am glad it can be a reference. 

The difference in numbers comes from partially overlapping barcodes in the Seurat object vs contigs. At a baseline, cells recovered for GEX and TCR/BCR overlap is about 85-95%. So attaching the clonal information, you should see a drop off in clones. There can be additional discrepancies based on QC filtering that may change the numbers as well. Looking at your numbers, it seems consistent with that and no overall bias by sample.

In terms of the incoporation of BCR data, you can use ```combineExpression()``` at the same time for both BCR and TCR:

```
TCR <- [combineTCR](https://www.borch.dev/uploads/screpertoire/reference/combinetcr)(...)
BCR <- [combineBCR](https://www.borch.dev/uploads/screpertoire/reference/combinebcr)(...)
list.receptors <- [c](https://rdrr.io/r/base/c.html)(TCR, BCR)


seurat <- combineExpression(list.receptors, 
                            seurat, 
                            cloneCall="gene", 
                            proportion = TRUE)
```

Hope that helps,
Nick

**Comment by Sogand65** [comment]
> Hey @Sogand65,
> 
> Excellent run down of the issue - thanks so much. This is an important point so I am glad it can be a reference.
> 
> The difference in numbers comes from partially overlapping barcodes in the Seurat object vs contigs. At a baseline, cells recovered for GEX and TCR/BCR overlap is about 85-95%. So attaching the clonal information, you should see a drop off in clones. There can be additional discrepancies based on QC filtering that may change the numbers as well. Looking at your numbers, it seems consistent with that and no overall bias by sample.
> 
> In terms of the incoporation of BCR data, you can use `combineExpression()` at the same time for both BCR and TCR:
> 
> ```
> TCR <- [combineTCR](https://www.borch.dev/uploads/screpertoire/reference/combinetcr)(...)
> BCR <- [combineBCR](https://www.borch.dev/uploads/screpertoire/reference/combinebcr)(...)
> list.receptors <- [c](https://rdrr.io/r/base/c.html)(TCR, BCR)
> 
> 
> seurat <- combineExpression(list.receptors, 
>                             seurat, 
>                             cloneCall="gene", 
>                             proportion = TRUE)
> ```
> 
> Hope that helps, Nick

Hi @ncborcherding 
Thanks, So much for the clarifications, that was very helpful. Yes I will incorporate both. 

Best,
Sogand

**Comment by Sogand65** [comment]
Hi @ncborcherding

I tried to incorporate BCR TCR in my Seurat object and did it successfully, it might be a stupid question since I am a beginner in BCR/TCR analysis but I could not find how to specify the analysis that I wanna perform on TCR or BCR, separately. I might have missed it in the vignette so I appreciate your help very much.  so in code below if I want to perform a dimPlot or a clonalQuant() it gives me kind of mixed of both data (BCR, TCR). 
...
list.receptors <- c(TCR, BCR)
scRep <- combineExpression(list.receptors, cbmc, cloneCall="gene", 
                                   proportion = TRUE)
p1 <- clonalQuant(scRep, cloneCall="strict", chain = "both", scale = T, 
            group.by = "orig.ident")
colorblind_vector <- hcl.colors(n=7, palette = "inferno", fixup = TRUE)
p2 <- DimPlot(scRep, group.by = "cloneSize", pt.size = 1.25) +
  scale_color_manual(values=rev(colorblind_vector[c(1,3,5,7)]))

I also could not see any column specific to BCR or TCR in the Seurat object.

Thanks for your help.
Sogand

**Comment by ncborcherding** [comment]
Hey Sogand, 

I have gone back and forth on this topic - users have wanted things incorporated into the same analysis flow and others (like yourself) want them separated. For now, there are 2 options:

1. Use the **chain** parameter when visualizing clones - this will reduce the clone to a single chain, but will filter out any non-matching chain: 
```clonalQuant(...,chain = "TRB")```
2. Use ```subset()``` to only look at T or B clusters at a time.

Sorry there is not a better solution, but I am open to suggestions. One thing about making unique column for BCR vs TCR clonal information is that would break a lot of the visualization functions. 

Thanks,
Nick

**Comment by Sogand65** [comment]
Hi Nick,

Thanks for your prompt replies. I think the subsetting is the best way. But what if the chain argument could take two arguments like in case TCR c(“TRA”, “TRB”) or in case BCR c(“IGH”, “IGL”). However I understand my suggestion might not be easy to apply in terms of such complicated application. 

I appreciate your helps and efforts.
Best,
Sogand
