### ISSUE TITLE
Inconsistence in clonal sharing between chordDiagram and clonalNetwork visualizations?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [ncborcherding/scRepertoire#342]
Dear Nick, 

Thanks again for the great tool. 

I wonder if you might be able to help me find source of differences between these 2 visualisations in terms of whether there was indeed sharing? 

`clonalNetworks` shows sharing with weights computed (below). BTW, is there a way to export a table that essentially merge the info of `exportTable` and `exportClones`, because atm, they show useful info, but one cannot tell whether a clone in `exportClones` is shared between which `to`-`from`, and from `exportTable`, one cannot tell whether which clone was of a particular weight.

```
clonalNetwork(CD8_VDJ_proporTbyVdj_donor_ID, reduction = "umap", group.by = "donor_ID", cloneCall = "aa", filter.clones = NULL, filter.identity = NULL, chain="both", exportTable = F, exportClones = F)
```
<img width="465" alt="Screenshot 2024-04-02 at 13 14 40" src="https://github.com/ncborcherding/scRepertoire/assets/62179082/2f03fe4a-3b14-4e05-b56d-96ead16d3569">

But, in chordDiagram, there was not any sharing:

```
getCirclize(CD8_VDJ_proporTbyVdj_donor_ID, group.by = "donor_ID")
```

<img width="304" alt="Screenshot 2024-04-02 at 13 15 28" src="https://github.com/ncborcherding/scRepertoire/assets/62179082/dd289262-1e6d-4f84-9ab9-a089a18fb6fa">

**Comment by ncborcherding** [comment]
Hey Quang, 

Hard to tell from the example - but my guess is you are using different cloneCalls - default is CTstrict, whereas you are explicitly calling "aa" in ```clonalNetwork()```.

Nick

**Comment by denvercal1234GitHub** [comment]
Hi, Nick, 

Unfortunately, `clonalNetwork(cloneCall = "CTstrict")` which does show sharing

```
clonalNetwork(CD8_VDJ_proporTbyVdj_donor_ID, reduction = "umap", group.by = "HIV_ID", cloneCall = "CTstrict", filter.clones = NULL, filter.identity = NULL, chain="both", exportTable = T, exportClones = F)
```

<img width="166" alt="Screenshot 2024-04-02 at 13 36 44" src="https://github.com/ncborcherding/scRepertoire/assets/62179082/0d36a3aa-921e-4dfc-8761-301f0bd7e38a">

Now, with CTstrict in getCirculize, it still does not show links:

```
getCirclize(CD8_VDJ_proporTbyVdj_donor_ID, group.by = "HIV_ID", cloneCall = "CTstrict")
```

<img width="300" alt="Screenshot 2024-04-02 at 13 41 30" src="https://github.com/ncborcherding/scRepertoire/assets/62179082/56f17f12-abe2-41de-a1da-2682c50c210b">

**Comment by ncborcherding** [comment]
Hey Quang, 

Can you make a reproducible example of your issue? If you are worried about data privacy, please use the built in data for scRepertoire. 

Thanks,
Nick

**Comment by denvercal1234GitHub** [comment]
Hi, Nick, sent it to you via your gmail. I hope that is ok. Thank you for your help.

**Comment by ncborcherding** [comment]
Hey Quang, 

There are several things happening here that are leading to the difference you are observing and is actually the underlying reason ```clonalNetwork()``` was written. 

```getCircilize()``` is aggregating clones on the group.by level, while clonalNetwork is calculating the values at the individual clone level. There are different assumptions by doing that and that is the underlying cause of the difference you are observing. Issues #77 and #92 (which I think is your issue, so we previously discussed this). 

Not a bug per say, but maybe a place for future enhancement.
