### ISSUE TITLE
Order Clone Group and reduce font size inside heatmap of clonalHomeostasis and clonalOverlap

### ISSUE THREAD

**Issue by synatkeamsk** [ncborcherding/scRepertoire#344]
Hi Nick, 

Hope you are well. Regarding ```clonalHomeostasis```, I was asked by my PI to order the Clonal Group starting from bottom from Rare, Small, Medium, Large, Hyperexpanded.. 

I tried to access the combined object list using sth like the fellowing, but I could not get to Clonal Group variable (did not see it). 

``` 
view(combined@)
clone<- clonalHomeostasis(combined, 
                  cloneCall = "gene") + 
  theme_minimal() + 
   theme(axis.text.x = element_text(angle=90,hjust=0.95,vjust=0.2, face = "bold", size = 13), 
         axis.text.y = element_text(face = "bold", size = 13), 
         axis.title = element_text(face = "bold", size = 15),
         legend.text = element_text(size= 12, face = "bold"), 
         legend.title = element_text(size= 13, face = "bold")) + 
  labs(x= "Patients")
``` 
![homeostatasis](https://github.com/ncborcherding/scRepertoire/assets/121846660/43a01a02-03d0-459f-aa6e-e768d436216c)

Could you help with some script to reorder the legend. 

# Another question regarding ```clonalOverlap``` 
Is there a way to reduce the font size inside the heatmap because it was a bit crowded with my data (attached) and hard to see it. 
I could not find any arguments inside the function to reduce font size. 

```
clonalOverlap(integrated.obj.T, 
              cloneCall = "aa", 
              method = "overlap") + 
  theme_minimal() + 
 theme(axis.text.x = element_text(angle=90,hjust=0.95,vjust=0.2, face = "bold", size = 13), 
         axis.text.y = element_text(face = "bold", size = 13), 
         axis.title = element_text(face = "bold", size = 15),
         legend.title = element_text(size= 12, face = "bold"), 
         legend.text = element_text(size= 12, face = "bold"),
         legend.position = "right") + 
  labs(x= "Patients", y= "patients")
``` 

![heatmap](https://github.com/ncborcherding/scRepertoire/assets/121846660/0462886f-72b2-4cfa-9f4c-a9ce5ed6cc52)

Thanks for your help so far!

Best Regards,

Synat

Kind Regards,

Synat

**Comment by ncborcherding** [comment]
Hey Synat, 

Thanks for the well-formated question. This mostly can be address with a little bit of refactoring using ggplot:

# Issue 1:
You can try to add a new layer with ```scale_fill_manual()``` using **breaks** to assign the specifc order. You will have to set the colors again and maybe modify the labels. 

```
clonalHomeostasis(combined.TCR, 
                  cloneCall = "gene") + 
  scale_fill_manual(values = rev(scRepertoire:::.colorizer(n=5)), breaks=c("Hyperexpanded (0.1 < X <= 1)", "Large (0.01 < X <= 0.1)", "Medium (0.001 < X <= 0.01)", "Small (1e-04 < X <= 0.001)", "Rare (0 < X <= 1e-04)")) + 
  lab(fill = "Clonal Groups")
```
<img width="693" alt="Screenshot 2024-04-03 at 1 17 07 PM" src="https://github.com/ncborcherding/scRepertoire/assets/22754118/3d681beb-5edd-453f-9cb4-e26194e321aa">

# Issue 2:

You can save the plot larger or you could somewhat break apart the function itself to call the ggplot itelslf:

```
df <- clonalOverlap(combined.TCR, 
              cloneCall = "strict", 
              method = "raw", 
              exportTable = TRUE) 
mat_melt <- suppressMessages(reshape2::melt(as.matrix(df)))
mean_value <- mean(na.omit(mat_melt[,"value"]))
    
plot <- ggplot(mat_melt, aes(x=Var1, y=Var2, fill=value)) +
                geom_tile() + 
                geom_tile(data = mat_melt[!is.na(mat_melt[,"value"]),], 
                          fill = NA, 
                          lwd= 0.25, 
                          color = "black") +
                geom_text(aes(label = round(value, digits = 3), 
                              color = ifelse(value <= mean_value,
                                             "white", "black")), 
                          na.rm = TRUE, 
                          size = 2) + #Modify here for different sizes
                scale_fill_gradientn(colors = scRepertoire:::.colorizer(n=7), na.value = "white") +
                scale_color_identity() +
                theme_classic() + 
                theme(axis.title = element_blank())
```
<img width="691" alt="Screenshot 2024-04-03 at 1 16 12 PM" src="https://github.com/ncborcherding/scRepertoire/assets/22754118/c44c18aa-11ed-45f2-b882-e42718a07153">

Hope that helps and let me know if you have any other questions. 

Nick
