### ISSUE TITLE
Is there another way to perform the old functionality from the Deprecated expression2list()?

### ISSUE THREAD

**Issue by Eduard278** [ncborcherding/scRepertoire#345]
Hello,

First of all thank you for all your work on this amazing package. I was wondering if there is an alternative method to perform expression2list() that I am missing, I was unable to figure out how to do this now in version 2.0.0 since this function has been deprecated. It it sometimes of course very useful to filter the seurat object and then extract relevant VDJ data for analyses such as clonalOverlap().

Thank you!
Eduard

**Comment by ncborcherding** [comment]
Hey Eduard, 

I think that is a fair point and thanks for reaching out. 

```expression2list()``` deprecation was more for my sanity as the number of repeated emails/github issues that were confused by the functions existence was quite a bit. I just wanted to streamline things with v2.

It is still present though (just not exported) - so you can access it via the triple ::: and it's new name ```.expression2List()```.

```
scRepertoire:::.expression2List()
```

Nick
