### ISSUE TITLE
Cluster with same CTnt sequence length using combineBCR

### ISSUE THREAD

**Issue by zhanzmr** [ncborcherding/scRepertoire#346]
Hi, Thank you for this great package! I just have a question on the sequence length in defining the cluster ("CTstrict"). When I run combineBCR with default "threshold = 0.85", then the sequence "CTnt" are all have the same length for each "CTstrict" cluster. But when I change the threshold to 0.75. then for each output "CTstrict" cluster, the "CTnt" length are different. 

Just wondering is there any reason this happened? For CTstrict cluster, should the "CTnt" need to be grouped by same length first before calculate the distance? Thank you so much for your help! 
Ray.

**Comment by ncborcherding** [comment]
Hey Ray, 

Thanks for the question - the threshold is the normalized edit distance between 2 sequences using the levenshtein distance (not hamming distance), which allows for sequences of different lengths. By decreasing the threshold, you are allowing more sequences to be called as related. We have found 0.85-0.9 to be pretty decent. 

Nick
