### ISSUE TITLE
Finding expanded clone to relevant cluster after integration

### ISSUE THREAD

**Issue by synatkeamsk** [ncborcherding/scRepertoire#347]
Hi Nick, 

Apologies for many questions recently and understand you are busy, but if you could help address, that would be great. my PI really like the package, but there is some information we need to extract, which I am not sure. 

I have integrated ScRNAseq and ScTCRseq and used the integrated object to to run ```clonalScatter``` using the following script and got the plot (attached). 
``` 
clonalScatter(integrated.obj.T, 
              cloneCall ="gene", 
              x.axis = "patient_1_time1", 
              y.axis = "patient_1_time2",
              dot.size = "total",
              graph = "proportion",
               group.by = "orig.ident", 
              exportTable = TRUE)
``` 
![dual expanded clones](https://github.com/ncborcherding/scRepertoire/assets/121846660/6b22898c-af25-4a1a-bac7-e252cb2f5710)

In this scattered plot, I have circled clones in red that are dual expanded and had high expansion. My goal is to locate whether these specific clone are derived from what specific cluster? I used export table and I could not find any cluster information in the table (attached image). Not sure if you could help to address it? How do I know know at least whether they are CD4 or CD8 or if we could match them to their specific cluster, that would be fantastic since we have already integrated? 

![table](https://github.com/ncborcherding/scRepertoire/assets/121846660/410ac7ca-d893-4849-b57c-b4d30fac474b)

Thanks for wonderful work on this package. We all like it, but I am still learning to leverage the full potential of your packages.

Kind Regards,

synat

**Comment by ncborcherding** [comment]
Hey Synat, 

I can understand wanting more in-depth analysis - there are 2 more straight forward options: 

1. Subset your Seurat object before using ```clonalScatter()```
2. Use the exported table and the meta data to assign CD4 or CD8 (or mixed) status by the CTgene column in the meta data

As much as I would like to help more, it is not sustainable for me to write bespoke code for every user. So for these questions related to specific use cases, I have to start pointing the direction and having users do it more. Again apologies - if you need more specialized help and want to make a more formal collaboration, you can [email](ncborch@gmail.com) me.

Nick
