### ISSUE TITLE
Define the color for each colonal size in Dimplot

### ISSUE THREAD

**Issue by mainharryHR** [ncborcherding/scRepertoire#349]
Dear Nick,

Please see the following examples, I am trying to use the same color for the medium clonal size based on the following code, But each sample still plots different color for medium clonal size. Any input will be apprecaited?  

Thank you very much!

`colorblind_vector <- hcl.colors(n=7, palette = "inferno", fixup = TRUE)
DimPlot(SampleA, reduction = "harmony_UMAP",  group.by = "cloneSize") +
    scale_color_manual(values=rev(colorblind_vector[c("Hyperexpanded" = 1, "Large"=3, "Medium"=4, "Small"=5, "Single"=6, "NA"=7)])) `
![Screenshot 2024-04-07 at 14 05 49](https://github.com/ncborcherding/scRepertoire/assets/164251298/97470171-1a58-4bbc-b67b-2f73bf57ce67)

`DimPlot(SampleB, reduction = "harmony_UMAP",  group.by = "cloneSize") +
    scale_color_manual(values=rev(colorblind_vector[c("Hyperexpanded" = 1, "Large"=3, "Medium"=4, "Small"=5, "Single"=6, "NA"=7)])) `

![Screenshot 2024-04-07 at 14 05 55](https://github.com/ncborcherding/scRepertoire/assets/164251298/af9634eb-a882-4e8d-9911-f3b6a339fd79)

**Comment by ncborcherding** [comment]
Hey Hairu,

Close in terms of adjusting the colors using ggplot. Make sure you are generating a palette and then just add names to the color palette.

```
col.pal <- hcl.colors(n=4, palette = "inferno", fixup = TRUE)
names(col.pal) <- c("Single (0 < X <= 1", "Small (1 < X <= 5", "Medium. (5 < X <= 20", "Large (20 < X <= 100")

DimPlot(SampleB, reduction = "harmony_UMAP",  group.by = "cloneSize") + scale_color_manual(values=col.pal)
```

Nick
