### ISSUE TITLE
help with combineExpression: Error: Cannot find 'Type' in this Seurat object

### ISSUE THREAD

**Issue by france-hub** [ncborcherding/scRepertoire#35]
Hi!
Thank you for this great package. 

I think I am doing something wrong but I haven't understood what. 
Briefly, I have two samples labeled as "06" and "07", it's the sample patient 06 = pre-chemotherapy, 07 = post-chemotherapy. 
The following is my combined file:
combined <- combineTCR(contig_data, 
                       samples = c("06", "07"), 
                       ID = c("pre", "post"), cells ="T-AB")
Then I've modified the metadata rownames in my seurat object to make them the same of the barcodes in combined:
> head(rownames(sobj_CD8@meta.data)[ind_1])
[1] "06_pre_AAACCTGAGACGCACA-1" "06_pre_AAACCTGTCCCTAATT-1" "06_pre_AAACCTGTCTTGCATT-1" "06_pre_AAACGGGTCCAGAAGG-1" "06_pre_AAAGATGAGGCGCTCT-1"
[6] "06_pre_AAAGATGCAAAGTGCG-1"
> head(rownames(sobj_CD8@meta.data)[ind_2]) 
[1] "07_post_AAACCTGCAAAGTGCG-1" "07_post_AAACCTGGTCAATACC-1" "07_post_AAACCTGTCCAAATGC-1" "07_post_AAACCTGTCGACCAGC-1" "07_post_AAACCTGTCTGAGGGA-1"
[6] "07_post_AAACGGGAGCGTTCCG-1"
> head(combined$`06_pre`$barcode)
[1] "06_pre_AAACCTGAGACGCACA-1" "06_pre_AAACCTGCACCGAAAG-1" "06_pre_AAACCTGGTCTACCTC-1" "06_pre_AAACCTGGTGGTAACG-1" "06_pre_AAACCTGTCAGCAACT-1"
[6] "06_pre_AAACCTGTCCCTAATT-1"
> head(combined$`07_post`$barcode)
[1] "07_post_AAACCTGCAAAGTGCG-1" "07_post_AAACCTGGTCAATACC-1" "07_post_AAACCTGGTGCGATAG-1" "07_post_AAACCTGTCCAAATGC-1" "07_post_AAACCTGTCCACGTTC-1"
[6] "07_post_AAACCTGTCTGAGGGA-1"

Then i run successfully
sobj_CD8 <- combineExpression(combined, sobj_CD8, cloneCall = "gene", groupBy = "sample")

but when I try to plot the UMAP as in the vignette
colorblind_vector <- colorRampPalette(c("#FF4B20", "#FFB433", "#C6FDEC", "#7AC5FF", "#0348A6"))
DimPlot(seurat, group.by = "Type") + NoLegend() +
    scale_color_manual(values=colorblind_vector(2))

It gives me the following error: Error: Cannot find 'Type' in this Seurat object (Indeed I can't find "Type" in the object metadata)

I've even tried to skip this and go to the following 
slot(seurat, "meta.data")$cloneType <- factor(slot(seurat, "meta.data")$cloneType, 
                                              levels = c("Hyperexpanded (100 < X <= 500)", "Large (20 < X <= 100)", 
                                                         "Medium (5 < X <= 20)", "Small (1 < X <= 5)", 
                                                         "Single (0 < X <= 1)", NA))
DimPlot(seurat, group.by = "cloneType") +
  scale_color_manual(values = colorblind_vector(5), na.value="grey")

And I obtain a grey UMAP as there would be only missing values. 

Would you help me?

Thanks 

Francesco

**Comment by ncborcherding** [comment]
Hey Francesco,

Thanks for the well-formatted post - the grey values on your UMAP likely indicate the clonotype data was not successfully added. What is ind_1 vs ind_2 when you are calling the following?

```
head(rownames(sobj_CD8@meta.data)[ind_1])
```

My first guess is that column and rownames that begin with numbers is not ideal as some base functions in R will add **X.** to the beginning of the column/rownames. So what is likely happening is during the `combineExpression()`, your barcodes are getting converted to *X.07_post_AAACCTGCAAAGTGCG-1* \, specifically when the `combineExpression()` uses `data.frame()`.

Couple of go arounds - 

- Relabel barcodes to something like "Sample1_Pre" and "Sample2_Post"

- Modify the `combineExpression()` function when `data.frame` or `as.data.frame` is called, include **check.names = F** to prevent the conversion

- Use the follow modified version of the `combineExpression()` function to return the data before adding to the seurat object where you can remove the X. and then `AddMetaData()`

```
combineExpression <- function(df, sc, cloneCall="gene+nt", groupBy="none", 
                        cloneTypes=c(None=0, Single=1, Small=5, Medium=20, 
                        Large=100, Hyperexpanded=500), filterNA = FALSE) {
    df <- checkList(df)
    cloneCall <- theCall(cloneCall)
    Con.df <- NULL
    meta <- grabMeta(sc)
    cell.names <- rownames(meta)
    if (groupBy == "none") {
        for (i in seq_along(df)) {
            data <- data.frame(df[[i]], stringsAsFactors = FALSE)
            data2 <- unique(data[,c("barcode", cloneCall)])
            data2 <- na.omit(data2[data2[,"barcode"] %in% cell.names,])
            data2 <- data2 %>% group_by(data2[,cloneCall]) %>%
                summarise(Frequency = n())
            colnames(data2)[1] <- cloneCall
            data <- merge(data, data2, by = cloneCall, all = TRUE)
            Con.df <- rbind.data.frame(Con.df, data)
        }
    } else if (groupBy != "none") {
        data <- data.frame(bind_rows(df), stringsAsFactors = FALSE)
        data2 <- na.omit(unique(data[,c("barcode", cloneCall, groupBy)]))
        data2 <- data2[data2[,"barcode"] %in% cell.names, ]
        data2 <- as.data.frame(data2 %>% group_by(data2[,cloneCall], 
                    data2[,groupBy]) %>% summarise(Frequency = n()))
        colnames(data2)[c(1,2)] <- c(cloneCall, groupBy)
        x <- unique(data[,groupBy])
        for (i in seq_along(x)) {
            sub1 <- subset(data, data[,groupBy] == x[i])
            sub2 <- subset(data2, data2[,groupBy] == x[i])
            merge <- merge(sub1, sub2, by=cloneCall)
            Con.df <- rbind.data.frame(Con.df, merge) } }
    Con.df$cloneType <- NA
    for (x in seq_along(cloneTypes)) { names(cloneTypes)[x] <- 
        paste0(names(cloneTypes[x]), ' (', cloneTypes[x-1], 
        ' < X <= ', cloneTypes[x], ')') }
    for (i in 2:length(cloneTypes)) { Con.df$cloneType <- 
        ifelse(Con.df$Frequency > cloneTypes[i-1] & Con.df$Frequency 
        <= cloneTypes[i], names(cloneTypes[i]), Con.df$cloneType) }
    PreMeta <- unique(Con.df[,c("barcode", "CTgene", "CTnt", 
                "CTaa", "CTstrict", "Frequency", "cloneType")])
    rownames(PreMeta) <- PreMeta$barcode
    return(Premeta) #This now returns the meta data before attachment so assign like pre.meta <- combineExpression() to not overwrite you single cell object
```

Let me know if that is the correct issue or if I am totally off base. 

Thanks,
Nick

**Comment by france-hub** [comment]
Hi! thank you for your great and detailed reply. 

To quickly answer to your question, the rownames of my initial Seurat obj are:

> head(rownames(sobj_CD8@meta.data))
[1] "AAACCTGAGACGCACA-1_pre" "AAACCTGTCCCTAATT-1_pre" "AAACCTGTCTTGCATT-1_pre"
[4] "AAACGGGTCCAGAAGG-1_pre" "AAAGATGAGGCGCTCT-1_pre" "AAAGATGCAAAGTGCG-1_pre"

I've used grep in the following way:
> ind_1 <- grep("_pre", rownames(sobj_CD8@meta.data))
> ind_2 <- grep("_post", rownames(sobj_CD8@meta.data))

to obtain the indexes of the rownames to be modified as in the combined object. 

As you suggested I've used Sample_06_pre and Sample_07_post:
> head(rownames(sobj_CD8@meta.data)[ind_1])
[1] "Sample_06_pre_AAACCTGAGACGCACA-1" "Sample_06_pre_AAACCTGTCCCTAATT-1"
[3] "Sample_06_pre_AAACCTGTCTTGCATT-1" "Sample_06_pre_AAACGGGTCCAGAAGG-1"
[5] "Sample_06_pre_AAAGATGAGGCGCTCT-1" "Sample_06_pre_AAAGATGCAAAGTGCG-1"
> head(combined$Sample_06_pre$barcode)
[1] "Sample_06_pre_AAACCTGAGACGCACA-1" "Sample_06_pre_AAACCTGCACCGAAAG-1"
[3] "Sample_06_pre_AAACCTGGTCTACCTC-1" "Sample_06_pre_AAACCTGGTGGTAACG-1"
[5] "Sample_06_pre_AAACCTGTCAGCAACT-1" "Sample_06_pre_AAACCTGTCCCTAATT-1"

Then if I run combineExpression, still does not work. 
So I've tried to modify the function as you suggested but I get the following error:
> pre.meta <- combineExpression(combined, sobj_CD8, cloneCall = "gene", groupBy = "sample", filterNA = FALSE)
Error: Argument 1 must have names.
Run `rlang::last_error()` to see where the error occurred.

Is combined the problem?

> summary(combined)
               Length Class      Mode
Sample_06_pre  14     data.frame list
Sample_07_post 14     data.frame list

> names(combined)
[1] "Sample_06_pre"  "Sample_07_post"

Thank you very much!
Francesco

**Comment by ncborcherding** [comment]
Hey Francesco,

Darn hoping that would work, but now I think we are having a different issue. I don't see an issue with the naming now, what are the sample and ID variables in your combined data look like? Also what does the following output?

```
head(rownames(sobj_CD8@meta.data)[ind_2])
head(combined$Sample_07_post$barcode)
```

> pre.meta <- combineExpression(combined, sobj_CD8, cloneCall = "gene", groupBy = "sample", filterNA = FALSE)
Error: Argument 1 must have names.

I have seen a similar argument before when the **groupBy** leads to a data frame with zero rows - maybe specifically focus on this part of the function: 

```
data <- data.frame(bind_rows(df), stringsAsFactors = FALSE)
data2 <- na.omit(unique(data[,c("barcode", cloneCall, groupBy)]))
data2 <- data2[data2[,"barcode"] %in% cell.names, ]
```

Sorry no quick fixes, thanks for bearing with me as we troubleshoot.

Nick

**Comment by france-hub** [comment]
Thank you Nick!

No worries, problem solving is rarely quick especially with naive users like me. 

Hope this answer to your questions:
> head(combined$Sample_06_pre$ID)
[1] "pre" "pre" "pre" "pre" "pre" "pre"
> head(combined$Sample_07_post$ID)
[1] "post" "post" "post" "post" "post" "post"
> head(combined$Sample_07_post$barcode)
[1] "Sample_07_post_AAACCTGCAAAGTGCG-1" "Sample_07_post_AAACCTGGTCAATACC-1"
[3] "Sample_07_post_AAACCTGGTGCGATAG-1" "Sample_07_post_AAACCTGTCCAAATGC-1"
[5] "Sample_07_post_AAACCTGTCCACGTTC-1" "Sample_07_post_AAACCTGTCTGAGGGA-1"
> head(rownames(sobj_CD8@meta.data)[ind_2])
[1] "Sample_07_post_AAACCTGCAAAGTGCG-1" "Sample_07_post_AAACCTGGTCAATACC-1"
[3] "Sample_07_post_AAACCTGTCCAAATGC-1" "Sample_07_post_AAACCTGTCGACCAGC-1"
[5] "Sample_07_post_AAACCTGTCTGAGGGA-1" "Sample_07_post_AAACGGGAGCGTTCCG-1"

I'll focus on the part of the function you mentioned and let you know. 

Thanks
Francesco

**Comment by france-hub** [comment]
Good afternoon Nick, 

Sorry to bother with my issue

I've tried the modified version you posted here but I haven't been able to make it works:

> pre.meta <- combineExpression(combined, sobj_CD8, cloneCall = "gene", groupBy = "sample")
`summarise()` regrouping output by 'data2[, cloneCall]' (override with `.groups` argument)
Error in combineExpression(combined, sobj_CD8, cloneCall = "gene", groupBy = "sample") : 
  object 'Premeta' not found

Then I decided to run your function step by step and look at the outputs (I don't know if it's the proper approach (to simplify I have even modified sample_06_pre in S06_DG and sample_07_post in S07_Post)

This is what I did:
> meta <- grabMeta(sobj_CD8)
> cell.names <- rownames(meta)
> Con.df <- NULL
> data <- data.frame(bind_rows(combined), stringsAsFactors = FALSE)
> data2 <- na.omit(unique(data[,c("barcode", "CTgene", "sample")]))
> data2 <- data2[data2[,"barcode"] %in% cell.names, ]
> data2 <- as.data.frame(data2 %>% group_by(data2[,"CTgene"], 
+                                           data2[,"sample"]) %>% summarise(Frequency = n()))
`summarise()` regrouping output by 'data2[, "CTgene"]' (override with `.groups` argument)
> head(data2)
                                        data2[, "CTgene"] data2[, "sample"] Frequency
1 NA_TRBV10-3.TRBJ1-2.None.TRBC1;TRBV9.TRBJ1-5.None.TRBC1               S07         1
2                          NA_TRBV10-3.TRBJ2-3.None.TRBC2               S06         1
3                          NA_TRBV11-1.TRBJ2-2.None.TRBC2               S06         1
4                          NA_TRBV11-1.TRBJ2-3.None.TRBC2               S06         1
5                          NA_TRBV11-3.TRBJ1-1.None.TRBC1               S07         1
6                          NA_TRBV11-3.TRBJ2-1.None.TRBC2               S07         1
> colnames(data2)[c(1,2)] <- c("CTgene", "sample")
> x <- unique(data[,"sample"])
> for (i in seq_along(x)) {
+   sub1 <- subset(data, data[,"sample"] == x[i])
+   sub2 <- subset(data2, data2[,"sample"] == x[i])
+   merge <- merge(sub1, sub2, by="CTgene")
+   Con.df <- rbind.data.frame(Con.df, merge) }
> Con.df$cloneType <- NA
> cloneTypes <- c(None=0, Single=1, Small=5, Medium=20, 
+              Large=100, Hyperexpanded=500)
> for (x in seq_along(cloneTypes)) { names(cloneTypes)[x] <- 
+   paste0(names(cloneTypes[x]), ' (', cloneTypes[x-1], 
+          ' < X <= ', cloneTypes[x], ')') }
> for (i in 2:length(cloneTypes)) { Con.df$cloneType <- 
+   ifelse(Con.df$Frequency > cloneTypes[i-1] & Con.df$Frequency 
+          <= cloneTypes[i], names(cloneTypes[i]), Con.df$cloneType) }
> PreMeta <- unique(Con.df[,c("barcode", "CTgene", "CTnt", 
+                             "CTaa", "CTstrict", "Frequency", "cloneType")])
> rownames(PreMeta) <- PreMeta$barcode
> str(PreMeta)
'data.frame':	3119 obs. of  7 variables:
 $ barcode  : chr  "S06_DG_ACACTGATCGGCGCAT-1" "S06_DG_TGTATTCTCGTTGCCT-1" "S06_DG_GGGTTGCTCGTGTAGT-1" "S06_DG_GTCGGGTAGCCACGTC-1" ...
 $ CTgene   : chr  "NA_TRBV10-3.TRBJ2-3.None.TRBC2" "NA_TRBV10-3.TRBJ2-3.None.TRBC2" "NA_TRBV11-1.TRBJ2-2.None.TRBC2" "NA_TRBV11-1.TRBJ2-3.None.TRBC2" ...
 $ CTnt     : chr  "NA_TGTGCCATCAGTGAACGGACAGATACGCAGTATTTT" "NA_TGTGCCATCAGTGTCCAGGGTACAGATACGCAGTATTTT" "NA_TGTGCCAGCAGCTTAGGAGGTCCCGGGGAGCTGTTTTTT" "NA_TGTGCCAGCAGCTCTCCACTAGCGGGGTCAGCGTCAGATACGCAGTATTTT" ...
 $ CTaa     : chr  "NA_CAISERTDTQYF" "NA_CAISVQGTDTQYF" "NA_CASSLGGPGELFF" "NA_CASSSPLAGSASDTQYF" ...
 $ CTstrict : chr  "NA_NA_TRBV10-3.TRBJ2-3.None.TRBC2_TGTGCCATCAGTGAACGGACAGATACGCAGTATTTT" "NA_NA_TRBV10-3.TRBJ2-3.None.TRBC2_TGTGCCATCAGTGTCCAGGGTACAGATACGCAGTATTTT" "NA_NA_TRBV11-1.TRBJ2-2.None.TRBC2_TGTGCCAGCAGCTTAGGAGGTCCCGGGGAGCTGTTTTTT" "NA_NA_TRBV11-1.TRBJ2-3.None.TRBC2_TGTGCCAGCAGCTCTCCACTAGCGGGGTCAGCGTCAGATACGCAGTATTTT" ...
 $ Frequency: int  1 1 1 1 1 1 1 10 10 10 ...
 $ cloneType: chr  "Single (0 < X <= 1)" "Single (0 < X <= 1)" "Single (0 < X <= 1)" "Single (0 < X <= 1)" ...

Is there something that looks weird in my Premeta? 
Thanks 

Francesco

**Comment by ncborcherding** [comment]
Hey Francesco -

No problem at all.

Your pre meta looks correct to me, can you attach it to your Seurat object using `AddMetaData()`?

Also did you change the names of your cells names in the Seurat object to match the new naming scheme you have?

In terms of the modified function - I forgot to add the closing bracket, I think that may be a source of that error?

I am off clinical service this week, feel free to drop a line and I can be more responsive. 

Thanks,
Nick

**Comment by france-hub** [comment]
Yes I can attach it to my sobj with AddMetaData but the output is the same as previously when I used combineExpressione directly. 

I changed the names and they are the same. 

Regarding the bracket, yes you forgot it but then I put the bracket and it wasn't working as well. 

I've compared my combined file with the one in your vignette and I think mine should be correct. However after adding the metadata the columns are different. 

Is that normal that I have, after combineExpression, these variables as colnames?
> colnames(sobj@meta.data)
[1] "orig.ident"      "nCount_RNA"      "nFeature_RNA"    "samples"         "timepoint"      
[6] "percent.mito"    "RNA_snn_res.0.5" "seurat_clusters"

You have the factor "Type" that I guess is assigned according to the ID argument of combineTCR

> colnames(screp_example@meta.data)
[1] "orig.ident"             "nCount_RNA"             "nFeature_RNA"           "integrated_snn_res.0.5"
[5] "seurat_clusters"        "Patient"                "Type"                   "RawBarcode"

Thanks

Francesco

**Comment by france-hub** [comment]
Also, if it can help to solve this issue, when I tried to use DimPlot after the combineExpression step I got this:

> DimPlot(sobj_CD8, group.by = "cloneType") + NoLegend() +
   scale_color_manual(values=colorblind_vector(2))
Error: Cannot add more or fewer cell meta.data information without values being named with cell names

I've tried to understand what type of error is this and looked into my Idents:
> head(Idents(sobj_CD8))
AAACCTGAGACGCACA-1_pre AAACCTGTCCCTAATT-1_pre AAACCTGTCTTGCATT-1_pre 
                    C1                     C8                     C2 
AAACGGGTCCAGAAGG-1_pre AAAGATGAGGCGCTCT-1_pre AAAGATGCAAAGTGCG-1_pre 
                    C1                     C5                     C1 
Levels: C1 C2 C3 C4 C5 C6 C7 C8 C9 C10 C11 C12

I wondered wether being the names of the Indents different compared to rownames metadata this could be the reason of the error so I changed the names of the indents:
> names(sobj_CD8@active.ident) <- c(rownames(sobj_CD8@meta.data)[ind_1], rownames(sobj_CD8@meta.data)[ind_2])

And apparently this solved the error but running again the same line of code I get a blank picture:
> DimPlot(sobj_CD8, group.by = "cloneType") + NoLegend() +
   scale_color_manual(values=colorblind_vector(2))
Warning message:
Removed 3019 rows containing missing values (geom_point).

Surprisingly when I use single cell experiment it works (jpeg
![UMAP_TCR_sce](https://user-images.githubusercontent.com/56587709/95792831-3fdb9800-0cb2-11eb-9eaf-ab3b39929330.jpeg)
 attached)

**Comment by ncborcherding** [comment]
Hey Francesco, 

Well first off, glad the singlecellexperiment route works.

In terms of the seurat object - the `combineExpression()` should work with any seurat object (regardless of the initial headers), but there might be some issues if you are trying to add the same column names, for instance if your seurat object already has a **CTgene** or **CTnt** variable. Yes the **Type** is my ID variable that was already a part of my seurat object. The columns that will be added are the columns in the *PreMeta* object. 

Are you sure there is no difference in the cell names between your combined TCR and the sobj_CD8? I see you have the following:

**PreMeta**
> str(PreMeta)
'data.frame': 3119 obs. of 7 variables:
$ barcode : chr "S06_DG_ACACTGATCGGCGCAT-1" "S06_DG_TGTATTCTCGTTGCCT-1" "S06_DG_GGGTTGCTCGTGTAGT-1" "S06_DG_GTCGGGTAGCCACGTC-1" ...
$ CTgene : chr "NA_TRBV10-3.TRBJ2-3.None.TRBC2" "NA_TRBV10-3.TRBJ2-3.None.TRBC2" "NA_TRBV11-1.TRBJ2-2.None.TRBC2" "NA_TRBV11-1.TRBJ2-3.None.TRBC2" ...
$ CTnt : chr "NA_TGTGCCATCAGTGAACGGACAGATACGCAGTATTTT" "NA_TGTGCCATCAGTGTCCAGGGTACAGATACGCAGTATTTT" "NA_TGTGCCAGCAGCTTAGGAGGTCCCGGGGAGCTGTTTTTT" "NA_TGTGCCAGCAGCTCTCCACTAGCGGGGTCAGCGTCAGATACGCAGTATTTT" ...
$ CTaa : chr "NA_CAISERTDTQYF" "NA_CAISVQGTDTQYF" "NA_CASSLGGPGELFF" "NA_CASSSPLAGSASDTQYF" ...
$ CTstrict : chr "NA_NA_TRBV10-3.TRBJ2-3.None.TRBC2_TGTGCCATCAGTGAACGGACAGATACGCAGTATTTT" "NA_NA_TRBV10-3.TRBJ2-3.None.TRBC2_TGTGCCATCAGTGTCCAGGGTACAGATACGCAGTATTTT" "NA_NA_TRBV11-1.TRBJ2-2.None.TRBC2_TGTGCCAGCAGCTTAGGAGGTCCCGGGGAGCTGTTTTTT" "NA_NA_TRBV11-1.TRBJ2-3.None.TRBC2_TGTGCCAGCAGCTCTCCACTAGCGGGGTCAGCGTCAGATACGCAGTATTTT" ...
$ Frequency: int 1 1 1 1 1 1 1 10 10 10 ...
$ cloneType: chr "Single (0 < X <= 1)" "Single (0 < X <= 1)" "Single (0 < X <= 1)" "Single (0 < X <= 1)"

**sobj_CD8**
> head(Idents(sobj_CD8))
AAACCTGAGACGCACA-1_pre AAACCTGTCCCTAATT-1_pre AAACCTGTCTTGCATT-1_pre
C1 C8 C2
AAACGGGTCCAGAAGG-1_pre AAAGATGAGGCGCTCT-1_pre AAAGATGCAAAGTGCG-1_pre
C1 C5 C1
Levels: C1 C2 C3 C4 C5 C6 C7 C8 C9 C10 C11 C12

**Specifically:**

- **sobj_CD8:** AAACCTGAGACGCACA-1_pre

- **combined:** S06_DG_ACACTGATCGGCGCAT-1

I think this explains why the singlecellexperiment works - it stores the meta data differently - so adding it with your modified names should not produce an error, but using `combineExpression()` on a seurat object where the cell names and the row names of the meta data are mismatched could lead to errors? [This ](https://github.com/satijalab/seurat/issues/935#issuecomment-439170158) is the explanation from the Seurat issues page.

As far as the last error from
> names(sobj_CD8@active.ident) <- c(rownames(sobj_CD8@meta.data)[ind_1], rownames(sobj_CD8@meta.data)[ind_2])

Have you tried the seurat function `RenameCells()`? This will universally change the cell barcodes (across the seurat object), just need to provide a vector with the new names (in order) using the *new.names* parameter.

Sincerely,
Nick

**Comment by france-hub** [comment]
Thanks again for you feedback. 

I think I haven't been clear in my explanation, apologize. 

I am sure the rownames of my seurat object and the names in the combined TCR are the same:
> head(combined$S06_pre$barcode)
[1] "S06_pre_AAACCTGAGACGCACA-1" "S06_pre_AAACCTGCACCGAAAG-1" "S06_pre_AAACCTGGTCTACCTC-1" "S06_pre_AAACCTGGTGGTAACG-1"
[5] "S06_pre_AAACCTGTCAGCAACT-1" "S06_pre_AAACCTGTCCCTAATT-1"
> head(combined$S07_post$barcode)
[1] "S07_post_AAACCTGCAAAGTGCG-1" "S07_post_AAACCTGGTCAATACC-1" "S07_post_AAACCTGGTGCGATAG-1" "S07_post_AAACCTGTCCAAATGC-1"
[5] "S07_post_AAACCTGTCCACGTTC-1" "S07_post_AAACCTGTCTGAGGGA-1"
> head(rownames(sobj_CD8@meta.data)[ind_1])
[1] "S06_pre_AAACCTGAGACGCACA-1" "S06_pre_AAACCTGTCCCTAATT-1" "S06_pre_AAACCTGTCTTGCATT-1" "S06_pre_AAACGGGTCCAGAAGG-1"
[5] "S06_pre_AAAGATGAGGCGCTCT-1" "S06_pre_AAAGATGCAAAGTGCG-1"
> head(rownames(sobj_CD8@meta.data)[ind_2])
[1] "S07_post_AAACCTGCAAAGTGCG-1" "S07_post_AAACCTGGTCAATACC-1" "S07_post_AAACCTGTCCAAATGC-1" "S07_post_AAACCTGTCGACCAGC-1"
[5] "S07_post_AAACCTGTCTGAGGGA-1" "S07_post_AAACGGGAGCGTTCCG-1"

However I realized that my Idents where different (as you pointed out):
> head(Idents(sobj_CD8))
AAACCTGAGACGCACA-1_pre AAACCTGTCCCTAATT-1_pre AAACCTGTCTTGCATT-1_pre AAACGGGTCCAGAAGG-1_pre AAAGATGAGGCGCTCT-1_pre AAAGATGCAAAGTGCG-1_pre 
                    C1                     C8                     C2                     C1                     C5                     C1 
Levels: C1 C2 C3 C4 C5 C6 C7 C8 C9 C10 C11 C12

Then to make everything the same I did:
> names(sobj_CD8@active.ident) <- c(rownames(sobj_CD8@meta.data)[ind_1], rownames(sobj_CD8@meta.data)[ind_2])
> head(Idents(sobj_CD8))
S06_pre_AAACCTGAGACGCACA-1 S06_pre_AAACCTGTCCCTAATT-1 S06_pre_AAACCTGTCTTGCATT-1 S06_pre_AAACGGGTCCAGAAGG-1 S06_pre_AAAGATGAGGCGCTCT-1 
                        C1                         C8                         C2                         C1                         C5 
S06_pre_AAAGATGCAAAGTGCG-1 
                        C1 
Levels: C1 C2 C3 C4 C5 C6 C7 C8 C9 C10 C11 C12

However after this change, when I try to use Dimplot I get the following warning:
> DimPlot(sobj_CD8, group.by = "cloneType") + NoLegend() +
      scale_color_manual(values=colorblind_vector(2))
Warning message:
Removed 3019 rows containing missing values (geom_point)

Anyway thanks for all your help. I'll try to use RenameCells() too and see if I can figure out why it's not working. 

Have a great day

Francesco

**Comment by france-hub** [comment]
Good afternoon Nick, 

I think I've solved it even if I really don't know how. I kept obtaining the same warning with DimPlot(). 
Since my barcodes in my seurat object have this pattern *******-1_pre and *******-1_post (for the two timepoints pre and post) I tried to change the barcodes in the combined file as *******-1_pre and *******-1_post  too and it worked!

I am sure my rownames in seurat's metadata were properly modified but I don't know why it wasn't working in that way. 

Thanks for your help!

**Comment by ncborcherding** [comment]
Hey Francesco, 

Thanks for following up and glad you got things figured out. I just had another user with an issue who was using cell barcodes starting with numbers (see above link). There was no issue there with the addition using the numbers - very interesting. 

Good luck with your data analysis and let me know if you have any issues. 

Nick
