### ISSUE TITLE
x.axis did not appear in clonalDiversity

### ISSUE THREAD

**Issue by synatkeamsk** [ncborcherding/scRepertoire#350]
Hi Nick, 

Hope you are well. I run ```ClonalDiversity``` of integrated scTCR and scRNAseq using the following codes: I have a group column with two levels ```ICI-arthritis``` and ```Osteoarthritis``` and I would like to call it using x.axis so I can two box plots (one for ICI-arthritis and another one for Osteoarthritis), but it did not appear (kindly review image attach). Do you have a quick way of order the ordering the clusters from C0, C1, C2, C3..etc. currently it is not in order. Thanks for your help. Wonderful package! 

``` 
clonalDiversity(integrated.obj.T, 
                cloneCall = "gene",
                metrics = c("shannon", "inv.simpson"),
                group.by = "ident", 
                x.axis = "group") 
``` 
![Capture](https://github.com/ncborcherding/scRepertoire/assets/121846660/fe945dfd-b7b5-4e11-b8e5-a6d3108ba01d)

Hope you could help check. 

Kind Regards,

synat

**Comment by ncborcherding** [comment]
Hey Synat, 

Looks like your "groups" variable is a numeric value. You can try a couple of things:

- Change group to a factor 

```
integrated.obj.T$group <- as.factor(integrated.obj.T$group )
```
Honestly I am not sure if this one will work, but it is the most straightforward to try.

- define discrete breaks in the x.axis

```
clonalDiversity(integrated.obj.T, 
                cloneCall = "gene",
                metrics = c("shannon", "inv.simpson"),
                group.by = "ident", 
                x.axis = "group")  + 
                scale_x_discrete(breaks = unique(integrated.obj.T$group))
```

Hope that helps,
Nick

**Comment by synatkeamsk** [comment]
Thanks, Nick. thank for your immense help and being patient with me. Unfortunately, look like both did not work. if you have spare dataset and have found solution, kindly let me know. I need to show it in my publication, but I will try myself too. 

Best Regards,

synat

**Comment by gianfilippo** [comment]
Hi,

I have the same issue. I think, the problem is that the input data is not split by x.axis.
A potential way around is to split your object by x.axis and feed the separate objects to the clonalDiversity function, setting exportTable=TRUE. You  end up with length(x.axis) data frames, which you can combine and plot.
Other than that, as far as I can see, you have to modify function.
Best

**Comment by gianfilippo** [comment]
On second thoughts, this is not ideal, since the min as estimated from short.check could be different.
