### ISSUE TITLE
Clonality matrix under scRepertoire

### ISSUE THREAD

**Issue by synatkeamsk** [ncborcherding/scRepertoire#353]
Hi Nick, 

Hope it is not too much from me. I am wondering whether you have a matric for clonality calculation under scRepertoir. Or does less index score in diversity matrix of scRepertoir such as "shannon", "ACE" of  means more clonal? I heard about  1-Pielou evenness, but not sure whether we can do it under scRepertoir. Apologies and hope you do not mind. 

Kind Regards,

synat

**Comment by ncborcherding** [comment]
Hey Synat,

The diversity metrics are all really inversely proportional to clonal expansion. So a simple method would be to take 1/metric. This is not perfectly ideal. Pielou index is Shannon Diversity/ ln(number of clones). So it is scaling the diversity by the total number of clones. Those would be the straight forward ones from scRepertoire outputs.

Another approach that you could try is getting the counts for each clone and fitting a distribution model. You could then compare different samples this way. I'd probably start with a Poisson based approach.

Hope that helps and sorry traveling at the moment so this is on a phone.
Nick

**Comment by synatkeamsk** [comment]
Thanks you nick for your continued support. 
Safe travel. 

Kind Regards,

synat

**Comment by synatkeamsk** [comment]
Hi Nick, 
Just a fellow-up with your suggestion regarding ```Pielou index is Shannon Diversity/ ln(number of clones)```. For ```number of clones```,  do you mean the total number of reads per/sample? Is there a quick way to generate the numbers of clones per sample so I can calculate Shannon Diversity/ ln(number of clones)? 

Kind Regards,

synat

**Comment by ncborcherding** [comment]
Hey Synat, 

So here I mean just the total number of unique clones (in ecology it is referred to as "species" in case that is confusing). 

A quick way to calculate the number of unique clones would be ```length(unique(SeuratObj$CTaa))```. But you might need to subset the meta data if you want to get individual groupings. 

Hope that helps,
Nick

**Comment by synatkeamsk** [comment]
Thanks, Nick! you are the best! 

Kind Regards,

Synat
