### ISSUE TITLE
Issue Merging Seurat Data with the Combined TCR Object

### ISSUE THREAD

**Issue by ghoeltzel38** [ncborcherding/scRepertoire#358]
Hey thanks so much for designing this package for use. Greatly useful and I'm very appreciative.

I have a seurat object that ive annotated as specific CD4 subsets. I have the VDJ data for all of the cells that were originally present in the sequencing run. My first attempt was to filter the VDJ based on what barcodes I had in my seurat object with some code similar to following but for many different patients (12 in total with 2 sample runs per patient): 

#Patient 1
P1_T1 = read_csv(paste0(common_path, "filtered_contig_annotations_TCR_01_PDAC1_biopsy_CD45p1.csv"))
P1_T1_filt = P1_T1 %>% filter(barcode %in% cd4s_pimmune_3_TCR$TCR_X.cell)
dim(P1_T1_filt)
P1_T2 = read_csv(paste0(common_path, "filtered_contig_annotations_TCR_01_PDAC1_biopsy_CD45p2.csv"))
P1_T2_filt = P1_T2 %>% filter(barcode %in% cd4s_pimmune_3_TCR$TCR_X.cell)

    cd4s_pimmune_TCR_combined = combineExpression(combined_orig_ident_filt, cd4s_pimmune_3_TCR, 
                                              cloneCall = "aa", 
                                              group.by = "sample",
                                              proportion = FALSE,
                                              cloneTypes = c(Single = 1, Small = 5, Medium = 20, Large = 100, Hyperexpanded = 500)
                                              )
       

when i call the combineExpression function to try to join the two, i get an error that not all cells are in the seurat object. but surely there are situations where individuals have QCed some Tcells out of their analysis and so the dimensions do not perfectly match? I am unable to get beyond this step, have been spending many hours trying to perfectly align the barcodes between the two objects. Also - i am confused as to how this function knows how to map the TCR data to the seurat meta data since group.by in this example is specified at the sample rather than at the cell level?

any insight would be greatly appreciated.

**Comment by ncborcherding** [comment]
Hey thanks for reaching out.

> I have a seurat object that ive annotated as specific CD4 subsets. I have the VDJ data for all of the cells that were originally present in the sequencing run. My first attempt was to filter the VDJ based on what barcodes I had in my seurat object with some code similar to following but for many different patients (12 in total with 2 sample runs per patient)

You should be able just to load all the contig information, use ```combineTCR()```, then ```combineExpression()``` on your filtered object - cd4s_pimmune_3_TCR. 

```
P1_T1 = read_csv(paste0(common_path, "filtered_contig_annotations_TCR_01_PDAC1_biopsy_CD45p1.csv"))
P1_T2 = read_csv(paste0(common_path, "filtered_contig_annotations_TCR_01_PDAC1_biopsy_CD45p2.csv"))
contig.list <- list(P1_T1, P1_T2, ...)

combined.TCR <- combineTCR(contig.list, samples = XXX)

cd4s_pimmune_3_TCR <- combineExpression(combined_orig_ident_filt, cd4s_pimmune_3_TCR, 
                                        cloneCall = "aa", 
                                        group.by = "sample",
                                        proportion = FALSE,
                                        cloneTypes = c(Single = 1, Small = 5, Medium = 20, Large = 100, Hyperexpanded = 500)
                                                )
```

> when i call the combineExpression function to try to join the two, i get an error that not all cells are in the seurat object. 

What is the exact error you are getting? 

Also what is the output of ```sessionInfo()```?

 ```combineExpression()``` should filter the combined contigs using the barcode in the single-cell object before adding the clonal information to the meta data. 

> Also - i am confused as to how this function knows how to map the TCR data to the seurat meta data since group.by in this example is specified at the sample rather than at the cell level?

**group.by** is just modulating the calculation of clonalFrequency, clonalProportion, and clonalSize. The attachment of the data are the exact same whether **group.by** = X or NULL.

Thanks,
Nick

**Comment by ghoeltzel38** [comment]
after getting the first error, i assumed part of the issue was that the rownames of my meta data were not the same as the barcode column of the TCR dataframe, so i recreated a matching barcode using the paste0 as shown above, then did the following which is where the 'all cells' errors shown below came into play:


rownames(cd4s_pimmune_3_TCR@meta.data) = cd4s_pimmune_3_TCR$barcode_TCR
cd4s_pimmune_3_TCR <- combineExpression(combined_contig, cd4s_pimmune_3_TCR, 
                                        cloneCall = "aa", 
                                        group.by = "sample",
                                        proportion = FALSE,
                                        cloneTypes = c(Single = 1, Small = 5, Medium = 20, Large = 100, Hyperexpanded = 500))

Error in validObject(object = x) : 
  invalid class “Seurat” object: 1: all cells in assays must be present in the Seurat object
invalid class “Seurat” object: 2: all cells in assays must be present in the Seurat object
invalid class “Seurat” object: 3: All cells in reductions must be present in the Seurat object
invalid class “Seurat” object: 4: All cells in reductions must be present in the Seurat object
invalid class “Seurat” object: 5: All cells in reductions must be present in the Seurat object
invalid class “Seurat” object: 6: all cells in graphs must be present in the Seurat object
invalid class “Seurat” object: 7: all cells in graphs must be present in the Seurat object
invalid class “Seurat” object: 8: 'active.idents' must be named with cell names

**Comment by ncborcherding** [comment]
I think what is likely happening here is there is a version issue between scRepertoire v1.8 (built before v5 of Seurat) and the newest Seurat you have installed. They are likely not compatible. I would suggest updating to scRepertoire to v2 using: 

```
remotes::install_github("ncborcherding/scRepertoire")
```

Nick

**Comment by ghoeltzel38** [comment]
Hey Nick,

Thanks so much. I just updated but still getting the same error regarding 'all cells in assays must be present in the seurat object' . Sorry for the bother - trying to sort something for my PI by tomorrow AM and clearly struggling lol 

> cd4s_pimmune_3_TCR <- combineExpression(combined_contig, cd4s_pimmune_3_TCR, 
+                                         cloneCall = "aa", 
+                                         group.by = "sample",
+                                         proportion = FALSE,
+                                       cloneSize = c(Single = 1, Small = 5, Medium = 20, Large = 100, Hyperexpanded = 500))
Error in validObject(object = x) : 
  invalid class “Seurat” object: 1: all cells in assays must be present in the Seurat object
invalid class “Seurat” object: 2: all cells in assays must be present in the Seurat object
invalid class “Seurat” object: 3: All cells in reductions must be present in the Seurat object
invalid class “Seurat” object: 4: All cells in reductions must be present in the Seurat object
invalid class “Seurat” object: 5: All cells in reductions must be present in the Seurat object
invalid class “Seurat” object: 6: all cells in graphs must be present in the Seurat object
invalid class “Seurat” object: 7: all cells in graphs must be present in the Seurat object
invalid class “Seurat” object: 8: 'active.idents' must be named with cell names

**Comment by ncborcherding** [comment]
Hey no problem - totally understand. This is a completely new error for me, so bear with me. 

I see this issue here with the same error message: https://github.com/satijalab/seurat/issues/8297

Is your data a list or not a fully integrated/merged object? I do not think ```combineExpression()``` will work in that setting.

**Comment by ghoeltzel38** [comment]
<img width="873" alt="image" src="https://github.com/ncborcherding/scRepertoire/assets/147325153/3b81196c-40ef-459e-ae4f-0f0732c00b5d">

**Comment by ncborcherding** [comment]
That looks integrated - 

Very strange because scRepertoire detects the input object (Seurat vs Single-cell experiment) and then appends the clonal information to the meta data. There is no interaction with assays, reductions, or graphs slots in a Seurat object.

Are you able to do your downstream analysis with Seurat with cd4s_pimmune_3_TCR? Like differential expression and other plotting functions? It might indicate that there is an issue with the Seurat object?

Happy to take a look a closer look if you are under time pressure (totally understand if you want to keep the data private) - but if you share with me the combined data and the seurat object, debugging would go fast I think. You can [email me](mailto:ncborch@gmail.com)?

Nick

**Comment by ncborcherding** [comment]
Hey Gerard, 

I will close this issue because I think we found the underlying problem - barcode mismatch. But I wanted to leave an explanation if other users find this. 

When using Seurat for multiple sequencing runs, barcodes are automatically appended with a "_X" to prevent issues with duplicate barcodes across sequencing runs. This creates a barcode mismatch for the contig files and subsequent outputs of ```combineTCR()``` and ```combineBCR()```. 

```
original: ACGTACGTACGTACGT-1
seurat-modified: ACGTACGTACGTACGT-1_1
```

Probably the easiest way to approach this mismatch is to modify the contig file or the outputs of ```combineTCR()``` and ```combineBCR()```. There is some code for this on the[ scRepertoire FAQ](https://www.borch.dev/uploads/screpertoire/articles/faq). But also here is a loop that would do something similar across multiple runs.

```
for(i in seq_along(contig_list)) {
  contig_list[[i]]$barcode <- paste0(contig_list[[i]]$barcode, "_", i)
}
```

Hope that helps,
Nick
