### ISSUE TITLE
plotUMAP(sce, colour_by = "cloneSize") :    could not find function "plotUMAP"

### ISSUE THREAD

**Issue by hangsuUNC** [ncborcherding/scRepertoire#360]
Hi,

Thanks for the tool! I was trying to combine expression and clone data and plot UMAP following the tutorial. I got an Error saying "plotUMAP(sce, colour_by = "cloneSize") : 
  could not find function "plotUMAP"". Could you please help double check your package?

Thanks,

Hang

**Comment by ncborcherding** [comment]
Hey Hang, 

There is no UMAP/Dimensional Reduction plotting functions (outside of ```clonalNetwork()```) in scRepertoire. If you are trying to replicate the vignette - ```plotUMAP()``` is from the [scater](https://bioconductor.org/packages/release/bioc/html/scater.html) R package. But you could use other methods of plotting as well. 

Hope that helps, 
Nick
