### ISSUE TITLE
The Github version and Bioconductor version differ

### ISSUE THREAD

**Issue by llrs** [ncborcherding/scRepertoire#361]
Hi! Thanks for maintaining and updating the package. 

I thought that the changes in this github version would be published in the release 3.19 of Bioconductor.
However, I've seen that the Bioconductor version was not updated. 

Do you need help to make a release thorough Bioconductor? 
It will help both users and other developers who might want to use and depend on the latest upgrades on the package for their own analysis or packages.

**Comment by ncborcherding** [comment]
Hey Llus, 

The major overhaul of scRepertoire to version 2 is available at [bioconductor](https://www.bioconductor.org/packages/release/bioc/html/scRepertoire.html)]. I am making some additional changes in the dev branch and in github actions that will be pushed to bioconductor after getting them working on the master branch. 

Alternatively, I may misunderstand what exactly you are asking and I am always willing to receive help - just let me know. 

Nick

**Comment by llrs** [comment]
Apologies I must been confused by error in a function (`quantContig`) I thought it was new but it might be from previous version (I was expecting a warning or a deprecation message in this case).  

It might help me and other users if you could it provide a deprecation warning for those functions. There is a [guide on how to proceed](https://contributions.bioconductor.org/deprecation.html?q=depreca#step-1-deprecate-the-function) for packages in Bioconductor.
Thanks for this useful package!
