### ISSUE TITLE
retaining labels from clonalCompare(relabel.clones=TRUE)

### ISSUE THREAD

**Issue by kriegerm** [ncborcherding/scRepertoire#363]
Me again - I apologize for the repeat asks, but hopefully this issue will be more straightforward now that I've got things working!

I'm just curious if there's any way that the labels "Clone 1," "Clone 2," etc. from `clonalCompare(relabel.clones=TRUE)` could be added to my combined.TCR list for future use? It'd be more helpful to retain these shorter labels for downstream analysis.

Many thanks :)

**Comment by ncborcherding** [comment]
Hey Madeline, 

Unfortunately, there is no current method to do this without comparing the proportion of the clones. Which is not ideal. I just pushed a commit to the dev branch to keep the original clonal information as part of the relabeling. This will let users assign the info using: 

```
clonalCompare(..., 
              relabel.clones = TRUE,
              exportTable = TRUE)
```
That will still take some additional testing, and it will roll out with v2.0.4.

Thanks for the suggestion,
Nick

**Comment by kriegerm** [comment]
Great, I'll keep my eyes out for the new version! Thanks!
