### ISSUE TITLE
Specifics of clonalQuant()

### ISSUE THREAD

**Issue by kriegerm** [ncborcherding/scRepertoire#365]
Hi Nick,

One more quick question. I am wondering how exactly clonalQuant() works to quantify clones. Is there a threshold for aa and nt similarity? If so, can this parameter be adjusted? 

I looked through the code documentation and manuals but couldn't find what I was looking for. 

Thanks,
Maddie

**Comment by ncborcherding** [comment]
Hey Maddie, 

Thanks for reaching out. There is no similarity threshold built-in ```clonalQuant()```; it will call the clones by whatever the **cloneCall** used. This is fine for TCRs, but you might want to call related clones for BCRs. In that case, you can use the **cloneCall** = "strict," which includes an edit distance-based clustering of the nucleotide sequences. 

Hope that helps and have a great weekend,

Nick

**Comment by kriegerm** [comment]
Thanks for the quick reply!

Just to clarify, clonalQuant() is going to simply use exact aa or nt sequences (or both, depending on what you specify) and aligns them, and then sequences with the exact same homology are called as the same clone? If so, is that an issue for really closely related clones (ones that just have one or two nt or aa differences)?

**Comment by ncborcherding** [comment]
Yes - only exact matches are used (with the exception of the BCR "strict"). This is the case for all functions in scRepertoire (and alternative single-cell pipelines that I am aware of).

I think you make a great point about closely related sequences. There is a lot of info in those neighborhoods for antigen/disease. However, "clone" generally refers to the individual recombination event. 

You may want to check out ```clonalCluster()``` - it will give you clusters based Vgene match and edit distance for sequences.

**Comment by kriegerm** [comment]
Ok great to know, thank you! Have a great weekend!

**Comment by kriegerm** [comment]
Hey @ncborcherding  - an additional related question. As I use clonalCluster(), it's not appending any output to the combined.TCR object. I see that it's printing out a dataframe with a cluster based column, but it's not actually adding that to the combined.TCR. Am I missing an option, or do I need to add the newly defined clusters some other way?

```r
clonalCluster(
  combined.TCR,
  sequence = "aa",
  threshold = 0.8,
  exportGraph = FALSE)
```

**Comment by ncborcherding** [comment]
Hey Maddie, 

You just need to save the result into your environment: 

```
new.combined.TCR <- clonalCluster(
                                  combined.TCR,
                                  sequence = "aa",
                                  threshold = 0.8,
                                  exportGraph = FALSE)
```

Nick

**Comment by kriegerm** [comment]
Perfect, thank you!
