### ISSUE TITLE
Regular expression used for quietTCRgenes.R

### ISSUE THREAD

**Issue by user-pagh** [ncborcherding/scRepertoire#369]
Hi Nick and team. 

This is more of a comment than an issue. I looked through past posts on this page and couldn't find any comments on the regular expression used for Trex::quietTCRgenes.R(). 

According to https://rdrr.io/github/ncborcherding/Trex/src/R/quietTCRgenes.R ("built on April 27, 2024, 5:02 a.m") the regular expression used for this function is: 

`unwanted_genes <- "^TR[ABDG][VDJ]"`

This also filters away the gene "TRADD" (Tumor necrosis factor receptor type 1-associated DEATH domain protein). I have previously used the following to avoid this:   "^TR[ABDG][VDJ][^D]"

It's a tiny detail - and TRADD is so far the only case of non-TCR genes I've seen included with the given regular expression that you propose. 

Kind regards,
Nikolaj

**Comment by ncborcherding** [comment]
Hey Nikolaj, 

Thanks for the suggestions - I have incorporated into the dev version of Trex and will push it to the master branch when I am done with some additional changes.

Nick
