### ISSUE TITLE
Error while plotting Seurat objects after running "combineExpression"

### ISSUE THREAD

**Issue by sopenaml** [ncborcherding/scRepertoire#37]
Hi,
I have been following your vignette for scRepertoire and while trying to apply it to my own data I've encounter a problem. After running `combineExpression` I get and error when trying to plot the data: This is my code:
```
gd1 <-read.csv("all_contig_annotations.csv", header=T)
 combined.gd1 <- combineTCR(gd1, 
                            paste0(1, "_gammadelta" ),
                            ID= paste0("sample_",1 ),
                            cells ="T-GD")
 
 
 sample1.singlet <-readRDS("sample1.singlet.RDS")
 

 rownames(sample1.singlet@meta.data) <- paste0( "1_gammadelta_sample_1_", rownames(sample1.singlet@meta.data), "-1")
 
 seurat <- combineExpression(combined.gd1 , sample1.singlet, cloneCall="gene")
 
 DimPlot(seurat)
Error: Must request at least one colour from a hue palette.
```
I've noticed that the problem is that after combining the TCR data with gene expression data, I get barcodes with NAs. And if I remove cells that have 'NA's on meta.data, then the problem is solved. But why does it happen when I try to just plot and highlight clusters. Also, my data is supposed to have cells with no TCR but I still want to visualize them on my TSNE, so removing isn't a solution for me.

**Comment by ncborcherding** [comment]
Hey sopenami,

Thanks for posting the issue.

## Couple of questions first
- What do you mean barcodes with NAs? You have rows with NA values for the TCR information or rows with NAs across more than that? Or barcodes/row names with NA values?
     - To this end can you show me what you mean with an example of your meta data after `combineExpression()`?
- What is the naming schemes for your seurat and combined Contig info:
     - head(rownames(sample1.singlet@meta.data)) #metadata barcodes
     - head(combined.gd1$barcode) #combinedTCR barcodes
     - head(names(sample1.singlet$active.ident)) #seurat object cell names
*****
Your call `DimPlot(seurat)` should not be affected by the `combineExpression` unless there is a change in active.identity, which is the default call. Do you have any issues calling `DimPlot( sample1.singlet)`? You should be able to graph T and Non-T cells with no issue, there are some functions in Seurat that might require a workaround, but the plotting, especially of meta.data in `DimPlot` should not be affect. Here is an example of the example data set (renal clear cell carcinoma immune populations) with all the cell types:

![Figure2_example](https://user-images.githubusercontent.com/22754118/96581085-e7eaf580-129e-11eb-9f6b-fde10a096278.png)

The grey predominant clusters are B cells and Myeloid cells (there is some contamination due to the integration step performed). 

Hope this helps, let me know if you have further problems and we can troubleshoot.

Thanks,
Nick

**Comment by sopenaml** [comment]
Hi Nick,

Sorry I didn't explain properly, What I meant with "barcodes with NAs" is that after I've run combinedExpression, I've noticed that some of the barcodes had NAs for the TCR information, and if I filter those out I can create a DimPlot. I should also mention that I have tried DimPlot in the object before I run combinedExperiment it works, it's just after. And as I said if I remove the cells that don't have values for the TCR data, it works again.

Please find below the information requested:

This is the metadata after combinedExpression is run:
head(seurat@meta.data)
                                          orig.ident nCount_RNA nFeature_RNA
1_aplabeta_sample_1_AAACGGGAGTCCATAC-1 SeuratProject       5145         1589
1_aplabeta_sample_1_AAACGGGCAGATAATG-1 SeuratProject       7308         1826
1_aplabeta_sample_1_AAACGGGTCGCCGTGA-1 SeuratProject       4496         1272
1_aplabeta_sample_1_AAACGGGTCGGACAAG-1 SeuratProject      15260         3227
1_aplabeta_sample_1_AAAGATGAGCTTATCG-1 SeuratProject       4890         1405
1_aplabeta_sample_1_AAAGATGCAGCTGTTA-1 SeuratProject       5971         1931
                                              sampleID percent.mt nCount_HTO
1_aplabeta_sample_1_AAACGGGAGTCCATAC-1 sample1.hashtag  2.0991254       1904
1_aplabeta_sample_1_AAACGGGCAGATAATG-1 sample1.hashtag  1.8199234       1548
1_aplabeta_sample_1_AAACGGGTCGCCGTGA-1 sample1.hashtag  1.9572954       1947
1_aplabeta_sample_1_AAACGGGTCGGACAAG-1 sample1.hashtag  2.2018349       1697
1_aplabeta_sample_1_AAAGATGAGCTTATCG-1 sample1.hashtag  0.7770961       2303
1_aplabeta_sample_1_AAAGATGCAGCTGTTA-1 sample1.hashtag  2.6796182       1254
                                       nFeature_HTO                HTO_maxID
1_aplabeta_sample_1_AAACGGGAGTCCATAC-1            6 Hashtag5-AAGTATCGTTTCGCA
1_aplabeta_sample_1_AAACGGGCAGATAATG-1            7 Hashtag3-TTCCGCCTCTCTTTG
1_aplabeta_sample_1_AAACGGGTCGCCGTGA-1            6 Hashtag5-AAGTATCGTTTCGCA
1_aplabeta_sample_1_AAACGGGTCGGACAAG-1            5 Hashtag5-AAGTATCGTTTCGCA
1_aplabeta_sample_1_AAAGATGAGCTTATCG-1            5 Hashtag4-AGTAAGTTCAGCGTA
1_aplabeta_sample_1_AAAGATGCAGCTGTTA-1            6 Hashtag5-AAGTATCGTTTCGCA
                                                   HTO_secondID HTO_margin
1_aplabeta_sample_1_AAACGGGAGTCCATAC-1                 unmapped   2.419700
1_aplabeta_sample_1_AAACGGGCAGATAATG-1 Hashtag4-AGTAAGTTCAGCGTA   3.078683
1_aplabeta_sample_1_AAACGGGTCGCCGTGA-1 Hashtag2-TGATGGCCTATTGGG   2.354408
1_aplabeta_sample_1_AAACGGGTCGGACAAG-1                 unmapped   2.412686
1_aplabeta_sample_1_AAAGATGAGCTTATCG-1                 unmapped   3.590583
1_aplabeta_sample_1_AAAGATGCAGCTGTTA-1                 unmapped   2.319491
                                             HTO_classification
1_aplabeta_sample_1_AAACGGGAGTCCATAC-1 Hashtag5-AAGTATCGTTTCGCA
1_aplabeta_sample_1_AAACGGGCAGATAATG-1 Hashtag3-TTCCGCCTCTCTTTG
1_aplabeta_sample_1_AAACGGGTCGCCGTGA-1 Hashtag5-AAGTATCGTTTCGCA
1_aplabeta_sample_1_AAACGGGTCGGACAAG-1 Hashtag5-AAGTATCGTTTCGCA
1_aplabeta_sample_1_AAAGATGAGCTTATCG-1 Hashtag4-AGTAAGTTCAGCGTA
1_aplabeta_sample_1_AAAGATGCAGCTGTTA-1 Hashtag5-AAGTATCGTTTCGCA
                                       HTO_classification.global
1_aplabeta_sample_1_AAACGGGAGTCCATAC-1                   Singlet
1_aplabeta_sample_1_AAACGGGCAGATAATG-1                   Singlet
1_aplabeta_sample_1_AAACGGGTCGCCGTGA-1                   Singlet
1_aplabeta_sample_1_AAACGGGTCGGACAAG-1                   Singlet
1_aplabeta_sample_1_AAAGATGAGCTTATCG-1                   Singlet
1_aplabeta_sample_1_AAAGATGCAGCTGTTA-1                   Singlet
                                                        hash.ID RNA_snn_res.0.5
1_aplabeta_sample_1_AAACGGGAGTCCATAC-1 Hashtag5-AAGTATCGTTTCGCA               3
1_aplabeta_sample_1_AAACGGGCAGATAATG-1 Hashtag3-TTCCGCCTCTCTTTG               2
1_aplabeta_sample_1_AAACGGGTCGCCGTGA-1 Hashtag5-AAGTATCGTTTCGCA               0
1_aplabeta_sample_1_AAACGGGTCGGACAAG-1 Hashtag5-AAGTATCGTTTCGCA               1
1_aplabeta_sample_1_AAAGATGAGCTTATCG-1 Hashtag4-AGTAAGTTCAGCGTA               0
1_aplabeta_sample_1_AAAGATGCAGCTGTTA-1 Hashtag5-AAGTATCGTTTCGCA               1
                                       seurat_clusters nCount_ADT nFeature_ADT
1_aplabeta_sample_1_AAACGGGAGTCCATAC-1               3       2105           13
1_aplabeta_sample_1_AAACGGGCAGATAATG-1               2       1863           12
1_aplabeta_sample_1_AAACGGGTCGCCGTGA-1               0       2111           14
1_aplabeta_sample_1_AAACGGGTCGGACAAG-1               1       1638           11
1_aplabeta_sample_1_AAAGATGAGCTTATCG-1               0       2076           13
1_aplabeta_sample_1_AAAGATGCAGCTGTTA-1               1       1331           13
                                                                      barcode
1_aplabeta_sample_1_AAACGGGAGTCCATAC-1                                   <NA>
1_aplabeta_sample_1_AAACGGGCAGATAATG-1 1_aplabeta_sample_1_AAACGGGCAGATAATG-1
1_aplabeta_sample_1_AAACGGGTCGCCGTGA-1 1_aplabeta_sample_1_AAACGGGTCGCCGTGA-1
1_aplabeta_sample_1_AAACGGGTCGGACAAG-1 1_aplabeta_sample_1_AAACGGGTCGGACAAG-1
1_aplabeta_sample_1_AAAGATGAGCTTATCG-1 1_aplabeta_sample_1_AAAGATGAGCTTATCG-1
1_aplabeta_sample_1_AAAGATGCAGCTGTTA-1 1_aplabeta_sample_1_AAAGATGCAGCTGTTA-1
                                                                               CTgene
1_aplabeta_sample_1_AAACGGGAGTCCATAC-1                                           <NA>
1_aplabeta_sample_1_AAACGGGCAGATAATG-1  TRAV2.TRAJ24.TRAC_TRBV6-1.TRBJ1-5.TRBD1.TRBC1
1_aplabeta_sample_1_AAACGGGTCGCCGTGA-1    TRAV6.TRAJ39.TRAC_TRBV27.TRBJ2-7.None.TRBC2
1_aplabeta_sample_1_AAACGGGTCGGACAAG-1 TRAV8-4.TRAJ37.TRAC_TRBV4-1.TRBJ1-4.None.TRBC1
1_aplabeta_sample_1_AAAGATGAGCTTATCG-1 TRAV9-2.TRAJ53.TRAC_TRBV19.TRBJ2-4.TRBD2.TRBC2
1_aplabeta_sample_1_AAAGATGCAGCTGTTA-1                NA_TRBV10-3.TRBJ2-6.TRBD1.TRBC2
                                                                                                                                    CTnt
1_aplabeta_sample_1_AAACGGGAGTCCATAC-1                                                                                              <NA>
1_aplabeta_sample_1_AAACGGGCAGATAATG-1             TGTGCTGTGGTACCTGACAGCTGGGGGAAATTCCAGTTT_TGTGCCAGCAGTGAAGAGGGGTCAGGGAATCAGCCCCAGCATTTT
1_aplabeta_sample_1_AAACGGGTCGCCGTGA-1                   TGTGCTTCGAATAATGCAGGCAACATGCTCACCTTT_TGTGCCAGCAGCCGTACCCCGGGGTCCTACGAGCAGTACTTC
1_aplabeta_sample_1_AAACGGGTCGGACAAG-1          TGTGCTGTGAGTGATCGGGGCTCTAGCAACACAGGCAAACTAATCTTT_TGCGCCAGCAGCCAATTCTCTAATGAAAAACTGTTTTTT
1_aplabeta_sample_1_AAAGATGAGCTTATCG-1 TGTGCTCTGACTGGAGGGAGTGGAGGTAGCAACTATAAACTGACATTT_TGTGCCAGTAGTAGCCGCTCGGACCTAACTAGAAACATTCAGTACTTC
1_aplabeta_sample_1_AAAGATGCAGCTGTTA-1                                            NA_TGTGCCATCAGTGAGGACAGGGGGCTCTCTGGGGCCAACGTCCTGACTTTC
                                                                    CTaa
1_aplabeta_sample_1_AAACGGGAGTCCATAC-1                              <NA>
1_aplabeta_sample_1_AAACGGGCAGATAATG-1     CAVVPDSWGKFQF_CASSEEGSGNQPQHF
1_aplabeta_sample_1_AAACGGGTCGCCGTGA-1       CASNNAGNMLTF_CASSRTPGSYEQYF
1_aplabeta_sample_1_AAACGGGTCGGACAAG-1    CAVSDRGSSNTGKLIF_CASSQFSNEKLFF
1_aplabeta_sample_1_AAAGATGAGCTTATCG-1 CALTGGSGGSNYKLTF_CASSSRSDLTRNIQYF
1_aplabeta_sample_1_AAAGATGCAGCTGTTA-1              NA_CAISEDRGLSGANVLTF
                                                                                                                                                                               CTstrict
1_aplabeta_sample_1_AAACGGGAGTCCATAC-1                                                                                                                                             <NA>
1_aplabeta_sample_1_AAACGGGCAGATAATG-1              TRAV2.TRAJ24.TRAC_TGTGCTGTGGTACCTGACAGCTGGGGGAAATTCCAGTTT_TRBV6-1.TRBJ1-5.TRBD1.TRBC1_TGTGCCAGCAGTGAAGAGGGGTCAGGGAATCAGCCCCAGCATTTT
1_aplabeta_sample_1_AAACGGGTCGCCGTGA-1                      TRAV6.TRAJ39.TRAC_TGTGCTTCGAATAATGCAGGCAACATGCTCACCTTT_TRBV27.TRBJ2-7.None.TRBC2_TGTGCCAGCAGCCGTACCCCGGGGTCCTACGAGCAGTACTTC
1_aplabeta_sample_1_AAACGGGTCGGACAAG-1          TRAV8-4.TRAJ37.TRAC_TGTGCTGTGAGTGATCGGGGCTCTAGCAACACAGGCAAACTAATCTTT_TRBV4-1.TRBJ1-4.None.TRBC1_TGCGCCAGCAGCCAATTCTCTAATGAAAAACTGTTTTTT
1_aplabeta_sample_1_AAAGATGAGCTTATCG-1 TRAV9-2.TRAJ53.TRAC_TGTGCTCTGACTGGAGGGAGTGGAGGTAGCAACTATAAACTGACATTT_TRBV19.TRBJ2-4.TRBD2.TRBC2_TGTGCCAGTAGTAGCCGCTCGGACCTAACTAGAAACATTCAGTACTTC
1_aplabeta_sample_1_AAAGATGCAGCTGTTA-1                                                           NA_NA_TRBV10-3.TRBJ2-6.TRBD1.TRBC2_TGTGCCATCAGTGAGGACAGGGGGCTCTCTGGGGCCAACGTCCTGACTTTC
                                       Frequency           cloneType
1_aplabeta_sample_1_AAACGGGAGTCCATAC-1        NA                <NA>
1_aplabeta_sample_1_AAACGGGCAGATAATG-1         1 Single (0 < X <= 1)
1_aplabeta_sample_1_AAACGGGTCGCCGTGA-1         1 Single (0 < X <= 1)
1_aplabeta_sample_1_AAACGGGTCGGACAAG-1         1 Single (0 < X <= 1)
1_aplabeta_sample_1_AAAGATGAGCTTATCG-1         1 Single (0 < X <= 1)
1_aplabeta_sample_1_AAAGATGCAGCTGTTA-1         1 Single (0 < X <= 1)


head(rownames(sample1.singlet@meta.data))
[1] "1_aplabeta_sample_1_AAACGGGAGTCCATAC-1"
[2] "1_aplabeta_sample_1_AAACGGGCAGATAATG-1"
[3] "1_aplabeta_sample_1_AAACGGGTCGCCGTGA-1"
[4] "1_aplabeta_sample_1_AAACGGGTCGGACAAG-1"
[5] "1_aplabeta_sample_1_AAAGATGAGCTTATCG-1"
[6] "1_aplabeta_sample_1_AAAGATGCAGCTGTTA-1"

> head(combined.ab1[[1]])
                                  barcode     sample       ID
1  1_aplabeta_sample_1_AAACCTGGTACGCTGC-1 1_aplabeta sample_1
6  1_aplabeta_sample_1_AAACGGGCAGATAATG-1 1_aplabeta sample_1
8  1_aplabeta_sample_1_AAACGGGCATCACGAT-1 1_aplabeta sample_1
10 1_aplabeta_sample_1_AAACGGGTCGCCGTGA-1 1_aplabeta sample_1
12 1_aplabeta_sample_1_AAACGGGTCGGACAAG-1 1_aplabeta sample_1
14 1_aplabeta_sample_1_AAACGGGTCTTGCAAG-1 1_aplabeta sample_1
                  TCR1         cdr3_aa1
1                 <NA>             <NA>
6    TRAV2.TRAJ24.TRAC    CAVVPDSWGKFQF
8  TRAV8-6.TRAJ53.TRAC CAVSVRRGGSNYKLTF
10   TRAV6.TRAJ39.TRAC     CASNNAGNMLTF
12 TRAV8-4.TRAJ37.TRAC CAVSDRGSSNTGKLIF
14                <NA>             <NA>
                                           cdr3_nt1                        TCR2
1                                              <NA>                        <NA>
6           TGTGCTGTGGTACCTGACAGCTGGGGGAAATTCCAGTTT TRBV6-1.TRBJ1-5.TRBD1.TRBC1
8  TGTGCTGTGAGTGTACGTCGGGGAGGTAGCAACTATAAACTGACATTT  TRBV14.TRBJ2-2.TRBD1.TRBC2
10             TGTGCTTCGAATAATGCAGGCAACATGCTCACCTTT   TRBV27.TRBJ2-7.None.TRBC2
12 TGTGCTGTGAGTGATCGGGGCTCTAGCAACACAGGCAAACTAATCTTT  TRBV4-1.TRBJ1-4.None.TRBC1
14                                             <NA> TRBV4-1.TRBJ2-7.TRBD2.TRBC2
          cdr3_aa2                                      cdr3_nt2
1             <NA>                                          <NA>
6  CASSEEGSGNQPQHF TGTGCCAGCAGTGAAGAGGGGTCAGGGAATCAGCCCCAGCATTTT
8  CASSPGQRDTGELFF TGTGCCAGCAGCCCGGGACAGCGGGACACCGGGGAGCTGTTTTTT
10  CASSRTPGSYEQYF    TGTGCCAGCAGCCGTACCCCGGGGTCCTACGAGCAGTACTTC
12   CASSQFSNEKLFF       TGCGCCAGCAGCCAATTCTCTAATGAAAAACTGTTTTTT
14 CASSPDSGGGYEQYF TGCGCCAGCAGCCCGGATTCGGGGGGGGGCTACGAGCAGTACTTC
                                           CTgene
1                                            <NA>
6   TRAV2.TRAJ24.TRAC_TRBV6-1.TRBJ1-5.TRBD1.TRBC1
8  TRAV8-6.TRAJ53.TRAC_TRBV14.TRBJ2-2.TRBD1.TRBC2
10    TRAV6.TRAJ39.TRAC_TRBV27.TRBJ2-7.None.TRBC2
12 TRAV8-4.TRAJ37.TRAC_TRBV4-1.TRBJ1-4.None.TRBC1
14                 NA_TRBV4-1.TRBJ2-7.TRBD2.TRBC2
                                                                                             CTnt
1                                                                                            <NA>
6           TGTGCTGTGGTACCTGACAGCTGGGGGAAATTCCAGTTT_TGTGCCAGCAGTGAAGAGGGGTCAGGGAATCAGCCCCAGCATTTT
8  TGTGCTGTGAGTGTACGTCGGGGAGGTAGCAACTATAAACTGACATTT_TGTGCCAGCAGCCCGGGACAGCGGGACACCGGGGAGCTGTTTTTT
10                TGTGCTTCGAATAATGCAGGCAACATGCTCACCTTT_TGTGCCAGCAGCCGTACCCCGGGGTCCTACGAGCAGTACTTC
12       TGTGCTGTGAGTGATCGGGGCTCTAGCAACACAGGCAAACTAATCTTT_TGCGCCAGCAGCCAATTCTCTAATGAAAAACTGTTTTTT
14                                               NA_TGCGCCAGCAGCCCGGATTCGGGGGGGGGCTACGAGCAGTACTTC
                               CTaa
1                              <NA>
6     CAVVPDSWGKFQF_CASSEEGSGNQPQHF
8  CAVSVRRGGSNYKLTF_CASSPGQRDTGELFF
10      CASNNAGNMLTF_CASSRTPGSYEQYF
12   CAVSDRGSSNTGKLIF_CASSQFSNEKLFF
14               NA_CASSPDSGGGYEQYF
                                                                                                                                        CTstrict
1                                                                                                                                           <NA>
6            TRAV2.TRAJ24.TRAC_TGTGCTGTGGTACCTGACAGCTGGGGGAAATTCCAGTTT_TRBV6-1.TRBJ1-5.TRBD1.TRBC1_TGTGCCAGCAGTGAAGAGGGGTCAGGGAATCAGCCCCAGCATTTT
8  TRAV8-6.TRAJ53.TRAC_TGTGCTGTGAGTGTACGTCGGGGAGGTAGCAACTATAAACTGACATTT_TRBV14.TRBJ2-2.TRBD1.TRBC2_TGTGCCAGCAGCCCGGGACAGCGGGACACCGGGGAGCTGTTTTTT
10                   TRAV6.TRAJ39.TRAC_TGTGCTTCGAATAATGCAGGCAACATGCTCACCTTT_TRBV27.TRBJ2-7.None.TRBC2_TGTGCCAGCAGCCGTACCCCGGGGTCCTACGAGCAGTACTTC
12       TRAV8-4.TRAJ37.TRAC_TGTGCTGTGAGTGATCGGGGCTCTAGCAACACAGGCAAACTAATCTTT_TRBV4-1.TRBJ1-4.None.TRBC1_TGCGCCAGCAGCCAATTCTCTAATGAAAAACTGTTTTTT
14                                                               NA_NA_TRBV4-1.TRBJ2-7.TRBD2.TRBC2_TGCGCCAGCAGCCCGGATTCGGGGGGGGGCTACGAGCAGTACTTC
   cellType
1      T-AB
6      T-AB
8      T-AB
10     T-AB
12     T-AB
14     T-AB

head(names(sample1.singlet$active.ident))
Error: Cannot find 'active.ident' in this Seurat object

However,
head(Idents(sample1.singlet))
AAACGGGAGTCCATAC AAACGGGCAGATAATG AAACGGGTCGCCGTGA AAACGGGTCGGACAAG
               3                2                0                1
AAAGATGAGCTTATCG AAAGATGCAGCTGTTA
               0                1
Levels: 0 1 2 3 4 5 6


Thank you for your time and help!

Miriam
________________________________

**Comment by ncborcherding** [comment]
Hey Miriam,

Thanks for the info!

I think what might be happening here is although `combineExpression()` works as intended your call of:

`rownames(sample1.singlet@meta.data) <- paste0( "1_gammadelta_sample_1_", rownames(sample1.singlet@meta.data), "-1")`

Changes the rownames of your meta data, but that causes a mismatch in your seurat object. Thus calling `DimPlot(seurat)` where the default is active.ident, you are getting an error because your meta data barcodes no longer match your active.ident. 

Instead of the above, where you just modify the rownames of your meta data, have you tried using the Seurat function `RenameCells()`?

Something like this would convert all the barcodes to the same format 
```
##similar to your approach but saving the new names as a vector to feed into RenameCells()
cell.names <- rownames(sample1.singlet[[]])
cell.names <- paste0( "1_gammadelta_sample_1_", cell.names) 
sample1.singlet <- RenameCells(sample1.singlet, new.names = cell.names)
```

Nick

**Comment by sopenaml** [comment]
Hi Nick,

I see, thank you very much for your response, I didn't know about RenameCells().
That's very helpful!


Miram

________________________________

**Comment by ncborcherding** [comment]
Glad to help, let me know if you have any further issues or suggestions!
