### ISSUE TITLE
Unexpected behaviour of `filter.graph` in `clonalNetwork`?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [ncborcherding/scRepertoire#376]
Hi Nick, 

Thank you for the tool! 

When I used `filter.graph=T`, only TMNC only shared with PBMC, but when I used `filter.graph=T`, there were now also sharing with `TMNC` as below. 

Could you help me understand the difference? I thought filter.graph will only remove the arrows pointing back and it does not remove actual sharing?

Thank you again for your help.

```
clonalNetwork(proporTbyTCR_Tissue_Type, group.by = "Tissue_Cell_Leiden_w14TTMNC_CD8_26_MapQueryPBMCs_clusterID", cloneCall = "gene", filter.clones = NULL, filter.identity = NULL, chain="both", exportTable = T, reduction = "umap", filter.graph = F) -> df1

df1 %>% dplyr::filter(from == "TMNC_CD8T_25")

```

<img width="256" alt="Screenshot 2024-06-06 at 00 45 29" src="https://github.com/ncborcherding/scRepertoire/assets/62179082/5b56138d-f9f2-4a95-85f2-0a709b8e87d7">

```
clonalNetwork(cxcr5posnegcd8_TCR_TonsilPBMC_OnlyP230_contig_list_combined_wTonsilrefPBMCquery_MERGED_cd8_cxcr5posneg_T230T240T246.data_filtergene_filtercell_list_IndividualDatasetMERGED_denovoUMAP_proporTbyTCR_Tissue_Type, group.by = "Tissue_Cell_Leiden_w14TTMNC_CD8_26_MapQueryPBMCs_clusterID", cloneCall = "gene", filter.clones = NULL, filter.identity = NULL, chain="both", exportTable = T, reduction = "umap", filter.graph = T) -> df1

df1 %>% dplyr::filter(from == "TMNC_CD8T_25")
```
<img width="293" alt="Screenshot 2024-06-06 at 00 46 27" src="https://github.com/ncborcherding/scRepertoire/assets/62179082/9becb145-e74c-4494-9deb-a9c292127848">

**Comment by ncborcherding** [comment]
Hey Quang, 

Without more info (or full screen shots) it will be hard to troubleshoot - please see Hadley's rundown of a [reproducible example ](http://adv-r.had.co.nz/Reproducibility.html). If data privacy is a concern, please make an example with the built-in data from scRepertoire. 

Thanks,
Nick
