### ISSUE TITLE
Understand difference of NA and none in BCR sequence

### ISSUE THREAD

**Issue by MariusMathies** [ncborcherding/scRepertoire#378]
Hi Nick,

I was wondering what's the difference between NA and none, when calling the BCR sequence of CDR3. I did not find the information on the website, maybe I have missed that.

<img width="194" alt="Screenshot 2024-06-06 at 11 25 16 AM" src="https://github.com/ncborcherding/scRepertoire/assets/64126902/9d1e6cda-1e10-45d8-96e7-c78bc6c0e600">

Thank you very much!

Best,
Marius

**Comment by ncborcherding** [comment]
Hey Marius, 

This is likely a result of the pipeline/platform designating a cdr3 as either NA or None. scRepertoire does not change "none" hence why you are getting both. 

Hope that helps,
Nick

**Comment by MariusMathies** [comment]
Hi Nick,

Thank you very much for your quick response. I am a bit confused because I used, as in the Vignette, the filtered_contig_annotations.csv output from the 10x Genomics Cell Ranger. Did you have similar outputs?

Best,
Marius

**Comment by MariusMathies** [comment]
Thank you very much!
