### ISSUE TITLE
what is the proportion(y axis) in compareClonotypes() function?

### ISSUE THREAD

**Issue by ilovegreentea** [ncborcherding/scRepertoire#379]
what is the proportion(y axis) in compareClonotypes() function?

I'm wonder why the maximum of y axis is not 1..
if that is proportion, then the value should be 0 to 1 .

Anyone know how calculated the proportion?? then just let me know please..

thank you so much

**Comment by ncborcherding** [comment]
Hey @ilovegreentea, 

Proportion refers to the the: number of copies of single clonotype / total number of clones. 

A clone with 5 copies in a sample with 100 receptor sequences would be 0.05. 

Unless you are mapping a lot of clones or have samples with heavily expanded sequences, generally the total proportion stays low. ggplot picks the y-axis, but you could modify that.

Hope that helps,
Nick
