### ISSUE TITLE
Question : compareClonotypes output >number of top clones

### ISSUE THREAD

**Issue by paulrbuckley-kcl** [ncborcherding/scRepertoire#380]
Hi

Thanks for making a great package.

I have a question re compareClonotypes function - i am using an older version AFAIK.

I am using the following code to loop through a load of patients and plot clones across timepoints. You will note I am asking for the top 10, I am wondering how this works as at TP1 (left side) i have more than ten clones? An example plot is attached. I am wondering if you could help explain please

Thank you

```

foreach(i=1:length(unique(uncorrected$patient_id)))%do% {

patient = (unique(uncorrected$patient_id))[i]
subset <- subsetContig(combined_TCR, name = "patient_id", 
                       variables = patient)

response = colData(uncorrected) %>% as.data.table() %>% dplyr::filter(patient_id == patient) %>% pull(response) %>% unique()
SAMPLES = colData(uncorrected) %>% as.data.table() %>% dplyr::filter(patient_id == patient)%>% select(ID_SAMPLE)%>% pull() %>% unique()%>% sort()       
options(repr.plot.height=7,repr.plot.width=15,repr.plot.res=300)

plot = compareClonotypes(subset,  
                  samples = SAMPLES, 
                  cloneCall="aa", 
                  numbers=10,
                  graph = "alluvial")+ggtitle(paste0("Patient ID: ",patient," Response: ",response))
    
}
```

<img width="1545" alt="Screenshot 2024-06-07 at 17 37 45" src="https://github.com/ncborcherding/scRepertoire/assets/117730072/76a9d789-340e-4d41-b8db-d97a8dda26aa">

**Comment by ncborcherding** [comment]
Hey Paul, 

Not knowing which version you are using exactly - there can be 2 things causing this. 

- Tied clones (in terms of proportion) will be displayed.
- Depending on version, numbers is either referring to total number or number by grouping variable (so here if there are 4 groups, it will be asking for the top 40 clones, presumably with a large overlap).

Hope that helps - let me know if you have any other questions.
Nick
