### ISSUE TITLE
Make hyperexpanded clones appears clearly and big/large

### ISSUE THREAD

**Issue by synatkeamsk** [ncborcherding/scRepertoire#382]
Hi Nick, 

Hope you are well. I have integrated single cell and TCR seq. I would like to make the hyperexpanded clones appear in big/large dots (kindly one I circled in red). Do you have any functions to make it appear clearly in very large dot. Or you have any manual technique to change the color in hyperexpanded clones manually to make it distinct from others, so reviewers will spot them immediately. 

I have attached the previous publication I found and they make the TCR dot appears large. Not sure what they did because I could not find any script. 

Also, could we combine single (0<X<=1) and small (1< X<=5) together? Thanks for your help so far.  Following are my codes!

```# Integration of T cells and TCR
integrated.obj.T <- combineExpression(combined, seurat.obj.T, 
                            cloneCall = "gene", 
                            proportion = FALSE, 
                            cloneSize  = c(Single=1, Small=5, Medium=20, Large=100, Hyperexpanded=500))
view(integrated.obj.T@meta.data)

#Dimplot 
colorblind_vector <- hcl.colors(n=7, palette = "inferno", fixup = TRUE)   # inferno

#integrated.obj.T@meta.data$group<- factor(integrated.obj.T@meta.data$group, levels = c("Osteoarthritis", "ICI-arthritis"))
integrated.obj.T@meta.data$type<- factor(integrated.obj.T@meta.data$type, levels = c("Osteoarthritis", "First arthritis", "Second arthritis"))

interated.T<- DimPlot(integrated.obj.T , group.by = "cloneSize", split.by = "type") +
  theme_classic() + 
  theme(plot.title = element_blank(), 
        legend.text = element_text(size= 13, face = "bold"), 
        strip.text = element_text(size = 14, face = "bold")) + 
  theme(legend.position = "top") +
  NoAxes() + 
  scale_color_manual(values=rev(colorblind_vector[c(1,3,4,5,7)]))
interated.T
``` 
Kind Regards,

![integration](https://github.com/ncborcherding/scRepertoire/assets/121846660/21db636e-b8dc-4f17-a615-df9973343142)

![Capture](https://github.com/ncborcherding/scRepertoire/assets/121846660/c0950700-0387-41b9-a3ed-1771d343d964)

**Comment by Qile0317** [comment]
Will write in more detail when I get time later - a rough solution is to get the umap ggplot, and take the `umap_plot$data` and modify it accordingly, and the manually replotting with custom ggplot instructions. Alternative - I recommend you to check out [APackOfTheClones](https://github.com/Qile0317/APackOfTheClones), a CRAN package that provides you an alternative way to visualize expanded clones as accurately sized circles with a scRepertoire seurat object. If you have your `Idents(seuratObject)` correctly assigned, then plotting is as simple as `APackOfTheClones::vizAPOTC(seuratObject)`
