### ISSUE TITLE
clonalNetwork 

### ISSUE THREAD

**Issue by Anikagir** [ncborcherding/scRepertoire#383]
Hi, can you tell me what the weight column represents when I run the following code? Thanks.
shared.clones <- clonalNetwork(sce, 
                                reduction = "umap", 
                                group.by = "cell_type",
                                cloneCall = "aa", 
                                exportTable=T)

**Comment by ncborcherding** [comment]
Thanks for the question - the weight is the mean proportion of the shared clones between clusters (or other grouping variable).

Nick
