### ISSUE TITLE
Functions not working

### ISSUE THREAD

**Issue by sumanta-barman** [ncborcherding/scRepertoire#387]
Hello scRepertoire team,

I have installed scRepertoire version 2.0.4. Unfortunately most of the functions (e.g. clonalQuant, clonalCompare) are not working. Could you please have a look?

Thank you,
Sumanta

**Comment by Qile0317** [comment]
Do you have any reproducible examples? SessionInfo? Everything seems to be in order on my machine. Are you sure you have valid inputs?

**Comment by sumanta-barman** [comment]
Strangely some functions did not work yesterday, now everything is working. Thank you.

**Comment by bebejhun** [comment]
how did you resolve this problem? I'm having the same issue.
