### ISSUE TITLE
Clarification regarding (1) the output of differential enrichment of enrichment scores and (2) negative enrichment scores

### ISSUE THREAD

**Issue by denvercal1234GitHub** [ncborcherding/scRepertoire#395]
Hi Nick, 

Thanks again for a great tool. When you get a moment, would you mind helping me understand the following points?

**Q1.** I was wondering about the whether the output of `FindAllMarkers` on the enrichment scores would be interpreted similarly as for the expression data? Specifically, does the gene sets that have `avg_log2FC` >0 represent gene sets that are "enriched" but then how do we interpret the `avg_log2FC` <0?

**Q2.** Relatedly, what do the negative enrichment scores represent in 'runEscape`? 

**Q3.** When we set `make.positive=F` the normalised enrichment scores, is it correct that we can only say the higher the positive enrichment scores, the more greatly a gene set is enriched, but cannot say that a gene set with very small enrichment score is not enriched)?

Thank you for your help!

**Comment by ncborcherding** [comment]
Hey @denvercal1234GitHub 

Thanks for reaching out. 

1. Yes. The output of ```escape.matrix()``` or ```runEscape()``` is an enrichment score, which is the maximum value that the gene set reaches along the walk of the ranked genes (at least for GSVA and ssGSEA). Good info on the method can be found [here](https://docs.gsea-msigdb.org/#GSEA/GSEA_User_Guide/#viewing-analysis-results). Differential methods will calculate the p-value and log2-fold change between the enrichment values by grouping of the individual cells and avg_log2FC > 0 would be "enriched". 

2. During the calculation of enrichment, you can have a negative value for enrichment based on where the gene set lies on the ranked gene list. 

3. A positive score means enriched. I think the best policy might be defining a cut-off based on empirical values. For instance, saying mean enrichment score for a cluster above > 10 were evaluated. 

Hope that helps, 
Nick

**Comment by denvercal1234GitHub** [comment]
Thanks, Nick. Very helpful.

One clarification about the heatmap.

After I ran escape::performNormalization(make.positive = T, scale.factor = obj$nFeature), I then used the result as input to escape::heatmapEnrichment(assay = "runEscape.ssGSEA_C5_GOBP_normalized".

But, when running escape::heatmapEnrichment(), I am still a bit confused why setting scale=T here in escape::heatmapEnrichment() would return the scores now being again negative? And, when setting scale=F in escape::heatmapEnrichment(), the values range stays positive.

[Should have been posted in https://github.com/ncborcherding/escape/issues/108]

**Comment by ncborcherding** [comment]
```scale=TRUE``` will center and scale values using a z distribution - so by definition there will be cells with negative, zero and positive values. ```scale=FALSE`` will maintain the normalized or non-normalized enrichment values for each cell - there is a bias towards positive values based on the calculation of the enrichment score.
