### ISSUE TITLE
New cloneCall option to more closely match `immunarch` options?

### ISSUE THREAD

**Issue by jeremymsimon** [ncborcherding/scRepertoire#396]
Hi @ncborcherding I'm wondering if it's at all possible to include another option in `cloneCall` to be CDR3 AA + V + J, which would more closely match `immunarch`'s `TrackClonotypes(aa+v+j)` function. 

`strict` in your options includes the `C` gene, which is one notch more stringent, and `aa` of course only includes the CDR3 amino acid sequence alone. 

Since we're using both it would be amazing if we could be sure all groupings are done consistently

Thanks!

**Comment by ncborcherding** [comment]
Hey @jeremymsimon 

I think you make a great point - that ideally there would be a matching option between the 2 workflows - immunarch and scRepertoire. I think the fundamental problem with making the change would be interupting/changing clonal definitions for users, which makes me hesitate. 

I think a work around would be to modify the CTstrict column using something like the stringr package. As along as the header is the same, there should be no break in any of the downstream functions. 

I will think more on this though - I have been really interested in making scRepertoire as compatible with other workflows. 

Thanks,
Nick

**Comment by jeremymsimon** [comment]
That would be great! Keep me posted, happy to help with testing as well

**Comment by jeremymsimon** [comment]
Hi @ncborcherding any updates on this?

**Comment by ncborcherding** [comment]
@jeremymsimon 

I think for the near term, we won't update the definition of strict clonotype - I do not want to change definitions for the majority of users.

I will update scRepertoire for a new release through bioconductor 3.21

Nick

**Comment by jeremymsimon** [comment]
Hey @ncborcherding - totally understand not being destructive about the change. Do you think it's possible to introduce an alternative matching criteria choice that could potentially align with how immunarch does it in `TrackClonotypes` ?
