### ISSUE TITLE
could not find function "quantContig" 

### ISSUE THREAD

**Issue by Lingxuewang** [ncborcherding/scRepertoire#398]
I encountered this error: 

p1 <- quantContig(combined, cloneCall="gene+nt", scale = F) +   theme(axis.text.x = element_text(angle = 30,vjust = 0.85,hjust = 0.75))
Error in quantContig(combined, cloneCall = "gene+nt", scale = F) : 
  could not find function "quantContig" . 
The package scRepertoire 2.0.5 has been installed and loaded. I tried to reinstalled different  version of this package but still didn't work.

**Comment by ncborcherding** [comment]
`quantContig()` is the version 1.x.x nomenclature. For anything >= version 2, it is now `clonalQuant()`.

Hope that helps,
Nick

**Comment by Lingxuewang** [comment]
Thank you very much! It works.
