### ISSUE TITLE
[question] Comparsion of the "same" clones btwn samples

### ISSUE THREAD

**Issue by jinhys** [ncborcherding/scRepertoire#399]
Hi @ncborcherding, 

Thank you for developing this very useful tool!

I would like to ask whether we can extract **[raw_clonotype_id]** values for top clones selected from the `clonalCompare()` function. If this is not part of the package (yet), I would like to hear about your suggestions on an efficient way to extract these IDs.

---
_To give you further details:_ 
I'm analyzing a patient's longitudinal TCR data and I found that there are some **recurrent** clonotypes across the samples. 

These are the columns I get if I use the `clonalCompare(exportTable = T)`:
![table](https://github.com/user-attachments/assets/ea3bf5a2-9836-46d2-b4a3-fb6ae83b94de)

So far, I've collected the information on these clones using all modes (i.e., "aa", "gene", "nt", and "strict") and the contig file. Especially, in the "aa" mode, I noticed that each CDR3 sequence maps to multiple [raw_clonotype_ids] but there is only one [raw_clonotype_id] that matches between the 2-3 CDR3 sequences. 

Also, certain clones are composed of more than 1 TRA and 1 TRB chain (e.g., 2 TRAs + 1 TRB _or_ 1 TRA + 2 TRBs). As an example, I can tell that this clone's clonotype ID is "clonotype22" in [sample A] by checking the common [raw_clonotype_ids] across the CDR3 sequences:
![example](https://github.com/user-attachments/assets/2e0638c4-8d71-40af-bdc2-0e06019ee221)

Regarding this, I was wondering whether we can extract [raw_clonotype_id] values for each row included in the table exported using the `clonalCompare()` function.

---

As far as I understand, [raw_clonotype_ids] are uniquely assigned _within each sample_. So, if we could extract these IDs from the `clonalCompare()` function, I thought it would be much easier to track clones-of-interest across multiple samples.

Thanks for reading this and please let me know if you need further details.

Looking forward to hearing from you soon!

**Comment by ncborcherding** [comment]
Hwy @jinhys 

Unfortunately scRepertoire does not retain the raw_clonotype_id from the 10x output, so you will not be able to extract that from ```clonalCompare()```. Because raw_clonotype_id is defined uniquely by sample, that is why scRepertoire avoids using them in clonal definition - what is clontype22 in one sample is completely different in another sample. 

I'll have to think more on if that would be possible in the future to have a distinct clonotype definition - however, that is complicated that not all workflows will define that.

**Comment by jinhys** [comment]
Thank you for the quick reply, @ncborcherding!

I see, thanks for the detailed explanation as well. I agree with you - I've been working on extracting each CDR3 sequence's [raw_clonotype_ids], but they're all varied in different samples. 

Please let us know if you find a better solution! I will stay tuned :)
