### ISSUE TITLE
Following clonotypes between SEURAT clusters

### ISSUE THREAD

**Issue by EAC-T** [ncborcherding/scRepertoire#40]
Hi All,

Thank you so much for developing this convenient package, it's great that we can use it with SEURAT.
I have T cells that I clustered, I think they are differentiating from naive-->Effector-->Memory and during this differentiation process, a unique T cell will keep the same TCR. I was wondering how can I see if different clusters share any clonotype? I'm not sure I found something like that in the vignette. 

Thank you again!

**Comment by ncborcherding** [comment]
Hey EAC-T,

I think there are a couple of ways to visualize this sort of relationship. 

The most direct way is to take the seurat object after `combineExpression` and use `expression2List()` to convert the meta data into a list. Then you can look at the overlap of unique clonotypes.

```
combined2 <- expression2List(seurat, group = "cluster")
clonalOverlap(combined2, cloneCall="aa", method="overlap")
```

Another option in terms of visualizations are the alluvial and chord-based diagrams after the `combineExpression()` call.

`alluvialClonotypes` will group the TCR sequencings into clones and allow you to visualize the clones between whatever groups are present in you meta data - so below we are looking at the vectors **Patient, cluster, and Type** that is in seurat[[]] or seurat@meta.data.

```
alluvialClonotypes(seurat, cloneCall = "gene", 
                   y.axes = c("Patient", "cluster", "Type"), 
                   color = "cluster") 
```

The other visualization is a chord diagram from the circlize package, scRepertoire has a function `getCirclize()` to order the clonotype information to help with the visualization. I would just note that unlike above - the relationship here is going to show unique clonotypes shared between clusters, so everything is relative to unique clonotypes as opposed to T cell number.

```
library(circlize)
library(scales)

circles <- getCirclize(seurat, groupBy = "cluster")

#Just assigning the normal colors to each cluster
grid.cols <- scales::hue_pal()(length(unique(seurat@active.ident)))
names(grid.cols) <- levels(seurat@active.ident)

#Graphing the chord diagram
circlize::chordDiagram(circles, self.link = 1, grid.col = grid.cols)
```
I am going to close the issue (as this is not an active problem with code), but please feel free to keep posting and we can troubleshoot anything you need. I think this would be a good reference for other users. 

Thanks,
Nick

**Comment by EAC-T** [comment]
Hi Nick,
I have tried the code you sent. I'm wondering how can I get the list of clones that overlap between 2 clusters?
I did this:
combined2 <- expression2List(seurat, group = "cluster")
clonalOverlap(combined2, cloneCall="aa", method="overlap")
the heatmap is intersting and I think there is overlap, I just need to pull out the info, like the sequence so I can visualize it on a UMAP.

Thank you again.

**Comment by ncborcherding** [comment]
Hey EAC-T,

This is actually a great question and maybe should be included in the vignette for other users. 

Should be able to generate a list of overlap using `intersect()` and the corresponding combined2 elements for the clusters of interest.

```
combined2 <- expression2List(seurat, group = "cluster")
overlap <- intersect(combined2[[x]]$CTaa, combined2[[y]]$CTaa)
```

Hope that helps and let me know if you have any other questions.

Nick

**Comment by EAC-T** [comment]
Hi Nick,
Thank you for your help,
Ok so I was able to find the clones that are shared between clusters and then plot them on UMAP,
I tried to get the number of cells from each cluster that express the clone CTaa sequence but I couldn't do it.
Any idea how I can get the number of cells?

Thank you again

**Comment by ncborcherding** [comment]
Hey EAC-T,

I can think of a rough way to do it:

```
#SpecificAA is the sequence
length(which(combined[[x]]$CTaa == "specificAA",]
```

If you are wanting to compare more than 1 specificAA, I would think about maybe a loop. The loop below will return a named character vector in 1 cluster with your specific AAs of interest. **Warning** this was written without R near by, so it might involve a little tweaking. 

```
#SpecificAA is the sequence
listAA <- c("specificAA1", "specificAA2", ...)

output <- NULL #generate something to store the lengths
for (i in seq_along(listAA)) {
    num <- length(which(combined[[x]]$CTaa == listAA[i],]
    output <- c(output,num)
}
names(output) <- listAA #name the specific lengths
```

Hope that helps,
Nick

**Comment by christoforos-dimitropoulos** [comment]
Hello, I have a related question thus I will not open a new issue.
In my seurat object I have a metadata column which classifies the cells in two categories (lets say A and B)
Is ther away to do an alluvialClonotypes plot but instead of having clusters in one column and an other metadata column compared, can I have a column for A and a column for B and see the overlap of the clones?

**Comment by ncborcherding** [comment]
Hey Christoforos, 

Thanks for reaching out, alluvial graphs with A and B columns might work if there are different variables, but I am not sure how NA values would affect the construction of the chords/ribbons. An alternative might be to place your clonotype variable first and then use your meta data column of interest. This would create ribbons for every clonotype that you can then see where they go in A and B variables


```
alluvialClonotypes(seurat, cloneCall = "gene", 
                   y.axes = c("CTaa", "meta.column", "other.meta.data"))
```

**Comment by christoforos-dimitropoulos** [comment]
> Hey Christoforos,
> 
> Thanks for reaching out, alluvial graphs with A and B columns might work if there are different variables, but I am not sure how NA values would affect the construction of the chords/ribbons. An alternative might be to place your clonotype variable first and then use your meta data column of interest. This would create ribbons for every clonotype that you can then see where they go in A and B variables
> 
> ```
> alluvialClonotypes(seurat, cloneCall = "gene", 
>                    y.axes = c("CTaa", "meta.column", "other.meta.data"))
> ```

OK cool, this might work. Is there a way to select which clones to visualize? for example only the top 10 clones (in terms of size)?

**Comment by christoforos-dimitropoulos** [comment]
And one mor thing: when I try to do use the clonaloverlay function I get this:

Error in clonalOverlay(seu_merge_tcr, reduction = "umap", freq.cutpoint = 30,  : 
  could not find function "clonalOverlay"

I have installed the dev version, is it the right one?

**Comment by ncborcherding** [comment]
> OK cool, this might work. Is there a way to select which clones to visualize? for example only the top 10 clones (in terms of size)?

One alternative might be to use ```expression2List()``` to get the combined data based on A or B (will return a 2 element list) and then you can use ```compareClonotype()``` select the top X clones. The y-axis can be scaled for proportion, so you will be reporting the relative proportion of the specific clones in A and B and also looking at the interaction of the two.

> Error in clonalOverlay(seu_merge_tcr, reduction = "umap", freq.cutpoint = 30,  : 
  could not find function "clonalOverlay"

```clonalOverlay()``` is in the most recent dev version (1.3.4), have you tried restarting your R instance since installing? The error you are receiving makes me suspect either that or not the same version.

**Comment by ASNbioinf** [comment]
I have a similar problem to @EAC-T. I have T cells that I clustered. There are clones shared between samples that belong to the same patient. I used `clonalCompare()` to show the **proportion** of each clone within the specified samples. Is there a function that allows me to plot the **frequency** of each clone within the specified samples.
