### ISSUE TITLE
interpretation of BCR clones with BCRstrict

### ISSUE THREAD

**Issue by jjs847** [ncborcherding/scRepertoire#403]
I am looking at the top clones in my dataset but I don't understand how clones are assigned without IGH information. What do the NAs mean? 

NA.NA_IGLC:Cluster.11.IGKV1D-39
NA.NA_IGLC:Cluster.36.IGKV3-20
NA.NA_IGLC:Cluster.36.IGKV3-15
NA.NA_IGLC:Cluster.11.IGKV4-1
NA.NA_IGLC:Cluster.58.IGLV2-8
NA.NA_IGLC:Cluster.12.IGKV1-12
NA.NA_IGLC:Cluster.68.IGLV2-23
NA.NA_IGLC:Cluster.83.IGLV3-25
IGH:Cluster.524.IGHV3-7_IGLC:Cluster.36.IGKV3-15
IGH:Cluster.1253.IGHV3-33_IGLC:Cluster.36.IGKV3-15

**Comment by ncborcherding** [comment]
Hey @jjs847,

The CTstrict column will assign clones using a 2 step approach - 1) calculate the edit distance across all cdr3s and if connected to other sequences form clusters, and 2) attach a vgene. 

In the examples you have above, here would be an example of the same cluster in terms of the light chain.

```
NA.NA_IGLC:Cluster.36.IGKV3-15
IGH:Cluster.524.IGHV3-7_IGLC:Cluster.36.IGKV3-15
```

The NA is in places in switch there is no sequence information. There is variable levels of Heavy or Light chains without the corresponding second chain within single-cell data. Using the 2 sequences above - I would suspect these may be the same clone, however it is hard to tell as the first sequence does not have a corresponding heavy chain. 

I hope that helps and let me know if you have any other questions. 

Nick

**Comment by jjs847** [comment]
thanks so much, this makes sense. Is it this normal in single-cell data that the light chain is captured way more than heavy chain transcripts? Also, is there documentation on the meaning of the output of CTstrict besides whats described here? https://www.borch.dev/uploads/screpertoire/articles/combining_contigs?

**Comment by ncborcherding** [comment]
I don't have any data for this, but I have observed that there is usually about a 80-90% overlap in light vs heavy chain cell recovery. I have not noticed a bias either way for single chains, but I have seen BCR with far more light chain calls when it comes to secondary chains in a single cell - so Heavy1_Light1, NA_Light2, NA_Light3.

The actual function itself has a definition as well: [https://www.borch.dev/uploads/screpertoire/reference/combinebcr](https://www.borch.dev/uploads/screpertoire/reference/combinebcr)
