### ISSUE TITLE
Can't capitalize custom variables in cloneCall

### ISSUE THREAD

**Issue by chloetu-dfci** [ncborcherding/scRepertoire#405]
Hi @ncborcherding! 

I noticed that using a capitalized variable name in `combineExpression's cloneCall` doesn't work! ie: `combineExpression(input, sc.obj, cloneCall="vdjaa")` works, but `combineExpression(input, sc.obj, cloneCall="VDJaa")` won't.

I think this happens in the function `.theCall`– the cloneCall variable is converted to lowercase via `.convertClonecall` before  there's a check for the variable in the inputs columns.

Thanks!

**Comment by ncborcherding** [comment]
Thanks will get it updated in the next commit!

Nick

**Comment by ncborcherding** [comment]
Got the fix up and running in the dev version, need to do more testing before I get it into the main branch and bioconductor.

Thanks again

Nick
