### ISSUE TITLE
error on subClones function

### ISSUE THREAD

**Issue by YuliangWang316** [ncborcherding/scRepertoire#408]
<img width="1578" alt="Screenshot 2024-09-23 at 15 55 13" src="https://github.com/user-attachments/assets/ac939e63-8f5b-41b4-9330-226272b5da6d">
my scRepertoire is 2.0.0 version

**Comment by ncborcherding** [comment]
Hey @YuliangWang316 

Make sure you have restarted the R session after the installation. If the problem persists, try re-installing scRepertoire. 

You can install the most up-to-date version using:
```
devtools::install_github("ncborcherding/scRepertoire")
```

Nick
