### ISSUE TITLE
Get p-value in clonal overlap

### ISSUE THREAD

**Issue by synatkeamsk** [ncborcherding/scRepertoire#411]
Dear Nick, 

Hope you are well. We have discussed with our team regarding heatmap of clonal overlap whether we can get p-value of the shared clones between samples (p<0.05 or p>0.05). Not sure we are able to do it using scRepertoire package. Thanks for your help. 

![Overlap](https://github.com/user-attachments/assets/c66f3fa3-ff88-4df7-b8ac-6addaad74d69)

Kind Regards, 

Synat

**Comment by ncborcherding** [comment]
Hey Synat

You can get the numbers to run your statistical test with `clonalOverlap(..., exportable = TRUE)`. From there you may need to filter to get the comparisons you're interested in and do the statistical test that is appropriate. Without more information I can't provide more details on the next step.

Hope that helps,
Nick
