### ISSUE TITLE
clonotypeBias sensible approach to calculating baseline frequency

### ISSUE THREAD

**Issue by jhjlee** [ncborcherding/scRepertoire#416]
Hi Nick,

Thanks for the wonderful tool.
I have a question about using clonotypeBias (or clonalBias). I have TCR data from multiple donors across multiple tissues. I am wondering what would be the most sensible way to calculate baseline frequency - is it using split.by on donor or tissue information? Thanks.

**Comment by ncborcherding** [comment]
Hey Joshua, 

Could you combine the donor and tissue into a single variable by concatenating them? Not sure if I can give you specific advice as the comparison should be based on the question you are trying to answer. 

Please let me know if you have any more information and happy to keep discussing. 

Nick
