### ISSUE TITLE
[Bug] Error when exportTable = TRUE for positionalProperty

### ISSUE THREAD

**Issue by pwwang** [ncborcherding/scRepertoire#420]
```R
library(scRepertoire)
data(contig_list)
data <- combineTCR(contig_list)

positionalProperty(data, exportTable = TRUE)

# Error in positionalProperty(data, exportTable = TRUE) : 
#  object 'mat_melt' not found
```

It is due to the typo here:

https://github.com/ncborcherding/scRepertoire/blob/3428d0875dda3a61384dcd80410a6cb90a91d81b/R/positionalProperty.R#L157

which should be `return(mat)`

**Comment by ncborcherding** [comment]
Hey thanks for finding another issue @pwwang. Much appreciated, will have it in the main branch after some tests. 

Also as an aside, very cool stuff you are doing with immunopipe! 

Nick

**Comment by pwwang** [comment]
@ncborcherding, I am currently developing an R package to visualize single-cell sequencing data. You can find it here: https://pwwang.github.io/scplotter/reference/index.html.

I want to thank you for your great work, which has given me the opportunity to work on this. Right now, I am re-implementing the visualization of scTCR/BCR-seq data and reviewing the APIs from scRepertoire. I have come across some bugs during this process.

I am almost finished with the re-implementation. It would be really helpful if you could hold version 2.0.8 for a couple of days while I review about 90% of the APIs, just in case I discover more bugs.

**Comment by ncborcherding** [comment]
Ok I will hold off on the pull request - do you want to make your own into the dev branch with the other bugs you find? That way your handle/name can be associated with the work you are doing on scRepertoire. I can make sure the documentation is updated and will then move everything to the main branch.

scplotter looks amazing! I love the different visualizations. Let me know when you are ready and I will make sure to shout it out on X/twitter - I think it will help a lot of researchers.

Nick

**Comment by pwwang** [comment]
Hi Nick,

Thank you for the offer to include my name on the contributor list. I haven't found any more bugs, but I did identify some areas that could be optimized. Specifically, when someone (like me) wants to export a table, the table should be returned eagerly, rather than after the plot is generated. Please let me know if this is a good point for improvement, and I will submit a pull request if so.

Thanks,
Panwen

**Comment by Qile0317** [comment]
> Hi Nick,
> 
> 
> 
> Thank you for the offer to include my name on the contributor list. I haven't found any more bugs, but I did identify some areas that could be optimized. Specifically, when someone (like me) wants to export a table, the table should be returned eagerly, rather than after the plot is composed. Please let me know if this is a good point for improvement, and I will submit a pull request if so.
> 
> 
> 
> Thanks,
> 
> Panwen

I agree that it's not needed to build the ggplot object first and the input to the plotting function probably can be returned first - go for it!

**Comment by pwwang** [comment]
Hi Nick, 

I just want to take a moment to thank you for tweeting scplotter. I appreciate it!

Thanks,
Panwen

**Comment by ncborcherding** [comment]
@pwwang 

My pleasure - let me know if you need anything in the future and always happy to collaborate.

Nick
