### ISSUE TITLE
potentially broken visualization of percentVJ on docsite

### ISSUE THREAD

**Issue by Qile0317** [ncborcherding/scRepertoire#422]
On the documentation site this is what I currently see:
![image](https://github.com/user-attachments/assets/69d6ddb6-bbbf-493d-9c6b-2071d8ae9f4c)

- The visualization looks like it's probably wrong? This also may be a problem with the rest of the vignette
- The docsite says it is based on scRepertoire 2.0.5 - is this intended?
- I haven't tested this personally yet - just something I spotted just now.

**Comment by ncborcherding** [comment]
This this is a product of the limited graphing size of the markdown. It does plot correctly. 

Deploying v2.0.8 website today. 

When you have your fixes/improvements, we will bump versions and get it in bioconductor.

**Comment by Qile0317** [comment]
> This this is a product of the limited graphing size of the markdown. It does plot correctly. 
> 
> 
> 
> Deploying v2.0.8 website today. 
> 
> 
> 
> When you have your fixes/improvements, we will bump versions and get it in bioconductor.

I see, thanks! A future workaround might involve some semi manual trial and error based rescaling of the output
