### ISSUE TITLE
loadContigs error when read TRUST4 output containing only 1 row

### ISSUE THREAD

**Issue by WuRAFY** [ncborcherding/scRepertoire#429]
Firstly thanks for the tool. When I load a bunch of TRUST4 files with the function `loadContigs`, I found that the error below would happen if the file list containing a file with only one row.

```
Error in `colnames<-`(`*tmp*`, value = c("v_gene", "d_gene", "j_gene",  : 
  attempt to set 'colnames' on an object with less than two dimensions
```
Here is the one-row file
https://1drv.ms/u/c/1aa2c7aee02dd080/Ebv7ISMqDRJFqwjPiBXMcxMBnmUu8EkOBzXPs6HR6AOaIA?e=MlpAoT

FY

**Comment by Qile0317** [comment]
@WuRAFY Thanks for reporting, found the issue and fix is on the way.

**Comment by Qile0317** [comment]
@WuRAFY #430 fixes the issue. If you are in urgent need of using the function, you can update your package with my fork using `devtools::install_github("Qile0317/scRepertoire@429")`
