### ISSUE TITLE
clonalOverlap() counting issue with  method = "overlap"

### ISSUE THREAD

**Issue by Ruismart** [ncborcherding/scRepertoire#43]
hi, it's been very convenient to quickly explore the sc-TCR data with scRepertoire.
I found that 'overlap' ratio might be calculated using 'number of overlapped clonotypes / cell number of smaller sample' but not '/ clonotype number of smaller sample', just report this.
 
in utils.R line 163:  " df.j_unique <- df.j[!duplicated(df.j$barcode),] " .

if this is combined df, then no need to uniq barcode, right ?  CTaa ?

**Comment by ncborcherding** [comment]
Hey Ruismart, 

Nice catch, you are absolutely correct. I am in the process of submitting a new version to bioconductor and will merge it with the master soon, but for now the overlap is updated in.

```
devtools::install_github("ncborcherding/scRepertoire@refine")
```
Thanks a ton,
Nick
