### ISSUE TITLE
quietBCRgenes not compatible with Seurat v5

### ISSUE THREAD

**Issue by timothyjtan** [ncborcherding/scRepertoire#434]
I am following the example here, using Seurat v5.0.2: https://www.borch.dev/uploads/screpertoire/articles/ibex#formation-of-the-single-cell-object, and when running this segment

> #Processing RNA
> DefaultAssay(MIS.sample) <- 'RNA'
> MIS.sample <- NormalizeData(MIS.sample) %>% FindVariableFeatures() %>% 
>   quietBCRgenes() %>% ScaleData() %>% RunPCA(verbose = FALSE)

I run into an error: 

> Error in is.factor(x) : 
>   no slot of name "var.features" for this object of class "Assay5"

To figure out where the error occurs, I removed the piping, and performed each step one at a time:

> MIS.sample <- NormalizeData(MIS.sample)
> MIS.sample <- FindVariableFeatures(MIS.sample, selection.method = "vst", nfeatures = 3000) 
> MIS.sample <- quietBCRgenes(MIS.sample, assay = "RNA")

After running quietBCRgenes, I get the error

> Error in is.factor(x) : 
>   no slot of name "var.features" for this object of class "Assay5"

I am using the following:
RStudio         v2024.09.0+375
R               v4.4.1
Seurat          v5.1.0
scRepertoire    v2.0.5
scCustomize     v2.1.2

**Comment by ncborcherding** [comment]
@timothyjtan 

Thanks for the issue - I am in the middle of updating both Ibex and Trex to be compatible with all versions of Seurat. Should be out by the end of November (I am training some additional models as we speak).

Nick

**Comment by timothyjtan** [comment]
Hey Nick, thanks for letting me know, and looking forward to the release for Seurat v5 compatibility! In the meantime, will using Convert_Assay from scCustomize to change the version of the 'RNA' assay of the Seurat object to v3 affect downstream analysis with Ibex?
I am integrating Ibex/scRepertoire with Seurat for combined analysis of RNA, ADT, and V(D)J.
Thanks!
