### ISSUE TITLE
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :    namespace ‘scRepertoire’ 1.10.1 is being loaded, but >= 2.0.8 is required

### ISSUE THREAD

**Issue by GaF123** [ncborcherding/scRepertoire#437]
When I was trying to install scplotter, it showed: Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘scRepertoire’ 1.10.1 is being loaded, but >= 2.0.8 is required

But the latest version is 2.0.5.

Please help.

many thanks

**Comment by Qile0317** [comment]
@GaF123 At the moment please install from the dev branch with devtools::install_github("ncborcherding/scRepertoire@dev")

**Comment by GaF123** [comment]
Thank you. but it still shows the package version is 1.10.1

**Comment by Qile0317** [comment]
> Thank you. but it still shows the package version is 1.10.1 

Have you reloaded the R session?

**Comment by GaF123** [comment]
Yes, it still shows:

Restarting R session...
> packageVersion("scRepertoire")
[1] ‘1.10.1’

**Comment by Qile0317** [comment]
@GaF123 Perhaps a cached or older installation of scRepertoire might still be loading, which would explain why version 1.10.1 keeps appearing even after you install from the dev branch. 

Try to completely restart whatever terminal / ide session you are in, then run `remove.packages("scRepertoire")` and afterwards `devtools::install_github("ncborcherding/scRepertoire@dev")` and restart again.

Either way, this is almost certainly not an issue with scRepertoire *package* itself.
