### ISSUE TITLE
Using expression2List()

### ISSUE THREAD

**Issue by zoqaiyum** [ncborcherding/scRepertoire#440]
Hi, 

I have v2.1.0 of the package. I understand that expression2List() function has been deprecated, however a slightly older tutorial I am using mentions this function in one of lines of code. Is there any way to use this again? Are there any alternatives if this function is gone forever?

Thank you!

**Comment by ncborcherding** [comment]
@zoqaiyum,

```expression2List()``` was causing a lot of questions from users, so the choice was made to deprecate it and support single-cell objects and the output of ```combineTCR()``` & ```combineBCR()``` for all functions. 

That being said, it does still exist and you can access it via ```scRepertoire:::.expresion2List()```. Notice 2 small changes here, we places a new **.** to mark it as an internal function and you can access via the 3 colons ***:::***. 

Hope that helps and good luck with your analysis. 

Nick

**Comment by zoqaiyum** [comment]
Hi @ncborcherding ,

I managed to access it, however when I call on group = myvariable, it gives me an error and says unused argument. Please see code below: 

`mergedseurat2_example_tcrbycluster <- scRepertoire:::.expression2List(mergedseurat2_example, group = "clusters_names_tissue")`

The error below: 
Error in scRepertoire:::.expression2List(mergedseurat2_example, group = "clusters_names_tissue") : 
  unused argument (group = "clusters_names_tissue")

If I try running this without the group argument completely, so just the scRepertoire:::.expression2List(mergedseurat2_example), I get the following: 

Error in scRepertoire:::.expression2List(mergedseurat2_example) : 
  argument "split.by" is missing, with no default

It appears that I need a split.by argument instead of group? Any insights would be helpful!

**Comment by Qile0317** [comment]
@zoqaiyum Yes, just use `split.by` or just omit the named argument. @ncborcherding I'll do a PR to re-export `expression2List` but with either a deprecation warning or keeping it defunct.
