### ISSUE TITLE
clonalOverlap() understanding which clonotypes are shared

### ISSUE THREAD

**Issue by zoqaiyum** [ncborcherding/scRepertoire#443]
Hello, 

Many thanks for your continued maintenance of this package and being so responsive with our questions. 

I used clonalOverlap with method="raw" to figure out which clonotypes are shared between my groups of interest, and used Complex Heatmap to plot the results 

<img width="328" alt="image" src="https://github.com/user-attachments/assets/976896a0-0c13-4115-ad72-569975d5f676">

As you can see from this image, there are 2 clonotypes that are shared between "InEx" and "ReA SFMC". Is there anyway to find out exactly which clonotypes are shared instead of how many?

**Comment by ncborcherding** [comment]
@zoqaiyum,

Unfortunately, ```clonalOverlap()``` does not store that information. 

You can get that info relatively easily using dplyr:

```
SeuratObj[[]] %>%
  filter(orig.ident %in% c("InEx", "ReA SFMC") %>%
  group_by(cluster, CTaa) %>%        # Group by both cluster and CTaa
  summarize(count = n()) %>%         # Count occurrences of each CTaa within each cluster
  filter(count > 1)  
  count()
```

Hope that helps - also make sure you change your label on your graph to "raw" and not Morisita Index (which is different)

Nick

**Comment by zoqaiyum** [comment]
Hi @ncborcherding 

Just to follow up on your suggestion, I ran the following code where I am comparing sample name "INEX" and "ReA SFMC" which are part of the variable called "Group" (I am really comparing how two levels of the variable Group share clonotypes): 

```
#gather data
a<- mergedseurat2[[]] %>%
  filter(Group %in% c("InEx", "ReA SFMC")) %>%
  group_by(Group, v_gene) %>%          # Group by v_gene
  summarize(count = n()) %>%  # Count occurrences of each v_gene within each group
  filter(count > 1)  
  count()
 
a<- na.omit(a) 

#create new data for each group
a_ReASFMC<- a %>% filter(Group == "ReA SFMC")
a_InEx<- a %>% filter(Group == "InEx")

#check which v_genes are shared between the two datasets
a_intersect<- intersect(a_ReASFMC$v_gene, a_InEx$v_gene)
print(a_intersect)
```

This then prints out which v genes are shared between INEX and ReA SFMC: 

<img width="878" alt="Screenshot 2024-11-15 at 14 04 09" src="https://github.com/user-attachments/assets/e1016937-dafa-4f56-84ef-0a315d902bdd">


However, now when I try to do the same but call on CTaa, I get character(0) as a result. This shouldn't be the case since I had used my seurat object as input for clonalOverlap() to get the heatmap in this thread above. The heatmap obtained earlier using "raw" method displayed that there are 2 clonotypes that are common between these two samples. Any insights on why I am unable to see the common clonotypes?

```
#gather data
a<- mergedseurat2[[]] %>%
  filter(Group %in% c("InEx", "ReA SFMC")) %>%
  group_by(Group, CTaa) %>%          # Group by CTaa
  summarize(count = n()) %>%  # Count occurrences of each CTaa within each group
  filter(count > 1)  
  count()

a<- na.omit(a)

#create new data for each group
a_ReASFMC<- a %>% filter(Group == "ReA SFMC")
a_InEx<- a %>% filter(Group == "InEx")

#check which CTaa are shared between the two 
a_intersect<- intersect(a_ReASFMC$CTaa, a_InEx$CTaa)
print(a_intersect)
```

<img width="394" alt="Screenshot 2024-11-15 at 14 11 23" src="https://github.com/user-attachments/assets/98d924b6-b118-43b5-95b7-69320e5b8e1b">


Many thanks as always!
