### ISSUE TITLE
How CompareClonotypes() function and HighlightClonotypes() differ ?

### ISSUE THREAD

**Issue by GauravJethva0** [ncborcherding/scRepertoire#444]
Dear scRepertoire Team,
Thank you for developing this useful and easy-to-use package to analyze TCR seq.
I started learning RNA-seq analysis a few months back now I am getting my hands on TCR seq of the same data.

To get to my question quickly, while embedding my TCR data into RNA  data, I am trying to see shared clones (which are identified from the Metadata) between my clusters of interest first by using **CompareClonotypes ()**

c1_c11_cc = compareClonotypes(processed_list_c,
                              clonotypes = c("CAAQTGANNLFF_CSARKRGTSGFQETQYF", 
                           "CAGAYSSASKIIF_CASSSRTISQNIQYF",
                           "CAAEGHTGFQKLVF_CASSIVRNTEAFF",
                           "CAAPHGSNFGNEKLTF_CAWSLRWDEQFF",
                           "CAFKGPGAQKLVF_CATLRGYGYTF",
                           "CAASNSGGGADGLTF;CAPTNAGKSTF_CASSLDGPYEQYF",
                           "CAASILQGGKLIF_CASSLEDRGGTEAFF",
                           "CAESGGTGRRALTF_CASSLGKAGPSGNTIYF",
                           "CAFLTGTASKLTF_CAGTGASTDTQYF",
                           "CAGNQAGTALIF_CAWSVQNYGYTF",
                           "CALNNAGNMLTF_CASRLGGHGYTF",
                           "CALSDLIRGGSSNTGKLIF_CASSWRQGAGNTIYF",
                           "CALSDTGARLMF_CASSPNFSGNTIYF",
                           "CALSDVFTGGGNKLTF_CASSVLGDTEAFF",
                           "CAMRPSNTGKLIF_CASSPGQLAKNIQYF"
                           ),
                                 cloneCall = "CTaa",
                  #samples = c("11", "1"),
                  graph = "alluvial",
                  chain = "both",
                  exportTable = F)
![Cmn_bw_c1_c11](https://github.com/user-attachments/assets/65e9a7c5-fc35-4dcb-9b75-da443fe04378)
              
With the above-mentioned code,  I see all clones are present in both clusters. However, when I try to plot them in UMAP using **HighlightClonotypes()**
# Higlight  specific clones
seurat_viz <- highlightClonotypes(seurat_cluster_object, 
              cloneCall= "CTaa", 
              sequence = c("CAAQTGANNLFF_CSARKRGTSGFQETQYF", 
                           "CAGAYSSASKIIF_CASSSRTISQNIQYF",
                           "CAAEGHTGFQKLVF_CASSIVRNTEAFF",
                           "CAAPHGSNFGNEKLTF_CAWSLRWDEQFF",
                           "CAFKGPGAQKLVF_CATLRGYGYTF",
                           "CAASNSGGGADGLTF;CAPTNAGKSTF_CASSLDGPYEQYF",
                           "CAASILQGGKLIF_CASSLEDRGGTEAFF",
                           "CAESGGTGRRALTF_CASSLGKAGPSGNTIYF",
                           "CAFLTGTASKLTF_CAGTGASTDTQYF",
                           "CAGNQAGTALIF_CAWSVQNYGYTF",
                           "CALNNAGNMLTF_CASRLGGHGYTF",
                           "CALSDLIRGGSSNTGKLIF_CASSWRQGAGNTIYF",
                           "CALSDTGARLMF_CASSPNFSGNTIYF",
                           "CALSDVFTGGGNKLTF_CASSVLGDTEAFF",
                           "CAMRPSNTGKLIF_CASSPGQLAKNIQYF"
                           ))

DimPlot(seurat_viz, 
        group.by = "highlight",
        pt.size = 2,
        order = T,
        repel = T,
        label = T,
        label.size = 5)+
       # split.by = "hash.ID") +
  theme(plot.title = element_text("Common clone b/w c1 & c11"))
![cmv_cln_bw_c1_c11_umap](https://github.com/user-attachments/assets/4aaf6e7c-b62f-474c-bbf4-2b70765ba3ba)

Based on my understanding, UMAP should show all the cells with the given "highlight" TCR sequence irrespective of any clusters.
In UMAP, I see only 1 clone shared and others are present in other clusters.

This put me in a confusion. Please give your comments and guidance so that I can make my statement for the given results.

Thank You.

**Comment by ncborcherding** [comment]
@GauravJethva0,

Thanks for the question.

I think this is more of an issue with UMAP plotting itself then a disconnect between the ```clonalCompare()``` and ```highlightClones()``` (I am using the version 2 names for the functions, but they are the same). 

In your ```clonalCompare()```, you show that there are 15 clones that represent roughly 1 - 1.5% of the total clonal population in the respective clusters. My guess is that these are single-count clones given the distributions along the alluvial plot. Highlighting the clones and plotting a UMAP is probably not the best approach for identify single clones between 2 clusters as the 2D representation does not necessarily correspond with the cluster assignment and there is a degree of stochasticity during plotting the individual cells. 

Nick
