### ISSUE TITLE
Is it possible to graph only the top 10 clonotypes using alluvialClones()?

### ISSUE THREAD

**Issue by zoqaiyum** [ncborcherding/scRepertoire#447]
Hi @ncborcherding 

I am trying to use alluvialClones() to plot the alpha and beta chains for my group called InEx (which has two patient samples). My code is as follows and uses the seurat object as input to plot: 

`subset(mergedseurat2_CDR3split, subset = Group == "InEx") %>% alluvialClones(y.axes = c("CTaa_alpha", "CTaa_beta"))`

My plot below: 

![image](https://github.com/user-attachments/assets/71d288d5-d730-4fc8-a3d2-ec7c44a6a5bc)

Here, as you can see, it appears very messy. Is there any way I can amend the code to plot only the top 10 or top 20 pairs? Following that, could I use different colours to code each of the 10 pairs (or maybe even use the inferno palette)? Finally, can I change the y axes labels in the plot akin to how one would change it for a ggplot2 object?

Many thanks!

**Comment by ncborcherding** [comment]
@zoqaiyum 

There is no built in functionality for subseting for ```alluvialClones()``` by clonal expansion/size. I think the easiest way to do this is to ID the top N clones and subset your Seurat object and then plot from there. It is not ideal, but that would be the fastest. I would make sure you consider the NA_XXX or XXX_NA clones - NA is going to be highly inflated and be present across clones, so you might need to handle that for the purpose of the analysis. 

For the *ggalluvial* package - I am not sure you can change the axis labels of the stratum post-hos like other ggplot objects. You could change the headers of your meta data to match what you would like them labeled as? Or else you might need to look into custom plotting by modifying the script: https://github.com/ncborcherding/scRepertoire/blob/master/R/alluvialClones.R

Hope that helps,
Nick
