### ISSUE TITLE
Parse BCR data load

### ISSUE THREAD

**Issue by ajsapre** [ncborcherding/scRepertoire#448]
Hello,

I am trying to load in **BCR** data generated using Parse tech but the "loadContigs" functions seems to looking for "TRA_V", "TRA_D", "TRA_J" in the column headers. Can you please update it to match the headers in the BCR barcode_report.tsv from Parse? 

Cheers!

**Comment by ncborcherding** [comment]
@ajsapre, 

Unfortunately, when I reached out to Parse, they would only provide me with their TCR data. 

We can update it if you want to provide some of the data/headers to call or you can make a pull request and code the solution? Either way works for me. 

Nick

**Comment by ajsapre** [comment]
Hi Nick! 
Here is a representative dataset from Parse: https://www.parsebiosciences.com/datasets/bcr-sequencing-of-1-million-healthy-and-diseased-samples-in-a-single-experiment/ 
If you scroll to the bottom you will see the barcode_report.tsv
Thanks!

**Comment by ncborcherding** [comment]
Just pushed the fix into the dev branch. If you want to test it out you can use: 

```
devtools::install_github("ncborcherding/scRepertoire@dev")

```

Just make sure to restart your R session. I will do a couple of additional tests and wait to see if you have any bugs and push it to the main branch and bioconductor next week. 

Thanks for the help,
Nick

**Comment by ajsapre** [comment]
I just tried but it looks like its having a hard time pulling the data correctly using the loadcontigs
[Screen Shot 2024-11-20 at 2.23.59 PM.png]
Ajay
From: theHumanBorch ***@***.***>
Date: Wednesday, November 20, 2024 at 12:31 PM
To: ncborcherding/scRepertoire ***@***.***>
Cc: ajsapre ***@***.***>, Mention ***@***.***>
Subject: Re: [ncborcherding/scRepertoire] Parse BCR data load (Issue #448)


Just pushed the fix into the dev branch. If you want to test it out you can use:

***@***.***")



Just make sure to restart your R session. I will do a couple of additional tests and wait to see if you have any bugs and push it to the main branch and bioconductor next week.

Thanks for the help,
Nick

**Comment by Qile0317** [comment]
@ajsapre did you perhaps incorrectly format your comment? Just as a general rule of thumb please make sure to restart the session after installing a new release.

Also please paste code or plots instead of screenshots if that was what you were attempting to do - and preferably open a new issue?
