### ISSUE TITLE
There is no quantContig function

### ISSUE THREAD

**Issue by 18520964064** [ncborcherding/scRepertoire#456]
”scRepertoire“ had been successfully downloaded and loaded in R.
but after I ran the code below :
p1 <- quantContig(combined_test, cloneCall="gene+nt", scale = F)
p2 <- quantContig(combined_test, cloneCall="gene+nt", scale = T)
plotc = p1 + p2
ggsave('VDJ/quantContig.png', plotc, width = 8, height = 4)

it showed :
Error with quantContig(combined_test, cloneCall = "gene+nt", scale = F):
There is no quantContig function

**Comment by ncborcherding** [comment]
Hello @18520964064 

It looks like you are likely using an updated version of scRepertoire (> v2), but an old vignette? There is not more ```quantContig()``` function, it is now ```clonalQuant()```

Check out the update vignette at: https://www.borch.dev/uploads/screpertoire/

Nick
