### ISSUE TITLE
TCR clone defination question. "NA", "None", multiple definations in one cell

### ISSUE THREAD

**Issue by yingluout** [ncborcherding/scRepertoire#457]
Hi,

I want to ask about the defination of clone using scRepertoire. I found a lot of "NA", "None", and more than one definations in one cell. Could you please let me what they are meaning? Does that mean the sequencing information is not enough that R or the package could not achieve good recognition? Thanks,

<img width="446" alt="WechatIMG600" src="https://github.com/user-attachments/assets/f051b71c-eb77-4d0d-9b2b-b37cb3261297" />

**Comment by ncborcherding** [comment]
Hey @yingluout 

Good quesiton: 

"None" denotes Cell Ranger inability to call the respective gene segment - this is very common for D genes and some C genes based on the coverage of the primers and the number of mutations introduced during recombination. "None" itself is dictated by the Cell Ranger pipeline, other alignment processes might have NA instead.

"NA" denotes a missing chain. So for row 83/84, no TRB was recovered associated with those cell barcodes. 

Hope that helps,
Nick

**Comment by yingluout** [comment]
Hi Nick,

Thanks for your response. I want to ask about the multiple definition on one cell such as #77. Why are 2 clones annotated on one cell? Thanks,

Ying

**Comment by ncborcherding** [comment]
@yingluout 

Multiple chains per cell barcode happen as part of the alignment process. As a default, scRepertoire retains the multiple chains (in your data you have a TRAV7-5 and TRAV9 chain in your first cell. This can have biological significance in the case of 10-20% of T cells that will express dual alpha chains. Other multiple chains per cell (like dual TRB or >2 TRA or TRB) happens and are likely an issue with Cell Ranger itself. 

If you would like to only keep the top expressed chain, you can use ```combineTCR(..., filterMulti = TRUE).

Nick

**Comment by yingluout** [comment]
Hi Nick,

Thanks for your reply. 

For "Other multiple chains per cell (like dual TRB or >2 TRA or TRB) happens and are likely an issue with Cell Ranger itself."

How should I handle this issue? How could I get the real clone difinition for these cells? Thanks,

Ying

**Comment by ncborcherding** [comment]
Hey Ying, 

This is a gray area in the field. There is no one best solution as dual chains do exist in immunobiology. For me, I use filterMulti as the best solution, as it is easy to justify in the methods section of the paper that you used the top expressing individual chains to form the clone. 

Hope that helps,
Nick

**Comment by yingluout** [comment]
Hi Nick,

Thank you for sharing your experience.

Ying

**Comment by yingluout** [comment]
One more question,

I found that in the clone definition, "TRAV-9N", “TRAV-9D”, and “TRAV-9” could be viewed. I want to ask whether they are different or the same. Thanks,

Ying



<img width="310" alt="image" src="https://github.com/user-attachments/assets/cd9f5942-76cf-4cc7-8dbf-8b4925e0e6f7" />
<img width="305" alt="image" src="https://github.com/user-attachments/assets/fd075d1b-5318-4b0f-9139-45db08f06caf" />

**Comment by ncborcherding** [comment]
@LynnChan99,

Only NAs would mean that the chain information is missing - I think this should only be the case for 1 chain, as if both chains were gone, you would not have the respective barcode in the contig information. If you are trying to separate the missing and uncalled gene segments - should be straight forward looking for "_NA" or "NA_" for missing ones. 

Nick
