### ISSUE TITLE
The defination of Clonetype

### ISSUE THREAD

**Issue by majeex233** [ncborcherding/scRepertoire#458]
Dear author,  I am willing to know what is the defination of clonetype and  how the R package definate the clonetype?
Looking forward to your kind reply! Thanks!

**Comment by ncborcherding** [comment]
Hey @majeex233, 

There are a couple of definitions of clonotypes that scRepertoire uses: h[ttps://www.borch.dev/uploads/screpertoire/articles/combining_contigs](https://www.borch.dev/uploads/screpertoire/articles/combining_contigs). 

These revolve around the CDR3, using either nucleotide sequence (CTnt), amino acid sequence (CTaa), VDJ gene usage (CTgene), or nucleotide + gene (CTstrict). B cell clonotypes have a additional wrinkle where nucleotide sequences are clustered by edit distance and the CTstrict clonotype is defined using the VDJ gene usage + group membership.

You can also pass a custom definition of clonotype to most of the analyses. So for example, if you are using the Immcantation workflow and have define BCR lineages - you can use the variable name associated. 

Hope that helps,
Nick

**Comment by majeex233** [comment]
Thanks for your kind reply! I also have a question that clonetype which frequency is one can be named after monoclonal, and  which have more than 3 be named after multiclonal ? This is a really important information for some immune diseases~ Looking forward to your reply~

**Comment by ncborcherding** [comment]
I don't think you want to use the term "monoclonal" as that usually refers to a hyperexpanded clone or a therapeutic, which might be confusing. 

1 = singlet, individual clone
3 = multiclone
