### ISSUE TITLE
Can this package be used on the BCR also?

### ISSUE THREAD

**Issue by Midsummer723** [ncborcherding/scRepertoire#46]
HI Thank you for your great package for the TCR analysis.
I wonder if this package also can work on the BCR analysis also ,because the codes seems can also work on the BCR.
If not do you have any advises to use for the BCR analysis?
Thank you very much.

**Comment by ncborcherding** [comment]
Hey Midsummer723,

Yes scRepertoire will work for BCR analysis - the function `combineBCR()` will parse the 10x output into the usable format for the rest of the package.

Couple of things though

- The package was tested on the 10x genomics sample BCR information from their [website](https://support.10xgenomics.com/single-cell-vdj/datasets), which is not the wealth of samples to really test every facet of the package. At the time of development, there was no public paired 5' expression and BCR data set.
- There are 4 ways to look at clonotype - 1) genes utilized or **"genes"**, 2) nucleotide sequences or **"nt"**, 3) amino acid or **"aa"** and 4) a strict definition using a normalized Hamming Distance > 0.85 (I just noticed this documentation is not ideal, will commit an update now that is not cut off).

There is a [manuscript](https://www.biorxiv.org/content/10.1101/2020.08.24.264069v1.abstract) in preprint that extensively uses scRepertoire for analysis of BCR in influenza model infection that includes the function calls in the methods section.

Hope that helps, please let me know if you run into any problems if you are going to perform the BCR analysis. 

Thanks,
Nick
