### ISSUE TITLE
using combineExpression multiple times (TCR/BCR) 

### ISSUE THREAD

**Issue by msalaciak** [ncborcherding/scRepertoire#47]
Hi,

Thanks for an excellent package. 

My background is in compsci not so much bio/immunology so forgive me if this comes off as naive!

I wanted to know the best practice for adding tcr (both t-ab and t-gd)/bcr data to my Seurat object.

Following the vignette provided, can I just call combineExpression for each?

For example,
`seurat_obj <- combineExpression(tcr_contig_combined_t_ab,seurat_obj,...)`
`seurat_obj <-combineExpression(tcr_contig_combined_t_gd,seurat_obj,...)`
`seurat_obj <-combineExpression(bcr_contig_combined,seurat_obj,...)`

Thanks!

**Comment by ncborcherding** [comment]
Hey msalaciak,

Interesting question - short answer, there is no best practice.

The idea of adding both BCR and TCR  never occurred to me when designing scRepertoire. My guess is that just using `combineExpression()` repeatedly will not work - there is a total crossover in variable/headers between T_GD and T_AB, but only a partial crossover with B cells. Although the 4 major clonotype calls: 1) "nt", 2) "gene", 3) "aa", and 4) "gene+nt" will be common among all, so downstream analyses might work?

Have you tried the above code? What does your meta data look like? 

Really interesting though, please follow up and let me know if I can help in anyway.

Thanks,
Nick

**Comment by msalaciak** [comment]
Thanks for the quick response. 

Going to try the above code today and I'll look at the metadata. My other option would be just to copy my Seurat object for each analysis (would like to avoid this since my object is quite large). 

We're trying to look at B and T cell clonotypes over time in a patient which is why I'm trying to add both.

I'll try this all and report back!

Thanks,
Matt

**Comment by ncborcherding** [comment]
Closing this issue. Please feel free to post a follow up though.

**Comment by ncborcherding** [comment]
This is really late - but I was finally able to find a data set with bot BCR and TCR - the dev version has a fix in ```combineExpression``` to allow for add both BCR and TCR at the same time. It just requires the making a full list before calling ```combineExpression``` (or during the calling).

```
BCR <- combineBCR(...)
TCR <- combineTCR(...)
full.list <- c(TCR, BCR

seuratObject <- combineExpression(full.list, seuratObject)
```

I am working on a few other things today and then I will knit up a fresh vignette that includes this

**Comment by msalaciak** [comment]
Better late than never! Super appreciative and thankful for remembering this and coming back with a solution.

I ended up combining TCR/BCR via a hacky solution that is not elegant at all which led to simply subsetting the data into T cells and B cells for separate analysis. Very excited to revisit it and implement this solution instead.

Thanks again!

**Comment by apal6** [comment]
Hi @ncborcherding,

I added a barcodes column in the seurat object to combine the contig_list but got this error: 
`Error in `[.data.frame`(data3, , c("barcode", "sample", tcr1_lines, tcr2_lines,  : undefined columns selected`

**Comment by ncborcherding** [comment]
Hey @apal6 

Would you mind posting the code (or example code) you are using to load the contigs, combine them (```combineBCR()``` and ```combineTCR()```) and then ```combineExpresion()```? That will help with troubleshooting. 

Thanks,
Nick

**Comment by ncborcherding** [comment]
During the ```combineExpression()``` function call there is a discrete step that selects columns to add to the meta data

```
#data being the intermediate data object of the combineTCR() list
data <- data[,("barcode", "CTgene", "CTnt", "CTaa", "CTstrict", "Frequency")]
```
Do you have all of these columns in your ```combined``` object?

Nick
