### ISSUE TITLE
"None" in CTgene calls 

### ISSUE THREAD

**Issue by rh707** [ncborcherding/scRepertoire#48]
Hello, 

Firstly, thank you for the great package, it really is awesome. 

I am trying to analyse a B cell dataset by comparing the different B cell clones (as defined by the clonecall "aa") that share the same V(D)J CTgenes. However, the vast majority of my CTgene calls for the heavy chain have "None" where the diverse gene segment should be. For example: "IGHV1-18.IGHJ3.None.IGHM_IGKV1-117.IGKJ2.IGKC"

I was wondering if this is simply an artefact from the sequencing, and therefore, there is nothing I can do about it in the R analysis or rather this is something I can rectify. 

Thanks!
Rob

**Comment by ncborcherding** [comment]
Hey Rob,

Thanks for reaching out. 

Unfortunately the "None" segment is an artifact of Cell Ranger output and not much you can do at the level of R. Although, maybe you can focus on the V genes? I have noticed in general the V gene recovery is generally greater than other segments.

Also, I would throw out I am not a B cell expert by any means. Please let me know if you have suggestions for functions or find issues with the analysis!

Thanks,
Nick

**Comment by rh707** [comment]
Hi Nicks, 

Thanks for getting back to me so fast! 

I thought that may be the case, thanks for letting me know. In terms of using scRep for B cells everything seems to be working great so far. 

Thanks, 

Rob

**Comment by ncborcherding** [comment]
Hey Rob, 

I am going to close this issue, hope the B cell analysis is going well and let me know if you have any additional questions.

Thanks,
Nick
