### ISSUE TITLE
Using an already 'merged' Seurat object

### ISSUE THREAD

**Issue by fabio-t** [ncborcherding/scRepertoire#49]
I have a weird use case and I wonder if there's quick solution to be able to use it with this package.

So far I've worked with separate seurat objects, one per sample - and successfully used `combineTCR` and `expression2List` to produce all the plots.

Now however I have a sort of normalised Seurat object, with all the samples together and the TCR data already added. But it seems I can't use it with `scRepertoire` because it expects a .

But is there some trick I can use to make it work? clonoType for example I would have to add manually, I guess. And so all the columns that combineTCR adds.

**Comment by ncborcherding** [comment]
Hey Fabio, 

Yes scRepertoire should work with a merged or integrated Seurat object - the vignette data is 3 patient samples across 6 sequencing runs that has been integrated using CCA. The most common issue with error during this process is the barcode mismatch. 

`combineTCR()` adds a "**sample**_**ID**" as a prefix to the barcodes - which unless you set up your integration beforehand with the TCR in mind, will not match. The sample and ID were put in place to prevent duplicate barcodes - instead of this approach, during the integration Seurat will add integar suffixes to barcodes. So I would make sure your barcodes match in the combined object and the Seurat object before using `combineExpression()`

Also what do you mean here:

> seems I can't use it with `scRepertoire` because it expects a .

**Comment by fabio-t** [comment]
Well, they are supposed to be in an R list to be combined, no?

```
combined <- combineTCR(contig_list, 
                        samples = c("PY", "PY", "PX", "PX", "PZ","PZ"), 
                        ID = c("P", "T", "P", "T", "P", "T"), cells ="T-AB")
```

Anyway, specifically, I get this error when I try to plot:

```
> quantContig(p, cloneCall="gene+nt", scale = TRUE)
Error: Cannot find '1' in this Seurat object
```

Also I'm not sure I was clear.

> So I would make sure your barcodes match in the combined object and the Seurat object before using combineExpression()

I wouldn't use combineExpression, because I only have one Seurat object with expression and TCR data. This is what I have in the metadata:

```
> colnames(p@meta.data)
 [1] "orig.ident"             "nCount_RNA"             "nFeature_RNA"          
 [4] "nCount_ADT"             "nFeature_ADT"           "RNA.weight"            
 [7] "wsnn_res.2"             "seurat_clusters"        "TCR_clonotype_id"      
[10] "TCR_cdr3s_aa"           "BCR_clonotype_id"       "BCR_cdr3s_aa"          
[13] "TCR_V_GENE"             "TCR_D_GENE"             "TCR_J_GENE"            
[16] "TCR_C_GENE"             "percent.mt"             "percent.ribo"          
[19] "RNA_snn_res.0.8"        "patient"                "condition"             
[22] "RNA_snn_res.0.9"        "RNA_snn_res.1"          "integrated_annotations"
[25] "RNA_snn_res.0.5"     
```

The cell barcodes already have the sample id has a prefix (essentially the `orig.ident` column was prefixed to the barcode). Also, the `condition` column is what contains the additional grouping (ie, severe/mild/healty).

**Comment by fabio-t** [comment]
Ah sorry about this sentence:

> But it seems I can't use it with scRepertoire because it expects a .

I guess I wanted to say that it expects columns added by `combineTCR`, which are obviously not in my Seurat object.

**Comment by ncborcherding** [comment]
Hey Fabio,


Yes a list is necessary for most of the functions - `combineTCR()` will place the contig data into the list format through. If a single set of contig data, the `combineTCR()` will return just a single element list (same with `expression2List()`)

Is p a seurat object in your `quantContig(p, cloneCall="gene+nt", scale = TRUE)` (I assume so as it has p@meta.data)?
If so, you will need to convert your attached meta data into a list using `expression2List()`

In addition - most of the functions in scRepertoire depending on the headers generated by `combineTCR()` and are preserved when using 'combineExpression()' (as you point out in the post after I started writing this). In scRepertoire, "combineExpression()' just attaches the contig data to your seurat (the expression info) or other single-cell object - it can be used for single sample or multiple samples and might make this whole thing easier. The alternative is when you are attaching the meta.data on your own, is to not change the header names from the `combineTCR()`. This will be complicated if you are trying to visualize BCR and TCR (just based on your meta.data)

In terms of headers - for instance:

```
quantContig(p, cloneCall="gene+nt", scale = TRUE)
```
cloneCall = "gene+nt", will extract a header called "CTstrict" which is the combined gene and nucleotide sequences for both loci. Without this header, the function will error as well. 

Hope that helps and let me know if you have any additional questions,
Nick

**Comment by fabio-t** [comment]
Seems like was easier than I thought, thanks for your help ;)

**Comment by ncborcherding** [comment]
Great - I will clarify the combineExpression() documentation more to help other users!
