### ISSUE TITLE
combineTCR using filterMulti = TRUE fails

### ISSUE THREAD

**Issue by loucashwashere** [ncborcherding/scRepertoire#5]
Running combineTCR function with parameter filterMulti = TRUE fails with
`Error in grepl(";", sampleID) : object 'sampleID' not found`

Checking source what I find is this:
```
if (filterMulti == T) {
      for (i in seq_along(final)) {
        final[[i]] <- filter(final[[i]], !grepl(";", 
                                                sampleID))
      }
    }
```

but column sampleID is defined nowhere. this should probably point to somethig else?

**Comment by ncborcherding** [comment]
Thank you for the well formatted comment. Most recent commit replaced sampleID to the collated nucleotide sequences in the vector "CTnt".

```
if (filterMulti == T) {
      for (i in seq_along(final)) {
        final[[i]] <- filter(final[[i]], !grepl(";", 
                                                CTnt))
      }
    }
```
Should work now, change was tested on the vignette data.

**Comment by loucashwashere** [comment]
Tested it today, works perfectly now. Thanks a lot
