### ISSUE TITLE
clonalDiversity legend text when grouping

### ISSUE THREAD

**Issue by fabio-t** [ncborcherding/scRepertoire#50]
I know that legend text can be modified via ggplot, but apart from the specific problem, I'd like to know if I'm doing this correctly. I'll give you a bit of context so that you can tell me how wrong I'm using the package, and point me in the right direction :)

Put simply, I have a set of Seurat objects, one per patient. The patients are tagged with one of several `condition`s.
I combine their TCR information via `combineTCR(tcr_list, samples = samples, ID = condition, cells ="T-AB")`, I add the gene expression information so that I have a single `sce` object, and then convert to several lists:

```
by_celltype <- expression2List(sce, group = "celltype")
by_condition <- expression2List(sce, group = "condition")
by_patient <- expression2List(sce, group = "patient")
```

For most of the plots, I simply use one of the above lists. But with `clonalDiversity`, I wanted to see each patient's diversity coloured by condition. So I ran:

`clonalDiversity(by_patient, cloneCall = "gene+nt", group = 'condition')`

All seems good but the **legend text is numeric**, from 1 to 5, rather than using the condition levels.

Of note, I've also tried to produce the plot via `clonalDiversity(combined, cloneCall="gene+nt", group = "ID")` and the legend shows the conditions' names, but the output is quite different. So one of the two must be wrong.

**Comment by ncborcherding** [comment]
Hey Fabio,

Interesting - can you give me what the output for both calls looks like and what are your conditions? Feel free to [email](mailto:ncborch@gmail.com) if you are more comfortable that way. Have you tried looking at the exportTable = TRUE output?

Thanks,
Nick

**Comment by ncborcherding** [comment]
Hey Fabio,

I am going to close this as I have not heard back - if you or any other user continues to have the problem, please let me know and we can open this again.

Thanks,
Nick
