### ISSUE TITLE
Failed to install 'scRepertoire'

### ISSUE THREAD

**Issue by HousLi** [ncborcherding/scRepertoire#52]
Hello Nick, 

I was trying to install the package on my desktop, for some reason, it kept failing to install, here is the error message I got: 

Error in system(paste("mv -f", shQuote(instdir), shQuote(dirname(final_instdir)))) : 
  (converted from warning) error in running command
sh: rm: command not found
Error: Failed to install 'scRepertoire' from GitHub:
  (converted from warning) installation of package ‘GenomeInfoDbData’ had non-zero exit status

I have a imac system with macOS Big Sur, and R version 4.0.3, the code I used to install is the following: 

devtools::install_github("ncborcherding/scRepertoire")

I was able to install the package on my laptop without running into any issues. 

Can you help me with this? 

Thanks,
Hous

**Comment by ncborcherding** [comment]
Hey Hous,

It looks like the installation is being held up by the package **‘GenomeInfoDbData’**. 

I would try to install the package first before scRepertoire by

```
BiocManager::install("GenomeInfoDbData")
```

Let me know if that does not work,
Nick

**Comment by HousLi** [comment]
Thanks for the quick response Nick! 

I just tried, it won't work, I got the following warning messages:

Warning message:
In install.packages(...) :
  installation of package ‘GenomeInfoDbData’ had non-zero exit status. 

This what I have after running BiocManager::install("GenomeInfoDbData"). 

Thanks, 
Hous

**Comment by ncborcherding** [comment]
Hey Hous,

Well that is unfortunate - I think secondarily I would try:

```
devtools:::install_github("Bioconductor/GenomeInfoDb")
```

Not sure why that package is not installing - the build on bioconductor page has successful build for Mac. Is there any other part of the warning message?

Thanks,
Nick

**Comment by HousLi** [comment]
Thanks Nick, 

Yes. I think maybe it requires updates of other CRAN packages? Here is what I have after running the code: 

These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                
2: CRAN packages only                 
3: None                               
4: S4Vectors (0.28.0 -> 0.28.1) [CRAN]
5: IRanges   (2.24.0 -> 2.24.1) [CRAN]

Enter one or more numbers, or an empty line to skip updates:

And I skip the updates, then I got the same error again. 

Thanks, 
Hous

**Comment by ncborcherding** [comment]
Hey Hous,

It looks like the creators of have the required versions less than you are currently at with S4vectors and IRanges (see below)
<img width="621" alt="Screen Shot 2020-12-18 at 11 28 23 AM" src="https://user-images.githubusercontent.com/22754118/102642992-2f1d2780-4124-11eb-8c27-8bfc168de490.png">

Have you restarted your R session since installing some packages? 

Sorry there doesn't seem to be a quick fix, this seems more an issue with a sub-dependency from another package unfortunately.

Nick

**Comment by HousLi** [comment]
Hi Nick, 

Yes. I do restarted a new R session ever since running other packages. 

Do I have to try to use an older version of S4vectors and IRanges? 

Thanks, 
Hous

**Comment by ncborcherding** [comment]
Hey Hous. 

You might try the installation of older versions S4vectors and IRanges? This might be a can asking for trouble though - as you might alter the usability of other packages. 

If that doesn't work - I might reach out to the authors of GenomeInfoDB at the [bioconductor forums](https://support.bioconductor.org/). 

Nick

**Comment by ncborcherding** [comment]
I am going to close this thread as this is really an issue with a dependency and not the code of scRepertoire. Please feel free to comment with follow up or additional issues.
