### ISSUE TITLE
Error: could not find function “StartracDiversity"

### ISSUE THREAD

**Issue by eumhh** [ncborcherding/scRepertoire#53]
I'm using scRepertoire (version 1.0.0) with R version 4.0.2.
When I try to use the 'StartracDiversity' function, I get the error below.

_Error: could not find function “StartracDiversity”_

Is the "StartracDiversity" function available now?

**Comment by ncborcherding** [comment]
Hey eumhh,

`StartracDiversity` is available in the current master branch of scRepertoire (v1.1.2). Which you can download with:

```
devtools::install_github("ncborcherding/scRepertoire")
```

Thanks,
Nick

**Comment by eumhh** [comment]
@ncborcherding,  It works well! Thank you =)
