### ISSUE TITLE
Feature Request: proportional cloneTypes definitions in combineExpression

### ISSUE THREAD

**Issue by GBeattie** [ncborcherding/scRepertoire#54]
Hey!

Great package! One suggestion I have (unless there is an approach to achieve the same thing within the package that I'm not seeing), is to give the option to use clonal proportion cutoffs, as can be done with clonalHomeostasis, to define expansion levels within the combineExpression command (instead of the raw number cutoffs).

I've worked with several scTCR datasets, and the common issue is that cell numbers vary greatly between samples, so a pipeline that has the option of using proportions throughout would be very useful!

**Comment by ncborcherding** [comment]
Hey Gordon,

This is actually a fantastic suggestion - users have run into issues with needing to know the extent of the clone frequency before entering and your approach would actually prevent that issue. I have added it to the list of features (closing this as it is not an active issue). 

Thanks for reaching out,
Nick

**Comment by GBeattie** [comment]
@ncborcherding No problem! Great to hear it will be useful to others as well. Is the feature in the github or the BioConductor release?

**Comment by ncborcherding** [comment]
Hey Gordan,

It will be initially posted on the screpertoire@refine branch - I have not gotten time to fully test the implementation though. So I will post here when it is up and ready.

**Comment by GBeattie** [comment]
> Hey Gordan,
> 
> It will be initially posted on the screpertoire@refine branch - I have not gotten time to fully test the implementation though. So I will post here when it is up and ready.

That's perfect, thanks!

**Comment by ncborcherding** [comment]
Added the function to the @refine branch, feel free to test it out with:

```
devtools::install_github("ncborcherding/scRepertoire@refine")
```
The default setting now is: 

```
combineExpression <- function(df, sc, cloneCall="gene+nt", groupBy="none", 
                              proportion = TRUE,
                            cloneTypes=c(Rare = 1e-4, Small = 0.001, 
                            Medium = 0.01, Large = 0.1, Hyperexpanded = 1), filterNA = FALSE) 
```

Where users can elect to use proportion by **proportion = TRUE** or total frequencies using **proportion = FALSE** with clonoTypes needing to be defined by the user. 

Please let me know if you have any issues while you use the new version and thanks for the suggestion, this was a better idea to use in the combineExpression() so thank you.

Nick

**Comment by GBeattie** [comment]
Thank you very much for the speedy addition, we might be use this approach in some scTCR data we hope to publish in the coming months. I hope to give this a try on Monday, I'll post here how I get on!

**Comment by GBeattie** [comment]
Hey @ncborcherding , I've given the new proportion option a go on my data, it seems to work well, although I'm a bit confused about one thing, there appears to be no rare clones in my dataset when defined by combineExpression. However there are rare clones in the clonalHomeostasis output. See below for the relevant code.

I could be very wrong, but in clonalHomeoStasis are cells with no annotated CDR3 counted as "rare" clones (I'm semi-new to the field, but I would have thought it best to just use the cells with annotated CDR3s for the analysis), and is this the same for the @refine combineExpression command? If combineExpression isn't labelling cells without CDR3 annotations, and my definition of rare is too narrow to include cells with annotated CDR3s, that might explain the discrepancy? 

```
clonetypes <- c(Rare = 1e-03, Small = 0.005, Medium = 0.01, Large = 0.1, Hyperexpanded = 1)
seu.int <- combineExpression(combined.TCR, seu.int, groupBy = "Patient",
                             cloneCall = "gene",
                             proportion = T,
                             cloneTypes = clonetypes)

clonalHomeostasis(expression2List(seu.int, group = "Patient"), cloneTypes = clonetypes)
```
![image](https://user-images.githubusercontent.com/11555832/104935985-d56a8000-59a3-11eb-8f67-d6db49b888a5.png)

```
table(seu.int@meta.data[["cloneType"]])

Hyperexpanded (0.1 < X <= 1)      Large (0.01 < X <= 0.1)   Medium (0.005 < X <= 0.01)   Small (0.001 < X <= 0.005) 
                        2914                         5908                         2220                         4731
```

**Comment by ncborcherding** [comment]
Hey Gordan,

Nice catch! It looks like I need to change the implenetation of the proportion cut-off. Your code:

```
table(seu.int@meta.data[["cloneType"]])

Hyperexpanded (0.1 < X <= 1)      Large (0.01 < X <= 0.1)   Medium (0.005 < X <= 0.01)   Small (0.001 < X <= 0.005) 
                        2914                         5908                         2220                         4731
```

Tells me that the rare = 1e-3 is being used as the lower end of the small group, but there is no 0 to append the rare group itself. I just added the automatic append of the "none = 0" so now try reinstalling the refine branch and running the code. This is why I think `clonalHomeostasis()` is giving you different results (it already had the appended none = 0). So `combineExpression()` was missing line 48.

<img width="758" alt="Screen Shot 2021-01-18 at 10 29 10 AM" src="https://user-images.githubusercontent.com/22754118/104940931-08971a00-5978-11eb-84d1-08c62485140b.png">


> I could be very wrong, but in clonalHomeoStasis are cells with no annotated CDR3 counted as "rare" clones (I'm semi-new to the field, but I would have thought it best to just use the cells with annotated CDR3s for the analysis), and is this the same for the @refine combineExpression command? If combineExpression isn't labelling cells without CDR3 annotations, and my definition of rare is too narrow to include cells with annotated CDR3s, that might explain the discrepancy?

<img width="481" alt="Screen Shot 2021-01-18 at 10 21 14 AM" src="https://user-images.githubusercontent.com/22754118/104940654-ab02cd80-5977-11eb-9886-80a7caff0f4e.png">

I did check this - `clonalHomeostasis` automatically removes NA values (line 41) before calculating the proportion (line 43). So I do not think that is the problem. 

Thanks for helping me troubleshoot the new feature. If you have anymore problems, don't hesitate. I will actually open this thread up just to ensure we have everything figured out.

Thanks,
Nick

**Comment by GBeattie** [comment]
@ncborcherding Thank you for the quick response, good to know for sure that it's ignoring non-annotated cells! I reinstalled but it didn't change the behaviour, I did manage to fix it by adding None = 0 to the cloneTypes vector. Let me know if you change anything or wish for me to try anything different to test it out, happy to even though it's working for my purposes.
