### ISSUE TITLE
TCR variant clustering

### ISSUE THREAD

**Issue by chjp** [ncborcherding/scRepertoire#56]
Would you consider adding TCR variant clustering function?

**Comment by ncborcherding** [comment]
Hey Jiapeng,,

Absolutely! This is in the works. I am going to close this issue because it is a feature request, but will post here when I get the clonotype clustering added. 

Thanks,
Nick

**Comment by ncborcherding** [comment]
Variant clustering for TCR is now up in the refine branch with the combineTCR() function
