### ISSUE TITLE
combineTCR function gave error

### ISSUE THREAD

**Issue by eudoraleer** [ncborcherding/scRepertoire#57]
Hi,

I ran the command below on my samples and it gave error as shown below:

contig_tcr_tgd <- combineTCR(samples, 
                                  samples = tcr_list,
                                ID = tcr_list,
                                cells = "T-GD")

**Error in `$<-.data.frame`(`*tmp*`, "sample", value = "Sample1") : 
  replacement has 1 row, data has 0**

Each data.frame in the list samples have "TRA","TRAB" and "TRD" chains. 

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/5945741/105406778-2e007e00-5c2d-11eb-9208-51eb7a7eeb0e.png">

Please assist me, thank you!

Best,
eudoraleer

**Comment by ncborcherding** [comment]
Hey Eudoraleer,

The error comes from having an empty data frame for the final combination of contigs. However, I am pretty sure I know where this is coming from.

What version of the scRepertoire package are you running and what is the cell ranger version?

Cell Ranger v5 just decided to change their output formats from "TRUE" or "True" to "true" (see your table$productive).

The refine branch is where this correction has been made, so please try installing:

```
devtools::install_github("ncborcherding/scRepertoire@refine")
```

Let me know if that fixes the problem or if you still have issues. 

Thanks,
Nick

**Comment by eudoraleer** [comment]
> Hey Eudoraleer,
> 
> The error comes from having an empty data frame for the final combination of contigs. However, I am pretty sure I know where this is coming from.
> 
> What version of the scRepertoire package are you running and what is the cell ranger version?
> 
> Cell Ranger v5 just decided to change their output formats from "TRUE" or "True" to "true" (see your table$productive).
> 
> The refine branch is where this correction has been made, so please try installing:
> 
> ```
> devtools::install_github("ncborcherding/scRepertoire@refine")
> ```
> 
> Let me know if that fixes the problem or if you still have issues.
> 
> Thanks,
> Nick

Hi Nick,

Thank you for your fast reply and update!! However it did not work for me. Indeed the output format is "true" in my case:

<img width="950" alt="image" src="https://user-images.githubusercontent.com/5945741/105522143-28627100-5cdd-11eb-9025-f60c590bc38f.png">

Could it be in function combineTCR() the bold part below, 

data3 <- merge(data2[, **-which(names(data2) %in% c("TCR1", 
            "TCR2"))**], Con.df, by = "barcode")

could be changed to:

data3 <- merge(data2[, **which(!names(data2) %in% c("TCR1", 
            "TCR2"))**], Con.df, by = "barcode")

Thank you for your assistance and hope to hear from you a solution to my problem.

Best Regards,
Eudoraleer

**Comment by ncborcherding** [comment]
Hey Eudoraleer,

Can you give me more details like the dimensions of your contig list? Ho many samples are you running? How many gamma-delta T cells are present?

Looking over your table again - 

![](https://user-images.githubusercontent.com/5945741/105406778-2e007e00-5c2d-11eb-9208-51eb7a7eeb0e.png)

scRepertoire will remove any nonproductive TCRs recovered - which it looks like your sample has these? Can you check to see if you have productive TCRgd variants?

Full caveat - the T-GD in the built-in data set is < 1% of total cells, so it has not been tested on a GD data set as of yet. So thanks for bearing with me - 

One thing I just notice was the internal function I use to parse the different cell types - `cellT()` had the gamme/delta chains in the incorrect order. **Just commited this fix on the refine branch**.
<img width="321" alt="Screen Shot 2021-01-22 at 11 29 03 AM" src="https://user-images.githubusercontent.com/22754118/105525017-16191080-5ca6-11eb-80b1-621262c41ff2.png">


**Could it be in function combineTCR() the bold part below**
> data3 <- merge(data2[, -which(names(data2) %in% c("TCR1",
"TCR2"))], Con.df, by = "barcode")
> could be changed to:
> data3 <- merge(data2[, which(!names(data2) %in% c("TCR1",
"TCR2"))], Con.df, by = "barcode")

I think your version is more elegant, but I actually think they return the same thing?

<img width="801" alt="Screen Shot 2021-01-22 at 11 25 42 AM" src="https://user-images.githubusercontent.com/22754118/105524632-81aeae00-5ca5-11eb-91a6-9e10b727cfb8.png">

Please let me know if this fixes the issue and again, thanks for bearing with me.

Nick

**Comment by ncborcherding** [comment]
Hey Eudoraleer,

I am going to close this as I never got follow-up. Please feel free to re-open though.

Thanks,
Nick
