### ISSUE TITLE
question on parseBCR function 

### ISSUE THREAD

**Issue by aldojongejan** [ncborcherding/scRepertoire#59]
Dear Dr. Borcherding,
In the parseBCR function the code when only having one entry is as follows:
   else if (length(location.i) == 1) {
      if (chain.i == "IGH") {
        Con.df[y, heavy_lines] <- data2[location.i[1],  h_lines]
      }
      else if (chain.i == "IGL") {
        Con.df[y, light_lines] <- data2[location.i[2], l_lines]  
      }
      else {
        Con.df[y, light_lines] <- data2[location.i[1],  k_lines]
      }
    }
But should the code in case chain.i == "IGL" not be identical to the code when chain.i would be not "IGH" or "IGL"? So, data2[location.i[1], l_lines] ... because you the location.i variable only has length 1 already?

with kind regards and thanks for your R-package!
Aldo

**Comment by ncborcherding** [comment]
Hey Aldo,

Please call me Nick. 

You are completely correct, dumb copy/paste error on my part I think. Thanks for letting me know, I will fix the master and refine branches (which I am using as the default development and has better combineBCR functionality)

Thanks again and let me know if you see anything else or have suggestions!

Nick

**Comment by aldojongejan** [comment]
Hi Nick,

Thanks for your very fast response and assurance I am not crazy ;-)
I modified your code a little to be able to read in and output some extra columns that I had by first merging the '<run>_all_contig_annotations.csv' and the '<run>_clonotypes.csv' we obtained from a 10X run. But I do not know whether you would want  something like that ..

Thanks again!

Regards,
Aldo

**Comment by ncborcherding** [comment]
Hey Aldo, 

Feel free to pull your changes or send [them to me](mailto:ncborch@gmail.com) and I would love to look them over. I know that the output for Cell Ranger VDJ varies by version, so I might need to check for compatibility, but would appreciate any and all contributions.

Nick
