### ISSUE TITLE
Diversity - export table

### ISSUE THREAD

**Issue by carneiro-m** [ncborcherding/scRepertoire#6]
Hi Nick,

Thank you for creating and sharing this package, it helps a lot!

 I'd like to ask you about the function clonalDiversity. It works fine when setted exportTable=F,  however I got an error when tried the option exportTable=T:

Error in clonalDiversity(tcd8, cloneCall = "gene", colorBy = "seurat_clusters",  : 
  object 'coef_matrix' not found

Thank you so much!

Mayra

**Comment by ncborcherding** [comment]
Found the issue, was not referencing the correct label of the matrix to export. Just committed the fix, let me know if it now works for you or you have any other issues.

Thanks!

**Comment by carneiro-m** [comment]
Many thanks!

It's working now :)

Em ter., 14 de abr. de 2020 às 13:22, theHumanBorch <
notifications@github.com> escreveu:
