### ISSUE TITLE
Pulling out dominant TCRs and Comparing clonoTypes after subsetting the data

### ISSUE THREAD

**Issue by dhcorn** [ncborcherding/scRepertoire#64]
Hey Nick,

I am trying to pull out dominant Clones after I have subsetted the data. I thought I could just sort my data on the Frequency column, but it is not working. Is there some way that I can pull out the dominant TCRs like in the compareClonotypes. 

The code I have been using to try and sort. It is not maintaining the rest of the column information. 

> cd8sort <- sort(cd8sub@meta.data$Frequency, decreasing = T, na.last = T)
> head(cd8sort, n = 50)
 [1] 0.0097461196 0.0097461196 0.0097461196 0.0097461196 0.0097461196 0.0097461196 0.0097461196 0.0097461196
 [9] 0.0097461196 0.0097461196 0.0097461196 0.0097461196 0.0097461196 0.0077605322 0.0027674167 0.0027674167
[17] 0.0027674167 0.0025405671 0.0025405671 0.0025405671 0.0021064302 0.0021064302 0.0021064302 0.0014438696
[25] 0.0014438696 0.0014438696 0.0014438696 0.0014438696 0.0012032246 0.0012032246 0.0010829022 0.0010653991
[33] 0.0010653991 0.0010653991 0.0009834453 0.0009834453 0.0009014916 0.0009014916 0.0008422572 0.0008422572
[41] 0.0007760532 0.0007219348 0.0007219348 0.0007219348 0.0007219348 0.0006651885 0.0006556302 0.0006556302
[49] 0.0006556302 0.0006556302

Also, after I have subsetted my data using this code, like I do when I am using Seurat:

>cd8sub <- subset(ExpTCR, subset = Cd8a > .01 & Cd44 > 0.01 & Cd4 < .001)

I cannot use the compareClonotypes() Function. I make get the data back into a list format (i think) using:

>cd8combined2 <- expression2List(cd8sub, group = "orig.ident") #because I would rather group by sample than cluster
>length(cd8combined2)

The try to run the compareClonotypes()function and I just get a blank figure. 

> compareClonotypes(cd8combined2, numbers = 5, samples = c("Peak_CNS", "Peak_SPL"), cloneCall="gene", graph = "alluvial") 

I am not sure what I am doing wrong, but any help would be appreciated. 

Doug

**Comment by ncborcherding** [comment]
Hey Doug,

Thanks for reaching out - to me your workflow makes sense: selecting the cells of interest by expression values and then looking at the dominant clonotypes. 

Couple of Questions:
```
subset(ExpTCR, subset = Cd8a > .01 & Cd44 > 0.01 & Cd4 < .001)
```

1. Does your subset function above return a seurat object that you can plot with - like ```dimPlot()```?
2. what is the output of the following:

```
cd8combined2 <- expression2List(cd8sub, group = "orig.ident")
length(cd8combined2)
lapply(cd8combined2, dim)
```

I actually think this is a pretty cool idea and it should work in principle, so let's figure out where we are going wrong!

Thanks
Nick

**Comment by dhcorn** [comment]
Hey Nick,

Thank you for your reply. The subset does return a Seurat object, see below. I can also use dimPlot() to plot the TCR clonoTypes. 

> cd8sub
An object of class Seurat 
33053 features across 2953 samples within 2 assays 
Active assay: integrated (2000 features, 2000 variable features)
 1 other assay present: RNA
 2 dimensional reductions calculated: pca, umap

**Comment by dhcorn** [comment]
Nick, 

Sorry for the double post, but I forgot to add the second part. When I run the lapply() on the cd8combined2 I get:

> lapply(cd8combined2, dim)
$`EAE chronic 1`
[1] 253  15

$`EAE chronic 2`
[1] 392  15

$EAE_peak
[1] 300  15

$`Spleen EAE chronic 1`
[1] 570  15

$`Spleen EAE chronic 2`
[1] 1191   15

$Spleen_EAE_peak
[1] 247  15

Thanks for your help.

Doug

**Comment by ncborcherding** [comment]
Hey Doug,

Thanks for the follow up! 

The sample slected in ```compareClonotype``` needs to match the names of the list elements in **cd8combined2**

So the following is coming up blank because there are no clonotypes associated with "Peak_CNS" or "Peak_SPL".
```
compareClonotypes(cd8combined2, numbers = 5, samples = c("Peak_CNS", "Peak_SPL"), cloneCall="gene", graph = "alluvial")
```

Maybe try (assuming the biology by names)
```
compareClonotypes(cd8combined2, numbers = 5, samples = c("EAE_peak", "Spleen_EAE_peak"), cloneCall="gene", graph = "alluvial")
```

Let me know if this fixes the issue, thanks,
Nick

**Comment by dhcorn** [comment]
Nick,

That worked great. I can't believe it was just the names. Thank you for your help with that. 

Also, something that seems easy in principle, but for some reason is not working. I would like to pull out the TCRs that are in the highest proportion, or number, in the dataset for each sample. So in order to do this I have tried to sort the data on the Frequency column, however, it hasn't really worked as I either only get the frequency numbers, as in my original post, or it doesn't sort at all. I have been using this code:

>cd8sort <- cd8sub[sort(cd8sub@meta.data$Frequency, decreasing = T, na.last = T)] 

I just dont know where I am going wrong with this. 

Thanks,

Doug

**Comment by ncborcherding** [comment]
Hey Doug,

Glad we figured it out!

For the above problem, I would make a data frame first of the meta data and then sort. 

```
cd8meta <- cd8sub[[]] #extract meta data
cd8sort <- cd8meta[sort(cd8meta$Frequency, decreasing = T, na.last = T),] #notice the comma I added to index for rows

```

Hope that helps, I will close the issue for now (as we have solved the initial problem), but feel free to keep asking questions.

Thanks,
Nick

**Comment by dhcorn** [comment]
Hey Nick,

Thank you for your help. I actually could not get the sort() function to work (it just returned a data frame full of NAs), however when I used the order() function it worked well. I am just posting in case someone else had this same issue. My code ended up looking like this:

>cd8meta <- cd8sub[[]] 
>cd8sort <- cd8meta[order(cd8meta$Frequency, decreasing = T, na.last = T),] 

Thanks again!
Doug
