### ISSUE TITLE
CombineTCR error

### ISSUE THREAD

**Issue by howardchen0810** [ncborcherding/scRepertoire#66]
Hi, I had problem when I was running combineTCR function.
I input 5 csv files and combined into a variable called my_list
csv1 <- read.csv("../../data/TCR/m1.csv", stringsAsFactors = F)
csv1a <- read.csv("../../data/TCR/m1a.csv", stringsAsFactors = F)
csv1b <- read.csv("../../data/TCR/m1b.csv", stringsAsFactors = F)
csv5 <- read.csv("../../data/TCR/m5.csv", stringsAsFactors = F)
csvML <- read.csv("../../data/TCR/ML.csv", stringsAsFactors = F)
mylist <- list(csv1, csv1a, csv1b,csv5,csvML)

then following is the code I used. I have 5 sample name and two ID
my_combined <- combineTCR(mylist, samples = c("m1","m1a","m1b","m5","ML"), ID = c("IRAE", "IRAE","IRAE","NOD","NOD"), cells = "T-AB")

But after I ran it, error pop up like this:
Error in `$<-.data.frame`(`*tmp*`, "sample", value = "m1") : 
  replacement has 1 row, data has 0

Thanks!
Howard

**Comment by howardchen0810** [comment]
When I installed this 
devtools::install_github("ncborcherding/scRepertoire@refine") 

then it fixed my problem

Thanks

**Comment by ncborcherding** [comment]
Hey Howard,

Thanks for posting the issue and solution!

Yes the is an issue an issue in the master branch for cell ranger v5 users, will fix right now.

As of right now though both of the following should work, but dev branch should be the way to go in the future.
```
devtools::install_github("ncborcherding/scRepertoire@refine")
devtools::install_github("ncborcherding/scRepertoire@dev")
```

Thanks
Nick

**Comment by toddknutson** [comment]
Sorry to comment on a closed issue, but I was having the same issue using the Bioconductor version 1.0.0. However, as mentioned above, installing the current GitHub "master" or "dev" branches solved my issue. I'm using cellranger 6.0.0 outputs.

I just wanted to mention that the Bioconductor version might need to be updated soon.

Thanks for a great package!

**Comment by ncborcherding** [comment]
Thanks, appreciate the comment, will be updating soon, want to make sure all the changes are stable.
