### ISSUE TITLE
Error when running combineExpression

### ISSUE THREAD

**Issue by s2hui** [ncborcherding/scRepertoire#67]
Hello,

I ran created a combined object that has 18 samples as:

```
contig_list = list()
for(i in 1:length(EXT_IDS)) {
   name = EXT_IDS[i]
   csv = read.csv(paste0(name,".vdj/filtered_contig_annotations.csv"), stringsAsFactors = F)
   contig_list[[i]] = csv
}

combined <- combineTCR(contig_list, samples = SAMPLE_IDS, ID = REGION_NUM, cells ="T-AB")

```
Then I loaded a Seurat object that I had previously preprocessed that contains 21 samples where the 19 samples in combined are a subset of the samples in my Seurat object.  Two samples did not have vdj data and the third did not have any TRA or TRB chains.  Then I ran combineExpression to try to add the clonotypic info to the Seurat object.

```
so <- readRDS("seurat_object.rds")

so <- combineExpression(combined,so)
```

But I get the following error:

```
Error in `[[<-`(`*tmp*`, col.name, value = PreMeta) : 
  [[<- defined for objects of type "S4" only for subclasses of environment
```

I confirmed that the barcodes in combined match barcodes in my seurat object (i.e. combined$sample$barcode  match Cells(so)).

I am wondering what the problem may be?  Is it failing b/c I don't have info in combined for 3 of the samples in my Seurat object.

Thanks for your help!

**Comment by s2hui** [comment]
I ended up installing scRepertoire again and now things are working.  I suspect there was some mismatch between the version of R (v4) and the version of scRepertoire I had installed previously.

**Comment by ncborcherding** [comment]
Hey s2hui,

Apologies for the delayed response but thanks so much for the well-characterized problem and solution. Really appreciate the help.

Thanks,
Nick
