### ISSUE TITLE
How to best ensure the same barcode name before combineExpression()?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [ncborcherding/scRepertoire#69]
Hi @ncborcherding, 

Thank you for a great package! 

I read the previous issues, but I am still confused how to best change my Seurat object rownames to match with my combined TCR clonotype barcodes. 

Question 1. Is it better to combine all 3 donors into 1 list for scRepertoire analysis (what I did)?

Question 2. Would you mind showing me how to change the cell barcodes so I can combineExpression()? I tried the RenameCells() function in Seurat but not very sure the best way to do it because I have 3 donors (see below - showing only R5pos data).

Question 3. I also have another set of scRNA transcript data and TCR sequence data for these same 3 donors, but of a different sorting (this data is of the same cell types but do not express CXCR5 protein). I had merged them (R5pos and R5neg) all and analyzed in Seurat. I now want to add TCR clonotype info to this merged analysis. Would you mind advising me the best way to do this? Should I make a list of 6 (3 from R5neg and 3 from R5pos) for scRepertoire and use the merged Seurat object? Or, should I aggregate the TCR sequence data of 3 donors in R5neg in Cellranger first?

Thank you so much!

**I have 3 donors T230, T240, and T246. For the TCR sequence data, I made each donor into 1 level of the list.**

```
# Showing the T230 donor
head(cxcr5pos_TCR_T230T240T246_contig_list_combined_TAB[[1]])
```
<img width="239" alt="Screen Shot 2021-03-24 at 2 21 17 AM" src="https://user-images.githubusercontent.com/62179082/112244769-9f69a680-8c47-11eb-8487-e14953078f20.png">

**For my Seurat object, I also have the same 3 donors. But, I merged the 3 donors into 1 Seurat object.**
The -1 in the rownames refers to T230 donor (-2 would be T240, and -3 would be T246). Same for the column orig.ident

```
# Showing the Seurat object meta.data
head(cxcr5pos_filtergene_cellselect@meta.data)
```
<img width="206" alt="Screen Shot 2021-03-24 at 2 25 45 AM" src="https://user-images.githubusercontent.com/62179082/112245141-3e8e9e00-8c48-11eb-9ef8-b574d7c515c1.png">

**Comment by ncborcherding** [comment]
Hey Quang, 

Thanks for reaching out and great/organized run down of your issues!

> Question 1. Is it better to combine all 3 donors into 1 list for scRepertoire analysis (what I did)?

I think so, it allows you to incorporate the immune receptors into the meta data of your seurat object so you can visualize everything all at once. 

> Question 2. Would you mind showing me how to change the cell barcodes so I can combineExpression()? I tried the RenameCells() function in Seurat but not very sure the best way to do it because I have 3 donors (see below - showing only R5pos data).

So for your seurat object, the barcodes labeled with unique suffixes? How do you differentiate the CXCR5 status? Or by the name of your seurat object, are there more than one seurat object? This should be possible, I think we will hav to modify the both the barcodes from your `combineTCR()` and seurat object, just need a couple more details.

> Question 3. I also have another set of scRNA transcript data and TCR sequence data for these same 3 donors, but of a different sorting (this data is of the same cell types but do not express CXCR5 protein). I had merged them (R5pos and R5neg) all and analyzed in Seurat. I now want to add TCR clonotype info to this merged analysis. Would you mind advising me the best way to do this? Should I make a list of 6 (3 from R5neg and 3 from R5pos) for scRepertoire and use the merged Seurat object? Or, should I aggregate the TCR sequence data of 3 donors in R5neg in Cellranger first?

I think if you would like to look at clonal sharing between CXCR5 pos/neg, you will need to make a list of 6 (3 from R5neg and 3 from R5pos), `combineExpression()` can then be used with the sample variable to allow you to call frequency/proportion across both your CXCR5-pos and CXCR5-neg runs for a single sample. An alternative would be to `combineExpression()` on the individual seurat objects and then merge? 

I am not sure what you mean by aggregate the TCR sequences of the 3 donors using Cellranger? 

Thanks,
Nick

**Comment by ncborcherding** [comment]
Hey Quang, 

Apologies for the delay. 

> When I merged the R5neg and R5pos data into 1 Seurat object, I use add.cells.id to append "R5pos" or "R5neg" in front of the cell barcode. I also created a meta.data column of R5_status to specify which cells from R5pos and R5neg.

>So, I managed to subset my Seurat R5pos object into individual donors, then use the RenameCells() to add "T230_R5pos" to the barcodes of my Seurat object for each donor. Then, I merged all 3 donors back. I did the same procedure for the R5neg object.

In my mind, the easiest way to do this would be 

1. Remove the suffixes for your barcodes - this will prevent the proper merge in the `combineExpression()
 This could be done by getting the cellnames of your seurat object and using ```stringr::stringr::str_remove(cellnames, "-1")``` - You could also use gsub and replace all the suffixes to -1 to match the barcode in your `combineTCR()` argument, which would prevent you from having to `stripBarcodes()` on your original contig files. 
2. Then add the sample names to the front to produce the **T230_R5pos_XXXXX** pattern

> Assuming I succeeded in changing the names properly, I encountered a new issue. 😅. For my R5pos data, when I combineExpression() using my TCR "combined" object for the R5pos TCRs (which is of a list type, each is from a donor) and my Seurat object (which is not a "list", but is just a "data frame" of Seurat class, so it has all 3 donors in 1 data frame just with a suffix _1 or _2 or _3), it appeared that only donor T230 (i.e. _1) gets the clonotype info added to my Seurat object meta.data.

This makes me think the suffix number might be the problem as if your orig.ident is ordered by sample name, I assume T230 might correspond to -1, while the other samples might have xxxxxx-2 or xxxxxxxx-3? Especially if the other samples meta data is appended as just NA values - that is usually a barcode matching issue. 

> Question 2. For my R5pos data, instead of merging my Seurat objects from each donor (into 1 Seurat R5pos object for 3 donors), do I need to actually make a "list" of 3 donors, i.e. having a Seurat list of 3 donor data? I am worried whether making a list of Seurat objects (instead of merging the count matrice) would impact somehow my Seurat clustering analysis.

No I do not think you need to make a list of seurat objects and I agree that might affect your clustering (as well as overall analyses/conclusions). I think we just need to figure out the barcodes.

If you're open to sharing, feel free to[ email ](mailto:ncborch@gmail.com) me a google drive or whatever with your meta.data/seurat/contigs (whatever you feel comfortable sharing) and I can write a loop for the barcode correction. I think it would be useful to others (pobably incorporate it into a function), as the way seurat now automatically combines sequencing runs makes using scRepertoire difficult.

Thanks,
Nick

**Comment by denvercal1234GitHub** [comment]
Hi @ncborcherding, 

You are correct that the suffix dictates the donor: -1 (for T230), -2 (for T240), and -3 (for T246). The column orig.ident also dictates the donor ID. 

I have emailed you some more info with title "Seurat and scRepertoire Cell Barcode Matching" from "ndm.ox.ac.uk"

Thank you so much again for your replies and help!

**Comment by denvercal1234GitHub** [comment]
Hi @ncborcherding - I have emailed you the objects. My apologies for the delay. Thank you again for your help with this issue! I hope all is well.

**Comment by ncborcherding** [comment]
I am going to close the issue, but I did want to share the code that helped solve the problem. Seurat new method during integration is to add a unique suffix to the barcode to prevent duplications, so in the instance above there was a -2 and -3 added for the second and third sample. To fix this, you can either modify your ```combineTCR()``` object or your seurat object. The seurat object is probably easier, because the creators have a function for this ```RenameCells()```

```
cellnames <- rownames(seurat.object[[]])
cellnames <- gsub("-2", "-1", cellnames)
cellnames <- gsub("-3", "-1", cellnames)

seurat.object <- RenameCells(seurat.object, new.names = cellnames)
```

I will work on optimizing this for users, thanks Quang for bringing this issue up.

Nick

**Comment by denvercal1234GitHub** [comment]
Hi @ncborcherding - Thank you for your response. 

I do not think it is the issue of the barcode mismatch, because the TCR list object has 3 donors, each donor denoted as -1, -2, or -3. This is the same in the Seurat object. If you examine the Seurat object (not in a list type) and the TCR list I emailed, you will see that they have this structure in the cell barcode. 

The issue I am facing is when I do combineExpression(), only the first element of the TCR list (donor 1) get the TCR clonotype transferred to donor 1 in the Seurat object, but donor 2 and 3 data do not get transferred. That is why I asked earlier whether I should also make my Seurat object as a list. 

Do you know why this is the case?
