### ISSUE TITLE
my issue in combined function

### ISSUE THREAD

**Issue by entcai** [ncborcherding/scRepertoire#7]
Hi Nicholas,
Thank you for the wonderful package. It is really nice and convenient for TCR and RNA analysis.
But, I found some problem when I used combined TCR function. The barcode would be different from the same input. my codes as following
`
options( stringsAsFactors = F)
join.cs<-colnames(pbmc)
group.info<-pbmc@meta.data$hash.ID

DGE.group<-data.frame(barcode=as.character(join.cs),group=as.character(group.info))

csv1 <- read.csv("../filtered_contig_annotations.csv")

csv1$barcode<-gsub('-1','',csv1$barcode)

tmp<-(intersect(csv1$barcode,join.cs)) ##1076 cell barcodes are shared in VDJ and DGE
table(duplicated(tmp))
csv1<-subset(csv1,csv1$barcode%in%tmp)

csv1<-left_join(csv1,DGE.group)

contig_list <- split(csv1,csv1$group)

combined <- combineTCR(contig_list, cells ="T-AB",samples = names(contig_list), ID = rep("VDJ",9))

############
csv2 <- read.csv("../filtered_contig_annotations.csv") ##CSV2 is the same as CSV1

csv2$barcode<-gsub('-1','',csv2$barcode)

tmp<-(intersect(csv2$barcode,join.cs)) ##1076 cell barcodes are shared in VDJ and DGE
table(duplicated(tmp))
csv2<-subset(csv2,csv2$barcode%in%tmp)

contig_list2 <- list(csv2)
combined2 <- combineTCR(contig_list2, cells ="T-AB",samples = 'SP1_3', ID = 'VDJ') ##the number of barcode in combined 2 is the same as combined 1, which is 950, but detailed sequence is different.

##########
VDJ.list2<-list()

for (i in 1:1) {VDJ.list2[[i]]=substr(combined2[[i]]$barcode,11,26)}

VDJ.list2<-unlist(VDJ.list2)

####
VDJ.list<-list()

for (i in 1:9) {VDJ.list[[i]]=substr(combined[[i]]$barcode,15,30)}

VDJ.list<-unlist(VDJ.list)

length(intersect(VDJ.list,VDJ.list2)) ##### the length here is only 24, rather than 950
` 
I checked the barcode in contig_list. I guess ,for some reason,the barcode changed after 'combined <- combineTCR(contig_list, cells ="T-AB",samples = names(contig_list), ID = rep("VDJ",9))
' But, interesting thing is the barcode remains same after 'combined2 <- combineTCR(contig_list2, cells ="T-AB",samples = 'SP1_3', ID = 'VDJ') '.

As you may saw, I preferred using 'ombined <- combineTCR(contig_list, cells ="T-AB",samples = names(contig_list), ID = rep("VDJ",9))' when my TCR file already combined with samples. Would you like to help me to solve this problem?

And, my second issue happended in

#####

`
seurat <- get(load("../pbmc.Robj"))
seurat<-seurat[,VDJ.list2]
DimPlot(seurat, label = T) + NoLegend()

seurat <- combineSeurat(combined2, seurat, cloneCall="gene", groupBy = "sample")`

it showed an error: `i` must have one dimension, not 2.

Sorry for the long questions. 
Best wishes and Stay safe.

**Comment by ncborcherding** [comment]
**For Issue 1:**

Would you mind giving me the head() output of combined[[1]] and combined[[2]]. What do you mean by "detailed sequence is different"?

The combineTCR() will add the sample and ID inputs as prefixes to the barcode. I am not sure why the barcode remains the same after combined2. 

**For Issue 2:** 
groupBy requires the specific header from your meta.data to calculate the frequency of the clonotype. In the example data, that is "sample", for most seurat objects, it is "orig.ident". What does the head(seurat[[]]) output look like?

**Comment by CP1085** [comment]
Hi, 
I have the same issue than issue 2. I put the header of the meta.data that I wanted and still get the same error. As you mention, the combineTCR() function adds a prefix  to the barcode. Are the barcodes the issue (now they do not match anymore)? and if yes, is there an easy way to change the barcodes back to what they were (sorry I am quite new in R coding...)?

**Comment by ncborcherding** [comment]
Hey CP1085 - 

A little off topic but want to answer because this is the question I receive the vast majority of the time. Yes the `combineTCR()` or `combineBCR()` adds both the sample and ID variables to the prefixes of the barcodes of the contigs. 

If the prefix of the barcodes are the only difference between the combined object and the seurat object, i.e. the combined object has barcodes like P1_Time1_AAACCTGAGAGCTGGT and the seurat object has barcodes like, P1_AAACCTGAGAGCTGGT. Using the `changeNames` function in scRepertoire on the seurat object will quickly modify the prefixes to match. 

The call would resemble something like:
`seurat <- changeNames(seurat, seuratID(prefixes of the seurat object), newID (prefixes in the combined object)`
`seurat <- changeNames(seurat, seuratID = c("P1", "P1", "P2", ....), newID = c("Time1", "Time2
, "Time1, ...)`

If the barcodes vary considerably (both prefixes and suffixes) that will be a little more difficult, feel free to [email](mailto:ncborch@gmail.com) me with outputs of head() on the seurat object and combine object and I can help figure out a solution.

**Comment by entcai** [comment]
Hi,Nicholas
Thank you for your reply. the detailed sequence is different means the barcode sequence changed more than adding sample and ID name on it. After combinedTCR, for example, the barcode "AAACCTGGTAAGTGTA " may change to "AAACTCCACCTTGTC", which is weird. I checked the source code in the package there seems nothing related to this alteration. But this type of alteration didn't happened in combined2, which is expected.  

If I remove the prefix, the overlap of barcodes between combined and combined2 should be 100%, right? but, here in my data, the overlap is only 24/950.

I compared the barcodes in contig_list, contig_list2, combined, combined2 derived from the same TCR CSV input. by 
`barcode.data<-as.data.frame(cbind(combined=sort(VDJ.list),combined2=sort(VDJ.list2),
                         contig_list=sort(col1),conti_list2=sort(col2)))
`

![image](https://user-images.githubusercontent.com/59844067/79481986-32cd3d00-7fde-11ea-8e59-fc7c3942fd2f.png)

As we can see in the picture, the "contig_list" is completely same as" contig_list2", and most of "combined2". But, The barcode in the "combined" column is so different(ONLY 24 BARCODES OVERLAPPED WITH OTHERS).  

For the issue2, it worked when I used groupBy='none'.  But, it didn't work when I use groupBy='sample' . my header of metadata like 
![image](https://user-images.githubusercontent.com/59844067/79482858-68bef100-7fdf-11ea-8272-e5aa414ac6d5.png). I will update and try it again.

Thank you.

**Comment by entcai** [comment]
head(combined2)
$SP1_3_VDJ
                       barcode sample  ID                                          TCR1
1   SP1_3_VDJ_AAACCTGGTAAGTGTA  SP1_3 VDJ                          TRAV12-2.TRAJ40.TRAC
3   SP1_3_VDJ_AAACGGGAGTTAAGTG  SP1_3 VDJ                            TRAV10.TRAJ43.TRAC
4   SP1_3_VDJ_AAACGGGGTGTCGCTG  SP1_3 VDJ                          TRAV12-2.TRAJ27.TRAC

**Comment by ncborcherding** [comment]
entcai,

**Issue 1**

How did you get col1 and col2?
`barcode.data<-as.data.frame(cbind(combined=sort(VDJ.list),combined2=sort(VDJ.list2), contig_list=sort(col1),conti_list2=sort(col2)))`

I ask because col1 have 15-letter barcodes and col2 has 16 letters?

**Issue 2**

Sorry I must have edited the comment while you were typing or submitting, poor practice on my part. I found the issue lies in the recent update subsetting in tibble. The combineSeurat() has been updated to prevent the conversion to a tibble during the groupBy portion of the function.

**Comment by entcai** [comment]
> entcai,
> 
> **Issue 1**
> 
> How did you get col1 and col2?
> `barcode.data<-as.data.frame(cbind(combined=sort(VDJ.list),combined2=sort(VDJ.list2), contig_list=sort(col1),conti_list2=sort(col2)))`
> 
> I ask because col1 have 15-letter barcodes and col2 has 16 letters?
> 
> **Issue 2**
> 
> Sorry I must have edited the comment while you were typing or submitting, poor practice on my part. I found the issue lies in the recent update subsetting in tibble. The combineSeurat() has been updated to prevent the conversion to a tibble during the groupBy portion of the function.

Hi,
I used the code. Both of them are 16
`contig_list <- split(csv1,csv1$group)
contig_list2 <- list(csv2)
col1<-list()
{for (i in 1:9) {col1[[i]]=contig_list[[i]]$barcode}
  
  col1<-unlist(col1)}

col2<-list()
{for (i in 1:1) {col2[[i]]=contig_list2[[i]]$barcode}
  
  col2<-unlist(col2)}`
May I email you the data I used?

**Comment by ncborcherding** [comment]
My apologies, I meant VDJ.list1/2 - 
based on nchar(VDJ.list[1,]) = 15 and nchar(VDJ.list2[1,]) = 16

Please do send me the data, my [email](mailto:ncborch@gmail.com). Let's get this figured out!

**Comment by ncborcherding** [comment]
Working through the issue this morning, no issue with combineTCR(), but rather VDJ.list creation. The group names varied in length

`VDJ.list<-list()`

`for (i in 1:9) {VDJ.list[[i]]=stringr::**str_split(combined[[i]]$barcode, “_”, simplify=T)[,3]}**`

`VDJ.list<-unlist(VDJ.list)`

I'm going to close this issue, but I think entcai's code is a great example of looping and pre-processing for new users of R!
