### ISSUE TITLE
general suggestion: interfacing with bulk repertoire seq

### ISSUE THREAD

**Issue by kanefos** [ncborcherding/scRepertoire#72]
Hi authors,

Firstly just wanted to say this looks like a great tool, I'm really looking forward to working with it. This idea has been on my mind a lot recently, and given this is an exciting new tool I was wondering if I could voice it here - have you had any thoughts or plans about interfacing single-cell repertoire data with bulk repertoire sequencing? 

Obviously it's a possibility to simply overlay the frequency of expanded receptors onto a UMAP, and there's also some specific advantages (i.e. connecting TCR alpha and beta chains from bulk RNA data) - but beyond these, have you thought about any statistical frameworks to better-characterise receptors between single and bulk data, or perhaps take single-cell phenotypes upwards into bulk data? I know [TESSA](https://github.com/jcao89757/TESSA) does the latter, but I am thinking of possible initial simpler solutions. 

If you've had any thoughts about this or know of some other tools which work along these lines let me know, it's an area I'm very interested in. Thanks, K

**Comment by ncborcherding** [comment]
Hey Kane, 

I had not thought about this, but I think it is a great suggestion. As of right now, I am not aware of tools that can bridge both single-cell and bulk AIRR sequencing and provides the necessary statistical frameworks. There is [immunarch](https://github.com/immunomind/immunarch) that allows for processing of both types of sequencing, but that does not seem to be what you are asking. 

I will add it to the ever growing scRepertoire "to-do" list. I would also be more than happy to receive any code/commits from you or others on this topic. I will have more dedicated research time this fall and am planning to have a major overhaul of the package for more advanced analyses and broader usability.

Thanks again,
Nick

**Comment by kanefos** [comment]
Hey Nick, thanks for sharing Immunarch I hadn't seen that tool before. I'll let you know if I take this idea anywhere or if I see anything relevant, excited to see where scRepertoire goes. Cheers
