### ISSUE TITLE
Error in combineTCR

### ISSUE THREAD

**Issue by dkcoxie** [ncborcherding/scRepertoire#73]
Looked for examples for creating the input object from the 10x Cell Ranger output file and loaded the `contig_list` example data and used that to compare my input data list/nested data.frame formats. But repeatedly getting getting an error that I find confusing when trying to run the `combineTCR` function.

SessionInfo summary: R version 4.0.3, Bioc 1.30.10, scRepertoire 1.0.0 (installed from Bioconductor)

My data: `VDJ_data` - Large list generated from reading in 8 different ‘filtered_contig_annotations.csv’ inputs (in separate directories so read in via a loop), but read csv line is:
`VDJ_data[[j]] = read.csv(dirname, colClasses = VDJClasses)`,
where `j` is a numeric index for the list assignment (1-8), `dirname` is the full path to the csv file for each sample,  and `VDJClasses` is a list of class assignments pulled from the example `contig_list` dataset (since logical columns were encoded as lower case/strings in original files). My barcodes are formatted as 'AAAGCAAGTCGACTAT-1' so did not strip the barcodes for any of my input data. Did have empty fields so replaced them with 'None' to match example but triggered the same error with/without filling in the blank fields.

Compared column names between the example data and my data:
`colnames(contig_list[[1]]) == colnames(VDJ_data[[1]]) # Returns all TRUE `

Also compared classes between the example data and my data:
`sapply(VDJ_data[[1]], class) == sapply(contig_list[[1]], class) # Returns TRUE for each column`

When I try to combine the example data (following the code in the vignette), 'combineTCR' works. However, when I try to execute the same command with my data I get an error:
`combinedVDJ <- combineTCR(VDJ_data, samples = c(YoungA1, YoungA2, YoungA3, YoungA4, AgedA1, AgedA2, AgedA3, AgedA4), ID = c(Young, Young, Young, Young, Aged, Aged, Aged, Aged), cells = "T-AB")`
Error is:
`Error in '$<-.data.frame'('*tmp*', "sample", value="YoungA1") : replacement has 1 row, data has 0`

However, I see my data in `VDJ_data`, i.e. `head(VDJ_data[[1]], n = 1` returns:
<img width="778" alt="Screen Shot 2021-05-03 at 5 55 42 PM" src="https://user-images.githubusercontent.com/8195950/116938581-f72d0180-ac38-11eb-8f43-5ab0b98962d5.png">

Happy to provide additional replication information but hoping there is something very obvious that I'm missing. Thanks for your help!

**Comment by ncborcherding** [comment]
Hey Dana,

Thank you for the great run down!!

My first guess is this is a result of using Cell Ranger >= 5.0 - 10x Genomics changed their outputs slightly in the newer versions and it has resulted in this error. 

My suggestion is to try the github repo to get the most-up-to-date version with:

```
devtools::install_github("ncborcherding/scRepertoire")
``` 

If the problem persists, please let me know and I would be happy to troubleshoot with you to figure things out. 

Thanks again,
Nick

**Comment by dkcoxie** [comment]
Awesome, thanks for the prompt reply. Will install the current version of scRepertoire instead of the Bioconductor version & report back.

**Comment by dkcoxie** [comment]
The github version worked great - matched my colClasses to the example data when reading in the csv and then had no error with combineTCR().

**Comment by mbartl13** [comment]
Hi- I am getting a similar error for combineTCR using v4 cellranger output but using the dev version did not solve:
```
> S1 <- read.csv("13F_TCR_20210607/outs/filtered_contig_annotations.csv")
> S2 <- read.csv("43F_TCR_20210607/outs/filtered_contig_annotations.csv")
> contig_list <- list(S1, S2)
> for (i in seq_along(contig_list)) {
+   contig_list[[i]] <- stripBarcode(contig_list[[i]], 
+                                    column = 1, connector = "_", num_connects = 1)
+ }

> combined <- combineTCR(contig_list, 
+                        samples = c("13F", "43F"), 
+                        ID = c("S1", "S2"), cells ="T-AB")
Error in `$<-.data.frame`(`*tmp*`, "sample", value = "13F") : 
  replacement has 1 row, data has 0
```
`> session_info()
- Session info -------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.1.0 (2021-05-18)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/New_York            
 date     2021-08-05                  

- Packages -----------------------------------------------------------------------------------------------
 package              * version  date       lib source                                     
 Biobase                2.52.0   2021-05-19 [1] Bioconductor                               
 BiocGenerics           0.38.0   2021-05-19 [1] Bioconductor                               
 bitops                 1.0-7    2021-04-24 [1] CRAN (R 4.1.0)                             
 cachem                 1.0.5    2021-05-15 [1] CRAN (R 4.1.0)                             
 callr                  3.7.0    2021-04-20 [1] CRAN (R 4.1.0)                             
 cli                    3.0.1    2021-07-17 [1] CRAN (R 4.1.0)                             
 cluster                2.1.2    2021-04-17 [2] CRAN (R 4.1.0)                             
 codetools              0.2-18   2020-11-04 [2] CRAN (R 4.1.0)                             
 colorspace             2.0-2    2021-06-24 [1] CRAN (R 4.1.0)                             
 crayon                 1.4.1    2021-02-08 [1] CRAN (R 4.1.0)                             
 cubature               2.0.4.2  2021-05-13 [1] CRAN (R 4.1.0)                             
 curl                   4.3.2    2021-06-23 [1] CRAN (R 4.1.0)                             
 DelayedArray           0.18.0   2021-05-19 [1] Bioconductor                               
 desc                   1.3.0    2021-03-05 [1] CRAN (R 4.1.0)                             
 devtools             * 2.4.2    2021-06-07 [1] CRAN (R 4.1.0)                             
 doParallel             1.0.16   2020-10-16 [1] CRAN (R 4.1.0)                             
 dplyr                  1.0.7    2021-06-18 [1] CRAN (R 4.1.0)                             
 ellipsis               0.3.2    2021-04-29 [1] CRAN (R 4.1.0)                             
 evd                    2.3-3    2018-04-25 [1] CRAN (R 4.1.0)                             
 evmix                  2.12     2019-09-03 [1] CRAN (R 4.1.0)                             
 fansi                  0.5.0    2021-05-25 [1] CRAN (R 4.1.0)                             
 fastmap                1.1.0    2021-01-25 [1] CRAN (R 4.1.0)                             
 foreach                1.5.1    2020-10-15 [1] CRAN (R 4.1.0)                             
 fs                     1.5.0    2020-07-31 [1] CRAN (R 4.1.0)                             
 generics               0.1.0    2020-10-31 [1] CRAN (R 4.1.0)                             
 GenomeInfoDb           1.28.1   2021-07-01 [1] Bioconductor                               
 GenomeInfoDbData       1.2.6    2021-08-05 [1] Bioconductor                               
 GenomicRanges          1.44.0   2021-05-19 [1] Bioconductor                               
 ggalluvial             0.12.3   2020-12-05 [1] CRAN (R 4.1.0)                             
 ggplot2              * 3.3.5    2021-06-25 [1] CRAN (R 4.1.0)                             
 glue                   1.4.2    2020-08-27 [1] CRAN (R 4.1.0)                             
 gsl                    2.1-6    2019-03-25 [1] CRAN (R 4.1.0)                             
 gtable                 0.3.0    2019-03-25 [1] CRAN (R 4.1.0)                             
 igraph                 1.2.6    2020-10-06 [1] CRAN (R 4.1.0)                             
 IRanges                2.26.0   2021-05-19 [1] Bioconductor                               
 iterators              1.0.13   2020-10-15 [1] CRAN (R 4.1.0)                             
 lattice                0.20-44  2021-05-02 [2] CRAN (R 4.1.0)                             
 lifecycle              1.0.0    2021-02-15 [1] CRAN (R 4.1.0)                             
 magrittr               2.0.1    2020-11-17 [1] CRAN (R 4.1.0)                             
 MASS                   7.3-54   2021-05-03 [2] CRAN (R 4.1.0)                             
 Matrix               * 1.3-3    2021-05-04 [2] CRAN (R 4.1.0)                             
 MatrixGenerics         1.4.1    2021-08-03 [1] Bioconductor                               
 matrixStats            0.60.0   2021-07-26 [1] CRAN (R 4.1.0)                             
 memoise                2.0.0    2021-01-26 [1] CRAN (R 4.1.0)                             
 mgcv                   1.8-35   2021-04-18 [2] CRAN (R 4.1.0)                             
 munsell                0.5.0    2018-06-12 [1] CRAN (R 4.1.0)                             
 nlme                   3.1-152  2021-02-04 [2] CRAN (R 4.1.0)                             
 permute                0.9-5    2019-03-12 [1] CRAN (R 4.1.0)                             
 pillar                 1.6.2    2021-07-29 [1] CRAN (R 4.1.0)                             
 pkgbuild               1.2.0    2020-12-15 [1] CRAN (R 4.1.0)                             
 pkgconfig              2.0.3    2019-09-22 [1] CRAN (R 4.1.0)                             
 pkgload                1.2.1    2021-04-06 [1] CRAN (R 4.1.0)                             
 plyr                   1.8.6    2020-03-03 [1] CRAN (R 4.1.0)                             
 powerTCR               1.12.0   2021-05-19 [1] Bioconductor                               
 prettyunits            1.1.1    2020-01-24 [1] CRAN (R 4.1.0)                             
 processx               3.5.2    2021-04-30 [1] CRAN (R 4.1.0)                             
 ps                     1.6.0    2021-02-28 [1] CRAN (R 4.1.0)                             
 purrr                  0.3.4    2020-04-17 [1] CRAN (R 4.1.0)                             
 R6                     2.5.0    2020-10-28 [1] CRAN (R 4.1.0)                             
 Rcpp                   1.0.7    2021-07-07 [1] CRAN (R 4.1.0)                             
 RCurl                  1.98-1.3 2021-03-16 [1] CRAN (R 4.1.0)                             
 remotes                2.4.0    2021-06-02 [1] CRAN (R 4.1.0)                             
 reshape2               1.4.4    2020-04-09 [1] CRAN (R 4.1.0)                             
 rlang                  0.4.11   2021-04-30 [1] CRAN (R 4.1.0)                             
 rprojroot              2.0.2    2020-11-15 [1] CRAN (R 4.1.0)                             
 rstudioapi             0.13     2020-11-12 [1] CRAN (R 4.1.0)                             
 S4Vectors              0.30.0   2021-05-19 [1] Bioconductor                               
 scales                 1.1.1    2020-05-11 [1] CRAN (R 4.1.0)                             
 scRepertoire         * 1.3.1    2021-08-05 [1] Github (ncborcherding/scRepertoire@204c169)
 sessioninfo            1.1.1    2018-11-05 [1] CRAN (R 4.1.0)                             
 SeuratObject         * 4.0.2    2021-06-09 [1] CRAN (R 4.1.0)                             
 SparseM                1.81     2021-02-18 [1] CRAN (R 4.1.0)                             
 stringdist             0.9.7    2021-07-28 [1] CRAN (R 4.1.0)                             
 stringi                1.7.3    2021-07-16 [1] CRAN (R 4.1.0)                             
 stringr                1.4.0    2019-02-10 [1] CRAN (R 4.1.0)                             
 SummarizedExperiment   1.22.0   2021-05-19 [1] Bioconductor                               
 testthat               3.0.4    2021-07-01 [1] CRAN (R 4.1.0)                             
 tibble                 3.1.3    2021-07-23 [1] CRAN (R 4.1.0)                             
 tidyselect             1.1.1    2021-04-30 [1] CRAN (R 4.1.0)                             
 truncdist              1.0-2    2016-08-30 [1] CRAN (R 4.1.0)                             
 usethis              * 2.0.1    2021-02-10 [1] CRAN (R 4.1.0)                             
 utf8                   1.2.2    2021-07-24 [1] CRAN (R 4.1.0)                             
 vctrs                  0.3.8    2021-04-29 [1] CRAN (R 4.1.0)                             
 vegan                  2.5-7    2020-11-28 [1] CRAN (R 4.1.0)                             
 VGAM                   1.1-5    2021-01-14 [1] CRAN (R 4.1.0)                             
 withr                  2.4.2    2021-04-18 [1] CRAN (R 4.1.0)                             
 XVector                0.32.0   2021-05-19 [1] Bioconductor                               
 zlibbioc               1.38.0   2021-05-19 [1] Bioconductor                               

[1] C:/Users/Maggie/Documents/R/win-library/4.1
[2] C:/Program Files/R/R-4.1.0/library`

`> head(contig_list[[1]])
             barcode is_cell                   contig_id high_confidence length chain v_gene d_gene j_gene
1 AAACCTGAGAAACGCC-1    TRUE AAACCTGAGAAACGCC-1_contig_1            TRUE    668  NONE   NONE   NONE   NONE
2 AAACCTGAGAAACGCC-1    TRUE AAACCTGAGAAACGCC-1_contig_2            TRUE    516  NONE   NONE   NONE   NONE
3 AAACCTGAGATGCCAG-1    TRUE AAACCTGAGATGCCAG-1_contig_1            TRUE    640  NONE   NONE   NONE   NONE
4 AAACCTGAGATGCCAG-1    TRUE AAACCTGAGATGCCAG-1_contig_2            TRUE    482  NONE   NONE   NONE   NONE
5 AAACCTGAGATGCCAG-1    TRUE AAACCTGAGATGCCAG-1_contig_3            TRUE    421  NONE   NONE   NONE   NONE
6 AAACCTGAGATGCGAC-1    TRUE AAACCTGAGATGCGAC-1_contig_1            TRUE    564  NONE   NONE   NONE   NONE
  c_gene full_length productive              cdr3                                             cdr3_nt reads
1   NONE       FALSE      FALSE      CIVIQAGTALIF                TGCATCGTGATCCAGGCTGGAACTGCACTGATCTTT   328
2   NONE       FALSE      FALSE   CASSEWTGGNQPQYF       TGCGCCAGCAGTGAGTGGACAGGGGGGAATCAGCCCCAGTATTTT   299
3   NONE       FALSE      FALSE   CAVRAGGAGYGKLTF       TGTGCTGTGAGGGCTGGTGGTGCTGGCTATGGAAAGCTGACATTT   140
4   NONE       FALSE      FALSE    CASSSTGAGEKLFF          TGCGCCAGCAGCTCGACAGGGGCTGGTGAAAAACTGTTTTTT   970
5   NONE       FALSE      FALSE   CAVSDRTTSYNKLMF       TGTGCTGTGAGTGACAGAACAACCTCCTACAACAAGCTGATGTTT   315
6   NONE       FALSE      FALSE CASSEADWGYRTDPQYF TGTGCCAGCAGTGAAGCGGACTGGGGTTATCGCACAGATCCGCAGTATTTT  1261
  umis raw_clonotype_id raw_consensus_id
1    7             NONE             NONE
2    5             NONE             NONE
3    4             NONE             NONE
4    5             NONE             NONE
5    3             NONE             NONE
6   14             NONE             NONE`

**Comment by ncborcherding** [comment]
Hey mbartl13, 

The most common reason for this error is that the filtering steps in combineTCR() results in 0 contigs left.  There are 2 major filters - 1) for productive chains only and 2) removal of chains designated as "Multi".

Based on what your showing in `head(contig_list[[1]])`, I'm concerned that possible your contigs are not "productive" as I do not see a chain, or v/d/j genes listed? But please let me know if that is not the case. If just one of the list elements has this issue, it will result in the same error. 

Please let me know and I will be happy to troubleshoot with you.

Nick

**Comment by mbartl13** [comment]
Hi Nick- thanks looks like they were missed during cellranger. I'll repeat and try again.

Thank you!
Maggie
________________________________
