### ISSUE TITLE
Alluvial graphs no longer labelled

### ISSUE THREAD

**Issue by JFavaloro** [ncborcherding/scRepertoire#74]
Hi Nick,

Still using your fantastic package! I’ve noticed in the update that alluvial graphs no longer appear to be labelled – was that an intentional change or have I just missed something?

Cheers

**Comment by ncborcherding** [comment]
Hey JFavaloro,

Good to hear from you!

Yes we needed to reduce the dependencies for the newer version, so we removed the automatic labeling (ggfittext has a number of dependencies). Sorry for the inconvenience.

You can add the labeling yourself with:

```
library(ggfittext)
alluvialClonotypes(...) + 
      geom_fit_text(stat = "stratum", infer.label = FALSE, reverse = TRUE)
```

Hope that helps,
Nick
