### ISSUE TITLE
Comparison of TCR clonotypes based on the alpha or beta chain only

### ISSUE THREAD

**Issue by lucygarner** [ncborcherding/scRepertoire#75]
Hi,

I would like to compare the clonality of TCR clonotypes defined using either the CDR3 alpha nucleotide sequence only or the CDR3 beta nucleotide sequence only.  Which metric of the ones that are offered in this package would you recommend for this?

Best wishes,
Lucy

**Comment by ncborcherding** [comment]
Hey Lucy,

Thanks for reaching out. 

As of right now, there is no easy to perform this using the functions built into the package (scRepertoire only offers 2-chain based functions). However, the alpha and beta sequences are combined using a "_". So you could manually edit the product of ```combinedTCR()``` by just selecting the chain of interest. 

something like:

```
for (i in seq_along(combined)) {
      combined[[i]]$CTnt <- stringr::str_split(combined[[i]]$CTnt, "_", simplify = TRUE)[,1] #1 for TCRA
}
```
Hope that helps, apologies for the inconvenience - I hope to be able to add the single chain function when I have more dedicated research time. 

Thanks,
Nick

**Comment by lucygarner** [comment]
Ok, thanks very much.  For this question, which diversity metric would you recommend out of Shannon, inverse Simpson, Chao1 and ACE?  From what I can tell, there doesn't seem to be a consensus within the literature on the most informative metric.

**Comment by ncborcherding** [comment]
Hey Lucy, 

I agree there isn't the greatest consensus with about which is best - the diversity functions in scRepertoire will automatically downsample by the smallest clonotype library in your contig list, which makes them more robust, but still not perfect. This approach is particularly advantageous for use in Shannon and species richness estimates (Chao1 v ACE) - note Chao1 assumes a Poisson distribution, I would check the distribution before I report this. 

Sorry that is not as helpful - but I generally show >1 estimator and I think Shannon and Inverse Simpson are more understood, so I opt for those.

Nick

**Comment by lucygarner** [comment]
Great, thanks very much

**Comment by ncborcherding** [comment]
Hey Lucy,

The dev branch will have support for single chains in the combineTCR()/combineBCR() functions - just committed the change, will work on adding the documentation today/tomorrow. You can indicate which chain you would like using the **chain** parameter - for T-AB, "TRA" or "TRB" for example. This uses the system outline above, but will do that automatically now that it is in the function itself.

Install new dev version
```
devtools::install_github("ncborcherding/scRepertoire@dev")

combineTCR(contig_list, samples = (), ID = (), cells = "T-AB",  chain = "TRA") #selects the TCRA chain
```

Thanks,
Nick
