### ISSUE TITLE
Difference in number unique clonotypes by quantContig vs getCirclize

### ISSUE THREAD

**Issue by JE001** [ncborcherding/scRepertoire#77]
Thank you for developing this useful package. I had a question regarding the number of unique clonotypes identified using the quantContig function vs the getCirclize function. When I use quantContig() I get a data frame with the number of unique clonotypes found in the list object generated by combineTCR() (see below, grouped by sample):

> quantContig(AFDN278_VDJ, cloneCall = "gene+nt", scale = TRUE, exportTable = TRUE)
      contigs              values                                 total        scaled
1     932         CD69+_AFDN278                        2048      45.50781
2     580         CD69+CD103+_AFDN278         1243       46.66130
3      62          DN_AFDN278                               83          74.69880
4     665         Naive_AFDN278                          3776      17.61123

However, when I use getCirclize() I get a data frame with a lower total number of unique clonotypes for each sample (see below):

> getCirclize(AFDN278_AllSubsets_VDJ, cloneCall = "gene+nt", groupBy = "subset", proportion = FALSE)
Using subset as value column: use value.var to override.
Aggregation function missing: defaulting to length
          from          to                           value
1        CD69+       CD69+                  615
2        CD69+      CD69+CD103+     78
3        CD69+       DN                         1
4        CD69+       Naive                     175
... 
(615 + 78 + 1 + 175 does not add up to 932 as counted in the first data frame).

Is this because getCirclize is drawing counts from the combineExpression object created by combining the TCR list object with the seurat object, which has less TCR sequences than the TCR list object (as not every TCR sequence may be matched to a cell?) I am new to this type of data analysis, so apologize if this seems to be a naive question. Thank you!

**Comment by ncborcherding** [comment]
Hey JE001, 

Thanks for reaching out. 

I think getCircilize drawing from the combineExpression object could be the cause of the difference in numbers - you can probably check this assumption by using ```expression2List(seurat, group = "orig.ident")``` to reform a combined contig object that you can then use ```quantContig()``` on. 

I would be interested in seeing the results of this -  ```getCircilize()``` was originally designed as a relative analysis of unique clonotypes - it has a key assumption of using the relative number of unique and overlaping clones, but is not using the clonotypes themselves - so there could be a small degree under/overestimate (this was to save memory usage), but your indicating possibly 7% difference as opposed to < 1%. 

So please follow up and thanks for letting me know,
Nick

**Comment by JE001** [comment]
Hi ncborcherding,

I apologize for the long delay in my response. I believe you are correct that the difference in numbers is caused by drawing from the combineExpression object versus the seurat object. Here are the results of running quantContig() on a reformed combined contig object:

> AFDN278_VDJ_2 <- expression2List(AFDN278_AllSubsets_VDJ, group = "subset")
> quantContig(AFDN278_VDJ_2, cloneCall = "gene+nt", scale = TRUE, exportTable = TRUE)
       contigs      values                      total           scaled
1     869            CD69+                     2255         38.53659
2     542            CD69+CD103+      1301           41.66026
3      61              DN                           85              71.76471
4     596            Naive                       3676         16.21328

Unlike my initial thought, there are now more total clonotypes for each sample (which may be because cells without TCR sequences mapped to them are still counted, but listed as "NA.") However, there are fewer unique clonotypes. The numbers now match the results of using the getCircilize() function on the seurat object.

**Comment by ncborcherding** [comment]
Hey great, thanks for the follow up!
