### ISSUE TITLE
Missing label in alluvial plots

### ISSUE THREAD

**Issue by mihem** [ncborcherding/scRepertoire#79]
Hi Nick,

sorry, in the latest version the labels within the y axes of `scRepertoire::alluvialPlot` are gone, this is also true for the alluvial plots produced in your nice tutorial.
taken from : https://www.bioconductor.org/packages/release/bioc/vignettes/scRepertoire/inst/doc/vignette.html

```
alluvialClonotypes(screp_example, cloneCall = "gene", 
                   y.axes = c("Patient", "cluster", "Type"), 
                   color = "TRAV12-2.TRAJ42.TRAC_TRBV20-1.TRBJ2-3.TRBD2.TRBC2") + 
    scale_fill_manual(values = c("grey", colorblind_vector(1)))
```

![image](https://user-images.githubusercontent.com/46907494/119544120-b6d12700-bd91-11eb-8861-fee48366e30a.png)

I think the information which patient/cluster/Type the different rectangles represent etc. is missing (while this worked fine in previous versions). 

Thanks!

**Comment by ncborcherding** [comment]
Hey Mischko,

Please see [issue 74](https://github.com/ncborcherding/scRepertoire/issues/74). 

This has to do with dependency issues that ggfittext imports, but you will be able to add the labeling yourself using 

```
library(ggfittext)
alluvialClonotypes(...) + 
      geom_fit_text(stat = "stratum", infer.label = FALSE, reverse = TRUE)
```

Thanks,

Nick

**Comment by ncborcherding** [comment]
Hey Mischko,

Automatic labeling will be added to the dev version. Will update to the master after some testing.

**Comment by mihem** [comment]
Hi NickOh that's great. Thanks!
