### ISSUE TITLE
ERROR: lazy loading failed for package ‘scRepertoire’

### ISSUE THREAD

**Issue by ncborcherding** [ncborcherding/scRepertoire#8]
Had a user email me with the following: 

> devtools::install_github("ncborcherding/scRepertoire")
Downloading GitHub repo ncborcherding/scRepertoire@master
Skipping 2 packages not available: Biostrings, powerTCR
   checking for file ‘/private/var/folders/y5/8f_d9m3x1mxdz8_f4wydlpwh0000gn/T/Rtmp4Ztt6s/remotes1f36415e38b6/ncborcherding-scRepertoire-eab0e39/DESCRIPTION’ ...✓  checking for file ‘/private/var/folders/y5/8f_d9m3x1mxdz8_f4wydlpwh0000gn/T/Rtmp4Ztt6s/remotes1f36415e38b6/ncborcherding-scRepertoire-eab0e39/DESCRIPTION’
─  preparing ‘scRepertoire’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘scRepertoire_1.0.0.tar.gz’
  
* installing *source* package ‘scRepertoire’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package ‘ggalluvial’ was built under R version 3.6.2
Execution halted
ERROR: lazy loading failed for package ‘scRepertoire’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/scRepertoire’
Error: Failed to install 'scRepertoire' from GitHub:
  (converted from warning) installation of package ‘/var/folders/y5/8f_d9m3x1mxdz8_f4wydlpwh0000gn/T//Rtmp4Ztt6s/file1f3610dd5641/scRepertoire_1.0.0.tar.gz’ had non-zero exit status

The problem seems to stem from a warning-to-error conversion and the issue was solved by changing the environmental variables:
 – R_REMOTES_NO_ERRORS_FROM_WARNINGS="true" (see this [link](https://github.com/r-lib/remotes#environment-variables)).

**Comment by pcantalupo** [comment]
Here is what I did to fix the error
```
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS = "true")
library(remotes)
install_github("ncborcherding/scRepertoire", upgrade = "never")
```
