### ISSUE TITLE
Reference for regressClonotype

### ISSUE THREAD

**Issue by kanefos** [ncborcherding/scRepertoire#80]
Hi there,

In section 6.6 of the vignette `regressClonotype()` is introduced with the following description:

> There is a high degree of overlap in the feature space of expanded clonotypes, not only in the adaptive receptor genes that form the clonotype, but also in potentially functional genes. 

Would I be able to get a reference for this? Specifically discussing how clonotype membership can contribute to clustering on gene expression data. Or if this is an observation you've simply made yourself - I think I might be encountering a similar effect with some of my data.

**Comment by ncborcherding** [comment]
Hey Kane, 

Sorry on mobile for awhile - pretty good summary of the studies on transcriptional similarity by clonotype in the [CoNGA preprint](https://www.biorxiv.org/content/10.1101/2020.06.04.134536v1.full.pdf).  Apologies for the self plug, but we noted it in the clonally expanded CD8 T cells in renal tumors [here](https://www.nature.com/articles/s42003-020-01625-6). 

To date, I am unaware of any group that comprehensively looked at the gene feature space by clonotype in a really rigorous way. One of the things I am working on is to try to quantify the difference/similarity of feature by clonotype (hence the testing of the regressClonotype() function and collecting large numbers of single-cell/TCR data).  More than happy to talk about it more anytime.

**Comment by kanefos** [comment]
Hey Nick

Thanks for such a speedy and informative reply! Really appreciate it. This definitely sounds like an important problem, I will be passing on any discoveries I make reading around this area. Thanks again.
