### ISSUE TITLE
Error in combineTCR() function

### ISSUE THREAD

**Issue by fouerghi** [ncborcherding/scRepertoire#81]
Hi, 

I keep getting this following error when trying to use the combineTCR() function:

Error in `$<-.data.frame`(`*tmp*`, "sample", value = "Tumor Only NS") : replacement has 1 row, data has 0

I saw in another thread that you suggested using the github version of scRepertoire, which I did and it worked fine for a little bit and then it went back to showing this error. I tried to force the reinstallation but the error is still there. Any help would be appreciated. Thanks!

**Comment by ncborcherding** [comment]
Hey Fouerghi,

apologies on mobile - 
The error is from having a list element without any rows. There are internal filtering steps in combineTCR - that removes unproductive TCR as called by Cell Ranger. The error is mostly commonly seen with newer versions of Cell Ranger and use of the bio conductor 3.12 release.

things to check
-each of the contig list elements have productive TCRs
- calling the correct T cells using cells =

what version of scRepertoire are you using? What version of cell Ranger?

I’m on vacation right now and do not have a laptop, but am happy to troubleshoot when I get access to cell reception.

just let me know when you get a chance.

Nick

**Comment by fouerghi** [comment]
Hi, 

Thank you so much for your prompt response! I followed your advice about checking that it's calling the correct T cells and it worked out. Thanks!
