### ISSUE TITLE
scatterClonotype suggestion

### ISSUE THREAD

**Issue by gt7901b** [ncborcherding/scRepertoire#82]
Hi, Nick:

It's so nice that you added scatterClonotype function. It works well. 
In Wu et al. 2020 paper, Fig.1A, Dots are sized for blood clone size. while Y axis is tumor and x axis is normal. 
Is it possible to have a size.by  option in scatterColonotype? 

for exmaple:
combined <- combineTCR(contig_list, 
                samples = c("tumor", "normal", "blood"), 
                ID = c("P", "P", "P"), cells ="T-AB")

scatterClonotype(combined, cloneCall ="gene", 
                             x.axis = "PY_P", y.axis = "PY_T",
                             graph = "proportion", size.by="P_blood")

thanks

**Comment by ncborcherding** [comment]
Hey Thanks - the parameter dot.size has been added to either allow for the display of the total number of clones (dot.size = "total") or by specific list element (dot.size = "Pxxx").

the changes are commited to the dev branch - I will update the vignette today.

Nick

**Comment by gt7901b** [comment]
thank you so much.
