### ISSUE TITLE
combineExpression creates NA values

### ISSUE THREAD

**Issue by chiararick** [ncborcherding/scRepertoire#83]
Hi Nick,

Thank you for this amazing package !

I'm kind of new to R and I have some problems with linking the contig to my SingleCellExperiment with the function combineExpression. I am using gene expression and VDJ from 3 subjects. The gene expression data are saved in a SCE object.

1. To match the barcodes of the SCE and contig list I modified the barcode column of the contig and removed the ID. The barcodes of the two objects match. Would it be better to modify the rownames of the SCE?
2. I run combineExpression : test.sce <- combineExpression(combined.test, test.sce, cloneCall = "gene", groupBy = "sample") and I did not get any error message, but all the new column generated in the SCE object contain NA values.
How can I solve this issue?

Thank you so much !

**Comment by ncborcherding** [comment]
Hey Chiarick,

Thanks for reaching out and glad you are learning R!

Would you mind showing the results coldata from your SCE and maybe the output of head(combined[[1]])? Also would you mind giving me the basic function calls you made up to **combineExpression()**, both of these would help immensely.

If all the contig information is returning NAs - my first impression would be that the barcodes of your combined list are not matching the barcodes of the SCE.

Let me know and I will help troubleshooting.

Nick

**Comment by chiararick** [comment]
Hi Nick,

thank you for your quick answer ! 

Here you can see the coldata of my SCE : 

<img width="916" alt="Screen Shot 2021-06-14 at 14 50 04" src="https://user-images.githubusercontent.com/85880451/121894881-f00d0f00-cd1f-11eb-82b8-215d1ba32872.png">


and output of combined

<img width="1185" alt="Screen Shot 2021-06-14 at 14 49 44" src="https://user-images.githubusercontent.com/85880451/121894903-f69b8680-cd1f-11eb-9ebf-e959a77a8ac8.png">

This is the function I used : 
`test.sce <- combineExpression(combined.test, test.sce, cloneCall = "gene", groupBy = "sample", proportion = FALSE, cloneTypes=c(Single=1, Small=5, Medium=20, Large=100, Hyperexpanded=500))`

I checked whether the barcodes of the combined list were matching the barcodes of the SCE : 

`"S1_AAACCTGAGAGACTAT-1" %in% combined.test$S1_A$barcode` and the result was TRUE.

Thank you again !

**Comment by ncborcherding** [comment]
Hey Chiarick,

Looks like the barcodes match so that is not the underlying issue, let me try to replicate the problem on my end.

Another issue might be the calling of the specific clonotype counts in the **combineExpression()**. The hyperexpanded is the top number of the frequency range (if clones > 500 exist, they will be added as NA in the colData). I don't think this is the problem, but while I am replicating the issue on my end, you could try 

```
test.sce <- combineExpression(combined.test, test.sce, cloneCall = "gene", groupBy = "sample", proportion = TRUE)
```

Thanks,
Nick

**Comment by chiararick** [comment]
Hi Nick,

thanks ! I tried it and I still get NA in the colData.

**Comment by ncborcherding** [comment]
Thanks for trying!

Found sometime this morning to try to replicate - I used the following from the vignette data:

#Converting to singlecellexperiment and combining object and TCR data
```
sce <- as.SingleCellExperiment(seurat)

sce <- combineExpression(combined, sce, cloneCall="gene", groupBy = "sample", proportion = TRUE)
```

From this, I was able to successfully attach the data:
<img width="894" alt="Screen Shot 2021-06-15 at 8 33 54 AM" src="https://user-images.githubusercontent.com/22754118/122062099-b6d2ae80-cdb4-11eb-9908-86f268042f48.png">

My concern now is possibly an issue with versions - could you give me the output of `sessionInfo()` just so I can see the versions you have installed? I might need to change versions on my end to replicate the issue.

Thanks for bearing with me,
Nick

**Comment by chiararick** [comment]
Hi Nick, 

thanks. Here you can find the output of sessionInfo() 
<img width="878" alt="Screen Shot 2021-06-15 at 15 43 56" src="https://user-images.githubusercontent.com/85880451/122063509-a04a4880-cdf0-11eb-8744-e3c68f270751.png">

**Comment by chiararick** [comment]
Hi Nick,

Thank you so much for your help. Now I tried it and afterwards I run `sce <- combineExpression(combined.test, test.sce, cloneCall="gene", groupBy = "sample", proportion = TRUE)`. I get this error message :

<img width="1300" alt="Screen Shot 2021-06-16 at 10 12 23" src="https://user-images.githubusercontent.com/85880451/122183329-6b3f0400-ce8b-11eb-8f4e-df775cc36f28.png">

**Comment by ncborcherding** [comment]
Hey chiararick,

Just updated the importing the `colData()` function from SummarizedExperiment to SingleCellExperiment - from my end it works, but please let me know if it works or we need to refine the approach.

Will need to reinstall and restart again:
```
devtools::install_github("ncborcherding/scRepertoire@dev")
.rs.restartR() #This restarts your R session to update the packages
````

Thanks,
Nick

**Comment by chiararick** [comment]
Hi Nick,

thank you. I tried it but I had again the same error message "Error in (function (classes, fdef, mtable) : unable to find an inherited method for function 'colData<-' for signature '"SingleCellExperiment", "data.frame"'"

**Comment by chiararick** [comment]
Hi Nick,

sorry for my late response, it worked! Thank you so much for your help I really appreciate :)

Have a good day!

**Comment by ncborcherding** [comment]
Great, glad we got it sorted out, thanks!

**Comment by purisuto** [comment]
Sorry to comment on closed.  Is there an option in `combineBCR()` or `combineTCR()` such that it doesn't add the sample prefixes to each barcode?

If not, it's relatively simple to edit them in combined.  Say you want to strip everything up to the word "GEM"
`for (i in 1:length(combined)) {
  combined[[i]]$barcode <- gsub("^.*GEM", "GEM", combined[[i]]$barcode)
}`
