### ISSUE TITLE
CDR2 comparisons 

### ISSUE THREAD

**Issue by dhcorn** [ncborcherding/scRepertoire#85]
Hey Nick,

Cell Ranger 6.0 now pulls down CDR1 and CDR2 regions along with the CDR3 regions that it always has. I was wondering if it would be possible to include the CDR1 and CDR2 (both the amino acid and nucleotide) information when doing the combineTCR() command? Then I can use it in downstream analysis and look at those conserved regions in particular subsets of cells. 

Thanks,

Doug

**Comment by ncborcherding** [comment]
Hey Doug,

Just saw that too - I added incorporation of CDR1 and CDR2 data to my ever growing "to-do" list. In your opinion, should I keep them separated? Like make a column for the CDR1_AA and NT? This would enable you to add it as meta.data and look at it after attaching to single-cell data. (I'll have to think through the changes on combineTCR() and combineExpession() mostly).

Thanks for reaching out and I appreciate any advice you have on how you would like to see it implemented!

Nick

**Comment by dhcorn** [comment]
Nick,

Thanks! Im glad you have already been thinking about this. I really think keeping them separated would be the most useful. It would just provide an easier way to manipulate the data. I was just thinking, as you were, individual columns for each that I can call up and compare between sample and cluster would be great, essentially the same way the CDR3 data is set up. 

Thanks!

Doug

**Comment by ncborcherding** [comment]
Hey Doug,

I am just going to close this because it is a feature request and not an active issue with the package. It is on my list and I appreciate the input. 

Thanks,
Nick
