### ISSUE TITLE
scRepertoire functions: TCR gene or CDR3 gene in clonotype definition?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [ncborcherding/scRepertoire#87]
Hi Nick, 

Thank you again for this well-built package. 

In some functions, the description of clone call stating "gene" being genes comprising TCR, but in other functions, "gene" is described as the gene of CDR3. 

Which one is the correct one, or it really does depend on the function?

Thank you for your help!

**Comment by ncborcherding** [comment]
Hey Quang,

So there are 4 major definitions of clone that scRepertoire will let you choose from (headers in bold):
1. Gene composition of the VDJC regions for both TRA and TRB (or the other respective receptor combos) **CTgene** called by "gene"
2. Nucleotide sequence of the two chains **CTnt** called by "nt"
3. Amino acid sequence of the two chains **CTaa** called by "aa"
4. Combined gene and nucelotide sequences of both chains **CTstrict** called by "gene+nt"

All of these are consistent throughout each function - so there should not be a difference in **gene**-based clonotypes. I will find some time this week to go through the function annotations/vignette to make sure this is clarified.

Hope that helps and let me know if you have any other questions.

Nick

**Comment by denvercal1234GitHub** [comment]
Thank you Nick!

**Comment by denvercal1234GitHub** [comment]
Hi @ncborcherding -- I revisited the 4 definitions of clonotype you described above, and wonder what is the advantage (extra insights) of defining a clone using gene composition combined with nucleotide sequence (CTstrict) versus simply using nucleotide sequences? 😅 Thank you again for your help!

**Comment by ncborcherding** [comment]
Hey Quang,

The addition of CTstrict of gene + nt was the recommendation from users and it fits guidelines for definition of clonotype ([here](https://pubmed.ncbi.nlm.nih.gov/19568742/)). 

I am not sure if there is an advantage - anecdotally it is more specific/strict (hence the name). In the single-cell literature, I have seen the use of gene combinations, nucleotide sequence, amino acid sequence of one or two chains - it seems to be author/group dependent. The use of either nucleotide sequence or amino acid sequence is generally what I use, however, I had one reviewer specifically ask for the CTstrict version (nt+gene) of one of my manuscripts.

Hope that answers your question - let me know if you have any others! Or follow ups!

Nick

**Comment by denvercal1234GitHub** [comment]
Hey Nick, 

Sorry to reopen this issue, but I think I found a potential reason why we might want to use CTstrict. 

When I examined the combined TCR object below. For example, for the two cells I highlighted in red, although the CTnt and CTaa are all the same between these 2 cells, the CTgene and therefore also the CTstrict is different. This results in different Frequency values of 43 versus 4. 

Is it fair to say that these 2 clones are unique?

<img width="960" alt="Screen Shot 2021-06-29 at 11 39 54 PM" src="https://user-images.githubusercontent.com/62179082/123876468-4fc80480-d933-11eb-8ad0-70fc1fa0f31e.png">

My apologies for bombarding you both here and via email. I will post our Q&A from emails on here later as closed issues so others can see them too. 

Thank you again for your help!

**Comment by ncborcherding** [comment]
Hey Quang, 

Apologies I must not have seen this - I think this is the exact example for CTstrict - theoretically recombination could produce the same sequence information but from different genes - which I think is what you are showing.

> 2. In CTgene, there are None and NA as shown below. Is "None" referring to no info for a particular gene segment, and "NA" referring to no info for the whole chain?
> 
> TRAV3.TRAJ6.TRAC_TRBV2.TRBJ2-1.None.TRBC2
> TRAV29DV5.TRAJ52.TRAC_NA

Yes exactly - TRBV2.TRBJ2-1.**None**.TRBC2 implies no D recovered confidently, while TRAV29DV5.TRAJ52.TRAC_**NA** means no TCRB contig was recovered. 

Nick

**Comment by ncborcherding** [comment]
Hey Quang, 

I am going to close this - I think the discussion is good for other users. If you have more info to add, feel free to add

Thanks,
Nick

**Comment by denvercal1234GitHub** [comment]
Thank you, Nick! I think it is all, except for that minor issue of still having cell barcodes that have no associated TCR info remined in the final combined object. Thank you again for your help!
