### ISSUE TITLE
Bug? NA in all TCR gene segment retained in combined object

### ISSUE THREAD

**Issue by denvercal1234GitHub** [ncborcherding/scRepertoire#88]
Hi Nick, 

Whenever you get a chance, would you mind taking a look at why after running combineTCR(), cell barcodes that have NA in all of their TCR info (TCR1, cdr3_aa1, ...) still retained in the object? 

This is somewhat an issue because in the quantContig(), these NAs will be taken into the calculation of "total" to compute the "scaled" value of unique clones (before merging with Seurat object).

Thank you again for your help!

**Comment by ncborcherding** [comment]
Hey Quang, 

This is actually already in place in the dev branch of scRepertoire. Just need to: 

```
devtools::install_github("ncborcherding/scRepertoire@dev")
```

And restart your R session. 

Thanks,
Nick
