### ISSUE TITLE
Error when calling combineTCR

### ISSUE THREAD

**Issue by s2hui** [ncborcherding/scRepertoire#9]
Hello, 

Thank you for making this useful package available.

I have 6 filtered_contig_annotation.csv files from 10x Genomics Cell Ranger that I put into a contig_list as per the vignette.  I am trying to called CombineTCR on this list but get the following error:

> combined <- combineTCR(contig_list, samples = NAMES, ID = NAMES, cells ="T-AB")
Error in `$<-.data.frame`(`*tmp*`, "sample", value = "CD123456-1") : 
  replacement has 1 row, data has 0

I was wondering what is wrong and how to I can properly run combineTCR.

Thank you
shui

**Comment by s2hui** [comment]
I just realized I had loaded BCR csv files in the contig_list.  I removed them and the combineTCR method run without error.
shui

**Comment by sud93** [comment]
Hello Shui,

I am currently facing the same problem. I have 4 filtered_contig_annotations.csv files and as mentioned in the vignette I have created the object tcr_list. However, when I call combineTCR, I get the exact same error. 

```
combine_tcr<-combineTCR(tcr_list,samples=c("Control","Control","Patient","Patient"),
                        ID=c("T1","T2","T1","T2"), cells="T-AB")
                        
Error in `$<-.data.frame`(`*tmp*`, "sample", value = "Control"): replacement has 1 row, data has 0

```
I have counter-checked my files. They are TCR contig files. 
It would be great if you could help.

Thank you,
Sudeshna
