### ISSUE TITLE
Benchmarking with other TCRseq tools & Cytoscape Network integration?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [ncborcherding/scRepertoire#90]
Hi Nick, 

I have enjoyed very much the package and thanks for the great support! 

A collaborator, however, challenged us with the rationales as to why we chose the package versus other packages. A paper (particularly Figure 2A shown below) was presented to us, arguing it has a better visualization even though it is not RNA I think (I guess with Cytoscape network software -- is it possible to generate similar in scRepertoire?)

This question was raised when I presented the data visualized with Chord diagram; people just get confused what the numbers around the circle represent and what it is actually graphing if it "does not reflect exact clonotype matches."

Do you have any thoughts on these?

Thank you again for your continued support! I still strongly support scRepertoire 😊.

https://doi.org/10.1016/j.celrep.2019.12.016

<img width="751" alt="Screen Shot 2021-07-09 at 6 32 19 PM" src="https://user-images.githubusercontent.com/62179082/125116021-ffdfff00-e0e3-11eb-8652-35337a7d56eb.png">

**Comment by ncborcherding** [comment]
Hey Quang, 

I can put this on the to-do list (of trying to improve visualization of shared clonotypes and making network-based TCR visualizations - this can be done using igraph R package). I am also actively working on a newer version of the Chord diagrams with more options for visualization and uses the "exact" match clonotype, which will be out in the new version.

For me - I do not think there is one best way to show clonotype information and in fact there is probable benefit it showing the information in multiple ways. I can see merits in their representation of clonotype, it does show a lot of additional levels of data that a chord diagram will not be able to. 

Nick

(more than open to continuing discussion below [can add more comments back and forth after closing] - but to me this is a feature request and not an issue, so I am going to "close" it)

**Comment by denvercal1234GitHub** [comment]
You are awesome! Thanks Nick! Looking forward to the new version of scRepertoire soon! I hope all is well.
