### ISSUE TITLE
getCirclize data and Plot

### ISSUE THREAD

**Issue by NK-HD** [ncborcherding/scRepertoire#91]
Hey, 

thanks for developing this cool package.

We are currently trying arounf with the circle plot and are a little unsure on how to interpret the proportion argument and its meaning:
when using proportion=T, to my impression relative proportions are shown, and when proportion=F, absolute counts are displayed. To my understanding this is opposite to the docs: https://rdrr.io/github/ncborcherding/scRepertoire/man/getCirclize.html

Could you also please verify if (looking at absolute numbers) the interpretation is correct, that X (lets say 100) clonotypes are shared between cluster A and B ?

Please excuse if I misunderstand something drastically. :)

Really appreciate your work and your help! :)

Best, Niklas

P.s. I am using version 1.3.1

**Comment by ncborcherding** [comment]
Hey Niklas, 

Thanks for reaching out and letting me know version info.

I am working on a newer version of getCircilize (with better documentation). Proportion is really saying do you want to take the number of clonotypes in your group_by parameter and divide by the number of groups. So when **proportion = FALSE** you are looking at absolute clonotype numbers. 

In the mean time, I have changed the documentation in the dev version to better reflect this.

> #' @param proportion Binary will calculate relationship unique 
#' clonotypes (proportion = FALSE) or a ratio of the groupBy 
#' variable (proportion = TRUE)

Apologies for the confusion and thanks for pointing out the error in documentation.

Nick

**Comment by hz1010** [comment]
Hello.
Thanks for your great work, this tools really help me a lot. Now I am using getCirclize() function, but I am wondering whether  the direction of links between "groupBy" clusters has biological meanings? If the arrow links from cluster1 to cluster2, Does that means  the shared clonetypes in cluster1 are from cluster2?  （packageVersion("scRepertoire")=“1.3.2”）

I also really appreciate your work and your help!

Best
Hertz

**Comment by ncborcherding** [comment]
Hey Hertz, 

As of right now ```getCircilize()``` is agnostic when it comes from the direction of the links. The script itself orders the direction in alphanumerical order and then removes the reciprocal (that will be what the colors are based on in the chord diagram). There are emerging techniques that involve correlating clonotype information and gene expression score that could give rise to a more directed chord diagram - [CONGA](https://github.com/phbradley/conga) being by far the coolest one in my opinion. 

As of right now, the interpretation of the direction is likely going to require manual interpretation and consideration of the alphanumerical order of the **groupBy** variable. 

Feel free to reach out if you have any more questions. 

Nick

**Comment by hz1010** [comment]
Hello Nick.
I met a problem again. I am confused why I cannot call clonotypes from data1 by combineTCR. following figures show detailed information.  (packageVersion("scRepertoire")=“1.3.2”).
I also really appreciate your work and your help!

Best
Hertz

![image](https://user-images.githubusercontent.com/47652056/144966280-aa0854e4-f68e-42ba-8b29-f4b943ce79ad.png)
![image](https://user-images.githubusercontent.com/47652056/144966592-4fd56582-56ca-4773-bc21-c62382203ff3.png)

**Comment by ncborcherding** [comment]
Hey Hertz, 

Thanks for reaching out again and hope things are going well. 

Ironically just had this question yesterday as well - https://github.com/ncborcherding/scRepertoire/issues/125#issuecomment-986858888

The issue stems from scRepertoire only allowing up to 3 contigs per barcode - can you try the following and let me know if it works:

```
combined <- combineTCRdata1, 
                samples = "aal", 
                ID = "aal", 
                cells ="T-AB", 
                filterMulti = TRUE)
```

Thanks,
Nick

**Comment by hz1010** [comment]
Hey Nick.
     Thanks for your suggestion, it works.
Best
Hertz
