### ISSUE TITLE
Problem with compareClonotypes 

### ISSUE THREAD

**Issue by khojandin** [ncborcherding/scRepertoire#93]
I'm trying to compare clonotypes from two patients who have received treatments at three different time points. When I look at the 10 clonotypes by compareClonotypes non of the aa sequences matches my original TCR files, is there any way to fix this issue? did I do something wrong? Also, I would like to compare the top 10/20 clonotypes between time points, how can I do it? 
<img width="1059" alt="Screen Shot 2021-07-20 at 11 44 44 AM" src="https://user-images.githubusercontent.com/63659320/126363276-d8df33b6-44f5-43fe-995e-5d1611b8a2bd.png">

Thanks

**Comment by ncborcherding** [comment]
Hey Niloufar, 

First off, hello from across the city at WashU!

Some basic starting questions
1. What version of scRepertoire are you running?
2. What is the output of ```sessionInfo()```

> When I look at the 10 clonotypes by compareClonotypes non of the aa sequences matches my original TCR file
What do you mean by this? That the alluvial graph you are displaying doesn't have the correct corresponding clones? 

Based on your code - it looks like you are calling ```compareClonotypes()``` to look at tcr1.1 and tcr1.3 - if you want to compare from two patients, my guess is that you might want to use 

```compareClonotypes(..., samples = c("1_1", "2_1")```. 

If you want to compare time points (assuming your ID 1,2,3 are different time points) it would be 

```compareClonotypes(..., samples = c("1_1", "1_2", "1_3")```

To change the number to visualize you can use: 

```compareClonotypes(..., numbers = 20)```

Please let me know what you mean in the first part of your question and we can go from there.

Thanks,
Nick

**Comment by khojandin** [comment]
Hi Nick, 
Thanks for your quick response. The scRepertoir version that I'm using is 1.3.2. to clarify the first part of my question: when I set the numbers = 10 the clonotypes sequence on my graph can not be found in the original CSV file. 
I'm new in the bioinformatic field so I really appreciate your help.

**Comment by ncborcherding** [comment]
Hey Niloufar,

No worries - see the issue now. 

You defined your contig_list, but then overwrite the contig_list with the file that is built into scRepertoire. 

```
contig_list <- list(tcr1.1,....)
data(contig_list) #<- delete this line, this is using the built in data from scRepertoire 
#(why you are getting clones that aren't in your data)
```

If issues persist, maybe change the name, something like: 

```
my_contig_list <- list(tcr1.1,....) 
```

Nick

**Comment by khojandin** [comment]
Thank you, Nick, that resolved the problem. I still cannot isolate specific clonotype sequences using the clonotypes function. 
Also, wanted to thank you for the great vignette you provided, it's really helpful.

**Comment by khojandin** [comment]
Thank you, will do!
