### ISSUE TITLE
Demultiplexing hashtag (HTO) function in scRepertoire?

### ISSUE THREAD

**Issue by e-ashwat** [ncborcherding/scRepertoire#94]
Hello Dr. Borcherding,

I'm a medical student working with single-cell RNA data from tumor-infiltrating lymphocytes. The output file our lab is currently working with contains a variety of patients' T-cells that were all included in the same 10X run using HTOs. 

Similar to Seurat, is there any function in scRepertoire to demultiplex these hashtags? If not, how do you suggest they can be dealt with so that they appear as different samples in the downstream analyses? Is it just a matter of segmenting the filtered_contig_annotations.csv file properly based on HTO? 

I'm relatively new to R and the world of single-cellomics, so apologies if this question is one with a straightforward answer. This package looks awesome, and I greatly appreciate all the time and effort you put into it. 

Look forward to hearing back.

**Comment by ncborcherding** [comment]
Hey e-ashwat,

First off - please call me Nick. 

This is actually a really interesting question - I have experience with working with hashings on gene expression, but not TCR sequencing. 

Would you mind sending me a link to the output of your Cellranger to my [email](mailto:ncborch@gmail.com)? I think this might need a new function to handle depending on the outputs and I am sure that would be helpful to the rest of the community. 

Thanks,
Nick

**Comment by ncborcherding** [comment]
Will do

**Comment by ncborcherding** [comment]
Hey thought I would reach out - if anyone has the meta data of a Seurat object and the filtered_contig_annotation.csv output of the CellRanger pipelin of a hashed experiment, more than happy to write a function for this. I am just waiting on data. You can [email me](mailto:ncborch@gmail.com) to discuss more.

Thanks,
Nick

**Comment by ChrOertlin** [comment]
Hi Nick,

recently I found a piece of code that integrates HTO data with VDJ sequencing using a seurat object. 

The issue was described here also https://github.com/satijalab/seurat/issues/1435 
A function is provided there that achieves that. 

Cheers,
Chris

**Comment by ncborcherding** [comment]
Hey Chris, 

Thanks for the link - I actually know Jared (small world)! I can write the function as is and make it compatible with scRepertoire, but my big concern is there will be a number of barcodes that are shared between samples and have to be dropped - I would like to be able to quantify this issue before making the function.

**Comment by ncborcherding** [comment]
New function out in the dev version of scRepertoire for this - [check out](https://ncborcherding.github.io/vignettes/vignette.html#122_Multiplexed_Experiment) the vignette. Just need the seurat/single-cell expression object, the filter_contig_annotation.csv file, and how you want to group the list. Output will be the list of contigs, similar to loading them individually.
