### ISSUE TITLE
solve the `combineTCR ` error with "replacement has 1 row, data has 0"

### ISSUE THREAD

**Issue by likelet** [ncborcherding/scRepertoire#97]
I encountered this problem and found the solution from https://www.biostars.org/p/481563/
as to another user said
> In my dataset, the columns is_cell =" true" and productive ="true" are in lowercase. For the function combineTCR to work, it should be in uppercase - is_cell =" TRUE" and productive ="TRUE"

here I wrote a simple function to adjust the dataset before run the `combineTCR` function 
```R
adjust_dataset<-function(df){
  df$is_cell<-ifelse( df$is_cell=='true',"TRUE","FALSE")
  df$productive<-ifelse( df$productive=='true',"TRUE","FALSE")
  # df$<-ifelse( df$is_cell=='true',"TRUE","FALSE")
  return(df)
}

#adjust the contig list by lapply
adjust.tcr.file.rds<-lapply(tcr.file.rds, adjust_dataset)

```

**Comment by ncborcherding** [comment]
Hey Qi,

Thanks for reaching out and providing code to fix a problem. What version of scRepertoire were you using with this problem?

I ask because all the current bioconductor, github master, and github dev branches should have this fixed. In fact the github dev branch will now give you a message of what the error means. 

Thanks again for reaching out and hope to get things clarified,
Nick

**Comment by likelet** [comment]
hi Nick @ncborcherding 
my version is `scRepertoire_1.0.0 `.

**Comment by ncborcherding** [comment]
Hey Qi,

Ok that makes sense now, you had me concerned that I had missed something in the current versions. 

I would suggest updating to the current scRepertoire version (v1.3.1) - there have been a number of adjustments in handling/sorting contigs and optimization fo speed. 

```
devtools::install_github("ncborcherding/scRepertoire")
```
Thanks,
Nick

**Comment by likelet** [comment]
have to say that, the problem still exist after updating the latest version of scRepertoire


```R
R version 4.0.1 (2020-06-06)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblasp-r0.3.3.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] scRepertoire_1.3.1 reshape2_1.4.4     ggalluvial_0.12.3  ggplot2_3.3.5      dplyr_1.0.7        ggsci_2.9         
[7] SeuratObject_4.0.2 Seurat_4.0.3   
```
