### ISSUE TITLE
Error in clonalHomeostasis and clonalProportion with chain = "TRB"

### ISSUE THREAD

**Issue by ElviMagda** [ncborcherding/scRepertoire#98]
Hey Nick,

I analysed my TCR dataset based on TRB chains only by using the argument `chain = "TRB"` in the functions (as you suggested in my previous issue).

It worked very well except for a couple of functions. Particularly, `clonalHomeostasis` and `clonalProportion` are some of my favourites, and I really would like to have them in my results.

I used `combineTCR` as follows:
```
combined <- combineTCR(contig_list, samples = c("X", "X", "Y", "Y", "Y"), ID = c("A", "B", "A", "B", "C"), cells ="T-AB", removeNA = TRUE, removeMulti = FALSE, filterMulti = TRUE)
```
And I get the following errors:
```
clonalHomeostasis(combined, cloneCall = "gene+nt", chain = "TRB") 
```
>Error in dat[, cloneCall] : incorrect number of dimensions

```
clonalProportion(combined, cloneCall = "gene+nt", chain = "TRB")
```
>Error in `[.data.frame`(dat, , cloneCall) : undefined columns selected

I cannot find the problem here. So any help is very much appreciated :)

Sorry for insisting in this topic. In this dataset, the coverage of TRA chains is quite low, so I have many cells with a paired TRA_TRB1 and others with NA_TRB1. As for now, they are counted as separate clones, but I think they probably belong to the same clonotype. 

Thank you for your help.

Best,
Elvira

**Comment by ncborcherding** [comment]
Hey Elvira, 

I appreciate follow up! No need to apologize. I just committed the fixes for ```clonalProportion()``` and ```clonalHomeostasis()```

Just make sure to reinstall and restart your R session:

```
devtools::install_github("ncborcherding/scRepertoire@dev")
```

Also don't hesitate to reach out if this is not working for you or if you find another issue!

Thanks,
Nick
